### PR TITLE
feat(components): [ElCheckboxGroup] add Fragment

### LINKED ISSUE #4724: [Feature Request] CheckboxGroup as Fragment
### Existing Component
Yes

### Component Name
CheckboxGroup

### Description
Currently, the CheckboxGroup is a `div` element, but this can be a problem in `table`, for example.
This is because `tbody`, `tr`, etc. are allowed in a `table`, but `div` is not.
Therefore, I want to treat CheckboxGroup as fragment (or `tr` via props such as `is` or `tag`)

Code example:
```
<table>
  <tbody>
    <el-checkbox-group> <!-- <- This is a forbidden div. -->
      <tr v-for="i in 5">
        <el-checkbox :label="i" />
      </tr>
    </el-checkbox-group>
  </tbody>
</table>
```

### PR DESCRIPTION
**Pull request by emojiiii**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
close #4724

### CODE REVIEW

**Comment by Alanscut** [comment]
@emojiiii 
please resolve conficts and add unit test

**Comment by Eiryyy** [comment]
@emojiiii If you don't write unit tests, I'll write them.

**Comment by emojiiii** [comment]
I'll add it as soon as possible

**Comment by Eiryyy** [comment]
@Alanscut @sxzz I'm really waiting for this feature and I hope you will review it. Thank you 😃

**Review by sxzz — APPROVED** [review]

**Pull request merged**
