### PR TITLE
fix(components): el-loading spinner directive

### PR DESCRIPTION
**Pull request by adaex**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by adaex** [comment]
https://preview-4133-element-plus.surge.sh/en-US/component/loading.html

**Review by sxzz — APPROVED** [review]

**Review by imswk — APPROVED** [review]

**Comment by hovees** [comment]
@adaex So after the change, can't pass the icon component that comes with element-plus to set spinner? And may I know how to get the value of svg.

**Comment by adaex** [comment]
> @adaex So after the change, can't pass the icon component that comes with element-plus to set spinner? And may I know how to get the value of svg.

I've added a new feature to copy svg content. see #4169 

// cc @JeremyWuuuuu

**Comment by hovees** [comment]
> > @adaex So after the change, can't pass the icon component that comes with element-plus to set spinner? And may I know how to get the value of svg.
> 
> I've added a new feature to copy svg content. see #4169
> 
> // cc @JeremyWuuuuu

Just a suggestion, I think it’s more intuitive to pass in a component name as before when reading the code.
If can only use svg content, don't know what icon it is without running the project, need tools to preview it, and it’s not easy to search on docs
WDYT

**Pull request merged**
