### PR TITLE
docs(components): add attr version tag

### PR DESCRIPTION
**Pull request by kaine0923**
1. docs(components): [cascader] add version tag for togglePopperVisible expose

2. docs(components): [color-picker] add version tag for show & hide expose

3. docs(components): [date-picker] add version tag for handleOpen & handleClose method

4. docs(components): [dialog] add version tag for align-center atrr

5. docs(components): [dropdown] add version tag for teleported attr

6. docs(components): [form] add version tag for scroll-into-view-options attr

7. docs(components): [image] add version tag for zoom-rate attr

8. docs(components): [input-number] add version tag for readonly attr

9. docs(components): [menu] add version tag for popper-effect attr

10. docs(components): [message-box] add version tag for append-to attr & message function

11. docs(components): [rate] add version tag for clearable attr

12. docs(components): [select-v2] add max-collapse-tags attr

13. docs(components): [select] add version tag for collapse-tags-tooltip & placement

14. docs(components): [table] fix show-overflow-toolip attr version tag

15. docs(components): [time-picker] add version tag for handleOption & handleClose expose

16. docs(components): [tree-v2] add version tag for item-size attr

17. docs(components): [tree] add version tag for empty slot

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at e4f73c4</samp>

This pull request updates the documentation of various components to reflect the new features and versions that were implemented in the element-plus library. It adds or modifies the attributes, methods, slots, and options sections of the `Dialog`, `InputNumber`, `MessageBox`, `Select`, `Cascader`, `ColorPicker`, `DatePicker`, `Dropdown`, `Form`, `Image`, `Menu`, `Rate`, `SelectV2`, `Table`, `TimePicker`, `TreeV2`, and `Tree` components in the `docs/en-US/component` directory. The changes aim to improve the readability and usability of the documentation for the users of the library.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at e4f73c4</samp>

*  Add documentation for new features that allow users to manually control the visibility of poppers in `Cascader`, `DatePicker`, and `TimePicker` components ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-f66eff2fc058025d7436f3bf405e5b09e159d9c463cb2c6d47963d4877bfc0b1L192-R197), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-936f76a60feba4602e81cd280e37ac122e009f3326ea42c660e69272e806a483L191-R195), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-da5785b94fd7a09ee3a71aa32b18bd95bdf07e9e2fcae927a4100fb50f2b9ea4L89-R94))
*  Add documentation for new features that allow users to manually show or hide the color picker in `ColorPicker` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-53920513cd8ca0f64d92411329c34e4585b26d3fff9a4a4d7e54b485c4a3474eL75-R79))
*  Add documentation for new features that allow users to align the dialog both horizontally and vertically in `Dialog` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-abbb3d078da77db6d9ad1eed9a9356891f9119733d8e8bb4fc8771e3429dc626L136-R136))
*  Add documentation for new features that allow users to control whether the dropdown popup is teleported to the body in `Dropdown` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-586abc71d241a19767d79aaa80d6f09b83a8b9dd8c12085aa68d5f86c80403c7L88-R104))
*  Add documentation for new features that allow users to customize the scroll behavior when validation fails in `Form` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-938901c6b4a36faaf382938e98ca0757e24362185cecf77f8ad55c64390ac466L128-R145))
*  Add documentation for new features that allow users to customize the zoom rate of the image viewer zoom event in `Image` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-b54969024ba1fc4abdee254a61d8c974d4ec76252e1ebbccebc2b8181a6ab14dL110-R110))
*  Add documentation for new features that allow users to set the input number as readonly in `InputNumber` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-9979014a32759a92e1d7f72a3ddaab9b5109dae5614ffa471875f353d1dc935aL95-R95))
*  Add documentation for new features that allow users to customize the tooltip theme when the menu is collapsed in `Menu` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-68f9957a7840b355dcdda10667dc726edd89eefcade651c450066137e7c5e3a8L56-R70))
*  Add documentation for new features that allow users to use a render function for the message content in `MessageBox` and `Rate` components ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-a32d736a39bf41ec94aa0c117332f90cdbd97ffcaf8574d006e76a0e1d542466L162-R171), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-1428a606b78d90244d8867e76380840ac2c9535032e6b413ce2f74600084178fL110-R110))
*  Add documentation for new features that allow users to set the root element for the message box in `MessageBox` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-a32d736a39bf41ec94aa0c117332f90cdbd97ffcaf8574d006e76a0e1d542466L190-R196))
*  Add documentation for new features that allow users to limit the number of tags to be shown when multiple selecting in `Select` and `SelectV2` components ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-d6f3c0eb128f8c7ee92669db4c4a932679a3b739ee0fa86566798815e6957f85R176), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5L133-R133))
*  Add documentation for new features that allow users to show all selected tags when mouse hover text of collapse-tags in `Select` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5L133-R133))
*  Add documentation for new features that allow users to customize the position of the dropdown in `Select` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5L162-R162))
*  Add documentation for new features that allow users to hide extra content and show them in a tooltip when hovering on the cell in `Table` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-48aed1abfbd975e78df7b5352f8c1321bb18c360349e47559acde0c4346b7123L272-R272))
*  Add documentation for new features that allow users to customize the tree node height in `TreeV2` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-04e65d8e3b294d81d23b4684463b63493d9185831f7d227044ca31683fba47f7L88-R88))
*  Add documentation for new features that allow users to customize the content when data is empty in `Tree` component ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-3758802f5cd40597fcac97afb3818cd6403b2f1ea028679ae27d383e523ca8ebL200-R203))
*  Improve the readability and consistency of the table format in `Dialog` and `InputNumber` components by moving some attributes to new lines ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-abbb3d078da77db6d9ad1eed9a9356891f9119733d8e8bb4fc8771e3429dc626L117-R117), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-9979014a32759a92e1d7f72a3ddaab9b5109dae5614ffa471875f353d1dc935aL87-R87))
*  Indicate the version history of some features in `Select` and `Table` components by adding version tags to some attributes ([link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5L162-R162), [link](https://github.com/element-plus/element-plus/pull/13641/files?diff=unified&w=0#diff-48aed1abfbd975e78df7b5352f8c1321bb18c360349e47559acde0c4346b7123L272-R272))

### CODE REVIEW

**Comment by btea** [comment]
Could you resolve the conflict?

**Comment by kaine0923** [comment]
> Could you resolve the conflict?

I'm currently on a travel week if you can wait I will fix this problem on August 6

**Comment by btea** [comment]
Ok.

**Comment by btea** [comment]
Sorry, the code seems to be in conflict again.

**Review by btea — APPROVED** [review]
Thanks!

**Pull request merged**
