### PR TITLE
feat(components): [form] FormContext adds the getField method

### PR DESCRIPTION
**Pull request by cloudcome**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 36b5da1</samp>

This pull request enhances the form component and its items by adding a `getField` function to the parent form and a `fieldValue` property to the child items. These changes enable easier access and validation of the form values.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 36b5da1</samp>

*  Add `fieldValue` property to `form-item.vue` component to get the value of the form item based on its `prop` and the parent form's `modelValue` ([link](https://github.com/element-plus/element-plus/pull/14930/files?diff=unified&w=0#diff-ec639edfd5d7463de4e60beb64943914663f64e5e4fc14ca2d93166e1ef2bad3R382))
*  Add `getField` function to `form.vue` component to get the `FormItemContext` object of a child form item by its `prop` from the `fields` array ([link](https://github.com/element-plus/element-plus/pull/14930/files?diff=unified&w=0#diff-d6bf95a3b98add940e4a0d6bd70e0e475212ca0546e3f5524f323393c268ef3bR51-R54))
*  Expose `getField` function to child form items through the `FormContext` object returned by the `setup` function of `form.vue` and the `useForm` hook ([link](https://github.com/element-plus/element-plus/pull/14930/files?diff=unified&w=0#diff-d6bf95a3b98add940e4a0d6bd70e0e475212ca0546e3f5524f323393c268ef3bR175))
*  Add `getField` function to the `FormContext` interface and `fieldValue` property to the `FormItemContext` interface in `types.ts` to define the types of the new properties and methods ([link](https://github.com/element-plus/element-plus/pull/14930/files?diff=unified&w=0#diff-b26c539c585925e10bc6fda7a399f26fbd2f5cf583946b2375774ce36241f7b9L116-R116), [link](https://github.com/element-plus/element-plus/pull/14930/files?diff=unified&w=0#diff-b26c539c585925e10bc6fda7a399f26fbd2f5cf583946b2375774ce36241f7b9R135))

### CODE REVIEW

**Review by ryuhangyeong — COMMENTED** [review]
Can you explain your use case?

**Comment by cloudcome** [comment]
@ryuhangyeong [element-plus playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgTXlGb3JtIGZyb20gJy4vTXlGb3JtLnZ1ZSc7XG5cbmNvbnN0IG1vZGVsID0gcmVhY3RpdmUoe1xuICAvLyB3b3JkcyBtdXN0IGJlIFwiaGVsbG9cIlxuICB3b3JkczogJydcbn0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPkltcHJvdmUgZWxlbWVudC1wbHVzJ3MgYWJpbGl0eSB0byBjb25uZWN0IHRvIGV4dGVybmFsIGZvcm0gdmFsaWRhdGlvbiBzeXN0ZW1zPC9oMT5cbiAgPE15Rm9ybSA6bW9kZWw9XCJtb2RlbFwiIDpydWxlcz1cIntcbiAgICB3b3JkczogKHZhbHVlKSA9PiB2YWx1ZSA9PT0gJ2hlbGxvJ1xuICB9XCI+XG4gICAgPGVsLWZvcm0taXRlbSBwcm9wPVwid29yZHNcIiBsYWJlbD1cIm11c3QgYmUgaGVsbG9cIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwibW9kZWwud29yZHNcIi8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvTXlGb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9NeUZvcm0udnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGNvbXB1dGVkLCBpbmplY3QgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgZm9ybUNvbnRleHRLZXksIHR5cGUgRm9ybUl0ZW1SdWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzPHtcbiAgICBtb2RlbDogUmVjb3JkPHN0cmluZywgYW55PjtcbiAgICBydWxlczogUmVjb3JkPHN0cmluZywgKHZhbHVlOiBhbnkpID0+IGJvb2xlYW4+O1xufT4oKTtcbmNvbnN0IGZvcm0gPSBpbmplY3QoZm9ybUNvbnRleHRLZXkpO1xuXG5jb25zdCBlbEZvcm1SdWxlcyA9IGNvbXB1dGVkKCgpID0+IE9iamVjdC5lbnRyaWVzKHByb3BzLnJ1bGVzKS5yZWR1Y2UoKGFjYywgW3Byb3AsIHZhbGlkYXRvcl0pID0+IHtcbiAgICBhY2NbcHJvcF0gPSB7XG4gICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICB2YWxpZGF0b3I6IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgICAgICAgICAgIGlmICh2YWxpZGF0b3IodmFsdWUpKSByZXR1cm47XG5cbiAgICAgICAgICAgIC8vIOKdl++4j+Kdl++4j1xuICAgICAgICAgICAgLy8gSWYgdGhlIGZpZWxkIGluZm9ybWF0aW9uIGNhbiBiZSBvYnRhaW5lZCwgdGhlIGNvbXBsZXRlIGZvcm0gdmFsaWRhdGlvbiBlcnJvciBtZXNzYWdlIGNhbiBiZSBzcGxpY2VkXG4gICAgICAgICAgICAvLyBjb25zdCBsYWJlbCA9IGZvcm0uZ2V0RmllbGQocHJvcCk/LmxhYmVsO1xuICAgICAgICAgICAgY29uc3QgbGFiZWwgPSAndW5rbm93biBmaWVsZCBsYWJlbCdcblxuICAgICAgICAgICAgY2FsbGJhY2sobmV3IEVycm9yKGAke2xhYmVsfSB2YWxpZGF0ZWQgZmFpbGVkIWApKTtcbiAgICAgICAgfSBcbiAgICB9IGFzIEZvcm1JdGVtUnVsZTtcbiAgICByZXR1cm4gYWNjO1xufSwge30pKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtZm9ybSA6bW9kZWw9XCJtb2RlbFwiIDpydWxlcz1cImVsRm9ybVJ1bGVzXCI+XG48c2xvdD48L3Nsb3Q+XG48L2VsLWZvcm0+XG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=)

**Comment by cloudcome** [comment]
@btea 关注一下

**Comment by cloudcome** [comment]
> @ryuhangyeong [element-plus playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSc7XG5pbXBvcnQgTXlGb3JtIGZyb20gJy4vTXlGb3JtLnZ1ZSc7XG5cbmNvbnN0IG1vZGVsID0gcmVhY3RpdmUoe1xuICAvLyB3b3JkcyBtdXN0IGJlIFwiaGVsbG9cIlxuICB3b3JkczogJydcbn0pO1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPkltcHJvdmUgZWxlbWVudC1wbHVzJ3MgYWJpbGl0eSB0byBjb25uZWN0IHRvIGV4dGVybmFsIGZvcm0gdmFsaWRhdGlvbiBzeXN0ZW1zPC9oMT5cbiAgPE15Rm9ybSA6bW9kZWw9XCJtb2RlbFwiIDpydWxlcz1cIntcbiAgICB3b3JkczogKHZhbHVlKSA9PiB2YWx1ZSA9PT0gJ2hlbGxvJ1xuICB9XCI+XG4gICAgPGVsLWZvcm0taXRlbSBwcm9wPVwid29yZHNcIiBsYWJlbD1cIm11c3QgYmUgaGVsbG9cIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwibW9kZWwud29yZHNcIi8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvTXlGb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9NeUZvcm0udnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGNvbXB1dGVkLCBpbmplY3QgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgZm9ybUNvbnRleHRLZXksIHR5cGUgRm9ybUl0ZW1SdWxlIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzPHtcbiAgICBtb2RlbDogUmVjb3JkPHN0cmluZywgYW55PjtcbiAgICBydWxlczogUmVjb3JkPHN0cmluZywgKHZhbHVlOiBhbnkpID0+IGJvb2xlYW4+O1xufT4oKTtcbmNvbnN0IGZvcm0gPSBpbmplY3QoZm9ybUNvbnRleHRLZXkpO1xuXG5jb25zdCBlbEZvcm1SdWxlcyA9IGNvbXB1dGVkKCgpID0+IE9iamVjdC5lbnRyaWVzKHByb3BzLnJ1bGVzKS5yZWR1Y2UoKGFjYywgW3Byb3AsIHZhbGlkYXRvcl0pID0+IHtcbiAgICBhY2NbcHJvcF0gPSB7XG4gICAgICAgIHRyaWdnZXI6ICdjaGFuZ2UnLFxuICAgICAgICB2YWxpZGF0b3I6IChydWxlLCB2YWx1ZSwgY2FsbGJhY2spID0+IHtcbiAgICAgICAgICAgIGlmICh2YWxpZGF0b3IodmFsdWUpKSByZXR1cm47XG5cbiAgICAgICAgICAgIC8vIOKdl++4j+Kdl++4j1xuICAgICAgICAgICAgLy8gSWYgdGhlIGZpZWxkIGluZm9ybWF0aW9uIGNhbiBiZSBvYnRhaW5lZCwgdGhlIGNvbXBsZXRlIGZvcm0gdmFsaWRhdGlvbiBlcnJvciBtZXNzYWdlIGNhbiBiZSBzcGxpY2VkXG4gICAgICAgICAgICAvLyBjb25zdCBsYWJlbCA9IGZvcm0uZ2V0RmllbGQocHJvcCk/LmxhYmVsO1xuICAgICAgICAgICAgY29uc3QgbGFiZWwgPSAndW5rbm93biBmaWVsZCBsYWJlbCdcblxuICAgICAgICAgICAgY2FsbGJhY2sobmV3IEVycm9yKGAke2xhYmVsfSB2YWxpZGF0ZWQgZmFpbGVkIWApKTtcbiAgICAgICAgfSBcbiAgICB9IGFzIEZvcm1JdGVtUnVsZTtcbiAgICByZXR1cm4gYWNjO1xufSwge30pKTtcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG48ZWwtZm9ybSA6bW9kZWw9XCJtb2RlbFwiIDpydWxlcz1cImVsRm9ybVJ1bGVzXCI+XG48c2xvdD48L3Nsb3Q+XG48L2VsLWZvcm0+XG48L3RlbXBsYXRlPiIsIl9vIjp7fX0=)

@btea @ryuhangyeong 我们内部将 el-form 封装为 my-form，将 el-form-item 封装为 my-form-item 以便更好的接入内部的表单验证系统，它比内置的 async-validator 要更加的本地化，但在表单验证过程中却需要用到表单和字段元信息。这样的话，更多三方开发者可以更好的扩展 el-form 和 el-form-item。

We internally encapsulate el-form as my-form and el-form-item as my-form-item to better connect to the internal form validation system. It is more localized than the built-in async-validator. However, form and field meta-information is required during form validation. In this way, more third-party developers can better extend el-form and el-form-item.

**Review by ryuhangyeong — APPROVED** [review]
@btea @chenxch 

Can I ask you to review it

**Review by btea — APPROVED** [review]
@cloudcome  Sorry for replying so late. This modification looks good.

**Comment by cloudcome** [comment]
> @cloudcome Sorry for replying so late. This modification looks good. 

期待这个 pr 能够被合并。

**Pull request merged**
