### PR TITLE
style(components): [date-picker] fix background covers the border(#8953)

### PR DESCRIPTION
**Pull request by Mario34**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

[Details](https://github.com/element-plus/element-plus/issues/8953)

### CODE REVIEW

**Comment by holazz** [comment]
Hi, I have created a PR to solve this issue. https://github.com/element-plus/element-plus/pull/8879

**Comment by Mario34** [comment]
> Hi, I have created a PR to solve this issue. #8879
> 
> IMO, we should adjust the height of the inner input box to solve this issue, which is consistent with the behavior of common datapicker. @YunYouJun Could you please take a look?

There is nothing wrong with your point, if the problem is fixed, please close this PR

**Comment by YunYouJun** [comment]
Maybe we need to talk about it.

Reducing the height was a last resort to fix chrome's auto-fill color.

**Comment by xiaoxian521** [comment]
thank you very much for your pr

**Comment by xiaoxian521** [comment]
resolve: https://github.com/element-plus/element-plus/pull/8879

**Pull request closed without merging**
