### PR TITLE
Fix(transition): install ElCollapseTransition 

### PR DESCRIPTION
**Pull request by rottenpen**
- [ ] fix ElCollapseTransition bug

Fix ElCollapseTransition isn't installed . and can't run like this
image

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
We should export this member from the main package, consider registering it locally.

**Comment by rottenpen** [comment]
@JeremyWuuuuu what is the meaning of this？

**Comment by JeremyWuuuuu** [comment]
> We should export this member from the main package, consider registering it locally.

Typo **Should not** instead of should...

**Comment by JeremyWuuuuu** [comment]
cc @bastarder. But seems the original version had this one installed globally, maybe I was wrong about this.

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
