### PR TITLE
feat(components): [slider] placement

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## Description

The tooltip direction of the Slider component is always up. However, in some cases, I thought it would be appropriate to support it in a different direction. For example, if it is vertical as shown in the picture below, it would be more reasonable to float to the right than the top.

Just in case, it would be great if you could specify the direction in which the tooltip appears!

### Upgrade

image

### Current

image

### Etc

Additionally, `tooltip-placement` can be used as a way around this case!

image

## What is Expected?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyXG4gICAgXHR2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgdmVydGljYWxcbiAgICAgIGhlaWdodD1cIjIwMHB4XCJcbiAgICAgIHBsYWNlbWVudD1cInJpZ2h0XCJcbiAgICAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHZhbHVlID0gcmVmKDApXG48L3NjcmlwdD5cbjxzdHlsZSBzY29wZWQ+XG4uc2xpZGVyLWRlbW8tYmxvY2sge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLnNsaWRlci1kZW1vLWJsb2NrIC5lbC1zbGlkZXIge1xuICBtYXJnaW4tdG9wOiAwO1xuICBtYXJnaW4tbGVmdDogMTJweDtcbn1cbjwvc3R5bGU+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODU2MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg1NjEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctODU2MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy04NTYxLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

## What is actually happening?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwic2xpZGVyLWRlbW8tYmxvY2tcIj5cbiAgICA8ZWwtc2xpZGVyIHYtbW9kZWw9XCJ2YWx1ZVwiIHZlcnRpY2FsIGhlaWdodD1cIjIwMHB4XCIgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2YWx1ZSA9IHJlZigwKVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLnNsaWRlci1kZW1vLWJsb2NrIHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbn1cbi5zbGlkZXItZGVtby1ibG9jayAuZWwtc2xpZGVyIHtcbiAgbWFyZ2luLXRvcDogMDtcbiAgbWFyZ2luLWxlZnQ6IDEycHg7XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by btea — APPROVED** [review]

**Comment by tolking** [comment]
Maybe we can add `fallback-placements` attribute to the Tooltip component

tooltip-placement -> placement (refer to other components attribute, maybe this is better)

The optional values of the placement attribute seems can be add more.

**Comment by ryuhangyeong** [comment]
@tolking

Am I right to understand?

1. Rename attribute 'tooltip-placement' -> 'placement'
2. In addition to bottom/top/left/right, add another property.
3. Add property 'fallback-placements'.

**Comment by tolking** [comment]
> Am I right to understand?
> 
> 1. Rename attribute `tooltip-placement` -> `placement`
> 2. In addition to `bottom/top/left/right`, add another property (`top-start/top-end/bottom-start/bottom-end/left-start/left-end/right-start/right-end`).
> 3. Add attribute `fallback-placements`.

1. I suggest change the attribute name
2. Need to discuss
3. Only add the `fallback-placements` attribute to the Tooltip component and not expose. This attribute will avoid description related problems.

**Comment by ryuhangyeong** [comment]
## My opinion

> In addition to bottom/top/left/right, add another property (top-start/top-end/bottom-start/bottom-end/left-start/left-end/right-start/right-end).

This is subject to discussion. To tell you my opinion, I didn't think so at first, but after thinking about it again, I thought it would be better to take the placement props type of el-tooltip as it is.

> 3. Add attribute fallback-placements.

Based on other components, I thought `bottom, top, right, left` would be enough.

So I'm going to do it like below.

```vue
<el-tooltip
  :fallback-placements="['bottom', 'top', 'right', 'left']"
>
```

@tolking 

This is my opinion, could you please share your opinion as well?

**Comment by tolking** [comment]
The default value is top, so top should be first.

```vue
:fallback-placements="['top', 'bottom', 'right', 'left']"
```

**Comment by ryuhangyeong** [comment]
What we discussed is reflected in the code.

**Comment by YunYouJun** [comment]
How about adding an example in docs?

**Comment by ryuhangyeong** [comment]
It's late in the area where I live, so I'll add an example tomorrow!

**Comment by ryuhangyeong** [comment]
image

An example has been added~! 🎉🎉

**Review by tolking — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
If there are no more comments, I'll merge them! Thank you to everyone who reviewed.

**Comment by tolking** [comment]
> If there are no more comments, I'll merge them! Thank you to everyone who reviewed.

You should wait for other members opinions. If you need to fix the rest Bug of this component, just watch out for merge conflicts.

**Comment by ryuhangyeong** [comment]
all right.

**Review by YunYouJun — APPROVED** [review]

**Pull request merged**
