### PR TITLE
feat(docs): add PWA support for docs

### LINKED ISSUE #7073: [Feature Request] [Docs] add PWA support for documentation website
Feature type: **`Docs`**

## Details

- Enhanced compone nt name: `N/A`

## Description

Document won't open without network, add PWA support for documentation website to extended usage scenarios.

I found the documentation is built on Vitepress, just add a vite plugin vite-plugin-pwa.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by tolking**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

The image about PWA popup.

popup-img

close #7073

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@tolking good job there!

**Review by jw-foss — APPROVED** [review]

**Comment by sxzz** [comment]
AWESOME!

**Comment by sxzz** [comment]
image

But offline does not seem to be available

**Comment by tolking** [comment]
@sxzz I forgot that the output folder of vitepress is not the same as the PWA plugin, I will fix it.

**Comment by tolking** [comment]
@sxzz #7100

**Pull request merged**
