### PR TITLE
fix(components): [upload] expose headers and data field

### PR DESCRIPTION
**Pull request by kybetter**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by Giwayume** [comment]
What is the reason for exposing these? Both of these are props that you provide to the component, and would already have their values because of this.

**Comment by kybetter** [comment]
> What is the reason for exposing these? Both of these are props that you provide to the component, and would already have their values because of this.

Because our API need a file name field that user chose, I should fill this name in data props, and I can't get the file data before user fill it into upload component, so I had get it in before upload method.

**Comment by Giwayume** [comment]
This doesn't work? 
```
<template>
  <el-upload
    :headers="uploadHeaders"
    :data="uploadData"
    :before-upload="onBeforeUpload"
  />
</template>

<script setup>
import { nextTick } from 'vue'

const uploadHeaders = ref({})
const uploadData = ref({})
async function onBeforeUpload(rawFile) {
    uploadHeaders.value = {
        'some': 'value'
    }
    uploadData.value = {
        'some': 'value'
    }
    await nextTick()
    // Do whatever you need here
}
</script>
```

**Comment by JeremyWuuuuu** [comment]
Closing this because this is nonsense.

**Pull request closed without merging**
