### PR TITLE
fix(components): [drawer] fix low animation fps without graphics acceleration

### LINKED ISSUE #17212: [Performance] [drawer] el-drawer动画卡顿，帧数低
Bug Type: **`Performance`**

## Environment

- Vue Version: `3.4.27`
- Element Plus Version: `2.7.5`
- Browser / OS: `Edge`
- Build Tool: `Vite`

### Related Component

- `el-drawer`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/drawer.html)

### Steps to reproduce

1. 使用edge浏览器
2. 关闭浏览器中【在可用时使用图形加速】设置
3. 打开官网的drawer链接，点击组件即可复现

### What is Expected?

无论打不打开【在可用时使用图形加速】，展开收缩动画都不卡顿

### What is actually happening?

动画明显卡顿

### Additional comments

在playground里是正常的，不知为何

已知的解决方案
1. 打开【在可用时使用图形加速】
2. F12切手机模拟
3. 换其他浏览器如Firefox等

### PR DESCRIPTION
**Pull request by qianjiachun**
fixed the issue where the animation fps of the drawer was low when the graphics acceleration option was turned off in the browser

closed #17212

Before:
before

After:
fixed

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
能提供更多详细情况吗？比如视频或者gif效果，我本地打开 drawer 并不卡顿。

**Comment by qianjiachun** [comment]
[demo-video](https://ww0.lanzn.com/iE7wX25ukxxe)
是压缩包，包含了前后两个演示视频。
视频最高120帧录制，可能还是不太明显。我是240帧的屏幕，对比非常明显。

需要关闭浏览器的**图形加速**选项
image

**Comment by qianjiachun** [comment]
而且我感觉drawer的动画应该是纯左右平移更符合直觉一点，加上透明度变化似乎有一些多余

**Comment by btea** [comment]
确实，在你提供的截图中表现比较明显。

**Review by btea — APPROVED** [review]

**Comment by tolking** [comment]
改动后，Mask没有过度动画感觉好生硬

**Comment by qianjiachun** [comment]
动画只是去掉了透明度的变化，其他几个库都是这样实现的😂，我个人感觉纯平移更加好一点



---Original---
From: ***@***.***&gt;
Date: Wed, Jul 31, 2024 19:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [element-plus/element-plus] fix(components): [drawer] fix lowanimation fps without graphics acceleration (PR #17696)




 
改动后，Mask没有过度动画感觉好生硬

**Comment by tolking** [comment]
直接平移当然可以接受。但黑色的背景屏遮突然出现和消失就比较生硬

**Comment by qianjiachun** [comment]
@tolking 我改了一版，给overlay增加了透明度变化，同时保证了drawer动画的流畅度

fixed

**Review by tolking — APPROVED** [review]
LGTM

**Pull request merged**
