### PR TITLE
feat(components): [el-dropdown] add new "popper-class" prop

### LINKED ISSUE #4908: [Feature Request] Add "popper-class" prop to el-dropdown
### Existing Component
Yes

### Component Name
el-dropdown

### Description
All components that use Popper have a “popper class” prop except for ElDropdown — e.g. ElSelect and ElPopover have that prop.

That prop would give the possibility to add a custom class to popper element user for the dropdown which is really useful for applying certain styles only for specific poppers.

### PR DESCRIPTION
**Pull request by jagoncalves14**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jagoncalves14** [comment]
This PR is a fix for the following issue: #4909

**Comment by msidolphin** [comment]
Thank you for your contribution, the unit test did not pass,  can you check this?

**Comment by emojiiii** [comment]
This is an error in the unit test of the `time-picker` component @msidolphin

**Comment by msidolphin** [comment]
> This is an error in the unit test of the `time-picker` component @msidolphin

I know, I retry 4 times, still the same error

**Review by emojiiii — APPROVED** [review]

**Pull request merged**
