### PR TITLE
fix: [el-select-v2] 修復select-v2 v-model 不能正常的支持 Object

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
bug:[#6541 ](https://github.com/element-plus/element-plus/issues/6541)
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by baiwusanyu-c — COMMENTED** [review]
此处修改回显值，使用getValueKey方法；修复在传入value-key同时绑定对象时，回显 '[object Object]'

**Review by baiwusanyu — APPROVED** [review]

**Comment by msidolphin** [comment]
Please add the test cases🙏

**Review by baiwusanyu-c — COMMENTED** [review]
Add unit test 'default value is Object'

**Comment by czh740132583** [comment]
I'm sorry, I've added relevant unit tests now

> Please add the test cases🙏

I'm sorry, I've added relevant unit tests now

**Comment by czh740132583** [comment]
> Please add the test cases🙏

In addition, I only modified the default value display. In bug [6541], I didn't modify the expectation of clicking to obtain the object corresponding to the option list, because I observed that it seems that the component is designed in this way, that is, the change method can only get the value corresponding to valuekey

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
