### PR TITLE
fix(docs): [pagination] example bugfix according to new usage

### LINKED ISSUE #5700: [Bug Report] el-pagination Page number does not update when page-size changes
### Element Plus version
1.3.0-beta.3

### OS/Browsers version
Windows 10/Google Chrome 97.0.4692.99

### Vue version
3.2.25

### Reproduction Link
https://github.com/element-plus/element-plus

### Steps to reproduce
This problem is also present in the examples from the official documentation.When the size of each page (page-size) changes, the page numbers are not automatically updated.
官方文档的示例中也存在这个问题。在总数量(total)确定的情况下，选择器中修改每页数量后，后面的页码数没有自动更新。

### What is Expected?
when the size of each page (page-size) changes, the page numbers should be automatically updated.
在总数量确定的情况下，选择器中修改每页数量后，后面的页码数应该重新计算，自动更新。

### What is actually happening?
Page numbers have not changed.
实际结果是页码数没有变化，显示的还是修改前的页码数。

### PR DESCRIPTION
**Pull request by ioslh**
After pagination completely refactored, documentation code example should also be modified according to new usage. Also fix #5700.

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by neil585456525 — COMMENTED** [review]
Should the first example use defaultPageSize props ?
BTW, there is no defaultPageSize example in document, maybe this could be that one.

**Comment by ioslh** [comment]
> Should the first example use defaultPageSize props ?
> BTW, there is no defaultPageSize example in document, maybe this could be that one.

More examples will coming soon

**Comment by JeremyWuuuuu** [comment]
@ioslh @sam585456525 Do you think it is a good idea that adding more example in this PR? If you don't I think we can do a independent Pull Request for adding the demo case that @sam585456525 mentioned above, @sam585456525 would you like to add that case?

**Review by jw-foss — APPROVED** [review]
LGTM.

**Comment by sam585456525** [comment]
> @ioslh @sam585456525 Do you think it is a good idea that adding more example in this PR? If you don't I think we can do a independent Pull Request for adding the demo case that @sam585456525 mentioned above, @sam585456525 would you like to add that case?

That's my pleasure👌

**Comment by JeremyWuuuuu** [comment]
Then let's merge this one first so you can later write additional show cases to this component.

**Pull request merged**
