### PR TITLE
Fix/fromItem provide key reference issues in different projects

### LINKED ISSUE #10690: [Component] [form-item, form] 当我基于el-input 开发组件库my-ui-input时，在另一个项目使用我开发的组件my-ui-input，表单校验（失败）无效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.22`
- Browser / OS: `Chrome latest`
- Build Tool: `Vite`

### Related Component

- `el-form-item`
- `el-form`

### Reproduction Link

[Github Repo](https://github.com/xukaishan/el-demo)

### Steps to reproduce

https://github.com/xukaishan/el-demo
打包基于el-input开发的组件库如（my-ui-input）
 cd my-ui-lib
 npm i
 npm run build;
在此项目中使用my-ui-input组件
 cd my-app
 npm i
 npm run dev
运行项目点击第一个输入框，正常触发表单的规则校验；
点击第二个输入框，表单校验失败

### What is Expected?

基于el-input开发的组件库如（my-ui-input）可以正常进行表单校验

### What is actually happening?

封装的el-input表单校验失败，没有触发表单校验

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by xukaishan**
fix #10690

### CODE REVIEW

**Comment by chenxch** [comment]
Are you sure this solves your problem?

**Comment by xukaishan** [comment]
> Are you sure this solves your problem?
Sure

**Comment by chenxch** [comment]
> > Sure

I probably got it, please correct the title first.

**Comment by chenxch** [comment]
Please refer to the title format of other PRs. @xukaishan

**Comment by chenxch** [comment]
Sorry, this change is not currently under consideration.

**Pull request closed without merging**
