### PR TITLE
fix(tree): add deep option for the watch function of data

### LINKED ISSUE #1185: [bug report] tree: data cannot respond
### Element Plus version
1.0.1-beta.19

### OS/Browsers version
Windows 10/ Chrome 87

### Vue version
3.0.5

### Reproduction Link
https://github.com/unclecarlos/ep-tree

### Steps to reproduce
```html
<el-button @click="fetchData">fetch data</el-button>
<el-tree :data="treeData"></el-tree>
```
```typescript
export default defineComponent({
  name: 'App',
  setup () {
    const treeData = reactive([{ label: 'origin0', id: 0 }])
    const fetchData = () => {
      const data = [
        { label: 'new label1', id: 1 },
        { label: 'new label2', id: 2 },
        { label: 'new label3', id: 3 }
      ]
      setTimeout(() => {
        treeData.splice(0, treeData.length, ...data)
        treeData.push({ label: 'push', id: 10 })
        console.log('App', treeData)
      }, 1000)
    }
    return {
      treeData,
      fetchData
    }
  }
})
```

### What is actually happening?
点button更新数组，Tree没响应

### PR DESCRIPTION
**Pull request by BeADre**
fix #1185

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Though this temporarily fix this issue, deep watch data is not suggested though, it will have perf penalty when user injects a relatively large chunk of data.

**Comment by JeremyWuuuuu** [comment]
The ultimate way to solve this is that we want the watcher to take care of themselves, for example:

We have a tree data like:
```ts
const data = {
  node1: {
     children: [],
  },
  // ... others
}
```

We want the parent in this case `node1` to watch its own length of children, and each children watches themself, so that every time we trigger a change we don't ended up triggering a full scan over the entire data, could you figure a way that can manage to do so?

**Comment by BeADre** [comment]
I'm  sorry, I don't understand what '**a full scan over the entire data**' means

**Comment by JeremyWuuuuu** [comment]
> I'm sorry, I don't understand what '**a full scan over the entire data**' means

For example.

If you have an object over 1M fields, the deep option adds watcher to all of them, you'll get 1M setter/getter + 1(the object itself).

**Comment by JeremyWuuuuu** [comment]
We can merge this issue right now for temporary fix, but if you are interested in perf optimization, let me know.

**Review by jw-foss — APPROVED** [review]

**Review by jw-foss — APPROVED** [review]

**Comment by BeADre** [comment]
我英文不太好。。。 这段我就用中文表述吧  就是我个人认为proxy对字段的拦截是惰性的 不会像`Object.defineProperty`那样去主动给每个字段添加`getter`和`setter`，他的目标是对象数组本身 只有对对象数组的属性进行get set delete has等操作时 才会惰性执行对应的拦截器，所以并不是每个属性都会进行初始化拦截器，只有对象数组会。这样就已经绕过了很多属性的拦截操作了。我们的设计目的是达到修改任何节点(不限于children的长度操作)都能在视图中响应变化，所以在tree的数据结构中孩子节点的proxy也是绕不开的

**Comment by JeremyWuuuuu** [comment]
> 我英文不太好。。。 这段我就用中文表述吧 就是我个人认为proxy对字段的拦截是惰性的 不会像`Object.defineProperty`那样去主动给每个字段添加`getter`和`setter`，他的目标是对象数组本身 只有对对象数组的属性进行get set delete has等操作时 才会惰性执行对应的拦截器，所以并不是每个属性都会进行初始化拦截器，只有对象数组会。这样就已经绕过了很多属性的拦截操作了。我们的设计目的是达到修改任何节点(不限于children的长度操作)都能在视图中响应变化，所以在tree的数据结构中孩子节点的proxy也是绕不开的

Ok，我们可以先保留看看后续会不会有什么问题。确实那个 1M getter/setter 的表述是有问题的，不过考虑到 Vue 还会提供一个 Compat 版本，这个问题可能会被人提出来，保留观察一下吧。我个人觉得大概率不会有人给 `tree` 喂很多数据。

**Pull request merged**
