### PR TITLE
fix(input-number): update value

### LINKED ISSUE #1229: [Bug Report] delete value of number-input, increase and decrease button will not work
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
chrome87

### Vue version
3.0.5

### Reproduction Link
https://element-plus.org/#/zh-CN/component/input-number

### Steps to reproduce
delete value of number-input, increase and decrease button will not work

### What is Expected?
increase and decrease button will work

### What is actually happening?
increase and decrease button will not work

### PR DESCRIPTION
**Pull request by BeADre**
fix #1229

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Seems this is conflict with #1252. cc @Ryan2128

**Comment by Ryan2128** [comment]
Sorry, I haven't see #1229 before, there are two issues #1119 and #1229, both of them have been fixed in #1252.

**Comment by BeADre** [comment]
ok, I'll close the pr

**Pull request closed without merging**
