### PR TITLE
fix(components): [el-select] update visible immediately if query changed

### LINKED ISSUE #5914: [Bug Report] [select组件] default-first-option 混乱
### Element Plus version
2.0.1

### OS/Browsers version
macbook pro m1

### Vue version
3.2.25

### Reproduction Link
https://codepen.io/jchalex/pen/XWzRKrj

### Steps to reproduce
<el-select 
        v-model="value1" 
        multiple
        filterable
        default-first-option                         
        placeholder="Select" 
        @change="log">
        <el-option v-for="item in options" :key="item.value" :label="item.label" :value="item.value"></el-option>
      </el-select>

### What is Expected?
as point, select the first option, not chaos

### What is actually happening?
default-first-option select a wrong option

企业微信截图_c20b11f1-78d0-437b-ad14-4540c8ba9bf0

image

### PR DESCRIPTION
**Pull request by nieyuyao**
The `visible` property needs to be updated immediately when the `query` changed, otherwise the `visible` of option at func`checkDefaultFirstOption` will be old and incorrect. Also closes #5914 .

```javascript
// !!! should be invoked immediately, so that `n.visible` at the `checkDefaultFirstOption` is newest
watch(
    queryChange,
    (changes: Ref<QueryChangeCtx>) => {
      const { query } = unref(changes)

      const regexp = new RegExp(escapeStringRegexp(query), 'i')
      states.visible = regexp.test(currentLabel.value) || props.created
      if (!states.visible) {
        select.filteredOptionsCount--
      }
    },
    { flush: 'sync' }
  )
```
```javascript

const checkDefaultFirstOption = () => {
    const optionsInDropdown = optionsArray.value.filter(
      (n) => n.visible && !n.disabled && !n.states.groupDisabled
    )
    const userCreatedOption = optionsInDropdown.filter((n) => n.created)[0]
    const firstOriginOption = optionsInDropdown[0]
    states.hoverIndex = getValueIndex(
      optionsArray.value,
      userCreatedOption || firstOriginOption
    )
  }

```

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@nieyuyao Do you think you can add some test against this? Not mandatory though

**Comment by nieyuyao** [comment]
>

**Comment by nieyuyao** [comment]
> @nieyuyao Do you think you can add some test against this? Not mandatory though

Thanks for your reply! I will add the unit tests later.

**Comment by nieyuyao** [comment]
@JeremyWuuuuu Done!

**Comment by nieyuyao** [comment]
Is anyone working on this or?

**Comment by nieyuyao** [comment]
@JeremyWuuuuu Are there any other questions about this pr?

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Comment by kooriookami** [comment]
Fixed

**Pull request closed without merging**
