### PR TITLE
fix(components): [radio-button] model-value click style lost and format test file

### LINKED ISSUE #16689: [Component] [radio-button] radio-group-button的值绑定问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.25`
- Element Plus Version: `2.7.2`
- Browser / OS: `Chrome/124.0.0.0 Macos13.3.1 `
- Build Tool: `Vite`

### Related Component

- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgOm1vZGVsLXZhbHVlPVwicmFkaW8xXCIgc2l6ZT1cImxhcmdlXCIgQGNoYW5nZT1cImhhbmRsZUNoYW5nZVwiPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiBsYWJlbD1cIk5ldyBZb3JrXCIgdmFsdWU9XCJOZXcgWW9ya1wiIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiV2FzaGluZ3RvblwiIHZhbHVlPVwiV2FzaGluZ3RvblwiIC8+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIGxhYmVsPVwiTG9zIEFuZ2VsZXNcIiB2YWx1ZT1cIkxvcyBBbmdlbGVzXCIgLz5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gbGFiZWw9XCJDaGljYWdvXCIgdmFsdWU9XCJDaGljYWdvXCIgLz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgIDxlbC1yYWRpby1ncm91cCA6bW9kZWwtdmFsdWU9XCJyYWRpbzFcIiBzaXplPVwibGFyZ2VcIiBAY2hhbmdlPVwiaGFuZGxlQ2hhbmdlXCI+XG4gICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJOZXcgWW9ya1wiIHZhbHVlPVwiTmV3IFlvcmtcIiAvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiV2FzaGluZ3RvblwiIHZhbHVlPVwiV2FzaGluZ3RvblwiIC8+XG4gICAgICA8ZWwtcmFkaW8gbGFiZWw9XCJMb3MgQW5nZWxlc1wiIHZhbHVlPVwiTG9zIEFuZ2VsZXNcIiAvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiQ2hpY2Fnb1wiIHZhbHVlPVwiQ2hpY2Fnb1wiIC8+XG4gICAgPC9lbC1yYWRpby1ncm91cD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCByYWRpbzEgPSByZWYoJ05ldyBZb3JrJylcbmNvbnN0IHJhZGlvMiA9IHJlZignTmV3IFlvcmsnKVxuY29uc3QgcmFkaW8zID0gcmVmKCdOZXcgWW9yaycpXG5cbmZ1bmN0aW9uIGhhbmRsZUNoYW5nZShlKSB7XG4gIGNvbnNvbGUubG9nKCdjaGFuZ2U6ICcsIGUpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

1. 默认绑定NewYork
2. 点击radio-button的Washington, radio-button被清空了没有选中值
3. 点击radio-group的Washington, radio-group没有变化

### What is Expected?

由model-value控制绑定值, 点击radio-button的Washington时选中的依然是NewYork

### What is actually happening?

radio-button的值被清空

### Additional comments

_(empty)_

https://github.com/element-plus/element-plus/assets/23123540/f0d3c3c4-0e0f-4df8-9aec-c2f773561313

### PR DESCRIPTION
**Pull request by warmthsea**
fix: https://github.com/element-plus/element-plus/issues/16689

## Before

screenshots

## After

screenshots

### CODE REVIEW

**Comment by toviac** [comment]
这里是不是可以根据is-active类来判断[ns.is('active', modelValue === actualValue)](https://github.com/element-plus/element-plus/blob/42aa1724eab07de216d39f6f48da08c646ca75fd/packages/components/radio/src/radio-button.vue#L5)
el-radio组件中这个位置是is-checked

**Comment by warmthsea** [comment]
> 这里是不是可以根据is-active类来判断[ns.is('active', modelValue === actualValue)](https://github.com/element-plus/element-plus/blob/42aa1724eab07de216d39f6f48da08c646ca75fd/packages/components/radio/src/radio-button.vue#L5) el-radio组件中这个位置是[ns.is('checked', modelValue === actualValue),](https://github.com/element-plus/element-plus/blob/42aa1724eab07de216d39f6f48da08c646ca75fd/packages/components/radio/src/radio.vue#L8)

我不确定那种更改方案最好

**Comment by makedopamine** [comment]
This is along the right lines. I'd like to throw out an idea to fine-tune it.
```scss
@include b(radio-button) {
  @include when(active) {
     // checked style here
   }
} 
```
Then we don't need to change anywhere else. What do you think?

**Comment by warmthsea** [comment]
> This is along the right lines. I'd like to throw out an idea to fine-tune it.
> 
> ```css-scss
> @include b(radio-button) {
>   @include when(active) {
>      // checked style here
>    }
> } 
> ```
> 
> Then we don't need to change anywhere else. What do you think?

yes, that's better.

screenshots

**Review by YunYouJun — APPROVED** [review]

**Pull request merged**
