### PR TITLE
feat(dialog): add draggable function

### LINKED ISSUE #4809: [Feature Request] Dialog 弹窗组件添加可拖拽配置
### Existing Component
Yes

### Component Name
Dialog 对话框

### Description
弹窗组件能否添加可拖拽配置 每次都要自己重新封装一次太麻烦了

### PR DESCRIPTION
**Pull request by kooriookami**
# Feature needed draft
* [x] Dialog can be draggable.

If there is other feature or improvement, you can give me a comment.

### CODE REVIEW

**Comment by Vgbire** [comment]
I did the same thing for this.Maybe we can write a directive. add it in dialog__header to control.
image
image

**Comment by emojiiii** [comment]
please remove `demo-block.json`

**Comment by kooriookami** [comment]
> please remove `demo-block.json`

OK, it has been deleted.

**Comment by kooriookami** [comment]
Merged in #5369

**Pull request closed without merging**
