### PR TITLE
feat(components): [time-picker] add a timeFilter prop (#17120)

### LINKED ISSUE #17120: [Component] [date-picker, time-picker] 希望time-picker与date-picker支持step间隔时间功能
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.7.0`
- Browser / OS: `Chrome/125.0.6422.142`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`
- `el-time-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgdmFsdWUyID0gcmVmKCcnKVxuLy8g6IO95ZCm5pSv5oyB6Ze06ZqU5pe26Ze05Yqf6IO9XG5jb25zdCBzdGVwID0gXCIwMDowNTowMFwiXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICAgPGVsLXRpbWUtcGlja2VyXG4gICAgICB2LW1vZGVsPVwidmFsdWUyXCJcbiAgICAgIGFycm93LWNvbnRyb2xcbiAgICAgIHBsYWNlaG9sZGVyPVwiQXJiaXRyYXJ5IHRpbWVcIlxuICAgICAgc3RlcD1cInN0ZXBcIlxuICAgIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

正常使用

### What is Expected?

期望el-time-picker支持step属性，实现间隔时间功能

### What is actually happening?

没有此功能

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by wenliangzhou**
closed #17120

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
cc @element-plus/backers WDYT?

**Comment by wenliangzhou** [comment]
> cc @element-plus/backers WDYT?

image
Filter Options

**Comment by CherishTheYouth** [comment]
When will this feature be released? I really need it.

**Comment by wenliangzhou** [comment]
@btea @CherishTheYouth 
I added a timeFilter prop to the public timePicker component.

API： timeFilter: (

type: 'hours' | 'minutes' | 'seconds',

option: { key: number; disabled: boolean }

) => boolean

Return true or false to filter options


But later on, I realized that this submission was not comprehensive enough because in DateTimePicker, the value of the latter option sometimes needs to depend on the value of the previous option. But the current API cannot meet this requirement. But I haven't had time to perfect this recently.


It should be like this:

API： timeFilter: (

type: 'hours' | 'minutes' | 'seconds',

option: { key: number; disabled: boolean },

value: // value of other option

) => boolean

**Comment by wenliangzhou** [comment]
@CherishTheYouth I have temporarily published my modifications to my local repository, using the package created by Verdaccio. Perhaps it's also possible to directly package it locally, I haven't tried it before.

**Pull request closed without merging**
