### PR TITLE
docs(radio-ComponsitionApi): Update the documentation of the radio component

### PR DESCRIPTION
**Pull request by songjianet**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
I'm not quite sure what is this about, could you share some insights?

**Comment by songjianet** [comment]
> I'm not quite sure what is this about, could you share some insights?

Unified use of defineComponent, I noticed that there are many places where defineComponent is not used in the existing documents under the commitment api, and some punctuation marks will have errors in the default eslint. If you think it is not a particularly good suggestion, I can close this pr, if you think it is necessary to use defineComponent uniformly under the competition api option, I will continue to modify other problematic documents in the future

**Comment by JeremyWuuuuu** [comment]
> > I'm not quite sure what is this about, could you share some insights?
> 
> Unified use of defineComponent, I noticed that there are many places where defineComponent is not used in the existing documents under the commitment api, and some punctuation marks will have errors in the default eslint. If you think it is not a particularly good suggestion, I can close this pr, if you think it is necessary to use defineComponent uniformly under the competition api option, I will continue to modify other problematic documents in the future

Right, I'm just curious about the change though, and I think you had your point which I think is a fair point that we should do.

**Comment by JeremyWuuuuu** [comment]
But I think the tailing comma is something we'd want since we did that in the code base. Could you do some adjustment on this (Adding back the tailing comma). Also you might want to remove the tailing semicolon in the templates.

**Comment by songjianet** [comment]
> 但我认为拖尾逗号是我们想要的，因为我们在代码库中这样做了。你能不能对此做一些调整（加回尾逗号）。此外，您可能希望删除模板中的尾随分号。

I now delete the trailing comma and semicolon. I can add them back and only change the defineComponent part of the Composition Api.

**Comment by songjianet** [comment]
> But I think the tailing comma is something we'd want since we did that in the code base. Could you do some adjustment on this (Adding back the tailing comma). Also you might want to remove the tailing semicolon in the templates.

I now delete the trailing comma and semicolon. I can add them back and only change the defineComponent part of the Composition Api.

**Comment by JeremyWuuuuu** [comment]
Nah, the tailing comma needs to be there but semicolon should be deleted as you did, I am also asking you to remove the tailing semicolon in the previous added templates.
For instance:

image

**Review by iamkun — APPROVED** [review]

**Comment by songjianet** [comment]
> Nah, the tailing comma needs to be there but semicolon should be deleted as you did, I am also asking you to remove the tailing semicolon in the previous added templates.
> For instance:
> 
> image

The merge request has been approved, do I still need to make changes? Does your side need to adjust?

**Comment by JeremyWuuuuu** [comment]
I think you do @songjianet since @iamkun didn't get what I meant. But if you think this is some minor change we can do it later I will be happily to approve and merge. Let me you WDYT ;)

**Comment by songjianet** [comment]
> I think you do @songjianet since @iamkun didn't get what I meant. But if you think this is some minor change we can do it later I will be happily to approve and merge. Let me you WDYT ;)

I will make an amendment to this, and then submit it, if there are no problems, I can merge

**Comment by JeremyWuuuuu** [comment]
@songjianet 
Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.

**Comment by songjianet** [comment]
> @songjianet
> Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.

I will add back the trailing comma in the object, and the semicolon will still be deleted. I understand it this way, right?

**Comment by JeremyWuuuuu** [comment]
> > @songjianet
> > Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.
> 
> I will add back the trailing comma in the object, and the semicolon will still be deleted. I understand it this way, right?

That is correct.

**Comment by songjianet** [comment]
> > > @songjianet
> > > Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.
> > 
> > 
> > I will add back the trailing comma in the object, and the semicolon will still be deleted. I understand it this way, right?
> 
> That is correct.

Do I need to modify options related to Api? This is our first cooperation. I have many things that I am not particularly familiar with. Gradually, I will participate in the documentation of more components.

**Comment by JeremyWuuuuu** [comment]
> > > > @songjianet
> > > > Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.
> > > 
> > > 
> > > I will add back the trailing comma in the object, and the semicolon will still be deleted. I understand it this way, right?
> > 
> > 
> > That is correct.
> 
> Do I need to modify options related to Api? This is our first cooperation. I have many things that I am not particularly familiar with. Gradually, I will participate in the documentation of more components.

Can you make an example so that I would have some clues about what ur saying.

**Comment by songjianet** [comment]
> > > > > @songjianet
> > > > > Sure, thank you for being so collaborative. I will do as best as I can to offer you help during the contribution.
> > > > 
> > > > 
> > > > I will add back the trailing comma in the object, and the semicolon will still be deleted. I understand it this way, right?
> > > 
> > > 
> > > That is correct.
> > 
> > 
> > Do I need to modify options related to Api? This is our first cooperation. I have many things that I am not particularly familiar with. Gradually, I will participate in the documentation of more components.
> 
> Can you make an example so that I would have some clues about what ur saying.

image

In the documents in the existing Options Api, some objects have not added trailing commas and semicolons have not been deleted. Do I need to change this? I think the document should maintain a unified code style

**Comment by JeremyWuuuuu** [comment]
Yeah, I think it would be better if you do, but we can also separate the changes to make it more trackable.

**Comment by songjianet** [comment]
> Yeah, I think it would be better if you do, but we can also separate the changes to make it more trackable.

Take a look at this submission, right?

**Comment by songjianet** [comment]
> Yeah, I think it would be better if you do, but we can also separate the changes to make it more trackable.

I will do this. If there is no problem with this submission, I will mention the PR for revising the Options Api again. I also think it is easier to retrospectively submit the submission separately.

**Review by jw-foss — APPROVED** [review]
LGTM

**Comment by JeremyWuuuuu** [comment]
Thanks for being patient, the PR is now merged.

**Comment by songjianet** [comment]
> Thanks for being patient, the PR is now merged.

In the future, I would like to make comma and semicolon changes to the Options Api document of this component, and to change the content and code style of the Options Api and Composition Api documents of other components. Can you see this?

**Comment by songjianet** [comment]
> Thanks for being patient, the PR is now merged.

I want the document to achieve a unified code style and a complete distinction between the two Api writing methods, and now there is a mixed situation

**Pull request merged**
