### PR TITLE
docs(components): update el-input slot docs

### LINKED ISSUE #9037: [Docs] [input] Input component slots description is not correct.
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.10`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Other`

### Related Component

- `el-input`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/blob/dev/docs/en-US/component/input.md)

### Steps to reproduce

Document: https://element-plus.org/en-US/component/input.html#input-slots
Source Code: https://github.com/element-plus/element-plus/blob/dev/packages/components/input/src/input.vue#L27-L31

### What is Expected?

content as Input prefix, only works when type is not 'textarea'

### What is actually happening?

content as Input prefix, only works when type is 'text'

### Additional comments

_(empty)_

image

image

### PR DESCRIPTION
**Pull request by wangerzi**
closed #9037

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by wangerzi** [comment]
commit message already updated

**Comment by tolking** [comment]
@wangerzi  You need to format the code.

**Comment by wangerzi** [comment]
> @wangerzi You need to format the code.

@tolking Thanks for your reminding, I'm already  rebase the commit and push it again.

**Review by tolking — APPROVED** [review]

**Comment by tolking** [comment]
thanks for your contribution

**Pull request merged**
