### PR TITLE
chore: optimize md plugin config

### PR DESCRIPTION
**Pull request by winchesHe**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.
Optimize find markdown-transform plugin config
1. Define compPaths in buildStart
2. optimize display docs

before

image

after

image

### CODE REVIEW

**Comment by btea** [comment]
@winchesHe Hi, can you explain why you made the modification? Based on the screenshot you provided, I don't seem to see a difference.

**Comment by winchesHe** [comment]
> @winchesHe Hi, can you explain why you made the modification? Based on the screenshot you provided, I don't seem to see a difference.

The first point of change, as shown in the figure above, is only the optimization of redundant newlines, and the second point is to propose that the compaths variable be defined at the beginning of the build to avoid multiple definitions in the transform phase

**Comment by btea** [comment]
Oh, I see, also can reduce multiple fast-glob searches to one.

**Review by btea — APPROVED** [review]
LGTM

**Review by tolking — APPROVED** [review]

**Pull request merged**
