### PR TITLE
fix(components): [el-input] missing margin between two icons (#5942)

### LINKED ISSUE #5942: [Bug Report]: Missing padding between two icons
[reproduce](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwiaW5wdXRcIlxuICAgIHR5cGU9XCJwYXNzd29yZFwiXG4gICAgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXQgcGFzc3dvcmRcIlxuICAgIHNob3ctcGFzc3dvcmRcblx0XHRjbGVhcmFibGVcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcblxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5wdXQgPSByZWYoJycpXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

You can see the right side, missing padding:

image

<!-- generated by

### PR DESCRIPTION
**Pull request by kouchao**
close #5942

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@kouchao Hey, could you please add screenshots for the change? Before your change, and after your change. Thank you so much for contributing! :pray:

**Comment by kouchao** [comment]
### before - input
image

### after - input
image
---

### before - mouse over
image

### after - mouse over
image
---
### before - focus
image

### after - focus
image

@JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
@kouchao Thank you! There is one thing left for you, could you change the `10px` to `8px`? After updating that we should be able to merge this PR. :bow:

**Comment by kouchao** [comment]
@JeremyWuuuuu  done

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
