### PR TITLE
refactor(components): el-time-picker icon

### PR DESCRIPTION
**Pull request by adaex**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by adaex** [comment]
**Be sure to merge the `date-picker` first**

**Comment by adaex** [comment]
https://preview-3834-element-plus.surge.sh/en-US/component/time-picker.html @imswk

**Comment by imswk** [comment]
image
This document part has not been modified

**Comment by adaex** [comment]
> image This document part has not been modified

fixed in `el-input` branch

**Comment by adaex** [comment]
> image Doesn't appear to be centered vertically


fixed in el-input branch

**Review by adaex — COMMENTED** [review]
PTAL @JeremyWuuuuu 
https://preview-3834-element-plus.surge.sh/en-US/component/time-picker.html

**Please merge this branch last.**

**Review by imswk — APPROVED** [review]

**Pull request merged**
