### PR TITLE
feat(docs): support playground sync theme

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

Sync https://github.com/element-plus/element-plus-playground/pull/265

### CODE REVIEW

**Comment by kooriookami** [comment]
There's an error in dark mode: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

**Comment by btea** [comment]
I created this PR so that if the `dark` mode is selected when viewing the document, it will also be set to `dark` mode simultaneously when clicking on `playground` to jump.

I don’t understand a bit about the error you mentioned in `dark` mode. 🤔

**Comment by kooriookami** [comment]
[Demo](https://element-plus.run/?pr=16735#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24+RGVmYXVsdDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCI+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCI+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG4gIDxkaXYgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiBwbGFpbj5QbGFpbjwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBwbGFpbj5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHBsYWluPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcGxhaW4+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiBwbGFpbj5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcGxhaW4+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG4gIDxkaXYgY2xhc3M9XCJtYi00XCI+XG4gICAgPGVsLWJ1dHRvbiByb3VuZD5Sb3VuZDwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiByb3VuZD5QcmltYXJ5PC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwic3VjY2Vzc1wiIHJvdW5kPlN1Y2Nlc3M8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJpbmZvXCIgcm91bmQ+SW5mbzwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cIndhcm5pbmdcIiByb3VuZD5XYXJuaW5nPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgcm91bmQ+RGFuZ2VyPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG4gIDxkaXY+XG4gICAgPGVsLWJ1dHRvbiA6aWNvbj1cIlNlYXJjaFwiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiA6aWNvbj1cIkVkaXRcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJzdWNjZXNzXCIgOmljb249XCJDaGVja1wiIGNpcmNsZSAvPlxuICAgIDxlbC1idXR0b24gdHlwZT1cImluZm9cIiA6aWNvbj1cIk1lc3NhZ2VcIiBjaXJjbGUgLz5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJ3YXJuaW5nXCIgOmljb249XCJTdGFyXCIgY2lyY2xlIC8+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwiZGFuZ2VyXCIgOmljb249XCJEZWxldGVcIiBjaXJjbGUgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgQ2hlY2ssXG4gIERlbGV0ZSxcbiAgRWRpdCxcbiAgTWVzc2FnZSxcbiAgU2VhcmNoLFxuICBTdGFyLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuIn0=&theme=dark)

**Comment by btea** [comment]
Thanks for the demo, I understand.

**Comment by kooriookami** [comment]
image

Components still be light.

**Comment by btea** [comment]
This should be a problem on the playground side. The dark mode code corresponding to the PR-generated style code is not loaded.

**Review by tolking — APPROVED** [review]

**Pull request merged**
