### PR TITLE
fix(date-picker): modify the judgment logic of startDate and endDate

### LINKED ISSUE #1320: [bug report] datepicker when selecting a date range, when the first value is greater than the second value, the selected part has no background color
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
windows 10

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/pen/?&prefill_data_id=9a116ca3-a4ae-4e38-8ef9-9b4a562d2a2b

### Steps to reproduce
点击输入框->选择第一个值->滑动鼠标选择第二个值（要求为第一个值之前的日期，比如第一个值选择2021-01-24，第二个选择2021-01-01）->现象为选中部分没有背景颜色

### What is Expected?
有背景颜色区分

### What is actually happening?
实际没有背景色不好区分

### PR DESCRIPTION
**Pull request by BeADre**
fix #1320

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Would you mind adding test cases against this change?

**Comment by zazzaz** [comment]
LGTM, it will be great to add some test

**Comment by BeADre** [comment]
@JeremyWuuuuu @zazzaz  done

**Review by zazzaz — APPROVED** [review]

**Pull request merged**
