### PR TITLE
fix(components): [table] tooltipOptions.showAfter is not effective

### LINKED ISSUE #12564: [Component] [table] table组件，tooltipOptions.showAfter不生效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiA6dG9vbHRpcC1vcHRpb25zPVwie3Nob3dBZnRlcjogMTAwMH1cIiBzdHlsZT1cIndpZHRoOiAxMDAlXCI+XG4gICAgPGVsLXRhYmxlLWNvbHVtbiBwcm9wPVwiZGF0ZVwiIGxhYmVsPVwiRGF0ZVwiIHdpZHRoPVwiMTgwXCIgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uIHByb3A9XCJuYW1lXCIgbGFiZWw9XCJOYW1lXCIgd2lkdGg9XCIxODBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cImFkZHJlc3NcIiBsYWJlbD1cIkFkZHJlc3NcIiBzaG93LW92ZXJmbG93LXRvb2x0aXAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAzJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

el-table 设置:tooltip-options="{ showAfter: 1000 }"，el-table-column 设置show-overflow-tooltip；文字超出时发现tooltip还是立即出现

### What is Expected?

希望延迟展示tooltip

### What is actually happening?

tooltip还是立即出现

### PR DESCRIPTION
**Pull request by xingyixiang**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at bd69775</samp>

Add `showAfter` option for table tooltip and improve popper logic in `util.ts`. This allows users to customize the tooltip delay and fixes some bugs with the popper positioning and visibility.

## Related Issue

Fixes #12564, #14678.

### <samp>🤖 Generated by Copilot at bd69775</samp>

*  Add `showAfter` option for table tooltip to delay popper appearance ([link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L367-R384), [link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L382-R408), [link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R428-R430), [link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R443))
  * Define `togglePopperVisible` function to modify popper display style based on parameter ([link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L367-R384))
  * Simplify `onOpen` and `onClose` handlers assignment from `useDelayedToggle` hook ([link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L382-R408))
  * Add modifier to popper instance to initially hide popper if `showAfter` is enabled ([link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R428-R430))
  * Call `onOpen` at the end of `createTablePopper` function to create and update popper instance and start delay timer ([link](https://github.com/element-plus/element-plus/pull/13175/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R443))

### CODE REVIEW

**Comment by btea** [comment]
Seems to be the same as #12578

**Comment by xingyixiang** [comment]
Playground[XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTMxNzUtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xMzE3NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMzE3NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMzE3NS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ](url)

**Comment by xingyixiang** [comment]
@btea No one review the code

**Comment by ryuhangyeong** [comment]
I'll take a look when I can afford it~

**Comment by PeiJM** [comment]
还是无效啊?

**Comment by xingyixiang** [comment]
@PeiJM 代码没合入，没人review

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]

**Comment by xingyixiang** [comment]
@btea

**Comment by xingyixiang** [comment]
@btea When can the code be incorporated?

**Comment by btea** [comment]
Thank you for your contribution. It looks good, let's merge it now.

**Comment by xingyixiang** [comment]
@btea Sorry, there is something wrong with this mr. After tooltipOptions.showAfter is set, the popper will be closed when the mouse is moved to the popper and then to the table cell. You can roll back this mr. I'll study how to modify it.

**Comment by xingyixiang** [comment]
@btea 之前因为showAfter不生效，所以鼠标进入popper后，重新进入table的cell，会触发销毁removePopper。并重新走createTablePopper流程，此方法会立刻创建出一个新的popper并立刻展示，所以实际效果是再次移入table的cell不会关闭popper。现在showAfter生效，就需要一段时间才能重新展示。导致出现这个现象
(In the previous version, the showAfter command does not take effect. Therefore, after the cursor is moved to the popper and the cell of the table is re-entered, the removePopper will be destroyed. The createTablePopper process is used again. This method creates a new popper immediately and displays it immediately. Therefore, the actual effect is that the popper will not be closed when the cell is moved to the table again. Now that showAfter takes effect, it takes a while to redisplay it. Causes this phenomenon)

**Comment by btea** [comment]
Indeed, the reason is exactly as you said. Maybe we can add a flag, if showAfter is set, we can delay the popper from closing, and then close it if the creation is not triggered again in a short period of time. 
What do you think? @xingyixiang @tolking

**Comment by xingyixiang** [comment]
@btea @tolking 
微信图片_20231104110732
Just delete removePopper?.(), I don't know if it has any other effects

**Comment by xingyixiang** [comment]
@btea @tolking 
[#14741 ](https://github.com/element-plus/element-plus/pull/14741)

**Pull request merged**
