### PR TITLE
fix(components): [el-input] change icon when toggling password visibility

### PR DESCRIPTION
**Pull request by plainheart**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

It would be better to change the icon to **View**/**Hide** when toggling the visibility of the password. Currently, it always keeps the same icon **View**.

**Comparison**

| Before | After |
| :----: | :----: |
| Before | After |

### CODE REVIEW

**Review by HeftyKoo — APPROVED** [review]

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@plainheart Hi, just wondering would you like to join us maintaining Element Plus? If you'd like that please let me know! Thanks!

**Comment by plainheart** [comment]
@JeremyWuuuuu Thank you for the invitation. It would be my pleasure to help maintain Element Plus.

**Comment by JeremyWuuuuu** [comment]
@plainheart Just send you the invitation. Please check your email. :P

**Comment by plainheart** [comment]
@JeremyWuuuuu Accepted. Thanks!

**Comment by JeremyWuuuuu** [comment]
@plainheart I sent an email to your public email address, please take a look at it :bow:

**Pull request merged**
