### PR TITLE
fix(components): [tooltip] teleport change with visible

### LINKED ISSUE #10240: [Component] [popover] 【紧急】popover组件内使用v-model控制显示，点击内容区会自动收起
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.2.19`
- Browser / OS: `mac`
- Build Tool: `Vue CLI`

### Related Component

- `el-popover`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlclxuICAgIHYtbW9kZWw6dmlzaWJsZT1cInZpc2libGVcIlxuICAgIHBsYWNlbWVudD1cImJvdHRvbVwiXG4gICAgOndpZHRoPVwiMjAwXCJcbiAgPlxuICAgIDxkaXY+XG4gICAgICA8ZWwtc2VsZWN0XG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCJcbiAgICAgIHN0eWxlPVwid2lkdGg6IDI0MHB4XCJcbiAgICA+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuICAgIDwvZGl2PlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJ2aXNpYmxlID0gIXZpc2libGVcIj5NYW51YWwgdG8gYWN0aXZhdGU8L2VsLWJ1dHRvbj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLXBvcG92ZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCB2aXNpYmxlID0gcmVmKGZhbHNlKVxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gW1xuICB7XG4gICAgdmFsdWU6ICdPcHRpb24xJyxcbiAgICBsYWJlbDogJ09wdGlvbjEnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24yJyxcbiAgICBsYWJlbDogJ09wdGlvbjInLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb24zJyxcbiAgICBsYWJlbDogJ09wdGlvbjMnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb240JyxcbiAgICBsYWJlbDogJ09wdGlvbjQnLFxuICB9LFxuICB7XG4gICAgdmFsdWU6ICdPcHRpb241JyxcbiAgICBsYWJlbDogJ09wdGlvbjUnLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

点击按钮后 选择选择器值

### What is Expected?

点击按钮后 选择选择器值 不会收起，只有改变visible才收起

### What is actually happening?

点击按钮后选择选择器值莫名收起

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Simon-He95**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix: #10240

I think the teleport need to change with visible 

invisible: the content is under the body
visible: the content is under the using container

### CODE REVIEW

**Comment by chenxch** [comment]
Please try to do a good job of unit testing locally before submitting. It is not recommended to delete existing APIs at will, which will cause confusion to users.

**Comment by Simon-He95** [comment]
> Please try to do a good job of unit testing locally before submitting. It is not recommended to delete existing APIs at will, which will cause confusion to users.

the teleported default true will lead to always true, I revert the props temporarily.
Because multiple components use this prop, l think it needs to be transformed into a ref teleport inside the component

**Comment by Simon-He95** [comment]
@chenxch please help me review the code，tell me what you think？

**Comment by Simon-He95** [comment]
Hi, @jw-foss could you help me review the code? I think it can solve many problems similar to the disappearance of the pop-up layer using the teleport component

**Comment by jw-foss** [comment]
> Hi, @jw-foss could you help me review the code? I think it can solve many problems similar to the disappearance of the pop-up layer using the teleport component

Sure, looking 👀

**Comment by Simon-He95** [comment]
> > Hi, @jw-foss could you help me review the code? I think it can solve many problems similar to the disappearance of the pop-up layer using the teleport component
> 
> Sure, looking 👀

Thanks, feel free to contact me if you have any questions

**Comment by jw-foss** [comment]
@Simon-He95 I do not think this is the best way for solving the issue you were trying to solve. I posted the correct way to use manual trigger in the issue, I'm going to close this PR, thank you for your contribution 😄

**Comment by Simon-He95** [comment]
> 

I think where this container is going to go should be directly determined by to. I don't need to use disabled anymore. When it is visible, it will be in the position of to. In addition, it should be in the original DOM structure by default. If to is equal to body, it should be under the body. what do you think ？

**Comment by jw-foss** [comment]
Have you ever considered what type of changes this PR will bring to the users who are already using `teleported` and `appendTo` API?

I very much appreciated the work you put into this but this is just not the correct way of fixing these issues, the actual issue here is that 
the way how they use this component is not correct, I must admit that the documentation sucks and I will try to amend it ASAP. :pray:

**Comment by Simon-He95** [comment]
> R

Thank you for your reply, I did consider how to use this thing more conveniently, to ignore the people who have already used it.

**Comment by GregLtrnr** [comment]
> 

Hey, can you explain how to fix this problem ? I still have this issue and I would like to take a look at the PR you opened

**Comment by trry-github** [comment]
It seems that this problem has not been solved yet. Are there any alternative solutions?

**Pull request closed without merging**
