### PR TITLE
docs(collapse): update collapse docs #704

### PR DESCRIPTION
**Pull request by dwanl**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Hey buddy, please sync up with the `origin/dev` branch before you make any changes. Try google: "How to sync with forked repo"

**Comment by xingleizhao** [comment]
In `origin/dev`, will failed to compile occur?

**./packages/element-plus/index.ts**

`Module not found: Error: Can't resolve './version'`

image

**Comment by zazzaz** [comment]
@xingleizhao you can merge the latest dev branch, and run `yarn bootstrap`

**Comment by xingleizhao** [comment]
> @xingleizhao，您可以合并最新的dev分支并运行`yarn bootstrap`

Oh, thank you.

**Pull request closed without merging**
