### PR TITLE
chore(project): compatible windows the shell command

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

When the shell command is written to a line, an error will be reported on Windows system like this describe #3509

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@btea thank you for contributing this, have you tested this locally? I was not aware of the shell commands is not compatible for Windows, my apologies.

**Comment by btea** [comment]
@JeremyWuuuuu When I run `yarn docs:dev` locally, the terminal reported the error.
image

After I move the command to `ifBuild.sh` file,  the `build.sh` can running normally like this.
image

**Comment by JeremyWuuuuu** [comment]
@btea great, then let's merge it.

**Review by jw-foss — APPROVED** [review]

**Comment by btea** [comment]
@JeremyWuuuuu There is another problem. Windows does not have `rsync` command by default. Can I use other compatibility commands instead?
image

**Pull request merged**
