### PR TITLE
fix(components): [el-form] fix form style

### LINKED ISSUE #5006: [Bug Report] 表单验证功能和input插槽suffix同时存在时，Form表单status-icon为false失效
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Windows  /  Chrome 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/yangguanglei/pen/poWpKQz

### Steps to reproduce
光标聚焦到输入框，再离开触发rule校验 ———>显示bug

### What is Expected?
账号和密码输入框都不应该出现校验提示图标

### What is actually happening?
密码输入框出现了校验提示图标

### LINKED ISSUE #5141: [Bug Report] ElForm status-icon BUG
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
版本 96.0.4664.110（正式版本） （64 位）

### Vue version
3.2.26

### Reproduction Link
https://jsfiddle.net/ah4q0tfL/3/

### Steps to reproduce
When the clearable attribute of El input is set, the stauts-icon in El form displays an exception

### What is Expected?
stauts-icon should not appear

### What is actually happening?
stauts-icon appears

### LINKED ISSUE #5202: [Feature Request] The current design is a little ugly when form's s label-positon = 'top'  and size="small"
### Existing Component
Yes

### Component Name
form

### Description
The current design is a little ugly when form's s label-positon = 'top' ,belows are the example code:
```
// the gap between `ID` and input is too wide
<el-form size="small" label-position="top">
      <el-form-item label="ID：">
        <el-input></el-input>
      </el-form-item>
</el-form>
```

maybe it is more beautiful when the padding value should adjust with form size
image

### PR DESCRIPTION
**Pull request by kooriookami**
- [x] Remove status icon
image

- [x] Add 32px gap after inline form item
image

- [x] Ajust margin-bottom of form-item
image

- [x] Ajust gap of position top
image

### CODE REVIEW

**Comment by emojiiii** [comment]
oh, no! it's repeat! please see this [pr](https://github.com/element-plus/element-plus/pull/5013).

**Comment by kooriookami** [comment]
> oh, no! It's partly repeated! please see this [pr](https://github.com/element-plus/element-plus/pull/5013).

Oh, damn!

**Comment by kooriookami** [comment]
Fix #5006

**Comment by kooriookami** [comment]
#5202

**Review by jw-foss — CHANGES_REQUESTED** [review]
Change `defaut` to `default`

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
