### PR TITLE
fix(components): [watermark] Prevent console from deleting dom

### PR DESCRIPTION
**Pull request by jevin98**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

## Description

1.What happened？
  I found that users can delete watermarks through the console, but new watermarks will not be regenerated.

## Related Issue

Fixes #\_\_\_.

## Explanation of Changes

1. Save the parent dom
2. Use the useIntersectionObserver method in vueuse to monitor whether the watermark dom disappears
3. Append the disappeared watermark back to the parent dom

### CODE REVIEW

**Review by ryuhangyeong — COMMENTED** [review]
Can you provide example code for your problem?

**Comment by Jevin0** [comment]
[example ](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXdhdGVybWFyaz5cbiAgICA8ZGl2IHN0eWxlPVwiaGVpZ2h0OiA1MDBweFwiIC8+XG4gIDwvZWwtd2F0ZXJtYXJrPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

If I open the console through F12 and find the root element of the watermark component to delete it, the watermark component dom will not be regenerated.

**Comment by ryuhangyeong** [comment]
releated #14822

Is this what you want?

**Review by ryuhangyeong — COMMENTED** [review]
releated #14822

Is this what you want?

**Comment by Jevin0** [comment]
No, I have read this PR. It only solves the problem that if the watermark dom's own attributes are changed, the dom will be regenerated. However, if the parent node dom is manually deleted, it will not be regenerated.

**Comment by Jevin0** [comment]
Uploading 1700883195000.mp4…

This is my operation process, you can take a look

**Comment by Jevin0** [comment]
https://github.com/element-plus/element-plus/assets/69580637/49fc5ab7-bcd6-40c6-ba9f-857595051021

This is my operation process, you can take a look

**Comment by Jevin0** [comment]
@ryuhangyeong Do you think this question of mine is a real problem?

**Pull request closed without merging**
