### PR TITLE
build!: simplify build & support native esm import

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sxzz** [comment]
@JeremyWuuuuu Done.

**Review by jw-foss — CHANGES_REQUESTED** [review]
I left a few comments for you to consider. It is not suggested that we modify code which is not relevant to this PR.

**Comment by JeremyWuuuuu** [comment]
Also I think the output of the change seems weird, not saying that the bundled output should be readable. Based on the change, we will also make sure that the plugin that we provided can fetch the correct css file but I don't think naming `css[digits].js` is a good idea of fetching `css.js` and `index.css.js`

**Comment by sxzz** [comment]
Done.

**Comment by JeremyWuuuuu** [comment]
I actually think these output files were not needed for publishing since we already have `[component].js`, could we avoid emitting these files?

image

**Comment by JeremyWuuuuu** [comment]
@sxzz The code LGTM, but I think we need to make the published bundle as smaller as possible since some outputs were not needed at all.

**Review by jw-foss — APPROVED** [review]

**Comment by bitjjj** [comment]
build脚本貌似会有问题：
```js
parallel(
    runTask('buildModules'),
    runTask('buildFullBundle'),
    runTask('generateTypesDefinitions'),
    runTask('buildHelper'),
    series(
      withTaskName('buildThemeChalk', () =>
        run('pnpm run -C packages/theme-chalk build')
      ),
      copyFullStyle
    )
  ),
```
如果最后一个series task先于buildFullBundle完成，copy index.css以及font的时候，dist目录会找不到。本地跑出现了这个错误，不知道会不会有影响？

**Pull request merged**
