### PR TITLE
fix(carousel): blank happened when using indicator

### PR DESCRIPTION
**Pull request by binvb**
reference: https://github.com/element-plus/element-plus/issues/2535  

在走马灯切换时候先等新的active模块切换好了之后，再把原位置的banner切换走

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
I think the issue here is that the whole functionality is weird. 

Say if we have something like going from item 2 to item 4, we have 2 ways of doing so:
1. Moving forward, via 2 -> 3 -> 4.
2. Moving backward, via 2 -> 1 -> 4. This is the current moving strategies that we have which I think is weird. Logically we think that from 2 to 4 we normally use the first approach which is 2 -> 3 -> 4, but here instead of the normal approach we used 2 -> 1 -> 4 which naturally caused the the issue.

Also your change broke the animation which directly skipped the middle state 3, I think you might need to refine your change though.

**Comment by binvb** [comment]
> I think the issue here is that the whole functionality is weird.
> 
> Say if we have something like going from item 2 to item 4, we have 2 ways of doing so:
> 
> 1. Moving forward, via 2 -> 3 -> 4.
> 2. Moving backward, via 2 -> 1 -> 4. This is the current moving strategies that we have which I think is weird. Logically we think that from 2 to 4 we normally use the first approach which is 2 -> 3 -> 4, but here instead of the normal approach we used 2 -> 1 -> 4 which naturally caused the the issue.
> 
> Also your change broke the animation which directly skipped the middle state 3, I think you might need to refine your change though.

i think it's only active item has transition: transform .4s ease(other item is default) caused the blank problem. but your are right, it should be in a reasonable order. i will refine this commit later,thank you

**Comment by JeremyWuuuuu** [comment]
> > I think the issue here is that the whole functionality is weird.
> > Say if we have something like going from item 2 to item 4, we have 2 ways of doing so:
> > 
> > 1. Moving forward, via 2 -> 3 -> 4.
> > 2. Moving backward, via 2 -> 1 -> 4. This is the current moving strategies that we have which I think is weird. Logically we think that from 2 to 4 we normally use the first approach which is 2 -> 3 -> 4, but here instead of the normal approach we used 2 -> 1 -> 4 which naturally caused the the issue.
> > 
> > Also your change broke the animation which directly skipped the middle state 3, I think you might need to refine your change though.
> 
> i think it's only active item has transition: transform .4s ease(other item are defaults) caused the blank problem. but your are right, it should be in a reasonable order. i will refine this commit later,thank you

Sorry for the late response, and thank you for being collaborative, we look forward to see the updated version of this 👍

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Pull request closed without merging**
