### PR TITLE
fix(dialog): solve window inside click move to the outside will close

### LINKED ISSUE #1248: [Bug Report] dialog inside click move to the outside will close
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
chrome

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/vgbire/pen/gOwdYLm

### Steps to reproduce
The pop-up example on the official website has this problem

### What is Expected?
When you click inside the pop-up window and release outside the pop-up window, it should not be closed. When you click inside the mask and release inside the pop-up window, it should not be closed

### What is actually happening?
In both cases, they shut down.The drawer has the same problem

### PR DESCRIPTION
**Pull request by Vgbire**
fix #1248
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Umm. I had a fix #1235  to fix this issue.

**Comment by JeremyWuuuuu** [comment]
But I've seen your code. The way that you implemented the code seems better than my implementation, so after #1235 gets merged. I'll invite you to optimize the code.

**Comment by Vgbire** [comment]
Yeah,By the way,I meet a question.I found that deleting 31 lines of dialog index.vue still solved the problem.But I'm not sure if he has any other problems, so I keep it.
image

**Comment by JeremyWuuuuu** [comment]
See #1235 , already merged. This issue was caused by click event trigger mechanism.  So I am going to closing this PR, I also want to ask if you still want to make a PR for the `v-same-dom` directive.

**Comment by Vgbire** [comment]
> See #1235 , already merged. This issue was caused by click event trigger mechanism. So I am going to closing this PR, I also want to ask if you still want to make a PR for the `v-same-dom` directive.

yeah,I will.But how I make it.pull this request once again?

**Comment by zazzaz** [comment]
a new pull request is cool

**Pull request closed without merging**
