### PR TITLE
fix(components): [image-viewer] Maximum recursive updates exceeded error

### LINKED ISSUE #15234: [Component] [image-viewer] el-image-viewer 组件 一个页面写多个会出现 ”超过组件基转换的最大递归更新“ 警告
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.4.3`
- Browser / OS: `macOs`
- Build Tool: `Vite`

### Related Component

- `el-image-viewer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBlcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1pbWFnZS12aWV3ZXI+PC9lbC1pbWFnZS12aWV3ZXI+XG4gIDxlbC1pbWFnZS12aWV3ZXI+PC9lbC1pbWFnZS12aWV3ZXI+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

<template>
	<el-image-viewer></el-image-viewer>
<el-image-viewer></el-image-viewer>
</template>

### What is Expected?

不会出现警告

### What is actually happening?

出现警告

### Additional comments

给个解决方案 ，我想把这个组件封装到指令里面

### PR DESCRIPTION
**Pull request by Fuphoenixes**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fixed: https://github.com/element-plus/element-plus/issues/15234

### CODE REVIEW

**Review by kooriookami — APPROVED** [review]

**Review by kooriookami — COMMENTED** [review]
It can be simplified:
const zIndex = ref(props.zIndex ?? nextZIndex())
No need to use the computed function, and when it opened, you need to reset the zIndex.
You can refer to the dialog component. :D

**Comment by Fuphoenixes** [comment]
yeah, it's better!

**Comment by kooriookami** [comment]
When image-viewer shows, the z-index should be updated.
Look this: https://github.com/element-plus/element-plus/blob/dev/packages/components/dialog/src/use-dialog.ts#L165

**Comment by Fuphoenixes** [comment]
image-viewer use v-if to shows, so we don't need to do this.

**Comment by kooriookami** [comment]
> image-viewer use v-if to shows, so we don't need to do this.

OK, my bad~

**Pull request merged**
