### PR TITLE
fix(theme-chalk): [el-table] fix custom header background of fixed column

### PR DESCRIPTION
**Pull request by plainheart**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Fix the customized background color of the fixed column header isn't correct.

Please refer to this [playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICAgIDxlbC10YWJsZSBib3JkZXIgOmRhdGE9XCJkYXRhXCIgc3R5bGU9XCJ3aWR0aDogNTAwcHg7IC0tZWwtdGFibGUtaGVhZGVyLWJnLWNvbG9yOiAjZmFmYWZhXCI+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiTmFtZVwiIHByb3A9XCJuYW1lXCIgZml4ZWQ9XCJsZWZ0XCIgd2lkdGg9XCIxMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIlBob25lXCIgcHJvcD1cInBob25lXCIgd2lkdGg9XCIxMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkFkZHJlc3NcIiBwcm9wPVwiYWRkcmVzc1wiIHdpZHRoPVwiMjAwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25cIiBhbGlnbj1cImNlbnRlclwiIGZpeGVkPVwicmlnaHRcIiB3aWR0aD1cIjEwMFwiPlxuICAgICAgICA8ZWwtYnV0dG9uIHNpemU9XCJzbWFsbFwiPkVkaXQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdGFibGUtY29sdW1uPlxuICAgIDwvZWwtdGFibGU+XG4gIFxuICBcdDxlbC10YWJsZSBib3JkZXIgOmRhdGE9XCJkYXRhXCIgc3R5bGU9XCJ3aWR0aDogNDAwcHg7IC0tZWwtdGFibGUtaGVhZGVyLWJnLWNvbG9yOiAjZmFmYWZhOyBtYXJnaW4tdG9wOiA1MHB4XCI+XG4gICAgICA8ZWwtdGFibGUtY29sdW1uIGxhYmVsPVwiTmFtZVwiIHByb3A9XCJuYW1lXCIgZml4ZWQ9XCJsZWZ0XCIgd2lkdGg9XCIxMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIlBob25lXCIgcHJvcD1cInBob25lXCIgd2lkdGg9XCIxMDBcIiAvPlxuICAgICAgPGVsLXRhYmxlLWNvbHVtbiBsYWJlbD1cIkFkZHJlc3NcIiBwcm9wPVwiYWRkcmVzc1wiIHdpZHRoPVwiMjAwXCIgLz5cbiAgICAgIDxlbC10YWJsZS1jb2x1bW4gbGFiZWw9XCJPcGVyYXRpb25cIiBwcm9wPVwiY2VudGVyXCIgYWxpZ249XCJjZW50ZXJcIiBmaXhlZD1cInJpZ2h0XCIgd2lkdGg9XCIxMDBcIj5cbiAgICAgICAgPGVsLWJ1dHRvbiBzaXplPVwic21hbGxcIj5FZGl0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRhYmxlLWNvbHVtbj5cbiAgICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IGRhdGEgPSBbXG4gIHtcbiAgICBuYW1lOiAnSmFja3knLFxuICAgIHBob25lOiAnMTIzNDU2Nzg5JyxcbiAgICBhZGRyZXNzOiAnRWFydGhFYXJ0aEVhcnRoRWFydGhFYXJ0aCdcbiAgfVxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbmh0bWwsIGJvZHkge1xuICB3aWR0aDogMTAwdnc7XG4gIGhlaWdodDogMTAwdmg7XG4gIG1hcmdpbjogMDtcbn1cbiNhcHAge1xuICBoZWlnaHQ6IDEwMCU7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICBmbGV4LWRpcmVjdGlvbjogY29sdW1uO1xufVxuPC9zdHlsZT5cblxuXG5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==),

- When the table is not scrollable, **(the top table)**
  - **_is-scrolling-none_**: should be customized color.

| Before | After |
| :----: | :----: |
| Before | After |

- When the table is scrollable: **(the bottom table)**
  - **_is-scrolling-left_**: the columns fixed at the left should be the customized color when the scrollbar is at the left
  - **_is-scrolling-middle_**: the fixed columns should be **#fff** when the scrollbar is at the middle
  - **_is-scrolling-right_**: the columns fixed at the right should be the customized color when the scrollbar is at the right

| - | Left | Middle | Right |
| :----: | :----: | :----: | :----: |
| Before | Left | Middle | Right |
| After | Left | Middle | Right |

And I didn't add the test case as it seems we currently can't get and check the final computed background color in jest.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@msidolphin Could you please take a look on this one?

**Comment by JeremyWuuuuu** [comment]
@plainheart Excellent!

**Review by msidolphin — DISMISSED** [review]

**Review by msidolphin — COMMENTED** [review]
image

I found the style is not effective

**Comment by plainheart** [comment]
Do you mean we should remove `#fff` background color? I didn't remove it as I thought it was to highlight the fixed column.

**Comment by msidolphin** [comment]
> Do you mean we should remove `#fff` background color? I didn't remove it as I thought it was to highlight the fixed column.

Yeah, `#fff` will also override `var(--el-table-header-bg-color)`, do you think we need to change `#fff` to `var(--el-table-header-bg-color)`?

**Comment by plainheart** [comment]
> do you think we need to change #fff to var(--el-table-header-bg-color)?

The previous behavior is acceptable in my view. But it should be better if we change to `var(--el-table-header-bg-color)`  as it won't confuse the users at least.

**Comment by plainheart** [comment]
I found we shouldn't remove the background color `#fff` because it's useful for `td` to avoid the transparent background. So I added some specified styles for `th`. Also, I updated the playground for preview.

| - | Left | Right |
| :----: | :----: | :----: |
| **Unexpected** | image | image |
| **Expected** | image | image |

**Review by msidolphin — APPROVED** [review]

**Pull request merged**
