### PR TITLE
chore(project): Modify config

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@btea We didn't put `docs` into packages for reasons, since under `packages` we have `element-plus` folder which is a symbolic link in `node_modules` and we utilize local build when developing or on staging, by doing this your way, you create the access for docs to access `root/node_modules/element-plus` which is not a built version of Element Plus. This won't work. 

Please revert that change.

**Comment by btea** [comment]
> @btea We didn't put `docs` into packages for reasons, since under `packages` we have `element-plus` folder which is a symbolic link in `node_modules` and we utilize local build when developing or on staging, by doing this your way, you create the access for docs to access `root/node_modules/element-plus` which is not a built version of Element Plus. This won't work.
> 
> Please revert that change.

ok, I will close the pr.

**Comment by JeremyWuuuuu** [comment]
@btea I was not asking you close this PR since exposing `host` LGTM, the question you were asking I might not have the answer for you, but question is that can you setup your local dev env correctly?

**Comment by btea** [comment]
@JeremyWuuuuu Thanks! I will revert the code. And about the dev question i will open an issue.

**Comment by btea** [comment]
Sorry, the message is confused, I will rebuild the PR.

**Pull request closed without merging**
