### PR TITLE
test: fix ci image/avatar test error

### PR DESCRIPTION
**Pull request by warmthsea**
#### Edit Before: dev test*70 ✅

image

#### Edit before: probabilistic occurrence (Is the node version affected?) ❗
https://github.com/element-plus/element-plus/pull/16860#issuecomment-2109960857

image

#### Edit After:
✅

### CODE REVIEW

**Comment by warmthsea** [comment]
@btea 
Please ask a question, how can I execute ci unit-test again without changing the code?

**Comment by warmthsea** [comment]
new test error `avatar`

image

**Comment by btea** [comment]
> @btea Please ask a question, how can I execute ci unit-test again without changing the code?

Generally, it will only be run when the code is updated, or the project team members can help click re-run.
Regarding the test case you modified, it sometimes fails, but it should be related to the environment, so there is no need to modify it, just rerun it.

**Comment by warmthsea** [comment]
I only changed the test errors that I encountered with a high probability. (CI)

**Review by btea — APPROVED** [review]
I ran several tests and everything seemed to be normal. We can merge this PR first and see if there will be no errors in the future.

**Comment by warmthsea** [comment]
> I ran several tests and everything seemed to be normal. We can merge this PR first and see if there will be no errors in the future.

I added 25 duplicate CIs for testing, and 1 or 2 errors occurred each time.

screenshots

**Comment by btea** [comment]
I looked at some of the error conditions, and it seems that they are not a problem with the use case, but an internal problem with jsdom. This random situation can be ignored.

**Comment by warmthsea** [comment]
> I looked at some of the error conditions, and it seems that they are not a problem with the use case, but an internal problem with jsdom. This random situation can be ignored.

OK.

**Comment by sleepyShen1989** [comment]
It seems that this problem still exists
捕获

https://github.com/element-plus/element-plus/actions/runs/9378167810/job/25820936910

**Pull request merged**
