### PR TITLE
style(docs): change DocSearch colors

### PR DESCRIPTION
**Pull request by mewcoder**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
Can you please tell me why I need to change this?

**Comment by mewcoder** [comment]
> Can you please tell me why I need to change this?

I modify DocSearch to brand color and optimize its dark mode, as shown in the picture: 
image

**Comment by chenxch** [comment]
cc @YunYouJun

**Comment by YunYouJun** [comment]
Thanks.

**Review by YunYouJun — APPROVED** [review]

**Pull request merged**
