### PR TITLE
fix(components): fix #8663

### LINKED ISSUE #8663: [Component] [time-picker] 时间范围选择器在点击图标的时候会弹出两次，其他情况在点击图标时会有闪烁
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome103.0.5060.66/windows11`
- Build Tool: `Vite`

### Related Component

- `el-time-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/time-picker.html#%E4%BB%BB%E6%84%8F%E6%97%B6%E9%97%B4%E8%8C%83%E5%9B%B4)

### Steps to reproduce

时间选择器， 点击钟表图标

### What is Expected?

正常弹出

### What is actually happening?

范围会闪烁一次后在正常弹出， 其他的闪烁一次后不在弹出

### Additional comments

_(empty)_

### LINKED ISSUE #8667: [Component] [message-box, date-picker] 消息弹框中使用ElDatePicker无法选中日期
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.8`
- Browser / OS: `Chrome 103.0.5060.66 / win10`
- Build Tool: `Vite`

### Related Component

- `el-message-box`
- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGgsIHJlZiAsb25Nb3VudGVkIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxEYXRlUGlja2VyLEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcblxub25Nb3VudGVkKCgpID0+IHtcbiAgIEVsTWVzc2FnZUJveCh7XG4gICAgIHRpdGxlOiAn6YCJ5oup5pe26Ze05rKh5pyJdWnmlYjmnpwnLFxuICAgICBtZXNzYWdlOiBoKEVsRGF0ZVBpY2tlciwge1xuICAgICAgIHN0eWxlOiB7XG4gICAgICAgICB3aWR0aDogJzEwMCUnLFxuICAgICAgIH0sXG4gICAgICAgcGxhY2Vob2xkZXI6ICfml7bpl7QnLFxuICAgICAgIGNsZWFyYWJsZTogZmFsc2UsXG4gICAgICAgdHlwZTogJ2RhdGV0aW1lJyxcbiAgICAgICB2YWx1ZUZvcm1hdDogJ1lZWVktTU0tREQgSEg6bW06c3MnLFxuICAgICAgIG1vZGVsVmFsdWU6ICcnLFxuICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKGUpID0+IHtcbiAgICAgICAgIGNvbnNvbGUubG9nKGUpO1xuICAgICAgIH0sXG4gICAgIH0pLFxuICAgfSk7XG59KVxuPC9zY3JpcHQ+XG5cblxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTg1ODgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy04NTg4LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTg1ODgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctODU4OC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

### Steps to reproduce

```vue
<script setup lang="ts">
import { h, ref ,onMounted } from 'vue'
import { ElDatePicker,ElMessageBox } from 'element-plus'

onMounted(() => {
   ElMessageBox({
     title: '选择时间没有ui效果',
     message: h(ElDatePicker, {
       style: {
         width: '100%',
       },
       placeholder: '时间',
       clearable: false,
       type: 'datetime',
       valueFormat: 'YYYY-MM-DD HH:mm:ss',
       modelValue: "",
       'onUpdate:modelValue': (e) => {
         console.log(e);
       },
     }),
   });
})
</script>
```

### What is Expected?

ElDatePicker能正常展示当前选择日期

### What is actually happening?

点击日期，组件没有展示选中日期

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by LZHK1ng**

### CODE REVIEW

**Comment by LZHK1ng** [comment]
> please check the test code

Ok! I'm checking code

**Comment by LZHK1ng** [comment]
image
My last commit kept saying test was required，so I close it.😥
@ryuhangyeong Can you help me reopen this PR ? Thanks!

**Comment by ryuhangyeong** [comment]
@LZHK1ng Also, write your commit message clearly. An issue number is not required, but what you did should be in the commit message.

**Comment by LZHK1ng** [comment]
Sorry! I seem to have committed and not pushed last time.
I will write my commit message clearly in the subsequent submission.
Maybe use click instead of mousedown to solve the multiple pop-ups
mousedown -> focus -> mouseup -> click

**Comment by ryuhangyeong** [comment]
Sorry. My merge causes your test code to fail. It's currently resolved in dev, so you can bring it to your branch.

**Comment by xiaoxian521** [comment]
thanks for your pr
But it might be friendlier to block the default event
fix: [9044](https://github.com/element-plus/element-plus/pull/9044)

**Pull request closed without merging**
