### PR TITLE
fix(components): [radio] change not trigger

### PR DESCRIPTION
**Pull request by VENI-VIDIVICI**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

[https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmNvbnN0IHJhZGlvMSA9IHJlZigxKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvMVwiIGNsYXNzPVwibWwtNFwiPlxuICAgICAgPGVsLXJhZGlvIHZhbHVlPVwiMVwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAxPC9lbC1yYWRpbz5cbiAgICAgIDxlbC1yYWRpbyB2YWx1ZT1cIjJcIiBzaXplPVwibGFyZ2VcIj5PcHRpb24gMjwvZWwtcmFkaW8+XG4gICAgPC9lbC1yYWRpby1ncm91cD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319](url)

when v-model is number, radio value is sting, option not check, click option not check

### CODE REVIEW

**Comment by btea** [comment]
The link you provided seems to be 404, please check it.

**Comment by VENI-VIDIVICI** [comment]
> The link you provided seems to be 404, please check it.

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm1iLTIgZmxleCBpdGVtcy1jZW50ZXIgdGV4dC1zbVwiPlxuICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW8xXCIgY2xhc3M9XCJtbC00XCI+XG4gICAgICA8ZWwtcmFkaW8gdmFsdWU9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIHZhbHVlPVwiMlwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IHJhZGlvMSA9IHJlZigxKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by btea** [comment]
Hello, it seems that the value you set does not match the default value type.

This counter-intuitive operation should not be performed in the code, and we should not do type conversion matching on our own in our code.

**Comment by VENI-VIDIVICI** [comment]
> 你好，看起来你设置的值与默认值类型不匹配。
> 
> 这种违反直觉的操作不应该在代码中执行，我们也不应该在代码中自行进行类型转换匹配。

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdiBjbGFzcz1cIm1iLTIgZmxleCBpdGVtcy1jZW50ZXIgdGV4dC1zbVwiPlxuICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW8xXCIgY2xhc3M9XCJtbC00XCI+XG4gICAgICA8ZWwtcmFkaW8gdmFsdWU9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIHZhbHVlPVwiMlwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgICAgIDxlbC1yYWRpbyA6dmFsdWU9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDM8L2VsLXJhZGlvPlxuICAgIDwvZWwtcmFkaW8tZ3JvdXA+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgcmFkaW8xID0gcmVmKDEpXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=

1. click option1  check  
2. click option 3  not check

i think this value is innerValue

**Comment by btea** [comment]
It seems that I misunderstood what you meant. It seems that even if the type is different, Vue will set the state to `checked` when binding to the radio.

**Comment by VENI-VIDIVICI** [comment]
> 好像我理解错了你的意思，好像即使类型不同，Vue`checked`在绑定到 radio 时也会将 state 设置为。

right, if use base radio is true, but  in element Plus use `ns.is('checked', modelValue === actualValue)`

**Review by btea — COMMENTED** [review]
Maybe we don’t need to modify anything else, just manually bind `checked` to the radio, similar to `:checked="modelValue === actualValue"`.

https://github.com/element-plus/element-plus/blob/03cd828969e4273931f3fee33a362a83a715d291/packages/components/radio/src/radio.vue#L25

**Comment by VENI-VIDIVICI** [comment]
> Maybe we don’t need to modify anything else, just manually bind `checked` to the radio, similar to `:checked="modelValue === actualValue"`.
> 
> https://github.com/element-plus/element-plus/blob/03cd828969e4273931f3fee33a362a83a715d291/packages/components/radio/src/radio.vue#L25

ok, I revised it again

**Review by btea — APPROVED** [review]
LGTM.

**Review by tolking — APPROVED** [review]
LGTM.

Thanks for your contribution.

**Pull request merged**
