### PR TITLE
fix(components): [el-form] fix the methods validate callback invalid

### LINKED ISSUE #3581: [Bug Report] ElForm Methods validate callback invalid
### Element Plus version
1.1.0-beta.15

### OS/Browsers version
macOs Chrome 93.0.4577.63

### Vue version
3.2.14

### Steps to reproduce
use form methods validate
callback function invalid
or use return Promise can't trigger then/catch

### What is Expected?
It's good  in element-plus 1.1.0-beta.12 
use form methods validate

### What is actually happening?
It's bad  in element-plus 1.1.0-beta.12 after taht
use form methods validate

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix  #3581

### CODE REVIEW

**Review by imswk — APPROVED** [review]

**Comment by shangxinbo** [comment]
How's it going？bata-15 can't use?

**Comment by shangxinbo** [comment]
When will another version be released to fix this problem？

**Comment by xinzi1990** [comment]
好了吗？

**Comment by imswk** [comment]
The next version update will fix this problem

**Comment by shangxinbo** [comment]
so when is next version publish?

**Comment by shangxinbo** [comment]
Hard injury

**Comment by schunlee** [comment]
this afternoon, just after upgrading ...

**Comment by xinzi1990** [comment]
效率杠杠的

**Pull request merged**
