### PR TITLE
fix(components): [cascader] fix cascader tooltip zIndex

### LINKED ISSUE #9463: [Style] [cascader] 多选场景下，设置 collapse = true 将选中的标签折叠。 当鼠标悬停折叠文字时 collapse-tags-tooltip 被后面的元素遮盖
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.11`
- Browser / OS: `103.0.5060.114（正式版本）/ win10`
- Build Tool: `Vite`

### Related Component

- `el-cascader`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/cascader.html#%E5%A4%9A%E9%80%89)

### Steps to reproduce

多选场景下，设置 collapse = true 将选中的标签折叠。 当鼠标悬停折叠文字时 collapse-tags-tooltip 被后面的元素遮盖

### What is Expected?

多选场景下，设置 collapse = true 将选中的标签折叠。 当鼠标悬停折叠文字时 正常显示 collapse-tags-tooltip 

### What is actually happening?

多选场景下，设置 collapse = true 将选中的标签折叠。 当鼠标悬停折叠文字时 collapse-tags-tooltip 被后面的元素遮盖

### Additional comments

月底发版 急！！！！ 
微信截图_20220825173827
微信图片_20220825173526

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

fix #9463

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xiaoxian521** [comment]
嘿，请在[Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctOTQ3MC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTk0NzAtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctOTQ3MC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy05NDcwLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)给出解决后的demo，这样更方便我们快速review

**Comment by ryuhangyeong** [comment]
## Before

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1ibG9ja1wiPlxuICAgIDxzcGFuIGNsYXNzPVwiZXhhbXBsZS1kZW1vbnN0cmF0aW9uXCI+XG4gICAgICBDb2xsYXBzZSB0YWdzIHRvb2x0aXBcbiAgICA8L3NwYW4+XG4gICAgPGVsLWNhc2NhZGVyXG4gICAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgOnByb3BzPVwicHJvcHNcIlxuICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgY29sbGFwc2UtdGFncy10b29sdGlwXG4gICAgICBjbGVhcmFibGVcbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImV4YW1wbGUtYmxvY2tcIj5cbiAgICA8c3BhbiBjbGFzcz1cImV4YW1wbGUtZGVtb25zdHJhdGlvblwiPlxuICAgICAgQ29sbGFwc2UgdGFnc1xuICAgXHQ8L3NwYW4+XG4gICAgPGVsLWNhc2NhZGVyXG4gICAgXHQ6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgOnByb3BzPVwicHJvcHNcIlxuICAgICAgY29sbGFwc2UtdGFncyBcbiAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgICAgY2xlYXJhYmxlXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgcHJvcHMgPSB7IG11bHRpcGxlOiB0cnVlIH1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnQXNpYScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDIsXG4gICAgICAgIGxhYmVsOiAnQ2hpbmEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDMsIGxhYmVsOiAnQmVpamluZycgfSxcbiAgICAgICAgICB7IHZhbHVlOiA0LCBsYWJlbDogJ1NoYW5naGFpJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDUsIGxhYmVsOiAnSGFuZ3pob3UnIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogNixcbiAgICAgICAgbGFiZWw6ICdKYXBhbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogNywgbGFiZWw6ICdUb2t5bycgfSxcbiAgICAgICAgICB7IHZhbHVlOiA4LCBsYWJlbDogJ09zYWthJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDksIGxhYmVsOiAnS3lvdG8nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogMTAsXG4gICAgICAgIGxhYmVsOiAnS29yZWEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDExLCBsYWJlbDogJ1Nlb3VsJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDEyLCBsYWJlbDogJ0J1c2FuJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDEzLCBsYWJlbDogJ1RhZWd1JyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDE0LFxuICAgIGxhYmVsOiAnRXVyb3BlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogMTUsXG4gICAgICAgIGxhYmVsOiAnRnJhbmNlJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAxNiwgbGFiZWw6ICdQYXJpcycgfSxcbiAgICAgICAgICB7IHZhbHVlOiAxNywgbGFiZWw6ICdNYXJzZWlsbGUnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMTgsIGxhYmVsOiAnTHlvbicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAxOSxcbiAgICAgICAgbGFiZWw6ICdVSycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMjAsIGxhYmVsOiAnTG9uZG9uJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDIxLCBsYWJlbDogJ0Jpcm1pbmdoYW0nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjIsIGxhYmVsOiAnTWFuY2hlc3RlcicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAyMyxcbiAgICBsYWJlbDogJ05vcnRoIEFtZXJpY2EnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAyNCxcbiAgICAgICAgbGFiZWw6ICdVUycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMjUsIGxhYmVsOiAnTmV3IFlvcmsnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjYsIGxhYmVsOiAnTG9zIEFuZ2VsZXMnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjcsIGxhYmVsOiAnV2FzaGluZ3RvbicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAyOCxcbiAgICAgICAgbGFiZWw6ICdDYW5hZGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDI5LCBsYWJlbDogJ1Rvcm9udG8nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMzAsIGxhYmVsOiAnTW9udHJlYWwnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMzEsIGxhYmVsOiAnT3R0YXdhJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1ibG9jayB7XG4gIG1hcmdpbjogMXJlbTtcbn1cbi5leGFtcGxlLWRlbW9uc3RyYXRpb24ge1xuICBtYXJnaW46IDFyZW07XG59XG48L3N0eWxlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

image

## After

[Element Plus playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwiZXhhbXBsZS1ibG9ja1wiPlxuICAgIDxzcGFuIGNsYXNzPVwiZXhhbXBsZS1kZW1vbnN0cmF0aW9uXCI+XG4gICAgICBDb2xsYXBzZSB0YWdzIHRvb2x0aXBcbiAgICA8L3NwYW4+XG4gICAgPGVsLWNhc2NhZGVyXG4gICAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgOnByb3BzPVwicHJvcHNcIlxuICAgICAgY29sbGFwc2UtdGFnc1xuICAgICAgY29sbGFwc2UtdGFncy10b29sdGlwXG4gICAgICBjbGVhcmFibGVcbiAgICAvPlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImV4YW1wbGUtYmxvY2tcIj5cbiAgICA8c3BhbiBjbGFzcz1cImV4YW1wbGUtZGVtb25zdHJhdGlvblwiPlxuICAgICAgQ29sbGFwc2UgdGFnc1xuICAgXHQ8L3NwYW4+XG4gICAgPGVsLWNhc2NhZGVyXG4gICAgXHQ6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgOnByb3BzPVwicHJvcHNcIlxuICAgICAgY29sbGFwc2UtdGFncyBcbiAgICAgIGNvbGxhcHNlLXRhZ3MtdG9vbHRpcFxuICAgICAgY2xlYXJhYmxlXG4gICAgLz5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgcHJvcHMgPSB7IG11bHRpcGxlOiB0cnVlIH1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnQXNpYScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgdmFsdWU6IDIsXG4gICAgICAgIGxhYmVsOiAnQ2hpbmEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDMsIGxhYmVsOiAnQmVpamluZycgfSxcbiAgICAgICAgICB7IHZhbHVlOiA0LCBsYWJlbDogJ1NoYW5naGFpJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDUsIGxhYmVsOiAnSGFuZ3pob3UnIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogNixcbiAgICAgICAgbGFiZWw6ICdKYXBhbicsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogNywgbGFiZWw6ICdUb2t5bycgfSxcbiAgICAgICAgICB7IHZhbHVlOiA4LCBsYWJlbDogJ09zYWthJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDksIGxhYmVsOiAnS3lvdG8nIH0sXG4gICAgICAgIF0sXG4gICAgICB9LFxuICAgICAge1xuICAgICAgICB2YWx1ZTogMTAsXG4gICAgICAgIGxhYmVsOiAnS29yZWEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDExLCBsYWJlbDogJ1Nlb3VsJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDEyLCBsYWJlbDogJ0J1c2FuJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDEzLCBsYWJlbDogJ1RhZWd1JyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDE0LFxuICAgIGxhYmVsOiAnRXVyb3BlJyxcbiAgICBjaGlsZHJlbjogW1xuICAgICAge1xuICAgICAgICB2YWx1ZTogMTUsXG4gICAgICAgIGxhYmVsOiAnRnJhbmNlJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7IHZhbHVlOiAxNiwgbGFiZWw6ICdQYXJpcycgfSxcbiAgICAgICAgICB7IHZhbHVlOiAxNywgbGFiZWw6ICdNYXJzZWlsbGUnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMTgsIGxhYmVsOiAnTHlvbicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAxOSxcbiAgICAgICAgbGFiZWw6ICdVSycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMjAsIGxhYmVsOiAnTG9uZG9uJyB9LFxuICAgICAgICAgIHsgdmFsdWU6IDIxLCBsYWJlbDogJ0Jpcm1pbmdoYW0nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjIsIGxhYmVsOiAnTWFuY2hlc3RlcicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAyMyxcbiAgICBsYWJlbDogJ05vcnRoIEFtZXJpY2EnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAyNCxcbiAgICAgICAgbGFiZWw6ICdVUycsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAgeyB2YWx1ZTogMjUsIGxhYmVsOiAnTmV3IFlvcmsnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjYsIGxhYmVsOiAnTG9zIEFuZ2VsZXMnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMjcsIGxhYmVsOiAnV2FzaGluZ3RvbicgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIHZhbHVlOiAyOCxcbiAgICAgICAgbGFiZWw6ICdDYW5hZGEnLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHsgdmFsdWU6IDI5LCBsYWJlbDogJ1Rvcm9udG8nIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMzAsIGxhYmVsOiAnTW9udHJlYWwnIH0sXG4gICAgICAgICAgeyB2YWx1ZTogMzEsIGxhYmVsOiAnT3R0YXdhJyB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZXhhbXBsZS1ibG9jayB7XG4gIG1hcmdpbjogMXJlbTtcbn1cbi5leGFtcGxlLWRlbW9uc3RyYXRpb24ge1xuICBtYXJnaW46IDFyZW07XG59XG48L3N0eWxlPlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTk0NzAtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy05NDcwLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTk0NzAtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctOTQ3MC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

image

When I tested it, it seems that the method of operation is slightly different from the existing one.

**Comment by chenxch** [comment]
When `teleported` is `true` and `false`, the two performances are different. Is there a way to make them consistent?

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Comment by gjfei** [comment]
> 当`teleported`是`true`和`false`时，两种表现是不同的。有没有办法让它们保持一致？

两个方案，1、每一个tag 都是一行，2、以cascader 宽度作为tooltip 的宽度

**Pull request closed without merging**
