### PR TITLE
更新element-plus在线主题生成工具

### PR DESCRIPTION
**Pull request by WsmDyj**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

文档 element-plus 在线主题生成工具地址还是element2的地址，由于element-plus很多类名更换，导致下载的主题组件(dialog、radio-group...)样式会出现问题

### CODE REVIEW

**Comment by iamkun** [comment]
Thanks for this PR.

Would you mind create a pull request to https://github.com/element-plus/theme-chalk-preview so that we can make the domain more official?

If you are happy to do this, feel free to open a PR there, and I'll add you the admin access for your easy testing.

Cheers

**Comment by WsmDyj** [comment]
好的，我现在去提一个pr

**Comment by WsmDyj** [comment]
我如何在 [ https://github.com/element-plus/theme-chalk-preview]( https://github.com/element-plus/theme-chalk-preview)  提交一个pr，是否需要给我开一个权限。谢谢[](url)

**Comment by iamkun** [comment]
@WsmDyj Well, https://github.com/element-plus/theme-chalk-preview  is also an open-source project, you can fork it and make a PR the same as here.

Also, I've added you as a maintainer in element-plus/theme-chalk-preview, check your email for an invitation link, please.

**Comment by JeremyWuuuuu** [comment]
@WsmDyj Please modify the link in the change here. We can get this merged. Thanks.

**Review by iamkun — APPROVED** [review]

**Pull request merged**
