### PR TITLE
fix(utils): [icon] icon type support webstorm

### PR DESCRIPTION
**Pull request by mivui**
DefineComponent is not assignable to type Component ,and support jsx.

image
实际返回类型
image
相关问题 https://github.com/element-plus/element-plus-icons/pull/58

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by tolking** [comment]
```ts
type Test = DefineComponent extends Component ? true : false // true
```

It means that the `DefineComponent` can be assigned to `Component`.

Maybe it is just a problem with the IDE you use, which cannot be reproduced on VS Code.

**Comment by mioxs** [comment]
> ```ts
> type Test = DefineComponent extends Component ? true : false // true
> ```
> 
> It means that the `DefineComponent` can be assigned to `Component`.
> 
> Maybe it is just a problem with the IDE you use, which cannot be reproduced on VS Code.

是的vscode正常工作，webstorm只是警告⚠，但是使用DefineComponent也是正确的，不会造成破坏。

**Comment by tolking** [comment]
你可以提供下详细的警告信息。

**Comment by mioxs** [comment]
> 你可以提供下详细的警告信息。

**Comment by tolking** [comment]
另外可以可以将鼠标移动到 `:icon` 上查看 icon 类型吗，并测试 `Component` 是否能够跳转

**Comment by mioxs** [comment]
> 另外可以可以将鼠标移动到 `:icon` 上查看 icon 类型吗，并测试 `Component` 是否能够跳转

**Comment by mioxs** [comment]
> 你这跳转感觉像是点击 icon 的跳转
> 
> 弹窗里面的 Component 是否能够跳转？

可以的全局的组件，webstrom可以扫描。

**Comment by tolking** [comment]
这个警告很大可能是 webstorm 自身的问题。

据我所知 webstorm 目前依然还是通过 web-types.json 文件进行组件代码提示和类型约束，修改组件库中的类型意义不大。或许你可以尝试修改你本地 element-plus 文件夹中 web-types.json 文件测试一下。

**Pull request closed without merging**
