### PR TITLE
feat(components): el-image support set zoom-rate

### PR DESCRIPTION
**Pull request by JiatLn**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by kooriookami** [comment]
Can you improve the document?

**Review by kooriookami — APPROVED** [review]

**Comment by kooriookami** [comment]
@chenxch @jw-foss What do you think?

**Review by btea — APPROVED** [review]

**Review by holazz — APPROVED** [review]

**Comment by chenxch** [comment]
@JiatLn Do you mind formatting the document and fixing it?

**Comment by chenxch** [comment]
> @chenxch @jw-foss What do you think?

@JiatLn Good job.

**Pull request merged**
