### PR TITLE
fix(components): [table-v2] the selector is invalid when `row-key` is a number

### PR DESCRIPTION
**Pull request by Whbbit1999**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by warmthsea — COMMENTED** [review]
Related to https://github.com/element-plus/element-plus/pull/16635

You can update the branch code and CI will continue.

捕获

**Comment by Whbbit1999** [comment]
@warmthsea I've checked your code and there should be no conflict with what modified. At present, it seems that the problem in your document may be caused by querySelectorAll(`[rowkey=${rowKey as string}]`) not being recognized correctly.

**Comment by mkrjhn** [comment]
guys, approve please. I faced with the same bug, and the fix is easy to codereview

**Review by warmthsea — COMMENTED** [review]
`as string`  as affects code reading, change to `String(rowKey)` better. others I think ok.

``` vue
const rows = tableRoot.querySelectorAll(`[rowkey="${String(rowKey)}"]`)
```

**Review by warmthsea — COMMENTED** [review]
LGTM.
cc: @btea

**Review by btea — APPROVED** [review]

**Comment by btea** [comment]
Thanks!

**Pull request merged**
