### PR TITLE
fix: remove CreateElement

### PR DESCRIPTION
**Pull request by BeADre**
replace CreateElement to Function

### CODE REVIEW

**Comment by HerringtonDarkholme** [comment]
Thanks for the contribution. But `Function` is not a precise type definition. We should use `CreateElement` instead.

**Comment by BeADre** [comment]
yes, but there seems to be no CreateElement in Vue3...

**Comment by JeremyWuuuuu** [comment]
Because createElement has been exported as `h` in the main package

**Comment by BeADre** [comment]
ok。

**Pull request closed without merging**
