### PR TITLE
fix(components):[input] fix input suffix prefix height

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

修复input 高度异常

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
Hello. Please provide an issue number or example to help with the review, thank you!

**Comment by gjfei** [comment]
> Hello. Please provide an issue number or example to help with the review, thank you!
文档就可以复现会比原始的高2px

**Comment by codesinging** [comment]
没有合并吗，好像现在还有这个bug?

**Comment by codesinging** [comment]
> > 没有合并吗，好像现在还有这个bug?
> 
> 哎，提了pr 没人合并眼看issues 越来越多

`.el-input__prefix,
.el-input__suffix {
    height: calc(var(--el-input-height, 32px) - 2px) !important;
}
`
自己动手了...

**Comment by gjfei** [comment]
> > > 没有合并吗，好像现在还有这个bug?
> > 
> > 
> > 哎，提了pr 没人合并眼看issues 越来越多
> 
> `.el-input__prefix, .el-input__suffix { height: calc(var(--el-input-height, 32px) - 2px) !important; } ` 自己动手了...

自力更生吧

**Pull request closed without merging**
