### PR TITLE
fix(components): [el-form] clear validate after reset fields

### PR DESCRIPTION
**Pull request by hminghe**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jw-foss** [comment]
@hminghe can you elaborate why you need to update the code like this?

**Comment by hminghe** [comment]
> @hminghe can you elaborate on why you need to update the code like this?

不好意思，英文不太好。

1. 删除 `!isEqual(computedValue.value, initialValue)`
   - 如果加上这个比较， 就要约定其他子组件主动调用 `elFormItem.validate` 时，也要加上 isEqual 的比较才能触发 elFormItem.validate。
   - 组件 checkbox-group 就没有比较，watch value 后直接调用 elFormItem.validate('change') 就会导致 resetFields 后出现验证提示。
2. `isResettingField  = false` 移到 resetField 最后面
   - 在 `resetField` 完成后重置 isResettingField 会更加合理，调用 `validate` 也不一定是 resetField 已经完成了。
   - 基于第1点的修改，`validate` 不一定会触发。

**Comment by hminghe** [comment]
> @hminghe can you elaborate on why you need to update the code like this?

主要是为了修复这个BUG #7733

**Comment by tolking** [comment]
can you resolve the conflicts.

**Review by tolking — APPROVED** [review]
LGTM

**Pull request merged**
