### PR TITLE
docs(components): [affix]

### PR DESCRIPTION
**Pull request by jw-foss**
* Add lost exposed API to documentation.
* Refine code.
* Add descriptions for APIs.

### Screenshots

| Page |  Before | After |
|------| ---- | -------|
| Affix |  CleanShot 2022-11-01 at 21 07 40@2x |  CleanShot 2022-11-01 at 21 09 05@2x  |

Added missing API: 

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by holazz — APPROVED** [review]
Cool!

**Review by chenxch — COMMENTED** [review]
Amazing, this makes the document look very clean. But I still have a concern, that is, when viewing the document, you need to do a click operation to see the specific parameter type.

**Comment by jw-foss** [comment]
> Amazing, this makes the document look very clean. But I still have a concern, that is, when viewing the document, you need to do a click operation to see the specific parameter type.

I would say that there is always a trade off, we just want the user to focus on the document itself if they really need to know the details about the parameter they should click on that icon for getting it.

**Review by chenxch — APPROVED** [review]
LGTM.

**Pull request merged**
