### PR TITLE
refactor(components): [empty] refactor

### PR DESCRIPTION
**Pull request by buqiyuan**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
Also `packages/components/empty/src/img-empty.vue`

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/blob/5ee184fdfdcbb5c3d69725b35499c062317809e8/packages/components/empty/src/img-empty.vue#L123

Does anyone know what the `id` property is for?

/cc @JeremyWuuuuu

**Review by sxzz — COMMENTED** [review]
I see, maybe we can remove `id` and replace it with random number.

**Comment by JeremyWuuuuu** [comment]
> I see, maybe we can remove `id` and replace it with random number.

I'm not following, where is the `id` you've been talking about?

**Comment by buqiyuan** [comment]
> > I see, maybe we can remove `id` and replace it with random number.
> 
> I'm not following, where is the `id` you've been talking about?

It's [here](https://github.com/element-plus/element-plus/blob/aeee7339f4d7c115aaef02734bf32ab044eeca38/packages/components/empty/src/img-empty.vue#L123)

**Comment by JeremyWuuuuu** [comment]
@buqiyuan @sxzz https://github.com/element-plus/element-plus/pull/1534 here are the reason why this is used.

**Comment by buqiyuan** [comment]
> @buqiyuan @sxzz #1534 here are the reason why this is used.

I saw it, but I think the self-incrementing id here has the same meaning as the random number

**Comment by buqiyuan** [comment]
The reason for using random number is that the `script-setup` syntax does not cache variables

**Comment by JeremyWuuuuu** [comment]
@buqiyuan Random number will disrupt the server side rendering hydration, because each time you generates different id, the vnode will be treated as different which causes hydration mismatch.

**Comment by JeremyWuuuuu** [comment]
The id must be consistent from both server side and client side to complete hydration without error.

**Review by jw-foss — CHANGES_REQUESTED** [review]
We should keep the id consistent, no random id.

**Comment by buqiyuan** [comment]
@JeremyWuuuuu ok, maybe you are right then i revert this change

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
LGTM. /cc @sxzz

**Review by sxzz — APPROVED** [review]

**Pull request merged**
