### PR TITLE
fix(components): [el-tabs] label slot not update

### LINKED ISSUE #6733: [Bug Report] [Component] [tabs] tabs的label slot不能及时动态更新
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.4`
- Browser / OS: `Chrome/98.0.4758.102`
- Build Tool: `Vite`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJ0ZXh0XCIgQGNsaWNrPVwicmVmcmVzaERhdGFcIj7mm7TmlrDmlbDmja48L2VsLWJ1dHRvbj5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZU5hbWVcIiB0eXBlPVwiY2FyZFwiIGNsYXNzPVwiZGVtby10YWJzXCI+XG4gICAgPHRlbXBsYXRlIHYtZm9yPVwiKGl0ZW0sIGkpIGluIGRhdGFcIiA6a2V5PVwiaVwiPlxuICAgICAgPGVsLXRhYi1wYW5lIDpuYW1lPVwiaXRlbS5uYW1lXCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjbGFiZWw+XG4gICAgICAgICAge3sgaXRlbS5sYWJlbCB9fVxuICAgICAgICAgIDxzcGFuIDpzdHlsZT1cInsgY29sb3I6IGl0ZW0ubmFtZSA9PT0gJ2hlaWdodCcgPyAnI2YyNjE2MScgOiAnI2ZkYmUzNCcgfVwiPih7eyBpdGVtLm51bSB9fSk8L3NwYW4+XG4gICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIHt7IGl0ZW0ubGFiZWwgfX1cbiAgICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC10YWJzPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENhbGVuZGFyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5jb25zdCBhY3RpdmVOYW1lID0gcmVmKCdoZWlnaHQnKVxuY29uc3QgZGF0YSA9IHJlZihbXG4gIHtcbiAgICBuYW1lOiAnaGVpZ2h0JyxcbiAgICBsYWJlbDogJ1JvdXRlJyxcbiAgICBudW06IDEwXG4gIH0sXG4gICB7XG4gICAgbmFtZTogJ2xvdycsXG4gICAgbGFiZWw6ICdDb25maWcnLFxuICAgIG51bTogNVxuICB9XG5dKVxuXG5jb25zdCByZWZyZXNoRGF0YSA9ICgpID0+IHtcbiAgZGF0YS52YWx1ZSA9IFtcbiAgICB7XG4gICAgICBuYW1lOiAnaGVpZ2h0JyxcbiAgICAgIGxhYmVsOiAnUm91dGUnLFxuICAgICAgbnVtOiA2XG4gICAgfSxcbiAgICAge1xuICAgICAgbmFtZTogJ2xvdycsXG4gICAgICBsYWJlbDogJ0NvbmZpZycsXG4gICAgICBudW06IDRcbiAgICB9XG4gIF1cbn1cbjwvc2NyaXB0PlxuPHN0eWxlPlxuLmRlbW8tdGFicyA+IC5lbC10YWJzX19jb250ZW50IHtcbiAgcGFkZGluZzogMzJweDtcbiAgY29sb3I6ICM2Yjc3OGM7XG4gIGZvbnQtc2l6ZTogMzJweDtcbiAgZm9udC13ZWlnaHQ6IDYwMDtcbn1cbi5kZW1vLXRhYnMgLmN1c3RvbS10YWJzLWxhYmVsIC5lbC1pY29uIHtcbiAgdmVydGljYWwtYWxpZ246IG1pZGRsZTtcbn1cbi5kZW1vLXRhYnMgLmN1c3RvbS10YWJzLWxhYmVsIHNwYW4ge1xuICB2ZXJ0aWNhbC1hbGlnbjogbWlkZGxlO1xuICBtYXJnaW4tbGVmdDogNHB4O1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

点击更新数据按钮后，tags标题内容不更新，需要手动切换标签才会刷新

### What is Expected?

data的值刷新后，tags标题内容刷新

### What is actually happening?

data的值刷新后，tags标题内容不刷新，需要切换标签才会刷新

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by HeftyKoo**
fix: #6733
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@HeftyKoo The code seems good to me, I do have a question which is do we have any ways to test this via unit testing?

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
I'll approve this as-is, if you can add a test for guaranteeing this, it'd be awesome.

**Comment by HeftyKoo** [comment]
> I'll approve this as-is, if you can add a test for guaranteeing this, it'd be awesome.

@JeremyWuuuuu done

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Merged, thx!

**Comment by crlang** [comment]
Will this commit cause an infinite loop of ElTabs?
After updating to 2.1.5, the following prompt is triggered: @sxzz @HeftyKoo @JeremyWuuuuu 


[Vue warn]: Maximum recursive updates exceeded in component <ElTabs>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

**Comment by HeftyKoo** [comment]
> Will this commit cause an infinite loop of ElTabs? After updating to 2.1.5, the following prompt is triggered: @sxzz @HeftyKoo @JeremyWuuuuu
> 
> [Vue warn]: Maximum recursive updates exceeded in component . This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.

It's a stupid mistake. Sorry about that.

**Pull request merged**
