### PR TITLE
fix(components): [table] maxHeight shark

### LINKED ISSUE #12322: [Component] [table] When a max-height attribute is added to the table component, it constantly calculates the height, triggering page redrawing, jitter, and memory surge.（当Table组件添加max-height和show-summary属性后，它会不断计算高度，从而触发页面重绘、抖动和内存激增）
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.3.2`
- Browser / OS: `Microsoft Edge 111.0.1661.62 / Windows 10 Pro`
- Build Tool: `Vite`

### Related Component

- `el-table`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFibGUgOmRhdGE9XCJ0YWJsZURhdGFcIiBzdHlsZT1cIndpZHRoOiAxMDAlXCIgbWF4LWhlaWdodD1cIjI1MFwiIHNob3ctc3VtbWFyeT5cbiAgICA8ZWwtdGFibGUtY29sdW1uIGZpeGVkIHByb3A9XCJkYXRlXCIgbGFiZWw9XCJEYXRlXCIgd2lkdGg9XCIyMDBcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cInNpemVcIiBsYWJlbD1cIlNpemVcIiAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW4gcHJvcD1cIm5hbWVcIiBsYWJlbD1cIk5hbWVcIiAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHRhYmxlRGF0YSA9IFtcbiAge1xuICAgIGRhdGU6ICcyMDE2LTAyLTAzJyxcbiAgICBzaXplOiAxMDAwLFxuICAgIG5hbWU6ICdUb20xJ1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMTctMDMtMDQnLFxuICAgIHNpemU6IDEwMDEsXG4gICAgbmFtZTogJ1RvbTInXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxOC0wNC0wNScsXG4gICAgc2l6ZTogMTAwMixcbiAgICBuYW1lOiAnVG9tMydcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE5LTA1LTA2JyxcbiAgICBzaXplOiAxMDAzLFxuICAgIG5hbWU6ICdUb200J1xuICB9LFxuICB7XG4gICAgZGF0ZTogJzIwMjAtMDYtMDcnLFxuICAgIHNpemU6IDEwMDQsXG4gICAgbmFtZTogJ1RvbTUnXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAyMS0wNy0wOCcsXG4gICAgc2l6ZTogMTAwNSxcbiAgICBuYW1lOiAnVG9tNidcbiAgfVxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

English：Using the Table component, after adding the max-height and show-summary attributes, add some data to make the height of the Table exceed the value of max-height. There's going to be a problem.（Bonus: A high-resolution screen is required. If you don't have a high resolution device, use your browser's zoom feature to scale up. You can also appear.）

中文：使用Table组件，添加max-height和show-summary属性后，并添加一些数据，使Table的高度超过max-height的值，就可以复现。（附加：需要高分辨率的屏幕。如果没有，使用浏览器的缩放功能，放大后也可以复现）

```vue
<template>
  <el-table :data="tableData" style="width: 100%" max-height="250" show-summary>
    <el-table-column fixed prop="date" label="Date" width="200" />
    <el-table-column prop="size" label="Size" />
    <el-table-column prop="name" label="Name" />
  </el-table>
</template>

<script lang="ts" setup>
import { onMounted } from 'vue'
const tableData = [
  {
    date: '2016-02-03',
    size: 1000,
    name: 'Tom1'
  },
  {
    date: '2017-03-04',
    size: 1001,
    name: 'Tom2'
  },
  {
    date: '2018-04-05',
    size: 1002,
    name: 'Tom3'
  },
  {
    date: '2019-05-06',
    size: 1003,
    name: 'Tom4'
  },
  {
    date: '2020-06-07',
    size: 1004,
    name: 'Tom5'
  },
  {
    date: '2021-07-08',
    size: 1005,
    name: 'Tom6'
  }
]
</script>
```

### What is Expected?

English：Hopefully the height will be calculated correctly and not cause memory surge.

中文：希望高度正常计算，没有内存激增。

### What is actually happening?

English：Height is constantly recomputed, pages are constantly redrawn, and memory is soaring.

中文：高度一直重复计算，页面不断重绘，内存飙升

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by chenxch**
close #12322

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ruixiaozi** [comment]
赶快解决这个问题啊，已经阻碍使用了

**Review by tolking — APPROVED** [review]

**Review by btea — APPROVED** [review]

**Comment by jyj-277** [comment]
If the current table does not add height or max-height attribute, hold down ctrl+ mouse wheel to zoom, or pop up a modal box to report an error.

**Comment by jyj-277** [comment]
image

**Pull request merged**
