### PR TITLE
fix(components): [upload] clearFiles not change fileList

### LINKED ISSUE #8207: [Bug Report] [Component] [upload] el-upload组件在  :auto-upload="false"的情况下clearFiles方法存在问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.13`
- Element Plus Version: `2.2.5`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.61 Safari/537.36`
- Build Tool: `Webpack`

### Related Component

- `el-upload`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdXBsb2FkXG4gICAgcmVmPVwidXBsb2FkZXJcIlxuICAgIGFjdGlvbj1cImh0dHBzOi8vanNvbnBsYWNlaG9sZGVyLnR5cGljb2RlLmNvbS9wb3N0cy9cIlxuICAgIDpvbi1jaGFuZ2U9XCJoYW5kbGVDaGFuZ2VcIlxuICAgIDphdXRvLXVwbG9hZD1cImZhbHNlXCJcbiAgICA6bGltaXQ9XCIxXCJcbiAgICA6b24tZXhjZWVkPVwiaGFuZGxlRXhjZWVkXCJcbiAgIFxuICA+XG4gICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPkNsaWNrIHRvIHVwbG9hZDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjdGlwPlxuICAgICAgPGRpdiBjbGFzcz1cImVsLXVwbG9hZF9fdGlwXCI+XG4gICAgICAgIGpwZy9wbmcgZmlsZXMgd2l0aCBhIHNpemUgbGVzcyB0aGFuIDUwMEtCLlxuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cblx0XHR7e3RpcHN9fVxuICA8L2VsLXVwbG9hZD5cbiAgXG48L3RlbXBsYXRlPlxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsTWVzc2FnZSwgRWxNZXNzYWdlQm94IH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5pbXBvcnQgdHlwZSB7IFVwbG9hZFByb3BzLCBVcGxvYWRVc2VyRmlsZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbiAgXG5jb25zdCB1cGxvYWRlciA9IHJlZihudWxsKVxuY29uc3QgdGlwcyA9IHJlZignJylcblxuXG5cbmNvbnN0IGhhbmRsZUNoYW5nZSA9IGZ1bmN0aW9uKCl7XG4gIGFsZXJ0KCflgYflrprkuI3nrKblkIjopoHmsYLvvIzpmLvmraLkuIrkvKDlkIzml7bmuIXnqbrpmJ/liJcnKVxuXHR1cGxvYWRlci52YWx1ZS5jbGVhckZpbGVzKClcbiAgdGlwcy52YWx1ZSA9IGB1cGxvYWRlci52YWx1ZS5jbGVhckZpbGVzIOW3suiwg+eUqO+8jOS9huaYr+W5tuayoeacieeUn+aViO+8jOatpOaXtuWGjeasoeeCueWHu+aMiemSrumAieaLqeaWh+S7tu+8jOWwhuS8muaKpei2heWHumxpbWl06ZmQ5Yi244CCYFxufVxuXG5cbmNvbnN0IGhhbmRsZUV4Y2VlZDogVXBsb2FkUHJvcHNbJ29uRXhjZWVkJ10gPSAoZmlsZXMsIHVwbG9hZEZpbGVzKSA9PiB7XG4gIEVsTWVzc2FnZS53YXJuaW5nKFxuICAgIGBUaGUgbGltaXQgaXMgMWBcbiAgKVxufVxuXG5cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

* el-upload 配置：:limit="1"  :auto-upload="false"
* 在on-change函数中调用clearFiles方法
* 点击按钮进行选取文件
* 再次点击按钮进行选取文件
* 第二次触发了onExceed，说明clearFiles存在问题

### What is Expected?

不触发onExceed回调函数

### What is actually happening?

触发onExceed回调函数

### Additional comments

element-plus/packages/components/upload/src/use-handlers.ts 
第 156行  uploadFiles.value = fileList as UploadFiles。这里是一个浅拷贝，导致props.fileList被污染，在添加文件时该数组会被push数据。
第 42 行，uploadFiles.value = uploadFiles.value.filter...
这里对uploadFiles.value 赋值操作切断了和props.fileList的引用，导致 props.fileList 依然有值，影响了 
element-plus/packages/components/upload/src/upload-content.vue 第 62 行onExceed判断

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #8207

### CODE REVIEW

**Comment by sxzz** [comment]
I think we can have a better solution. `fileList` [here](https://github.com/element-plus/element-plus/blob/b750aa87e7525060869d6c6d960932bd015113b2/packages/components/upload/src/upload-content.vue#L60) is not a correct variable to check file count.

**Comment by sxzz** [comment]
Currently, we have an essential problem: there are two file list in upload, the one is file-list from props, another one is `uploadFiles` from `useHandlers`. So the better way to fix it is merging these, making sure there's only one source from `file-list` property. I will try to solve it in a new PR.

**Comment by sxzz** [comment]
I create a new PR #8258 for fixing this issue, I think we can close this PR.

**Comment by btea** [comment]
ok，I will close it.

**Pull request closed without merging**
