### PR TITLE
fix(components): [autocomplete] fix shaking at first open

### LINKED ISSUE #5551: [Bug Report] Autocomplete dropdown behavior is shaking in first open (render)
### Element Plus version
1.3.0-beta.6

### OS/Browsers version
macOS

### Vue version
3.2.28

### Reproduction Link
https://element-plus.org/en-US/component/input.html#autocomplete

### Steps to reproduce
Click autocomplete input

### What is Expected?
no shaking

### What is actually happening?
shaking
Kapture 2022-01-22 at 11 52 22

### PR DESCRIPTION
**Pull request by freedomlang**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Fixed #5551

### CODE REVIEW

**Review by msidolphin — DISMISSED** [review]

**Comment by msidolphin** [comment]
please resolve the conflicts

**Comment by freedomlang** [comment]
> please resolved the conflicts

resolved

**Comment by JeremyWuuuuu** [comment]
@freedomlang I believe you have mistakenly added the removed file `autocomplete/src/index.vue` it has already been removed and renamed to `autocomplete/src/autocomplete.vue`, please remove the file.

**Comment by JeremyWuuuuu** [comment]
@freedomlang Could you please also resolve the comment I left for this PR? Since this is relatively a simple fix.

**Comment by freedomlang** [comment]
> @freedomlang Could you please also resolve the comment I left for this PR? Since this is relatively a simple fix.

done. Sorry for the late reply

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
