### PR TITLE
fix(directives): [repeat-click] Interval time is too short for single clicks

### PR DESCRIPTION
**Pull request by opuu**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

-------------
The interval to detect long press (100ms) is too low, so single clicks are also being considered as repeat click. 

For example: Clicking the plus or minus button of the `Input Number` component increases number by 2 instead of the defined step value (1).

multiple-click

This PR fixes the [Input Number](https://element-plus.org/en-US/component/input-number.html) component.

### CODE REVIEW

**Comment by holazz** [comment]
Hi, maybe you need also to modify the test cases.

**Comment by opuu** [comment]
> Hi, maybe you need also to modify the test cases.

Yes, making the sleep time 630 ms will fix it. I will do it soon.

**Comment by opuu** [comment]
@holazz fixed the unit test issue, the current failed test does not seems to be related to this PR.

**Comment by opuu** [comment]
Now it should pass all tests 🧪

**Comment by holazz** [comment]
> Now it should pass all tests 🧪

I recommend making the last commit as a separate PR, since it's not relevant to this issue.

**Comment by opuu** [comment]
@holazz It is related to this PR. The up and down arrows are using repeat click directive in [Time Picker](https://element-plus.org/en-US/component/time-picker.html#arbitrary-time-range) which also registers single click as double clicks.

**Comment by holazz** [comment]
> @holazz It is related to this PR. The up and down arrows are using repeat click directive in [Time Picker](https://element-plus.org/en-US/component/time-picker.html#arbitrary-time-range) which also registers single click as double clicks.

You're right! I missed it.😅

**Comment by holazz** [comment]
@opuu Thank you for your contribution. After a little thought, I think a more reasonable way is not to increase the time interval of the long press trigger event, but to delay the trigger of the first event after the long press. I added a commit to this PR. What do you think?

**Comment by opuu** [comment]
> @opuu Thank you for your contribution. After a little thought, I think a more reasonable way is not to increase the time interval of the long press trigger event, but to delay the trigger of the first event after the long press. I added a commit to this PR. What do you think?

Thats even better 👌 This way it will behave more like HTML input with number type.

**Comment by holazz** [comment]
Would you mind taking a look on this? @buqiyuan @tolking

**Review by tolking — APPROVED** [review]

**Review by xiaoxian521 — APPROVED** [review]

**Pull request merged**
