### PR TITLE
fix(components): [input] the cursor is misplaced when type setting number

### PR DESCRIPTION
**Pull request by yuchiXiong**
[PR 8193](https://github.com/element-plus/element-plus/pull/8193) 修复了 el-input-number 组件在输入中文时会出现光标向上偏移的问题。

同时 [issue 6660](https://github.com/element-plus/element-plus/issues/6660) 提到了造成这个问题的原因：

> 这个是原生input已知问题，number模式下在设置line-height后会使用输入法会导致光标漂移到左上角，组件对应的文档中已有tip。 后续是不是可以考虑通过padding的方式去调整高度？

……but，当 el-input 组件指定 type=number 时，el-input 渲染的同样是一个 type=number 的 input 元素，因而同样会导致该问题，不知道是不是改漏了_(:з)∠)_

### CODE REVIEW

**Comment by btea** [comment]
@yuchiXiong Hello, I cannot reproduce this problem, can you provide a reproduction link?

**Comment by yuchiXiong** [comment]
> @yuchiXiong Hello, I cannot reproduce this problem, can you provide a reproduction link?

in [this playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgdHlwZT1cIm51bWJlclwiIC8+XG5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

step:

1. use Chinese Input Method
2. Input any letter
3. now you can see a candidate word list with Input Method
4. select a any word
5. now, input line-height is incorrect

image

**Review by btea — APPROVED** [review]

**Comment by dadaguai-git** [comment]
这个版本什么时候能修复呢 有点急

**Review by kooriookami — APPROVED** [review]
先这样吧

**Comment by btea** [comment]
@yuchiXiong Thanks!

**Comment by btea** [comment]
@dadaguai-git A version will be released in the near future, but if you are in a hurry, it is recommended to add styles to fix it yourself.

**Comment by dadaguai-git** [comment]
> @dadaguai-git A version will be released in the near future, but if you are in a hurry, it is recommended to add styles to fix it yourself.

好的谢谢

**Pull request merged**
