### PR TITLE
When the type is password, it seems that the show-word-limit attribute is also required.

### PR DESCRIPTION
**Pull request by pzzyf**
before 
image
after
image

### CODE REVIEW

**Comment by pzzyf** [comment]
cc @btea @chenxch @kooriookami

**Comment by chenxch** [comment]
@pzzyf Scenarios where the password needs to display the length are still too rare, so it is recommended to use the suffix slot.

**Comment by pzzyf** [comment]
> @pzzyf Scenarios where the password needs to display the length are still too rare, so it is recommended to use the suffix slot.

I think it is still very common to limit the length of passwords when registering an account, what do you think?

**Comment by chenxch** [comment]
> > @pzzyf Scenarios where the password needs to display the length are still too rare, so it is recommended to use the suffix slot.
> 
> I think it is still very common to limit the length of passwords when registering an account, what do you think?

I have only seen requirements for a minimum length, not a maximum length, and even if there is, it will not be displayed.

**Comment by pzzyf** [comment]
> @pzzyf Scenarios where the password needs to display the length are still too rare, so it is recommended to use the suffix slot.



> > > @pzzyf Scenarios where the password needs to display the length are still too rare, so it is recommended to use the suffix slot.
> > 
> > 
> > I think it is still very common to limit the length of passwords when registering an account, what do you think?
> 
> I have only seen requirements for a minimum length, not a maximum length, and even if there is, it will not be displayed.

You are right. When entering a password, limiting the maximum number of digits is equivalent to helping others narrow down the cracking scope. I closed this pr

**Pull request closed without merging**
