### PR TITLE
fix(components): [el-dialog] change 'margin-right' to 'padding-right' of the head

### PR DESCRIPTION
**Pull request by Fate-ui**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by Fate-ui** [comment]
image

**Review by jw-foss — DISMISSED** [review]

**Comment by JeremyWuuuuu** [comment]
The code seems legit to me, would you mind elaborate what problem you are currently encountering?

**Comment by JeremyWuuuuu** [comment]
@Fate-ui I have a request, please add `16px` to the `padding-right` so that we won't have collision with the close button. 

When we don't have the margin right, the content will overlap close button
image

After we have the padding:

image

**Comment by Fate-ui** [comment]
when I add a background to the head, the head doesn't blend well with dialog
image

**Comment by Fate-ui** [comment]
about add `padding-right`, I dont't know why i got an opposite conclusion.
image

**Comment by JeremyWuuuuu** [comment]
@Fate-ui You have spelled `calc` to `calac` that is why the rule does not applied. 😅

**Comment by Fate-ui** [comment]
> @Fate-ui You have spelled `calc` to `calac` that is why the rule does not applied. 😅

yes, you are right! I am sorry to take up your time. Thank you for for patience and careful.  And I changed 'margin-right' to 'padding-right', It works well.

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Pull request closed without merging**
