### PR TITLE
fix(theme-chalk):  sass `!global assignments` deprecation warning

### PR DESCRIPTION
**Pull request by warmthsea**
In sass 1.80.5, will receive a deprecation warning  、
fix: 
#18708 
https://github.com/element-plus/element-plus/issues/18759 
https://github.com/element-plus/element-plus/issues/18732#issuecomment-2450604214

image
image

### CODE REVIEW

**Review by btea — APPROVED** [review]
Thanks!

**Comment by Jackzyy** [comment]
image

see this!

**Comment by warmthsea** [comment]
> image
> 
> 
> 
> see this!

Refer to https://github.com/element-plus/element-plus/issues/18759#issuecomment-2456117573

**Comment by mahfuz-rahman007** [comment]
When i install the latest element-plus , inside he theme-chalk 
$B: null;
$E: null;

These two lines are not found, but here on GitHub, the code is updated.

**Comment by warmthsea** [comment]
> When i install the latest element-plus , inside he theme-chalk $B: null; $E: null;
> 
> These two lines are not found, but here on GitHub, the code is updated.


New version not released, please refer to:
https://github.com/element-plus/element-plus/issues/18759#issuecomment-2456117573

**Pull request merged**
