### PR TITLE
fix(components): [upload-content] Fix the screen flickering

### PR DESCRIPTION
**Pull request by lockontan**
Bug描述：在before-upload 钩子中进行图片尺寸校验，这是一个耗时操作。如果校验不通过，会把已经添加的rawFile进行移除，短时间内添加并移除rawFile，浏览器会先渲染文件列表，然后再删除，导致画面会出现闪烁。
Bug修复：在校验结束后再添加rawFile

Bug description: Perform image size verification in the before-upload hook, which is a time-consuming operation. If the verification fails, the added rawFile will be removed, and the rawFile will be added and removed in a short period of time. The browser will first render the file list and then delete it, causing the screen to flicker.
Bug fix: add rawFile after verification

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]
Changes LGTM, approving.

**Comment by tolking** [comment]
Hello @lockontan, the test reported an error, can you fix it.

**Comment by lockontan** [comment]
> Hello @lockontan, the test reported an error, can you fix it.

yeah,I will try in this weekend

**Comment by lockontan** [comment]
something wrong, i will commit a new pr

**Pull request closed without merging**
