### PR TITLE
fix(components): [checkbox] `modelValue` type (#6168)

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by msidolphin** [comment]
This pr does not seem to make any difference

**Comment by gjfei** [comment]
> This pr does not seem to make any difference

有区别的吧？ 我把boolean 放后面就可以了

**Comment by gjfei** [comment]
> > This pr does not seem to make any difference
> 
> 有区别的吧？ 我把boolean 放后面就可以了

因为布尔值的话如果会默认成true

**Comment by gjfei** [comment]
> This pr does not seem to make any difference

这个能合并进去吗？

**Comment by JeremyWuuuuu** [comment]
Even thought this code makes no mistake, would you like to elaborate the issue you have encountered?

**Comment by JeremyWuuuuu** [comment]
Personally I think checkbox should always been controlled which means you should always use `v-model` or `modelValue` for this component because it a form element.

**Comment by gjfei** [comment]
> Personally I think checkbox should always been controlled which means you should always use `v-model` or `modelValue` for this component because it a form element.

#6168 看下这个复现的？

**Comment by edazh** [comment]
可能是个BUG，或者空字符串代表 `true` 是一般约定，当 `Boolean` 的优先级更高时，空字符串 `''` 会被转换成 true，源于Vue有自动转换逻辑 👇

Snipaste_2022-02-22_15-30-09

[vue源码链接](https://github.com/vuejs/vue/blob/dev/src/core/util/props.js#L35)

#6168

**Comment by gjfei** [comment]
> 

表现也是如此

**Comment by gjfei** [comment]
@msidolphin 这个不能合并吗？

**Comment by gjfei** [comment]
> This pr does not seem to make any difference


为什么这个没办法合并？

**Comment by sxzz** [comment]
> > This pr does not seem to make any difference
> 
> 为什么这个没办法合并？

请别着急，稍等我们会评估的。

**Comment by gjfei** [comment]
> > > This pr does not seem to make any difference
> > 
> > 
> > 为什么这个没办法合并？
> 
> 请别着急，稍等我们会评估的。

这个东西对我们来说很重要

**Review by sxzz — APPROVED** [review]

**Pull request merged**
