### PR TITLE
fix(theme-chalk): [dark-model] vue-cli tree sharking

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
fix #7906 
In `vue-cli5`, execute `import 'element-plus/theme-chalk/dark/css-vars.css'` according to the documentation, the dark mode does not take effect due to `tree-shaking`.

**Comment by chenxch** [comment]
cc @YunYouJun

**Comment by YunYouJun** [comment]
Just a question, Can we write this form "theme-chalk/**/*.css"?

**Comment by chenxch** [comment]
> Just a question, Can we write this form \"theme-chalk/**/*.css\"?

Okay, I thought about this when I was working on it, but I'm not sure if there will be additional files, I'll check tomorrow morning, if not I'll adjust the plan.

**Comment by JeremyWuuuuu** [comment]
Would `/**/*.css` include `/*.css`?

**Comment by chenxch** [comment]
> Would `/**/*.css` include `/*.css`?

Yes.
`**/*.js`
includes
`a.js, a/b.js, a/b/c.js`

**Comment by JeremyWuuuuu** [comment]
> > Would `/**/*.css` include `/*.css`?
> 
> Yes. `**/*.js` includes `a.js, a/b.js, a/b/c.js`

Ok, approved

**Review by jw-foss — APPROVED** [review]

**Review by sxzz — APPROVED** [review]

**Pull request merged**
