### PR TITLE
refactor(utils): refactor `iconPropType`

### PR DESCRIPTION
**Pull request by holazz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
## Suggest

Due to this change, I think the type of icon props description in the document should also change. What do you think?

ex. https://element-plus.org/en-US/component/link.html#attributes

**Comment by holazz** [comment]
> ## Suggest
> Due to this change, I think the type of icon props description in the document should also change. What do you think?
> 
> ex. [element-plus.org/en-US/component/link.html#attributes](https://element-plus.org/en-US/component/link.html#attributes)

You're right! I forget it and I will add later.

**Review by ryuhangyeong — APPROVED** [review]

**Review by sxzz — APPROVED** [review]

**Comment by tolking** [comment]
Maybe the string type should not be removed.

When [globally register](https://v3.vuejs.org/guide/component-registration.html#global-registration) the Icon components, we can pass a string to use the icon.

```ts
// main.ts

import { Edit } from '@element-plus/icons-vue'

createApp(App).component('icon-edit', Edit).mount('#app')
```

```vue
<template>
    <el-button
      type="primary"
      icon="icon-edit"
      circle
    />
    <el-link
      type="primary"
      icon="icon-edit"
      circle
    >
      Link
   </el-link>
   <el-input suffix-icon="icon-edit" />
</template>
```

**Comment by holazz** [comment]
> Maybe the string type should not be removed.
> 
> When [globally register](https://v3.vuejs.org/guide/component-registration.html#global-registration) the Icon components, we can pass a string to use the icon.
> 
> ```ts
> // main.ts
> 
> import { Edit } from '@element-plus/icons-vue'
> 
> createApp(App).component('icon-edit', Edit).mount('#app')
> ```
> 
> ```
> <template>
>     <el-button
>       type="primary"
>       icon="icon-edit"
>       circle
>     />
>     <el-link
>       type="primary"
>       icon="icon-edit"
>       circle
>     >
>       Link
>    </el-link>
>    <el-input suffix-icon="icon-edit" />
> </template>
> ```

I haven't found a use case for passing string, turns out it's here! I'll create a PR later to fix this.

**Comment by tolking** [comment]
The Component type contains the function component type(`() => VNode`), it does not seem to make sense to split the two.

```ts
type True = (() => VNode) extends Component ? true : false
```

**Comment by holazz** [comment]
> The Component type contains the function component type(`() => VNode`), it does not seem to make sense to split the two.
> 
> ```ts
> type True = (() => VNode) extends Component ? true : false
> ```

Sorry for my carelessness. 😅

**Pull request merged**
