### PR TITLE
refactor: type narrowing

### PR DESCRIPTION
**Pull request by 836334258**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Description

type narrowing

### CODE REVIEW

**Comment by btea** [comment]
@ryuhangyeong Do you think this is necessary?

**Review by ryuhangyeong — COMMENTED** [review]
@btea 

It looks like your existing code has type errors and needs to be changed.

But when I change the code like PR, typecheck throws an error.

What do you think?

image

image

**Comment by 836334258** [comment]
The reason for my modification is that the editor has a line prompt, so I view it to modify it

**Comment by btea** [comment]
@ryuhangyeong The error reported in the first screenshot may be due to the ts version problem. vscode now defaults to version 5, and the project uses 4.7.4. Switching ts to the workspace version should not report an error.

**Comment by btea** [comment]
@836334258 Can you give a more specific description of the prompt?

**Comment by 836334258** [comment]
image
There is this prompt on my computer

**Comment by 836334258** [comment]
image
When I write like this, running `pnpm typecheck` will not report an error

**Comment by btea** [comment]
It seems to be the same problem as I said above, the ts version should be switched.

The error disappears after the ts version is switched to the workspace version

image

**Comment by 836334258** [comment]
I tried it, and there will be no error when switching the typescript version to the project version, thank you!

**Pull request closed without merging**
