### PR TITLE
test(components): switch all components to vitest

### PR DESCRIPTION
**Pull request by purepear**
Sorry for the big PR, i don't have much time to do things one by one 🙏 

Overall Vitest seems slower than Jest but this might be because of config or how the tests are written. There are a lot of uses of `useFakeTimers` and `rAF` which could be slowing things down because we are not using them efficiently 🤔 

Please let me know if you find things slow or unstable when running locally 🙇 

The `el-select`/`el-select-v2` tests feel a bit slower 🤔 . Hopefully fixable with future optimisations.

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by purepear** [comment]
Looks like the coverage GHA task can't upload the coverage 🤔

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Thank you soooooo much!

**Comment by sxzz** [comment]
Seems bug of codecov https://github.com/codecov/uploader/issues/553

@JeremyWuuuuu Can we just disable it for temporally?

**Comment by sxzz** [comment]
Seems bug of codecov https://github.com/codecov/uploader/issues/553

@JeremyWuuuuu Can we just disable it for temporally?

**Comment by JeremyWuuuuu** [comment]
> Seems bug of codecov [codecov/uploader#553](https://github.com/codecov/uploader/issues/553)
> 
> @JeremyWuuuuu Can we just disable it for temporally?

Sure. I think we should disable the coverage collection in PRs, only do that when releasing.

**Comment by sxzz** [comment]
@JeremyWuuuuu OK

**Comment by JeremyWuuuuu** [comment]
Well, before I talked to @sxzz that this should be working in parallel with the existing refactoring plan, but since you have already did the job, so I think we are free to go with this.

**Comment by JeremyWuuuuu** [comment]
@sxzz you can merge this if you think it is good to go.

**Pull request merged**
