### PR TITLE
chore(play): fix lint

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## Description

The original app.example file does not conform to the format of prettier and eslint

image

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
How about renaming `play/app.example` to `play/app.example.vue` and then it will be fixed automatically in next time.

**Comment by ryuhangyeong** [comment]
@sxzz Thank you for review! Should I just change the name while keeping the existing code?

**Comment by sxzz** [comment]
@ryuhangyeong Yes, just change it in this PR. (Don't forget to update `vite.init.ts`)

**Comment by ryuhangyeong** [comment]
@sxzz done!

Thank you for your kind notice.

**Review by sxzz — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
@sxzz Thank you!

**Comment by ryuhangyeong** [comment]
@sxzz Looking back, my commit message was unclear. From now on, I will think a little more and write in detail.

**Pull request merged**
