### PR TITLE
fix: fix the color picker can't colse on click twice and add z-index for the notification

### LINKED ISSUE #602: A Few Bug List
I'm not sure whether you have known these bugs, I just list them for your information.
1. The slider button above on the popover.
image
2. The color picker can't colse on click twice.
3. Notification under the doc header.
image
4. The message appeared in no animation.
image
5. The message hasn't bind functions like `this.$message[type]`(type of success/warning/info/error)

### PR DESCRIPTION
**Pull request by Ther-su**
Fix #602 the color picker can't colse on click twice.
In my opinion,the bug and solution is similar to #496.

Fix #602 Notification under the doc header.

### CODE REVIEW

**Comment by Ther-su** [comment]
color-picker
This is showed.

**Comment by Ther-su** [comment]
In my solution,I add a father div that is inline-block for the component so that it can fix the bug. Does it can be received? Or do you have a better idea?

**Comment by zazzaz** [comment]
Thanks. I did not check this bug yet. However, I do think it is not a good idea to change the dom structure.

**Comment by Ther-su** [comment]
Thanks,and let me see if there's a better idea.haha.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@Ther-su  Do you have further moving on this bug? ..I just merged it 😂, if you do please raise another PR for the fix.

**Pull request merged**
