### PR TITLE
test(components): [tooltip] switch to vitest

### PR DESCRIPTION
**Pull request by purepear**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sxzz** [comment]
Unit test seems failed.

**Comment by purepear** [comment]
@sxzz yep, i thought the ssr fix was the only problem and pushed without checking the tests locally.
I'm working on a fix but there are some problems when using vitest's fake timers with the transition. Will see if i can fix it.

**Comment by purepear** [comment]
Need to merge https://github.com/element-plus/element-plus/pull/7199 first and then i'll update this one.

**Comment by purepear** [comment]
Closing in favour of https://github.com/element-plus/element-plus/pull/7205

**Pull request closed without merging**
