### PR TITLE
refactor: replace typeof number with the built-in isNumber

### PR DESCRIPTION
**Pull request by zzjiaxiang**

### CODE REVIEW

**Review by btea — APPROVED** [review]
Thanks!

**Review by warmthsea — APPROVED** [review]

**Comment by warmthsea** [comment]
There are some conflicts, can you resolve them?

**Comment by zzjiaxiang** [comment]
done,Additionally, I found several typeof refactorings. Should I combine them into a single PR or submit a separate PR for each one?

**Review by tolking — APPROVED** [review]

**Comment by tolking** [comment]
If there are many changes, it is recommended to divide them into multiple PR

**Pull request merged**
