### PR TITLE
feat(tree): auto expand parent on set current key and node (#1502)

### LINKED ISSUE #1502: [bug report] tree setcurrentkey is not successful, use the data of the official website example
### Element Plus version
1.0.2-beta.32

### OS/Browsers version
mac Os

### Vue version
3.0.5

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-vnok0

### Steps to reproduce
测试代码如下
```
<template>
  <el-tree
    :data="data"
    node-key="id"
    ref="tree"
    highlight-current
    :props="{
      children: 'children',
      label: 'label'
    }"
  />
</template>

<script lang="ts">
import { defineComponent, nextTick, onMounted, ref } from "vue";
export default defineComponent({
  setup() {
    const tree = ref<any>(null);
    const data = ref([
      {
        id: 1,
        label: "一级 1",
        children: [
          {
            id: 4,
            label: "二级 1-1",
            children: [
              {
                id: 9,
                label: "三级 1-1-1",
              },
              {
                id: 10,
                label: "三级 1-1-2",
              },
            ],
          },
        ],
      },
      {
        id: 2,
        label: "一级 2",
        children: [
          {
            id: 5,
            label: "二级 2-1",
          },
          {
            id: 6,
            label: "二级 2-2",
          },
        ],
      },
      {
        id: 3,
        label: "一级 3",
        children: [
          {
            id: 7,
            label: "二级 3-1",
          },
          {
            id: 8,
            label: "二级 3-2",
          },
        ],
      },
    ]);
    onMounted(() => {
      nextTick(() => {
        tree.value.setCurrentKey(7);
      })
    });
    return { tree, data }
  },
});
</script>
```

### What is Expected?
应该要正确选中某个树节点

### What is actually happening?
没有任何反应

### PR DESCRIPTION
**Pull request by soc221b**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

Fix #1502

### CODE REVIEW

**Comment by Ryan2128** [comment]
I think this should be a new feature about the tree. But maybe we need a new parameter to control whether the node expanded. 

What do you think?

**Comment by iendeavor** [comment]
I think it would be better, I'll add `expand-on-highlight-node: boolean` prop, should I set the default value to `true` (It would cause BREAKING CHANGE)?

**Comment by Ryan2128** [comment]
> I think it would be better, I'll add `expand-on-highlight-node: boolean` prop, should I set the default value to `true` (It would cause BREAKING CHANGE)?

Sorry, I think you have misunderstood what I mean, I mean to add a parameter to the `setCurrentkey` and the `setCurrentNode` instead of a new prop.

**Comment by iendeavor** [comment]
😂 I'll change it tomorrow.

**Comment by Ryan2128** [comment]
> 😂 I'll change it tomorrow.

Okey, thank you for your efforts.

**Comment by iendeavor** [comment]
@Ryan2128  It is ready for review. 🙇‍♂️

**Comment by Ryan2128** [comment]
> @Ryan2128 It is ready for review. 🙇‍♂️

Can you add the descriptions to docs in other languages? You can all use English or translate it.

**Comment by iendeavor** [comment]
OK, I did it. 😄

**Comment by JeremyWuuuuu** [comment]
@iendeavor Should we set `autoExpand` to `true`? Since the issue you were trying to fix was asking us why the selected node's parent wasn't expanded.

**Review by jw-foss — APPROVED** [review]

**Comment by iendeavor** [comment]
> The code looks legit, I need to test on the old version, see how it works.

🙇‍♂️

**Review by jw-foss — APPROVED** [review]

**Comment by zimutao** [comment]
这个自动展开的操作，能不能同步给tree-v2

**Pull request merged**
