### PR TITLE
fix(component): [el-tabs] the initial pane should only render for once

### LINKED ISSUE #6559: [Bug Report] [Component] [tabs] Lazyload tabs maybe render for twice
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `Chrome 99.0.4844.51 / Windows 10`
- Build Tool: `Webpack`

### Related Component

- `el-tabs`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdGFicyB2LW1vZGVsPVwiQWN0aXZlXCI+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVGFiIEFcIiBuYW1lPVwiYVwiIGxhenk+XG4gIFx0XHQ8cGFuZSAvPlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gICAgPGVsLXRhYi1wYW5lIGxhYmVsPVwiVGFiIEJcIiBuYW1lPVwiYlwiIGxhenk+XG4gIFx0XHQ8cGFuZSAvPlxuICAgIDwvZWwtdGFiLXBhbmU+XG4gIDwvZWwtdGFicz5cbjwvdGVtcGxhdGU+XG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IHsgcmVmLCBkZWZpbmVDb21wb25lbnQsIGggfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgRWxUYWJzIH0gZnJvbSBcImVsZW1lbnQtcGx1c1wiO1xuXG5jb25zdCBBY3RpdmUgPSByZWYoXCJhXCIpO1xuY29uc3QgUmVuZGVyQ291bnQgPSByZWYoMCk7XG5jb25zdCBQYW5lID0gZGVmaW5lQ29tcG9uZW50KHtcbiAgc2V0dXAoKSB7XG4gICAgUmVuZGVyQ291bnQudmFsdWUgKz0gMTtcbiAgfSxcbiAgcmVuZGVyKCkge1xuICAgIHJldHVybiBoKFwiZGl2XCIsIFwiU2V0dXAgXCIgKyBSZW5kZXJDb3VudC52YWx1ZSlcbiAgfVxufSk7XG48L3NjcmlwdD4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

1. set the initial pane of el-tabs as lazyload pane.
2. switch out and back to the initial pane.

### What is Expected?

The initial pane only renders for once.

### What is actually happening?

The initial pane was rendered twice.

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by KawaiiZapic**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #6559

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic Would you mind writing a test for this?

**Comment by KawaiiZapic** [comment]
> @KawaiiZapic Would you mind writing a test for this?

Sorry, that seems too hard for me, but maybe I can handle it with someone's help.  
I need to create a component to test how many times the component is mounted.  
I don't know where to put this component.

**Comment by KawaiiZapic** [comment]
This problem should be found when someone has written the code down.   
But the test is not close enough to reality, the tabs should not be used without binding a model value.   
But in the tests, there are many cases used without binding a model value, maybe will miss some problems like this.

**Comment by JeremyWuuuuu** [comment]
@KawaiiZapic Noted! Thank you for the heads up, we should improve the test cases from time to time to make it more robust.

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
