### PR TITLE
perf(components): [table] export table defaults

### PR DESCRIPTION
**Pull request by xiaoxian521**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by holazz** [comment]
Would it be better to add `Table` prefix for some of these types if exporting to the global? like:

```ts
export type { ColumnCls as TableColumnCls } from './src/table/defaults'
```

**Review by holazz — APPROVED** [review]

**Comment by xiaoxian521** [comment]
> Would it be better to add `Table` prefix for some of these types if exporting to the global? like:
> 
> ```ts
> export type { ColumnCls as TableColumnCls } from './src/table/defaults'
> ```

用户可以在导入时使用别名🤔

**Comment by holazz** [comment]
> > Would it be better to add `Table` prefix for some of these types if exporting to the global? like:
> > ```ts
> > export type { ColumnCls as TableColumnCls } from './src/table/defaults'
> > ```
> 
> 用户可以在导入时使用别名🤔

OK， 我是担心像 `Sort`，`Filter` 这种其它组件也有导出会冲突，不过现在好像没有。😊

**Comment by sxzz** [comment]
Oh you're right, we'd better add `Table` as prefix.

**Comment by chenxch** [comment]
> Oh, you're right, we'd better add `Table` as the prefix.

+1

**Pull request merged**
