### PR TITLE
fix(components): [segmented] item may be undefined

### PR DESCRIPTION
**Pull request by vaebe**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

image

```
"vue": "^3.5.0",
"typescript": "^5.5.4",
"vue-tsc": "^2.1.4"
```

I encountered a ts error that "item" may be "undefined" when using the segmented component. However, in actual use, the Option type should not be undefined. If I understand it incorrectly, please let me know, thank you!

### CODE REVIEW

**Comment by vaebe** [comment]
Of course I'm not sure if this modification is correct, but it seems to solve my problem

**Comment by vaebe** [comment]
@kooriookami Please help confirm

**Comment by kooriookami** [comment]
image
Please update the doc

**Comment by vaebe** [comment]
> image Please update the doc



> image Please update the doc

Thanks, the document has been updated

**Comment by vaebe** [comment]
> image Please update the doc

Thanks, the document has been updated

**Review by kooriookami — APPROVED** [review]
Thanks for your contribution~

**Pull request merged**
