### PR TITLE
style(theme-chalk): fix input-number style

### LINKED ISSUE #10616: [Style] [input-number, input] 【el-input-number】与【el-input】并排的话，两者无法对其，差一个像素
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.44`
- Element Plus Version: `2.2.21`
- Browser / OS: `chrome 107`
- Build Tool: `Vite`

### Related Component

- `el-input-number`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbjxlbC1pbnB1dCBzdHlsZT1cIndpZHRoOiAxMDBweDtcIiAvPlxuPGVsLWlucHV0LW51bWJlciAvPlxuPGVsLWlucHV0IHN0eWxlPVwid2lkdGg6IDEwMHB4O1wiIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

【最小复现环境的链接】有代码

### What is Expected?

【el-input-number】与【el-input】并排可以对其

### What is actually happening?

【el-input-number】与【el-input】并排，el-input-number会高一个像素

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by qinran0423**
closed #10616

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
I think we might have to remove `vertical-align`, would you like to try it?

**Comment by qinran0423** [comment]
I want to try it，but I want to know what other influences of vertical-align have any other effects.

**Comment by chenxch** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGRpdiBzdHlsZT1cImJvcmRlci1ib3R0b206IDFweCBzb2xpZCAjY2NjXCI+XG4gIFx0PGVsLWJ1dHRvbj5CdXR0b248L2VsLWJ1dHRvbj5cbiAgXHQ8ZWwtaW5wdXQgdi1tb2RlbD1cIm1zZ1wiIHN0eWxlPVwid2lkdGg6MjAwcHhcIiAvPlxuICBcdDxlbC1zZWxlY3Q+PC9lbC1zZWxlY3Q+XG5cdCAgPGVsLWRhdGUtcGlja2VyPjwvZWwtZGF0ZS1waWNrZXI+XG4gICAgPGVsLWlucHV0LW51bWJlcj48L2VsLWlucHV0LW51bWJlcj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+UHJpbWFyeTwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cblxuICA8ZGl2PlxuICBcdDxlbC1zZWxlY3Q+PC9lbC1zZWxlY3Q+XG4gIFx0PGVsLWJ1dHRvbj5CdXR0b248L2VsLWJ1dHRvbj5cbiAgPC9kaXY+XG4gIFxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuPHN0eWxlPlxuLmVsLWJ1dHRvbixcbi5lbC1pbnB1dCxcbiAgLmVsLXNlbGVjdCB7XG4gICAgdmVydGljYWwtYWxpZ246IHVuc2V0ICFpbXBvcnRhbnQ7XG4gIH1cbjwvc3R5bGU+IiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

The current clue is that the prefix icon causes the displacement of `date-picker`.

**Comment by Simon-He95** [comment]
> playground

image
remove the verticle-align: unset then can be fixed

**Comment by chenxch** [comment]
> 

This is to test whether there is a way to fix the `date-picker` alignment problem when `verticle-align` is removed from the component by default, please pay attention to the key points.

**Comment by qinran0423** [comment]
image
If these two attributes are removed,it seems to be solved.😂

**Comment by chenxch** [comment]
> image If these two attributes are removed,it seems to be solved.😂

It looks like this, and if you look closely, you will find that the icon is too high, but there has been some progress, which is still very happy.

**Comment by qinran0423** [comment]
> image
I tried it again, removed these two attributes and then added `verticle-align` to `.el-input__prefix-inner`

**Comment by qinran0423** [comment]
Can't this method be solved?

**Comment by chenxch** [comment]
> Can't this method be solved?

Well done, maybe it's hard work for you to organize a repaired demo display.

**Comment by qinran0423** [comment]
sorry, I do not understand what you mean.😂

**Comment by chenxch** [comment]
You can refer to #10669

**Comment by qinran0423** [comment]
I will PR again

**Pull request closed without merging**
