### PR TITLE
fix(components): [dropdown] fix visible-change event delay trigger #8601

### PR DESCRIPTION
**Pull request by shooterRao**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by chenxch — APPROVED** [review]
Good job.

**Comment by chenxch** [comment]
cc @element-plus/backers Need to double check if there are other effects.

**Review by YunYouJun — APPROVED** [review]

**Comment by tolking** [comment]
It seems that this PR broke the original A11y. 

Use the `before-show` will not move focus into content.

**Comment by YunYouJun** [comment]
@shooterRao Can you work with @tolking  to fix the problem?

**Comment by chenxch** [comment]
In fact, we should talk about `handleShowTooltip` split into `handleBeforeShowTooltip`, `handleBeforeShowTooltip` is responsible for emit `visible-change`.

**Comment by chenxch** [comment]
use  `before-show` 、`show`、`hide`

**Comment by shooterRao** [comment]
ok,   I will fix this problem tomorrow.😀

**Pull request merged**
