### PR TITLE
feat(components): [dropdown] support set danger dropdown item

### PR DESCRIPTION
**Pull request by wzc520pyfm**
Danger dropdown items are relatively common with business requirements, my changes include:

* support set danger dropdown item

* update dropdown test for danger property

* update dropdown doc for danger property

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IEFycm93RG93biB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWRyb3Bkb3duPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgICAgRHJvcGRvd24gTGlzdDxlbC1pY29uIGNsYXNzPVwiZWwtaWNvbi0tcmlnaHRcIj48YXJyb3ctZG93biAvPjwvZWwtaWNvbj5cbiAgICAgIDwvZWwtYnV0dG9uPlxuICAgIDx0ZW1wbGF0ZSAjZHJvcGRvd24+XG4gICAgICA8ZWwtZHJvcGRvd24tbWVudT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDE8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAyPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8IS0tIGRhbmdlciBpdGVtIC0tPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjbGFzcz1cImRhbmdlclwiPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXNhYmxlZD5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAgLmRhbmdlcntcbiAgICBjb2xvcjogdmFyKC0tZWwtY29sb3ItZGFuZ2VyKSAhaW1wb3J0YW50O1xufVxuICAuZGFuZ2VyOmhvdmVye1xuICAgIGJhY2tncm91bmQ6IHZhcigtLWVsLWNvbG9yLWRhbmdlcikgIWltcG9ydGFudDtcbiAgICBjb2xvcjogI2ZmZiAhaW1wb3J0YW50O1xuICB9XG48L3N0eWxlPiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

@wzc520pyfm Thank you for your contribution, but I think this is an unnecessary attribute. If there are succes, do you need to add another attribute? This can be achieved through styles, but due to the current style priority problem, you need to add important. Do you mind? Help with this adjustment?

**Comment by wzc520pyfm** [comment]
https://github.com/element-plus/element-plus/pull/12601
@chenxch I have completed the adjustments and submitted a new PR, but, I think, as a function point, dangerous subitems may be implemented directly by the component, which can also reduce the user's burden. and you?

**Comment by chenxch** [comment]
@wzc520pyfm This is considered a niche scenario, and it should not increase the burden on components. I still can’t insist on setting a precedent for a problem that can be solved by a style, because later components may receive more such requirements, which will make the components difficult to maintain.

**Comment by wzc520pyfm** [comment]
I agree, thank you for your answer.

**Pull request closed without merging**
