### PR TITLE
docs: update NodeJs minimum version required

### PR DESCRIPTION
**Pull request by HelloChunWei**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

---

Here is my system information. 
186201863-8f21b8ea-4ed4-4775-9f13-2b52953dd2d6

When my NodeJs version is under **V16.17.0**,  vitest can't execute.

**at version v16.15.0**

https://user-images.githubusercontent.com/18310281/186199970-aed68708-9dc3-421b-ab1e-2871d9e08ad8.mov

**at version v16.16.0**

https://user-images.githubusercontent.com/18310281/186200161-588535fe-2c65-464c-ac05-2c0785e39e04.mov

So I just update NodeJs minimum version at CONTRIBUTING.md

### CODE REVIEW

**Comment by btea** [comment]
My system is win10 and the node version is 16.13.0, but vitest runs normally ~

**Comment by HelloJunWei** [comment]
I think the problem depend on the os system? 

I will close the pull request and create a issue later

**Comment by btea** [comment]
Perhaps you can create a simple example to test whether it is a vitest  bug?

**Comment by HelloJunWei** [comment]
@btea 

Sound a great idea! 👍

**Pull request closed without merging**
