### PR TITLE
fix(switch): fix switch has outline

### LINKED ISSUE #468: switch has outline
image

### PR DESCRIPTION
**Pull request by Ther-su**
fix switch has outline, the class el-switch need to add outline:none

- [ switch] Component Migration

Fix #468

### CODE REVIEW

**Comment by Ther-su** [comment]
Sorry,I just want to solve the issue #468 ,but it become #469,I don't konw what's wrong.

**Comment by JeremyWuuuuu** [comment]
Have you tested on your machine? By attaching a screenshot here might be better for us to know that you have already fixed the issue.

**Comment by Ther-su** [comment]
image
yes,I have tested on my machine.

**Comment by JeremyWuuuuu** [comment]
All right, I'm merging it

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
All right, I'm merging it.

**Pull request merged**
