### PR TITLE
fix(components): [input] the cursor error when click show-password

### LINKED ISSUE #18387: [Component] [input] Input 输入框密码框使用 show-password 属性切换显示隐藏的密码框,光标会移到第一位
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.8.3`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/input.html)

### Steps to reproduce

Input 输入框密码框使用 show-password 属性切换显示隐藏的密码框,光标会移到第一位

### What is Expected?

光标在最后一位

### What is actually happening?

光标在第一位

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by tolking**
fix #18387, closed #18831

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by btea — APPROVED** [review]
👍

**Comment by guda-art** [comment]
频繁的切换明文密文。鼠标位置会抖动，先移到开始再移到最后，所以，这个解决方案不完善

**Comment by guda-art** [comment]
使用setTimeout去改的做法本来就不正确，不是去解决原来代码的问题，而是通过另一种手段去避免问题，违背了 单一职责原则 
除非你告诉我这是chrom聚焦的bug
@tolking 官方审核应该加强 @btea 

现在只能添加补丁(需要销毁)
```ts
// TODO 修复频繁切换密码显示隐藏 光标抖动问题
function fixCursorShake() {
  const inputEl = inputRef.value?.$el.querySelector('input') as HTMLInputElement

  const observer = new MutationObserver(() => {
    inputEl.blur()
    inputEl.focus()
  })

  observer.observe(inputEl, { attributes: true, attributeFilter: ['type'] })
}

onMounted(() => {
  fixCursorShake()
})
```

**Comment by btea** [comment]
@guda-art 多谢反馈，已调整了修复方案。

**Pull request merged**
