### PR TITLE
fix(components): [select] dynamic change local placeholder

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by gjfei** [comment]
#7559

**Comment by gjfei** [comment]
@jw-foss

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Comment by kooriookami** [comment]
Fixed in 2.5.0

**Comment by gjfei** [comment]
> Fixed in 2.5.0

我其实很想知道你们的审核流程是啥，我提在很早提的pr没合并进去，后面的人提的反而合并进去了。

**Comment by kooriookami** [comment]
Element Plus是一个社区项目，没有谁全职工作，PR基本是谁看到了就审核一下，有时候大家忙会看漏一些，对于一些存在其他问题的PR也会搁置。团队成员的PR优先级会高一些，优先保证质量。

**Pull request closed without merging**
