### PR TITLE
fix: selet-v2 value-key mode selected style and onClonse bug

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
fix: #6502 
image

**Comment by chenxch** [comment]
在处理selected样式的时候发现target出现类似label in value的情况，不知道是原先设计如此还是中间环境出现问题

**Comment by JeremyWuuuuu** [comment]
@chenxch Please run `yarn format` to format the code properly.

**Comment by chenxch** [comment]
> @chenxch Please run `yarn format` to format the code properly.
@JeremyWuuuuu  processed.

**Review by jw-foss — APPROVED** [review]

**Comment by Karolis-Stoncius** [comment]
Could this be fixed in the simple select as well?

**Comment by chenxch** [comment]
> Could this be fixed in the simple select as well?

I'll take a look at it later.

**Pull request merged**
