### PR TITLE
fix(components): [select] drop-down selection  display

### LINKED ISSUE #10893: [Component] [select, drawer] el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框会显示。
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.26`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-drawer`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRyYXdlciA9IHJlZihmYWxzZSlcbmZ1bmN0aW9uIHRvZ2dsZSAoKSB7XG4gIGRyYXdlci52YWx1ZSA9IHRydWVcbn1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIGxhYmVsOiAnb3B0aW9uIDEnLFxuICAgIHZhbHVlOiAxXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ29wdGlvbiAyJyxcbiAgICB2YWx1ZTogMlxuICB9XG5dXG5cbmFzeW5jIGZ1bmN0aW9uIGJlZm9yZUNsb3NlKGRvbmUpIHtcbiAgdHJ5IHtcbiAgICBhd2FpdCBFbE1lc3NhZ2VCb3guY29uZmlybSgn56Gu5a6a5YWz6Zet77yfJylcblxuICAgIGRvbmUoKVxuICB9IGNhdGNoIChlcnJvcikge1xuICAgIGlmIChlcnJvciAhPT0gJ2NhbmNlbCcpIHtcbiAgICAgIHRocm93IGVycm9yXG4gICAgfVxuICB9XG59XG4gIFxuY29uc3Qgc3RlcHMgPSBbXG4gICfmiZPlvIAgZHJhd2Vy44CCJyxcbiAgJ+eCueWHuyBzZWxlY3Qg6K6p5YW26I635Y+W54Sm54K544CCJyxcbiAgJ+aMiSBFc2Mg5YWz6ZetIGRyYXdlcu+8iOatpOS4vuaYr+S4uuS6huiuqSBzZWxlY3Qg5L+d5oyB54Sm54K577yM6Iul6YCa6L+H6byg5qCH54K55Ye7IHgg5YWz6Zet5oyJ6ZKu5LiN5Y+v5aSN546w6Zeu6aKY77yJJyxcbiAgJ+atpOaXtiBkcmF3ZXIg5YWz6Zet77yM5L2GIG9wdGlvbnMg5LiL5ouJ5qGG6YCJ6aG55Y205pi+56S644CCJ1xuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgzPuWJjeaPkOadoeS7tu+8mmVsLXNlbGVjdFtmaWx0ZXJhYmxlXSDlnKggZWwtZHJhd2VyW2JlZm9yZS1jbG9zZV0g5YaFPC9oMz5cbiAgPGgzPlxuICAgIOWkjeeOsOatpemqpOWmguS4i++8mlxuICA8L2gzPlxuICA8b2w+XG4gICAgPGxpIHYtZm9yPVwiaXRlbSBpbiBzdGVwc1wiIDprZXk9XCJpdGVtXCI+e3tpdGVtfX08L2xpPlxuICA8L29sPlxuICBcbiAgXG4gIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlXCI+b3BlbiBkcmF3ZXI8L2VsLWJ1dHRvbj5cbiAgPGVsLWRyYXdlciB2LW1vZGVsPVwiZHJhd2VyXCIgOmJlZm9yZS1jbG9zZT1cImJlZm9yZUNsb3NlXCI+XG5cdFx0PGVsLXNlbGVjdCBmaWx0ZXJhYmxlPlxuICAgICAgPGVsLW9wdGlvbiBcbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiBcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICA8L2VsLWRyYXdlcj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion, ElMessageBox } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'

const drawer = ref(false)
function toggle () {
  drawer.value = true
}

const options = [
  {
    label: 'option 1',
    value: 1
  },
  {
    label: 'option 2',
    value: 2
  }
]

async function beforeClose(done) {
  try {
    await ElMessageBox.confirm('确定关闭？')

    done()
  } catch (error) {
    if (error !== 'cancel') {
      throw error
    }
  }
}
  
const steps = [
  '打开 drawer。',
  '点击 select 让其获取焦点。',
  '按 Esc 关闭 drawer（此举是为了让 select 保持焦点，若通过鼠标点击 x 关闭按钮不可复现问题）',
  '此时 drawer 关闭，但 options 下拉框选项却显示。'
]
</script>

<template>
  <h3>前提条件：el-select[filterable] 在 el-drawer[before-close] 内</h3>
  <h3>
    复现步骤如下：
  </h3>
  <ol>
    <li v-for="item in steps" :key="item">{{item}}</li>
  </ol>
  
  
  <el-button @click="toggle">open drawer</el-button>
  <el-drawer v-model="drawer" :before-close="beforeClose">
		<el-select filterable>
      <el-option 
        v-for="item in options" 
        :key="item.value" 
        :label="item.label"
        :value="item.value"></el-option>
      </el-select>
  </el-drawer>

  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>
```

### What is Expected?

el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框不会显示。

### What is actually happening?

el-select[filterable] 在获取焦点的前提下，通过 Esc 关闭 el-drawer[before-close]，选项下拉框会显示。

### Additional comments

除 drawer 外，不知道 dialog 否则存在同样的问题。
除 select 外，不知道其他拥有下拉框选项的组件是否有同样的问题。

### PR DESCRIPTION
**Pull request by Simon-He95**
close:  #10893

### CODE REVIEW

**Comment by Simon-He95** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24sIEVsTWVzc2FnZUJveCB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRyYXdlciA9IHJlZihmYWxzZSlcbmZ1bmN0aW9uIHRvZ2dsZSAoKSB7XG4gIGRyYXdlci52YWx1ZSA9IHRydWVcbn1cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIGxhYmVsOiAnb3B0aW9uIDEnLFxuICAgIHZhbHVlOiAxXG4gIH0sXG4gIHtcbiAgICBsYWJlbDogJ29wdGlvbiAyJyxcbiAgICB2YWx1ZTogMlxuICB9XG5dXG5cbmFzeW5jIGZ1bmN0aW9uIGJlZm9yZUNsb3NlKGRvbmUpIHtcbiAgdHJ5IHtcbiAgICBhd2FpdCBFbE1lc3NhZ2VCb3guY29uZmlybSgn56Gu5a6a5YWz6Zet77yfJylcblxuICAgIGRvbmUoKVxuICB9IGNhdGNoIChlcnJvcikge1xuICAgIGlmIChlcnJvciAhPT0gJ2NhbmNlbCcpIHtcbiAgICAgIHRocm93IGVycm9yXG4gICAgfVxuICB9XG59XG4gIFxuY29uc3Qgc3RlcHMgPSBbXG4gICfmiZPlvIAgZHJhd2Vy44CCJyxcbiAgJ+eCueWHuyBzZWxlY3Qg6K6p5YW26I635Y+W54Sm54K544CCJyxcbiAgJ+aMiSBFc2Mg5YWz6ZetIGRyYXdlcu+8iOatpOS4vuaYr+S4uuS6huiuqSBzZWxlY3Qg5L+d5oyB54Sm54K577yM6Iul6YCa6L+H6byg5qCH54K55Ye7IHgg5YWz6Zet5oyJ6ZKu5LiN5Y+v5aSN546w6Zeu6aKY77yJJyxcbiAgJ+atpOaXtiBkcmF3ZXIg5YWz6Zet77yM5L2GIG9wdGlvbnMg5LiL5ouJ5qGG6YCJ6aG55Y205pi+56S644CCJ1xuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgzPuWJjeaPkOadoeS7tu+8mmVsLXNlbGVjdFtmaWx0ZXJhYmxlXSDlnKggZWwtZHJhd2VyW2JlZm9yZS1jbG9zZV0g5YaFPC9oMz5cbiAgPGgzPlxuICAgIOWkjeeOsOatpemqpOWmguS4i++8mlxuICA8L2gzPlxuICA8b2w+XG4gICAgPGxpIHYtZm9yPVwiaXRlbSBpbiBzdGVwc1wiIDprZXk9XCJpdGVtXCI+e3tpdGVtfX08L2xpPlxuICA8L29sPlxuICBcbiAgXG4gIDxlbC1idXR0b24gQGNsaWNrPVwidG9nZ2xlXCI+b3BlbiBkcmF3ZXI8L2VsLWJ1dHRvbj5cbiAgPGVsLWRyYXdlciB2LW1vZGVsPVwiZHJhd2VyXCIgOmJlZm9yZS1jbG9zZT1cImJlZm9yZUNsb3NlXCI+XG5cdFx0PGVsLXNlbGVjdCBmaWx0ZXJhYmxlPlxuICAgICAgPGVsLW9wdGlvbiBcbiAgICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIiBcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIiBcbiAgICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIj48L2VsLW9wdGlvbj5cbiAgICAgIDwvZWwtc2VsZWN0PlxuICA8L2VsLWRyYXdlcj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEwOTkyLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTA5OTItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgIGxpbmsuaHJlZiA9ICdodHRwczovL3ByZXZpZXctMTA5OTItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTA5OTItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

**Comment by chenxch** [comment]
Please check again, it does not seem to have fixed the issue.

**Comment by Simon-He95** [comment]
> Please check again, it does not seem to have fixed the issue.

I modified it, it should work now

**Comment by chenxch** [comment]
When the option box is displayed, press the `ESC` key, which should close the option box and keep `select` in focus.

**Comment by chenxch** [comment]
@Simon-He95 The problem doesn't seem to be resolved.

**Comment by Simon-He95** [comment]
Is the image below the correct representation ？

屏幕录制2022-12-20 23 30 58

**Review by chenxch — APPROVED** [review]

**Comment by tolking** [comment]
There are some problems with this PR.

After focus a `Select` component, clicking Esc multiple times will make the `Select` component lose focus, This will destroy A11y.

**Pull request closed without merging**
