### PR TITLE
fix(components): set flex-shrink for first child of submenu title

### LINKED ISSUE #5506: [Bug Report] menu组件折叠问题
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
 Chrome 97.0.4692.71

### Vue version
3.2.27

### Reproduction Link
https://codesandbox.io/s/crazy-nightingale-yfdyr?file=/src/App.vue

### Steps to reproduce
menu菜单折叠展开，左侧icon会轻微抖动位移

### What is Expected?
折叠展开时侧边不抖动

### What is actually happening?
menu菜单折叠展开，左侧icon会轻微抖动位移

### PR DESCRIPTION
**Pull request by nieyuyao**
Fix #5506 

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by msidolphin** [comment]
This modification is not enough, you can refer to my code
```diff
--- a/packages/theme-chalk/src/menu.scss
+++ b/packages/theme-chalk/src/menu.scss
@@ -211,6 +211,11 @@
     border-radius: var(--el-border-radius-small);
     box-shadow: var(--el-box-shadow-light);
   }
+
+  .#{$namespace}-icon {
+    flex-shrink: 0;
+  }
+   
 }
 
 @include b(menu-item) {
@@ -229,6 +234,18 @@
       color: inherit;
     }
   }
+
+  .el-menu-tooltip__trigger {
+    position: absolute;
+    left: 0;
+    top: 0;
+    height: 100%;
+    width: 100%;
+    display: inline-flex;
+    align-items: center;
+    box-sizing: border-box;
+    padding: 0 20px;
+  }
 }
 
 @include b(sub-menu) {
```

```diff
--- a/packages/components/menu/src/menu-item.vue
+++ b/packages/components/menu/src/menu-item.vue
@@ -23,18 +23,7 @@
   <template #content>
     <slot name="title" />
   </template>
-      <div
-        :style="{
-          position: 'absolute',
-          left: 0,
-          top: 0,
-          height: '100%',
-          width: '100%',
-          display: 'inline-block',
-          boxSizing: 'border-box',
-          padding: '0 20px',
-        }"
-      >
+      <div class="el-menu-tooltip__trigger">
     <slot />
   </div>
 </el-tooltip>
```

**Comment by nieyuyao** [comment]
@msidolphin Thanks for your reply! So do I modify the pr or close it?

**Comment by msidolphin** [comment]
> @msidolphin Thanks for your reply! So do I modify the pr or close it?

modify

**Comment by nieyuyao** [comment]
> > @msidolphin Thanks for your reply! So do I modify the pr or close it?
> 
> modify

done

**Review by msidolphin — APPROVED** [review]

**Pull request merged**
