### PR TITLE
fix(components): form select size change with inline style

### PR DESCRIPTION
**Pull request by YunYouJun**
- not add `initialInputHeight` when size same as componentSize to avoid inline style override

https://github.com/chenxch/element-plus/blob/d26f995291964175295141d376462cb708d81d60/packages/components/select/src/useSelect.ts#L179

> https://github.com/element-plus/element-plus/pull/7471

When we watch these, select will always resetInputWidth.
This causes when we switch the form size, the size of the select is overwritten by the inline style.

The solution I thought of, when the size is the same as the default size, don't add the initialInputHeight.

@chenxch Can you have a look?

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]

**Comment by chenxch** [comment]
I'm here to confirm right away.

**Comment by chenxch** [comment]
```js
input.getBoundingClientRect().height + 2 !== getComponentSize(selectSize.value || elForm.size)
```
If the three heights of 22/30/38 are set, there will be failures.

**Comment by YunYouJun** [comment]
Thanks for the feedback, this approach may not work.
 But now select will not change dynamically with form size, do you have any good way?

**Comment by chenxch** [comment]
Previously, the change of size under `el-config-provider` was fixed. I used the previous demo to adjust it to `el-form`, which is ok.

**Comment by YunYouJun** [comment]
It works in drawer. Because it is reinitialized.

You can try to put it on the home page, at this time dynamic switching fails.

**Comment by chenxch** [comment]
Maybe we should remove `states.initialInputHeight`, the component seems to be working fine now.

**Comment by YunYouJun** [comment]
Do you know what the purpose of `states.initialInputHeight` is? 
I'm afraid it might affect something we don't know about.

**Comment by YunYouJun** [comment]
Would you like to create a pr to try? I'll check again in the preview documentation.

**Pull request closed without merging**
