### PR TITLE
fix(components): import dayjs by a more compatible way

### PR DESCRIPTION
**Pull request by tolking**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

dayjs is a cjs module, If we write it like now it will generate some errors.

[eq.](https://stackblitz.com/edit/vitest-dev-vitest-vh6cdr?file=test/basic.test.ts)

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by xiaofuyesnew** [comment]
There's still an error when building with vite in version 2.2.11.

**Comment by arslan2012** [comment]
@xiaofuyesnew do you have 
```javascript
"esModuleInterop": true,
"allowSyntheticDefaultImports": true,
```
in your tsconfig compilerOptions?

**Comment by xiaofuyesnew** [comment]
@arslan2012 In fact, I stick to pure JavaScript for development. When I upgraded dayjs to `version 2.0.0-alpha.2` the problem was solved. It seems that this is mainly a dayjs problem.

**Comment by KahrLu** [comment]
There's still an error when building with vite in version 2.2.13.

**Comment by xiaofuyesnew** [comment]
> There's still an error when building with vite in version 2.2.13.

you can try in the `vite.config.js`:
```js
export defalut {
  ...,
  build: {
    commonjsOptions: {
      include: [
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/customParseFormat.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/localeData.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/advancedFormat.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/weekOfYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/weekYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/dayOfYear.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/isSameOrAfter.js',
          'node_modules/.pnpm/dayjs@1.11.4/node_modules/dayjs/plugin/isSameOrBefore.js',
      ]
    }
  }
}
```

**Comment by BitRayDev** [comment]
There's still an error when building with vite in version 2.2.17.

**Comment by saslavik** [comment]
Same problem was on Nuxt3 + Vite.

`
build: {
    transpile: [(lifecycle === "build" || lifecycle === "generate" ? "element-plus" : "element-plus/es")],
  },
`

**Comment by tolking** [comment]
@saslavik The error cannot be reproduced using the [element-plus-nuxt-starter](https://github.com/element-plus/element-plus-nuxt-starter)

**Review by brizer — COMMENTED** [review]
Good job

**Pull request merged**
