### PR TITLE
refactor(utils): refactor menu-bar

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
It seems that the test failed, please fix it.

**Comment by btea** [comment]
> It seems that the test failed, please fix it.

ok.

**Comment by btea** [comment]
> It seems that the test failed, please fix it.

I checked the details and found the failed test is time-picker.spec.ts. But my local test passed...

**Comment by btea** [comment]
The test is unstable~

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Thanks~

**Pull request merged**
