### PR TITLE
feat(components): [description-item] add labelWidth prop

### PR DESCRIPTION
**Pull request by Lakphy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Related Issue

#18639 

## Solution

Add `labelWidth` prop to `description-item` component.

### CODE REVIEW

**Comment by Lakphy** [comment]
> 👋 @Lakphy, seems like this is your first time contribution to element-plus.
> 
> * Please make sure that you have read our [guidelines](#%7Bguideline_url%7D) and [code of conduct](%7Bcoc_url%7D) before making a contribution.
> * You can comment with `/label Components:[component_name]` to add a label for which component you are working on.
> * You may join our Discord for staying tuned.

/label Component::Descriptions

**Comment by Lakphy** [comment]
[playground preview](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInNpemVcIj5cbiAgICA8ZWwtcmFkaW8gdmFsdWU9XCJsYXJnZVwiPkxhcmdlPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gdmFsdWU9XCJkZWZhdWx0XCI+RGVmYXVsdDwvZWwtcmFkaW8+XG4gICAgPGVsLXJhZGlvIHZhbHVlPVwic21hbGxcIj5TbWFsbDwvZWwtcmFkaW8+XG4gIDwvZWwtcmFkaW8tZ3JvdXA+XG5cbiAgPGVsLWRlc2NyaXB0aW9uc1xuICAgIGNsYXNzPVwibWFyZ2luLXRvcFwiXG4gICAgdGl0bGU9XCJXaXRoIGJvcmRlclwiXG4gICAgOmNvbHVtbj1cIjNcIlxuICAgIDpzaXplPVwic2l6ZVwiXG4gICAgYm9yZGVyXG4gID5cbiAgICA8dGVtcGxhdGUgI2V4dHJhPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPk9wZXJhdGlvbjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNlbGwtaXRlbVwiPlxuICAgICAgICAgIDxlbC1pY29uIDpzdHlsZT1cImljb25TdHlsZVwiPlxuICAgICAgICAgICAgPHVzZXIgLz5cbiAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAg55So5oi35ZCNXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIOa1i+ivleS4gOS4quWQjeivjVxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIDpsYWJlbC13aWR0aD1cIjEwMFwiPlxuICAgICAgPHRlbXBsYXRlICNsYWJlbD5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNlbGwtaXRlbVwiPlxuICAgICAgICAgIDxlbC1pY29uIDpzdHlsZT1cImljb25TdHlsZVwiPlxuICAgICAgICAgICAgPGlwaG9uZSAvPlxuICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgICDlj7fnoIFcbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAg5rWL6K+V5LiA5Liq5ZCN6K+N5rWL6K+V5LiA5Liq5ZCN6K+N5rWL6K+V5LiA5Liq5ZCN6K+NXG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8bG9jYXRpb24gLz5cbiAgICAgICAgICA8L2VsLWljb24+XG4gICAgICAgICAgUGxhY2VcbiAgICAgICAgPC9kaXY+XG4gICAgICA8L3RlbXBsYXRlPlxuICAgICAgU3V6aG91XG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8dGlja2V0cyAvPlxuICAgICAgICAgIDwvZWwtaWNvbj5cbiAgICAgICAgICBSZW1hcmtzXG4gICAgICAgIDwvZGl2PlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC10YWcgc2l6ZT1cInNtYWxsXCI+U2Nob29sPC9lbC10YWc+XG4gICAgPC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgICA8dGVtcGxhdGUgI2xhYmVsPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY2VsbC1pdGVtXCI+XG4gICAgICAgICAgPGVsLWljb24gOnN0eWxlPVwiaWNvblN0eWxlXCI+XG4gICAgICAgICAgICA8b2ZmaWNlLWJ1aWxkaW5nIC8+XG4gICAgICAgICAgPC9lbC1pY29uPlxuICAgICAgICAgIOWcsOWdgFxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvdGVtcGxhdGU+XG4gICAgICDmtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or43mtYvor5XkuIDkuKrlkI3or41cbiAgICA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICA8L2VsLWRlc2NyaXB0aW9ucz5cblxuICA8ZWwtZGVzY3JpcHRpb25zXG4gICAgY2xhc3M9XCJtYXJnaW4tdG9wXCJcbiAgICB0aXRsZT1cIldpdGhvdXQgYm9yZGVyXCJcbiAgICA6Y29sdW1uPVwiM1wiXG4gICAgOnNpemU9XCJzaXplXCJcbiAgICA6c3R5bGU9XCJibG9ja01hcmdpblwiXG4gID5cbiAgICA8dGVtcGxhdGUgI2V4dHJhPlxuICAgICAgPGVsLWJ1dHRvbiB0eXBlPVwicHJpbWFyeVwiPk9wZXJhdGlvbjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVXNlcm5hbWVcIj5rb29yaW9va2FtaTwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiVGVsZXBob25lXCI+MTgxMDAwMDAwMDA8L2VsLWRlc2NyaXB0aW9ucy1pdGVtPlxuICAgIDxlbC1kZXNjcmlwdGlvbnMtaXRlbSBsYWJlbD1cIlBsYWNlXCI+U3V6aG91PC9lbC1kZXNjcmlwdGlvbnMtaXRlbT5cbiAgICA8ZWwtZGVzY3JpcHRpb25zLWl0ZW0gbGFiZWw9XCJSZW1hcmtzXCI+XG4gICAgICA8ZWwtdGFnIHNpemU9XCJzbWFsbFwiPlNjaG9vbDwvZWwtdGFnPlxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gICAgPGVsLWRlc2NyaXB0aW9ucy1pdGVtIGxhYmVsPVwiQWRkcmVzc1wiPlxuICAgICAgTm8uMTE4OCwgV3V6aG9uZyBBdmVudWUsIFd1emhvbmcgRGlzdHJpY3QsIFN1emhvdSwgSmlhbmdzdSBQcm92aW5jZVxuICAgIDwvZWwtZGVzY3JpcHRpb25zLWl0ZW0+XG4gIDwvZWwtZGVzY3JpcHRpb25zPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGNvbXB1dGVkLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQge1xuICBJcGhvbmUsXG4gIExvY2F0aW9uLFxuICBPZmZpY2VCdWlsZGluZyxcbiAgVGlja2V0cyxcbiAgVXNlcixcbn0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5pbXBvcnQgdHlwZSB7IENvbXBvbmVudFNpemUgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IHNpemUgPSByZWY8Q29tcG9uZW50U2l6ZT4oJ2RlZmF1bHQnKVxuXG5jb25zdCBpY29uU3R5bGUgPSBjb21wdXRlZCgoKSA9PiB7XG4gIGNvbnN0IG1hcmdpbk1hcCA9IHtcbiAgICBsYXJnZTogJzhweCcsXG4gICAgZGVmYXVsdDogJzZweCcsXG4gICAgc21hbGw6ICc0cHgnLFxuICB9XG4gIHJldHVybiB7XG4gICAgbWFyZ2luUmlnaHQ6IG1hcmdpbk1hcFtzaXplLnZhbHVlXSB8fCBtYXJnaW5NYXAuZGVmYXVsdCxcbiAgfVxufSlcbmNvbnN0IGJsb2NrTWFyZ2luID0gY29tcHV0ZWQoKCkgPT4ge1xuICBjb25zdCBtYXJnaW5NYXAgPSB7XG4gICAgbGFyZ2U6ICczMnB4JyxcbiAgICBkZWZhdWx0OiAnMjhweCcsXG4gICAgc21hbGw6ICcyNHB4JyxcbiAgfVxuICByZXR1cm4ge1xuICAgIG1hcmdpblRvcDogbWFyZ2luTWFwW3NpemUudmFsdWVdIHx8IG1hcmdpbk1hcC5kZWZhdWx0LFxuICB9XG59KVxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uZWwtZGVzY3JpcHRpb25zIHtcbiAgbWFyZ2luLXRvcDogMjBweDtcbn1cbi5jZWxsLWl0ZW0ge1xuICBkaXNwbGF5OiBmbGV4O1xuICBhbGlnbi1pdGVtczogY2VudGVyO1xufVxuLm1hcmdpbi10b3Age1xuICBtYXJnaW4tdG9wOiAyMHB4O1xufVxuPC9zdHlsZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xODY3My1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTg2NzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE4NjczLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xODY3My1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

**Comment by warmthsea** [comment]
Can you add test code?

**Comment by Lakphy** [comment]
> Can you add test code?

Of course, I'll make it up today.

**Comment by Lakphy** [comment]
> Can you add test code?

My test code is ready 🫡. @warmthsea

**Comment by warmthsea** [comment]
> > Can you add test code?
> 
> My test code is ready 🫡. @warmthsea

Good jobs , could you please change the above question?

**Comment by Lakphy** [comment]
> > > Can you add test code?
> > 
> > 
> > My test code is ready 🫡. @warmthsea
> 
> Good jobs , could you please change the above question?

Sorry, I don't see why the test code of the Avatar component failed in the last pipeline.

In my local similar environment, all test cases passed. _nodejs v22.11.0, pnpm@9.12.3_

Maybe we need to rerun the pipeline?

截屏2024-11-01 01 07 21

**Comment by warmthsea** [comment]
> > > > Can you add test code?
> > > 
> > > 
> > > My test code is ready 🫡. @warmthsea
> > 
> > 
> > Good jobs , could you please change the above question?
> 
> Sorry, I don't see why the test code of the Avatar component failed in the last workflow.
> 
> In my local similar environment, all test cases passed. _nodejs v22.11.0, pnpm@9.12.3_
> 
> Maybe we need to rerun the workflow?
> 
> 截屏2024-11-01 01 07 21

These comments.

image

**Comment by Lakphy** [comment]
> > > > > Can you add test code?
> > > > 
> > > > 
> > > > My test code is ready 🫡. @warmthsea
> > > 
> > > 
> > > Good jobs , could you please change the above question?
> > 
> > 
> > Sorry, I don't see why the test code of the Avatar component failed in the last workflow.
> > In my local similar environment, all test cases passed. _nodejs v22.11.0, pnpm@9.12.3_
> > Maybe we need to rerun the workflow?
> > 截屏2024-11-01 01 07 21
> 
> These comments.
> 
> image

OK, I have resolved the two comments in your screenshot. 

I don't know why I can't see your comments in my code, thank you for your suggestions on my code.

**Comment by Lakphy** [comment]
The markdown table code has been adjusted here, so many lines have changed. This screenshot may show the changes more clearly.

截屏2024-11-01 22 36 40

**Comment by warmthsea** [comment]
> The markdown table code has been adjusted here, so many lines have changed. This screenshot may show the changes more clearly.
> 
> 
> 
> 截屏2024-11-01 22 36 40
> 
> 

Yes, this is right.

**Comment by Lakphy** [comment]
It looks like I missed the 2.8.7 release window. I updated the document to be changed in my PR.

**Review by warmthsea — APPROVED** [review]
LGTM

**Comment by btea** [comment]
I think both `descriptions` and `descriptions-item` can support this configuration. If both are configured at the same time, the configuration of `descriptions-item` will take precedence.

**Comment by Lakphy** [comment]
> I think both `descriptions` and `descriptions-item` can support this configuration. If both are configured at the same time, the configuration of `descriptions-item` will take precedence.

OK, I have added these features.

**Comment by Lakphy** [comment]
But I also found some problems. Due to the characteristics of HTML table, the cell width may be out of control in some cases, for example:
- The text is very long and exceeds the set width
- There are other longer cells in the same column
Not only the `labelWidth` attribute, but also the `width` attribute used to limit the content width has such problems.
Maybe we need to be more clear about the component behavior in these cases: for example, the content exceeds the line break or is omitted, and a `maxWidth` attribute may be needed.

Of course, these problems may not be the focus of this PR. I just put forward some thoughts and suggestions. If you want to solve the above problems, I am also very happy to contribute.

**Comment by btea** [comment]
Maybe we don’t need to consider so much at the moment. We can directly refer to the `form` component's `label-width`. If the user specifies the width, it will automatically wrap if it exceeds that width.

**Review by btea — APPROVED** [review]

**Comment by Lakphy** [comment]
> Maybe we don’t need to consider so much at the moment. We can directly refer to the `form` component's `label-width`. If the user specifies the width, it will automatically wrap if it exceeds that width.

I think so. Thank you very much.🫡

**Review by warmthsea — APPROVED** [review]

**Comment by FireLightGuo** [comment]
非常有用的更新，之前用这个组件一直受label宽度的困扰（label宽度不固定）👍

**Comment by btea** [comment]
@nanbowanll1 There is already a related PR. https://github.com/element-plus/element-plus/pull/19162

**Pull request merged**
