### PR TITLE
fix(theme-chalk): [picker] adjust range picker input height

### LINKED ISSUE #8876: [Component] [date-picker] 当日期选择器组件 disabled 状态时内部 input 框的背景色遮盖了组件的边框
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `103.0.5060.114（正式版本） （64 位）`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWRhdGUtcGlja2VyIHR5cGU9XCJkYXRlcmFuZ2VcIiBkaXNhYmxlZCAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZT5cbiAgLmVsLWRhdGUtZWRpdG9yLmVsLWlucHV0X193cmFwcGVyLmlzLWRpc2FibGVkIHtcbiAgICAvL3BhZGRpbmc6IDFweCAxMHB4OyAvLyDmlL7lvIDov5nph4zmoLflvI/mraPluLhcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

nothing

### What is Expected?

样式正常，边框不被遮盖

### What is actually happening?

组件边框被遮盖
D43556BE-3C04-460c-B3D8-AC1C654957DA

### Additional comments

_(empty)_

### LINKED ISSUE #8953: [Component] [date-picker] when type is set to daterange and is disabled, the background color of the input box is incorrect
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `Chrome 102.0.5005.61/Mac os 12.2.1 `
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc3dpdGNoIHYtbW9kZWw9XCJkaXNhYmxlZFwiIC8+XG4gIDxlbC1kYXRlLXBpY2tlclxuICAgIHYtbW9kZWw9XCJ0aW1lXCJcbiAgICB0eXBlPVwiZGF0ZXJhbmdlXCJcbiAgICB1bmxpbmstcGFuZWxzXG4gICAgcmFuZ2Utc2VwYXJhdG9yPVwiVG9cIlxuICAgIHN0YXJ0LXBsYWNlaG9sZGVyPVwiU3RhcnQgbW9udGhcIlxuICAgIGVuZC1wbGFjZWhvbGRlcj1cIkVuZCBtb250aFwiXG4gICAgOnNob3J0Y3V0cz1cInNob3J0Y3V0c1wiXG4gICAgOmRpc2FibGVkPVwiZGlzYWJsZWRcIlxuICAvPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGRpc2FibGVkID0gcmVmKHRydWUpXG5jb25zdCB0aW1lID0gcmVmKFsnMjAyMi0wMi0wMycsICcyMDIyLTA1LTEyJ10pXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

Click the link

### What is Expected?

The background color is set correctly

### What is actually happening?

The background color covers the border

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by holazz**
closes #8876, closes #8953

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
@YunYouJun cc ~

**Comment by YunYouJun** [comment]
Maybe we can set `input` (when disabled) `background-color: transparent` to solve this problem.

Do you see any potential problems?

**Comment by YunYouJun** [comment]
I've been thinking about whether there is a better solution.
It looks like we still have to change the height to avoid the chrome auto-fill input background color issue.

**Comment by holazz** [comment]
@YunYouJun This is for consistency with the style of common datepicker.

WX20220726-083959@2x

WX20220726-084223@2x

**Review by xiaoxian521 — APPROVED** [review]

**Pull request merged**
