### PR TITLE
feat(components): [mention] explicit export dropdownVisible

### PR DESCRIPTION
**Pull request by SorrowX**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by SorrowX** [comment]
这个pr是针对 这个 feat https://github.com/element-plus/element-plus/discussions/18457 

希望可以抛出这个属性，业务开发需要知道提及弹窗是否打开

**Review by warmthsea — COMMENTED** [review]
Thank you for your contribution.
Please refer to this PR, mark the document version number, it would be better if you add tests.
https://github.com/element-plus/element-plus/pull/17650/files

**Review by warmthsea — APPROVED** [review]
Waiting for https://github.com/element-plus/element-plus/pull/18453 to be merged.

**Review by btea — APPROVED** [review]
Thanks!

**Pull request merged**
