### PR TITLE
style(theme-chalk): [menu] horizontal mode submenu line-high

### PR DESCRIPTION
**Pull request by WindBearr**
When you hover over the lower part of a menu-item, the next menu-item will be selected

closed N

The reason is found by checking the css, because the height of menu-item is 36px, but the line-height is 56px.

### CODE REVIEW

**Comment by WindBearr** [comment]
element-plus官网的示例就能看到现象
https://element-plus.gitee.io/en-US/component/menu.html#top-bar

**Comment by chenxch** [comment]
Sorry, I can't understand your description, can you provide a screen recording?

**Comment by WindBearr** [comment]
> Sorry, I can't understand your description, can you provide a screen recording?

image

**Comment by WindBearr** [comment]
This is a bug fed back to me by our product manager. After fixing it, I decided to provide you with solutions

**Comment by chenxch** [comment]
I get it, thanks for your feedback and contributions.  ❤️

**Comment by WindBearr** [comment]
> I get it, thanks for your feedback and contributions. ❤️
Please review again because I accidentally clicked the update branch. I'm very sorry

**Comment by chenxch** [comment]
Don't worry, it's been agreed again.

**Review by chenxch — APPROVED** [review]

**Review by ryuhangyeong — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Pull request merged**
