### PR TITLE
fix(select): should not stop at invisible options by up and down

### LINKED ISSUE #2563: [Bug Report] use down-direction to move hoverIndex not right
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows10 / Chrome 91.0.4472.124

### Vue version
3.2.0-beta.1

### Reproduction Link
https://codepen.io/codermonkie/pen/YzVQQpz

### Steps to reproduce
attributes:
    `multiple`
    `filterable`
    `allow-create`

1. type "foo" and down-direction and Enter (will create a "foo" tag that not in dropdown)
2. type "bar" and down-direction and Enter (will create a "bar" tag that not in dropdown)
3. click remove icon button to remove both "foo" and "bar" tag
4. keep input box focused and type direction key (up or down)
5. [BUG] to find hover style changing not correctly, it will stop at options not vilible

### What is Expected?
there are 3 options in dropdown, so take 3 times pressing down-direction for a round is better ?

### What is actually happening?
it will take 5 times pressing down-direction for a round

### PR DESCRIPTION
**Pull request by CoderMonkie**
this also fix another problem (#2562): about unselect user-created tag in ElSelect

fix #2563 #2562

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by msidolphin** [comment]
Thank you for your pr, i think you'd better provide test cases to verify your changes

**Comment by JeremyWuuuuu** [comment]
Some test cases were failed, you might need to figure out how to fix it and add code to test your own cases.

**Comment by CoderMonkie** [comment]
> Some test cases were failed, you might need to figure out how to fix it and add code to test your own cases.

thank you but,
image

**Comment by CoderMonkie** [comment]
> Some test cases were failed, you might need to figure out how to fix it and add code to test your own cases.

Hi~ Do you mean this:
image

but .. I have not change that code ever.

**Comment by msidolphin** [comment]
> > Some test cases were failed, you might need to figure out how to fix it and add code to test your own cases.
> 
> Hi~ Do you mean this:
> image
> 
> but .. I have not change that code ever.
> 
> (found that not recur everytime..)
> 
> 失敗したテストケースが自分が触っていないソースコードなのですが、
> 必ず再現できるのでもないです。。。

Hmmmm, but  your own unit tests are still necessary

**Comment by CoderMonkie** [comment]
@msidolphin 
I have added some test cases for "default-first-option",
and also tested "naviagteOptions" method.

thanks

**Review by jw-foss — APPROVED** [review]
Code LGTM cc @msidolphin can you do a double check?

**Comment by msidolphin** [comment]
> LGTM

I have no problem on my side either, I think we can merge

**Review by msidolphin — APPROVED** [review]

**Pull request merged**
