### PR TITLE
fix(components): [radio checkbox] fix click event triggered twice

### PR DESCRIPTION
**Pull request by FrontEndDog**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Description
if I using radio or checkbox in dropdown，@command will trigger twice

image

This problem is caused by input and label

[look here](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWRyb3Bkb3duIEBjb21tYW5kPVwiaGFuZGxlQ29tbWFuZFwiIDpoaWRlLW9uLWNsaWNrPVwiZmFsc2VcIj5cbiAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIERyb3Bkb3duIExpc3RcbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3gxXCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3gxXCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3gyXCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3gyXCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3gzXCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3gzXCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3g0XCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3g0XCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG5cbiAgPGRpdj5cbiAgICA8ZWwtcmFkaW8gQGNsaWNrPVwidGVzdFwiPnJhZGlvPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8tYnV0dG9uIEBjbGljaz1cInRlc3RcIj5yYWRpby1idXR0b248L2VsLXJhZGlvLWJ1dHRvbj5cbiAgICA8ZWwtY2hlY2tib3ggQGNsaWNrPVwidGVzdFwiPmNoZWNrYm94PC9lbC1jaGVja2JveD5cbiAgICA8ZWwtY2hlY2tib3gtYnV0dG9uIEBjbGljaz1cInRlc3RcIj5jaGVja2JveC1idXR0b248L2VsLWNoZWNrYm94LWJ1dHRvbj5cbiAgPC9kaXY+XG5cbiAgPGRpdj5cbiAgICA8bGFiZWwgQGNsaWNrPVwidGVzdFwiPlxuICAgICAgPGlucHV0IHR5cGU9XCJyYWRpb1wiIC8+XG4gICAgICBjbGljayBoZXJlIHRyaWdnZXIgdHdpY2VcbiAgICA8L2xhYmVsPlxuICAgIDxsYWJlbCBAY2xpY2s9XCJ0ZXN0XCI+XG4gICAgICA8aW5wdXQgdHlwZT1cInJhZGlvXCIgQGNsaWNrLnN0b3AgLz5cbiAgICAgIGNsaWNrIGhlcmUgdHJpZ2dlciBvbmNlXG4gICAgPC9sYWJlbD5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuY29uc3QgaGFuZGxlQ29tbWFuZCA9IChrZXkpID0+IHtcbiAgY29uc29sZS5sb2coa2V5KVxufVxuY29uc3QgdGVzdCA9ICgpID0+IHtcbiAgY29uc29sZS5sb2coJ2NsaWNrJylcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 4f66a48</samp>

*  Prevent click events from bubbling up and triggering change events twice in checkbox and radio components ([link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-481560faad6b7090a74c8e2506658fa6d2c14bf6ed44e9ada526d870c5a27d0aR16), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-481560faad6b7090a74c8e2506658fa6d2c14bf6ed44e9ada526d870c5a27d0aR30), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-ea5ffcb1d7a99d505b8cbe4d771f599f7faccb516c33fe8874de354bedc3a4ffR29), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-ea5ffcb1d7a99d505b8cbe4d771f599f7faccb516c33fe8874de354bedc3a4ffR45), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-3afc059b8778e73a6a6f76f57d5788e4236e84dc6b32c4899b5ecb51d592f182R21), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-d4b559306ebd21e526b0b178df13ebb73cc8506924cbaa0590c015f479c52b38R30))
  * Add `@click.stop` modifier to `el-button` and `el-checkbox` components in `checkbox-button.vue` and `checkbox.vue` files ([link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-481560faad6b7090a74c8e2506658fa6d2c14bf6ed44e9ada526d870c5a27d0aR16), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-481560faad6b7090a74c8e2506658fa6d2c14bf6ed44e9ada526d870c5a27d0aR30), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-ea5ffcb1d7a99d505b8cbe4d771f599f7faccb516c33fe8874de354bedc3a4ffR29), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-ea5ffcb1d7a99d505b8cbe4d771f599f7faccb516c33fe8874de354bedc3a4ffR45))
  * Add `@click.stop` modifier to `el-button` and `el-radio` components in `radio-button.vue` and `radio.vue` files ([link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-3afc059b8778e73a6a6f76f57d5788e4236e84dc6b32c4899b5ecb51d592f182R21), [link](https://github.com/element-plus/element-plus/pull/13936/files?diff=unified&w=0#diff-d4b559306ebd21e526b0b178df13ebb73cc8506924cbaa0590c015f479c52b38R30))

### CODE REVIEW

**Review by btea — APPROVED** [review]

**Review by ryuhangyeong — COMMENTED** [review]
It looks like a bug, but I wonder if there are many use cases for doing something with @click events on checkboxes and radio buttons. 🤔

**Comment by FrontEndDog** [comment]
> It looks like a bug, but I wonder if there are many use cases for doing something with @click events on checkboxes and radio buttons. 🤔

Whether used or not, triggering a click event twice is itself an error。

I came up with a scene，if click card edge，Triggered once，if click radio，Triggered twice

[look here](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWNhcmQgQGNsaWNrPVwib3Blbk5ld1BhZ2UoaXRlbSlcIiB2LWZvcj1cIml0ZW0gaW4gNVwiIDprZXk9XCJpdGVtXCI+XG4gICAgPGVsLXJhZGlvPnJhZGlvPC9lbC1yYWRpbz5cbiAgPC9lbC1jYXJkPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmNvbnN0IG9wZW5OZXdQYWdlID0gKGl0ZW0pID0+IHtcbiAgY29uc29sZS5sb2coJ29wZW4nLCBpdGVtKVxufVxuPC9zY3JpcHQ+XG48c3R5bGUgc2NvcGVkPlxuLmVsLWNhcmQge1xuICBtYXJnaW4tdG9wOiAxMHB4O1xuICB3aWR0aDogNDAlO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

**Review by ryuhangyeong — APPROVED** [review]
cc @tolking

**Comment by tolking** [comment]
Thank for your contribution. 

I do not think this is a BUG, You can use the change event instead of the click event.

If add the `@click.stop` to input, the click event will not be triggered when input is clicked, which is also unreasonable behavior.

**Comment by FrontEndDog** [comment]
> Thank for your contribution.
> 
> I do not think this is a BUG, You can use the change event instead of the click event.
> 
> If add the `@click.stop` to input, the click event will not be triggered when input is clicked, which is also unreasonable behavior.

The issue you mentioned will only appear in the native input and label，will not appear in element plus。

because input in element-plus is hidden。

**Comment by FrontEndDog** [comment]
To supplement, This issue was discovered when I was using el-dropdown, if I use `@change` instead of `@command`, the change event will not be triggered when click the el-dropdown-item edge.

So I should use `@command`, but `@command` will triggered twice when without  `click.stop`

image

[demo is here](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGRpdj51c2UgQGNvbW1hbmQ8L2Rpdj5cbiAgPGVsLWRyb3Bkb3duIEBjb21tYW5kPVwiaGFuZGxlQ29tbWFuZFwiIDpoaWRlLW9uLWNsaWNrPVwiZmFsc2VcIj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+XG4gICAgICBEcm9wZG93biBMaXN0XG4gICAgPC9lbC1idXR0b24+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3gxXCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3gxXCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBjb21tYW5kPVwiY2hlY2tib3gyXCI+XG4gICAgICAgICAgPGVsLWNoZWNrYm94IGxhYmVsPVwiY2hlY2tib3gyXCIgLz5cbiAgICAgICAgPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgPC9lbC1kcm9wZG93bi1tZW51PlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtZHJvcGRvd24+XG4gIDxwPjwvcD5cbiAgPGRpdj51c2UgQGNoYW5nZTwvZGl2PlxuICA8ZWwtZHJvcGRvd24gOmhpZGUtb24tY2xpY2s9XCJmYWxzZVwiPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIj5cbiAgICAgIERyb3Bkb3duIExpc3RcbiAgICA8L2VsLWJ1dHRvbj5cbiAgICA8dGVtcGxhdGUgI2Ryb3Bkb3duPlxuICAgICAgPGVsLWRyb3Bkb3duLW1lbnU+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGNvbW1hbmQ9XCJjaGVja2JveDFcIj5cbiAgICAgICAgICA8ZWwtY2hlY2tib3ggbGFiZWw9XCJjaGVja2JveDFcIiBAY2hhbmdlPVwiaGFuZGxlQ29tbWFuZCgnY2hlY2tib3gxJylcIiAvPlxuICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtIGNvbW1hbmQ9XCJjaGVja2JveDJcIj5cbiAgICAgICAgICA8ZWwtY2hlY2tib3ggbGFiZWw9XCJjaGVja2JveDJcIiBAY2hhbmdlPVwiaGFuZGxlQ29tbWFuZCgnY2hlY2tib3gyJylcIiAvPlxuICAgICAgICA8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICA8L2VsLWRyb3Bkb3duLW1lbnU+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1kcm9wZG93bj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5jb25zdCBoYW5kbGVDb21tYW5kID0gKGtleSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXkpXG59XG5jb25zdCBoYW5kbGVDaGFuZ2UgPSAoa2V5KSA9PiB7XG4gIGNvbnNvbGUubG9nKGtleSlcbn1cbjwvc2NyaXB0PlxuPHN0eWxlIHNjb3BlZD48L3N0eWxlPiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Review by tolking — APPROVED** [review]

**Comment by shahzadirtaza3-sudo** [comment]
FrontEndDog:fix-label-input

**Pull request merged**
