### PR TITLE
fix(date-time-picker): fix the bug of the second value is reset to the first value when the time range is selected (#1951)

### PR DESCRIPTION
**Pull request by zhazhanitian**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

**fix**: [1951](https://github.com/element-plus/element-plus/issues/1951)

**The cause of the bug**
Each time the data is backfilled, part of the data is not backfilled to, resulting in some fields using the initial data

### CODE REVIEW

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu @justwiner @zouhangwithsweet 

How often do you deal with a wave of PR? For developers who actively participate in the contribution, PR can not be dealt with, which is a great blow to their enthusiasm

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu @justwiner @zouhangwithsweet 

How often do you deal with a wave of PR? For developers who actively participate in the contribution, PR can not be dealt with, which is a great blow to their enthusiasm

**Comment by JeremyWuuuuu** [comment]
@zhazhanitian  We are sorry for the late response. The team has been through a big change since some of them don't have time to do OSS. I feel what you felt. I will review your PR immediately. Sorry again for the late response.

**Comment by HerringtonDarkholme** [comment]
Thanks for your contribution! Could you please add a unit test for this case? thanks1

**Comment by zhazhanitian** [comment]
> Thanks for your contribution! Could you please add a unit test for this case? thanks1

OK, I'll try to see if I can complete the unit test independently. If I have any difficulty, I'll ask for advice

**Comment by JeremyWuuuuu** [comment]
Since the testing code weren't ready for 1.0.2-beta.45 release. We will queue this into beta.46 then.

**Comment by zhazhanitian** [comment]
> Since the testing code weren't ready for 1.0.2-beta.45 release. We will queue this into beta.46 then.


I'm sorry, I'm working on my resignation recently, so I don't have time to invest. I'll speed up the unit test

**Comment by HerringtonDarkholme** [comment]
@zhazhanitian No hurry! And wish you a brilliant career and a bright future!

**Comment by JeremyWuuuuu** [comment]
@zhazhanitian Hey, just checking in to see if you need any help from us.

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu I am really sorry that this matter has been delayed for so long because of my resignation. I will actively respond to the follow-up tasks

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu @HerringtonDarkholme Please deal with this PR in your spare time. Thank you

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu 

I don't quite understand why I submitted the record without using it and reopened an issue to solve this problem. I don't see any difference in the code

https://github.com/element-plus/element-plus/pull/2747

**Comment by zhazhanitian** [comment]
I thought it was because I submitted the unit test too late, but I found that the submission record was still submitted later

**Comment by zhazhanitian** [comment]
If there is any problem in my code specification, please mention it so that I can correct it in the subsequent submission，Thank you！

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Comment by zhazhanitian** [comment]
@xiaoxian521  I thought this project had been abandoned. In the short term, I have no idea of participating in open source again. I think we can close this PR first

**Comment by xiaoxian521** [comment]
> @xiaoxian521 I thought this project had been abandoned. In the short term, I have no idea of participating in open source again. I think we can close this PR first

好的，感谢你的贡献～！

**Pull request closed without merging**
