### PR TITLE
refactor(build): duplicate variable name

### PR DESCRIPTION
**Pull request by Brain777777**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by holazz** [comment]
I think this is not an error, the inner `tasks`  is a local variable of the function and can only be accessed within the function. 🤔

**Comment by sxzz** [comment]
Yeah, is this really necessary?

**Comment by Brain777777** [comment]
🙃 This isn't really a mistake, and it might seem confusing

**Comment by Brain777777** [comment]
Yeah changing the naming of the variable is just to make it more recognizable 😸

**Comment by sxzz** [comment]
Ok then `subTasks` will be acceptable.

**Comment by Brain777777** [comment]
@sxzz 😆 Do i need to resubmit a PR ?

**Comment by sxzz** [comment]
@Brain777777 Just update the file in the this PR.

**Comment by Brain777777** [comment]
> @Brain777777 Just update the file in this PR.

👌

**Review by sxzz — APPROVED** [review]

**Comment by jw-foss** [comment]
Seems like we have some CI issue here @Brain777777 would you mind rebase the upstream and force push to trigger it again?

**Comment by Brain777777** [comment]
@jw-foss  Do I need to rebase the upstream to trigger CI again ?

**Comment by jw-foss** [comment]
> @jw-foss Do I need to rebase the upstream to trigger CI again ?

Yes, something happened to GitHub Actions, we can do nothing about it so you need to push again for triggering it.

**Comment by Brain777777** [comment]
> > @jw-foss Do I need to rebase the upstream to trigger CI again ?
> 
> Yes, something happened to GitHub Actions, we can do nothing about it so you need to push again for triggering it.

👌

**Pull request merged**
