### PR TITLE
chore: update issue workflow

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by juzhiyuan** [comment]
Hi @sxzz, may I know why we need this change? 😄 Would better update this PR's description and title so reviewers could know what exactly happened.

**Comment by sxzz** [comment]
GitHub Action bot can't comment locked issue.
https://github.com/element-plus/element-plus/runs/4496889566?check_suite_focus=true

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
I wonder can we comment on the issue first then lock it afterwards? Just thinking.

**Comment by juzhiyuan** [comment]
noted, thanks!

**Pull request merged**
