### PR TITLE
fix(components): [el-menu] childNodes is null

### PR DESCRIPTION
**Pull request by xiaoxian521**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xiaoxian521** [comment]
The error is as follows
image

**Comment by holazz** [comment]
Sorry I made a mistake here 😅

**Comment by xiaoxian521** [comment]
@holazz Hey, your recent contribution is really awesome, let me know if you are interested in joining the element-plus team❤️

**Comment by holazz** [comment]
> @holazz Hey, your recent contribution is really awesome, let me know if you are interested in joining the element-plus team❤️

Yes! It is my pleasure to join Element Plus if I could, and I will do my best to make it better. 😊

**Comment by xiaoxian521** [comment]
Great, please add my wechat: 18237613535

**Review by btea — APPROVED** [review]

**Pull request merged**
