### PR TITLE
use $namespace variable in all theme-chalk/src/* files and website/demo-style/* files

### PR DESCRIPTION
**Pull request by Chris-Kin**
related to [discussions/1401](https://github.com/element-plus/element-plus/discussions/1401)

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by zazzaz — APPROVED** [review]
LGTM

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@Chris-Kin , you need to resolve the conflict before gets merged.

**Comment by Chris-Kin** [comment]
> @Chris-Kin , you need to resolve the conflict before gets merged.

I resolved this conflict on github panel just now . If I should make a new PR to cover current PR, feel free to tell me.

**Comment by Chris-Kin** [comment]
Could this PR be merged as soon as possible. For reducing the potential conflict.

**Comment by zazzaz** [comment]
@Chris-Kin sorry for the late reply, could you please resolve the conflicts again and we will merge it ASAP

**Comment by Chris-Kin** [comment]
> @Chris-Kin sorry for the late reply, could you please resolve the conflicts again and we will merge it ASAP

the conflict has been resolved~

```scss
<<<<<<< feat/css-prefix-config
    &:focus.is-active.is-focus:not(:active) {
      box-shadow: 0 0 2px 2px $--color-primary inset;
      border-radius: 3px;
    }

    & .#{$namespace}-icon-close {
=======
    & .el-icon-close {
>>>>>>> dev
```

It should be resolved as:

```scss
    & .#{$namespace}-icon-close {
```

**Comment by zazzaz** [comment]
Cool

**Pull request merged**
