### PR TITLE
fix(loading): instance name

### LINKED ISSUE #1897: [Bug Report] Loading Diretvie error
### Element Plus version
1.0.2-beta.40

### OS/Browsers version
chrome 73

### Vue version
3.0.11

### Reproduction Link
https://github.com/element-plus/element-plus/blob/dev/packages/loading/src/directive.ts

### Steps to reproduce
 el.instance = Loading({
    text: vm && vm[textExr] || textExr,
    spinner: vm && vm[spinnerExr] || spinnerExr,
    background: vm && vm[backgroundExr] || backgroundExr,
    customClass: vm && vm[customClassExr] || customClassExr,
    fullscreen: !!binding.modifiers.fullscreen,
    target: !!binding.modifiers.fullscreen ? null : el,
    body: !!binding.modifiers.body,
    visible: true,
    lock: !!binding.modifiers.lock,
  })

### What is Expected?
el.Instance conflicts with other libraries.
The mount is not expected to overwrite.

### What is actually happening?
```
        el.instance = Loading({
    text: vm && vm[textExr] || textExr,
    spinner: vm && vm[spinnerExr] || spinnerExr,
    background: vm && vm[backgroundExr] || backgroundExr,
    customClass: vm && vm[customClassExr] || customClassExr,
    fullscreen: !!binding.modifiers.fullscreen,
    target: !!binding.modifiers.fullscreen ? null : el,
    body: !!binding.modifiers.body,
    visible: true,
    lock: !!binding.modifiers.lock,
  })
```
el.Instance conflicts with other libraries.

### PR DESCRIPTION
**Pull request by 19Qingfeng**
Please make sure these boxes are checked before submitting your PR, thank you!

fix [#1897](https://github.com/element-plus/element-plus/issues/1897)

 * [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
 * [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Please revert your `package-lock.json`.

**Comment by JeremyWuuuuu** [comment]
The code LGTM, but you need to address the issue I mentioned above.

**Comment by JeremyWuuuuu** [comment]
Looks like the test failed due to your change, please update tests against your change. Thank you

**Comment by 19Qingfeng** [comment]
> The code LGTM, but you need to address the issue I mentioned above.

ok,I will check my PR.thanks

**Comment by JeremyWuuuuu** [comment]
Closing since no further actions, feel free to reopen it.

**Pull request closed without merging**
