### PR TITLE
fix(components): [autocomplete] fetch-suggestions support AsyncFunction

### LINKED ISSUE #7278: [Bug Report] [Component] [autocomplete] The 'fetch-suggestions' prop of el-autocomplete does not support async method
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.10`
- Browser / OS: `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36'`
- Build Tool: `Vite`

### Related Component

- `el-autocomplete`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYXV0b2NvbXBsZXRlXG4gICAgdi1tb2RlbD1cInN0YXRlXCJcbiAgICA6ZmV0Y2gtc3VnZ2VzdGlvbnM9XCJxdWVyeVNlYXJjaEFzeW5jXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgQHNlbGVjdD1cImhhbmRsZVNlbGVjdFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgb25Nb3VudGVkLCByZWYsIG5leHRUaWNrIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBzdGF0ZSA9IHJlZignJylcblxuaW50ZXJmYWNlIExpbmtJdGVtIHtcbiAgdmFsdWU6IHN0cmluZ1xuICBsaW5rOiBzdHJpbmdcbn1cblxuY29uc3QgbGlua3MgPSByZWY8TGlua0l0ZW1bXT4oW10pXG5cbmNvbnN0IGxvYWRBbGwgPSAoKSA9PiB7XG4gIHJldHVybiBbXG4gICAgeyB2YWx1ZTogJ3Z1ZScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vdnVlanMvdnVlJyB9LFxuICAgIHsgdmFsdWU6ICdlbGVtZW50JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS9FbGVtZUZFL2VsZW1lbnQnIH0sXG4gICAgeyB2YWx1ZTogJ2Nvb2tpbmcnLCBsaW5rOiAnaHR0cHM6Ly9naXRodWIuY29tL0VsZW1lRkUvY29va2luZycgfSxcbiAgICB7IHZhbHVlOiAnbWludC11aScsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vRWxlbWVGRS9taW50LXVpJyB9LFxuICAgIHsgdmFsdWU6ICd2dWV4JywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWV4JyB9LFxuICAgIHsgdmFsdWU6ICd2dWUtcm91dGVyJywgbGluazogJ2h0dHBzOi8vZ2l0aHViLmNvbS92dWVqcy92dWUtcm91dGVyJyB9LFxuICAgIHsgdmFsdWU6ICdiYWJlbCcsIGxpbms6ICdodHRwczovL2dpdGh1Yi5jb20vYmFiZWwvYmFiZWwnIH0sXG4gIF1cbn1cblxubGV0IHRpbWVvdXQ6IE5vZGVKUy5UaW1lb3V0XG5jb25zdCBxdWVyeVNlYXJjaEFzeW5jID0gYXN5bmMgKHF1ZXJ5U3RyaW5nOiBzdHJpbmcsIGNiOiAoYXJnOiBhbnkpID0+IHZvaWQpID0+IHtcbiAgYXdhaXQgbmV4dFRpY2soKVxuICBjb25zdCByZXN1bHRzID0gcXVlcnlTdHJpbmdcbiAgICA/IGxpbmtzLnZhbHVlLmZpbHRlcihpdGVtID0+IGl0ZW0udmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwKVxuICAgIDogbGlua3MudmFsdWVcblxuICBjbGVhclRpbWVvdXQodGltZW91dClcbiAgdGltZW91dCA9IHNldFRpbWVvdXQoKCkgPT4ge1xuICAgIGNvbnNvbGUubG9nKHJlc3VsdHMpXG4gICAgY2IocmVzdWx0cylcbiAgfSwgMzAwMCAqIE1hdGgucmFuZG9tKCkpXG59XG5jb25zdCBjcmVhdGVGaWx0ZXIgPSAocXVlcnlTdHJpbmc6IHN0cmluZykgPT4ge1xuICByZXR1cm4gKHJlc3RhdXJhbnQ6IExpbmtJdGVtKSA9PiB7XG4gICAgcmV0dXJuIChcbiAgICAgIHJlc3RhdXJhbnQudmFsdWUudG9Mb3dlckNhc2UoKS5pbmRleE9mKHF1ZXJ5U3RyaW5nLnRvTG93ZXJDYXNlKCkpID09PSAwXG4gICAgKVxuICB9XG59XG5cbmNvbnN0IGhhbmRsZVNlbGVjdCA9IChpdGVtOiBMaW5rSXRlbSkgPT4ge1xuICBjb25zb2xlLmxvZyhpdGVtKVxuICBjb25zb2xlLmxvZyhzdGF0ZS52YWx1ZSlcbn1cblxub25Nb3VudGVkKCgpID0+IHtcbiAgbGlua3MudmFsdWUgPSBsb2FkQWxsKClcbn0pXG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcImltcG9ydHNcIjp7fX0ifQ==)

### Steps to reproduce

1. Open the link
2. F12 Open the console
3. click the input

### What is Expected?

No prompt error

### What is actually happening?

Uncaught (in promise) ElementPlusError: [ElAutocomplete] autocomplete suggestions must be an array

### Additional comments
If asynchronous methods are not supported, `remote search` cannot be carried out well

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.
fix #7278  #7311

### CODE REVIEW

**Comment by chenxch** [comment]
@sxzz Need your review, do you need to introduce `flush-promises` to replace 2 consecutive `nextTick` on the unit test side?

**Comment by sxzz** [comment]
Let's merge this PR first #7381

**Comment by CarterLi** [comment]
async函数在调用方看来不就是返回promise的函数么？为什么要特别对待？

**Comment by sxzz** [comment]
@CarterLi Yeah, so I think we can just add a `await` keyword.

**Review by sxzz — APPROVED** [review]

**Comment by chenxch** [comment]
> async函数在调用方看来不就是返回promise的函数么？为什么要特别对待？

你可以看一下反馈中的问题，会导致触发一次不必要的报错

**Pull request merged**
