### PR TITLE
fix(components): run pnpm test error

### PR DESCRIPTION
**Pull request by BigPengZai**
pnpm test error

### CODE REVIEW

**Comment by BigPengZai** [comment]
I think there are a lot of PR today, but ”pnpm test“   error

**Comment by BigPengZai** [comment]
Please check this question, or you won't be able to run the jest test. PR can't be submitted

**Comment by BigPengZai** [comment]
请check下这个问题，不然跑jest测试过不了。PR就提交不了
Please check this question, or you won't be able to run the jest test. PR can't be submitted

**Comment by sxzz** [comment]
请确保node >= 16就可以通过了

**Comment by BigPengZai** [comment]
> 请确保node >= 16就可以通过了

有 ```||=``` 这样的语法吗

**Comment by sxzz** [comment]
[Logical Assignment Operators](https://github.com/tc39/proposal-logical-assignment)

**Comment by sxzz** [comment]
Thanks your for contribution, but we currently support node >= 16 only for development.

**Pull request closed without merging**
