### PR TITLE
docs: handle `currentRelease` undefined

### PR DESCRIPTION
**Pull request by holazz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jw-foss** [comment]
@holazz maybe we should just rendering the error here when API limit reached we should just show the error.

**Comment by holazz** [comment]
> @holazz maybe we should just rendering the error here when API limit reached we should just show the error.

@jw-foss Yes, the API limit console error is still showing, and what I fixed is this error:

image

**Comment by jw-foss** [comment]
@holazz I meant that by rendering the error to the UI such as showing up a text to the users which explains the API limit has been reached they should try it later or watch if from the source.

**Comment by holazz** [comment]
> @holazz I meant that by rendering the error to the UI such as showing up a text to the users which explains the API limit has been reached they should try it later or watch if from the source.

Gotcha!

**Pull request closed without merging**
