### PR TITLE
refactor(components): el-dialog icon

### PR DESCRIPTION
**Pull request by adaex**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@adaex I think the font is quite bit small, could you tune it bigger?

**Comment by adaex** [comment]
> @adaex I think the font is quite bit small, could you tune it bigger?

Sure, I'll update it.

**Comment by adaex** [comment]
> @adaex I think the font is quite bit small, could you tune it bigger?

Sure, I'll update it.

**Comment by adaex** [comment]
@JeremyWuuuuu updated. Inherited the parent's size, now 16px

**Review by imswk — APPROVED** [review]

**Comment by imswk** [comment]
LGTM

**Pull request merged**
