### PR TITLE
docs(components): [date-picker] update example

### PR DESCRIPTION
**Pull request by MARIOMARUI**
Please make sure these boxes are checked before submitting your PR, thank you!

- [✔ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [✔ ] Make sure you are merging your commits to `dev` branch.
- [✔ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by MARIOMARUI** [comment]
正如如上所示所选择的是用的是十二小时制  所展示的使用的标准时间
image

**Review by btea — APPROVED** [review]

**Comment by btea** [comment]
@MARIOMARUI Hello, can you update the commit message?

**Comment by MARIOMARUI** [comment]
Sorry, can I submit it like this

**Comment by MARIOMARUI** [comment]
> @MARIOMARUI您好，您可以更新提交消息吗？

Sorry, can I submit it like this

**Comment by btea** [comment]
LGTM👍

**Pull request merged**
