### PR TITLE
add prop: collapse-counts in select 

### PR DESCRIPTION
**Pull request by yangzheng93**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by YangYmimi** [comment]
https://github.com/element-plus/element-plus/issues/2284

**Comment by YangYmimi** [comment]
image

**Comment by msidolphin** [comment]
Thank you for your PR. could you do rebase your commits?

**Comment by YangYmimi** [comment]
> Thank you for your PR. could you do rebase your commits?

done

**Pull request closed without merging**
