### PR TITLE
test(components): [el-config-provider] use useFakeTimers

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@btea can you rebase on the dev branch for running a coverage report?

**Comment by btea** [comment]
Done. But this unit test always fails...

**Comment by JeremyWuuuuu** [comment]
> Done. But this unit test always fails...

Understood, it seems like the actions we add treats the warning from the console as error, we might need to remove all the warnings in advance.

**Review by sxzz — APPROVED** [review]

**Comment by HerringtonDarkholme** [comment]
It is caused by tree.vue failure. It does not influence much.

**Comment by btea** [comment]
The reason for the failure seems to be that the fork's repository failed to publish the report and threw an error `Error: HttpError: Resource not accessible by integration`.

**Pull request merged**
