### PR TITLE
fix(components): [el-rate] fix extended judgement

### PR DESCRIPTION
**Pull request by luyh7**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by luyh7 — COMMENTED** [review]
review

**Comment by sxzz** [comment]
What does this pr fix?

**Comment by luyh7** [comment]
fix the problem that icons not display.the problem appear i think the function isExcludedObject not work
&nbsp;

卢宇浩
中山大学数据科学与计算机学院
School of Data and Computer Science, Sun&nbsp;Yat-Sen University
Tel: 18819253305
QQ: 470103427
E-mail: ***@***.***


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月19日(星期五) 凌晨2:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] fix(components): [el-rate] fix extended judgement (PR #4449)





 
What does this pr fix?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by luyh7** [comment]
fix the problem that icons not display, the problem appear because of the function isExcludedObject not work&nbsp;correctly

**Comment by sxzz** [comment]
We had fix this problem in #4452.

**Pull request closed without merging**
