### PR TITLE
fix(components): [scrollbar] multiple rendering

### LINKED ISSUE #15654: [Bug Report] Scrollbar 滚动条 里面元素调用方法时会执行2遍甚至多次
### Element Plus version
2.5.3

### OS/Browsers version
Google Chrome 120

### Vue version
3.4.15

### Reproduction Link
https://jsfiddle.net/tianhailiang/53kadnht/20/

### Steps to reproduce
https://jsfiddle.net/tianhailiang/53kadnht/20/

### What is Expected?
期待执行1次

### What is actually happening?
实际执行2次

### LINKED ISSUE #15801: [scrollbar] element-团队解决issue的能力缓慢啊，社区人员这么多给你免费测试参与提意见，issue过了好久都没人响应，请问对的起大家吗
Bug Type: **`Other`**

## Environment

- Vue Version: `3.4.15`
- Element Plus Version: `2.5.5`
- Browser / OS: `chrome 120`
- Build Tool: `Vite`

### Related Component

- `el-scrollbar`

### Reproduction Link

[JSFiddle](https://jsfiddle.net/tianhailiang/53kadnht/20/)

### Steps to reproduce

https://jsfiddle.net/tianhailiang/53kadnht/20/

### What is Expected?

期待执行1次

### What is actually happening?

实际执行2次

### Additional comments

element-团队解决issue的能力缓慢啊，社区人员这么多给你免费测试参与提意见，issue过了好久都没人响应，请问对的起大家吗

### PR DESCRIPTION
**Pull request by xingyixiang**
Please make sure these boxes are checked before submitting your PR, thank you!
fixes: #15654
fixes: #15801 
- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xingyixiang** [comment]
[Example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNjcm9sbGJhcj5cbiAgICA8ZGl2IDpjbGFzcz1cImlzQWN0aXZlKDkpID8gJ2FjdGl2ZScgOiAnJ1wiPua1i+ivlTwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJzY3JvbGxiYXItZmxleC1jb250ZW50XCI+XG4gICAgICA8cCB2LWZvcj1cIml0ZW0gaW4gNTBcIiA6a2V5PVwiaXRlbVwiIGNsYXNzPVwic2Nyb2xsYmFyLWRlbW8taXRlbVwiPlxuICAgICAgICB7eyBpdGVtIH19XG4gICAgICA8L3A+XG4gICAgPC9kaXY+XG4gIDwvZWwtc2Nyb2xsYmFyPlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmNvbnN0IGlzQWN0aXZlID0gKGluZGV4OiBudW1iZXIpID0+IHtcbiAgY29uc29sZS5sb2coJ29iai4uLicsIGluZGV4KVxuICByZXR1cm4gaW5kZXggPiAxMFxufVxuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbi5zY3JvbGxiYXItZmxleC1jb250ZW50IHtcbiAgZGlzcGxheTogZmxleDtcbn1cbi5zY3JvbGxiYXItZGVtby1pdGVtIHtcbiAgZmxleC1zaHJpbms6IDA7XG4gIGRpc3BsYXk6IGZsZXg7XG4gIGFsaWduLWl0ZW1zOiBjZW50ZXI7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xuICB3aWR0aDogMTAwcHg7XG4gIGhlaWdodDogNTBweDtcbiAgbWFyZ2luOiAxMHB4O1xuICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gIGJvcmRlci1yYWRpdXM6IDRweDtcbiAgYmFja2dyb3VuZDogdmFyKC0tZWwtY29sb3ItZGFuZ2VyLWxpZ2h0LTkpO1xuICBjb2xvcjogdmFyKC0tZWwtY29sb3ItZGFuZ2VyKTtcbn1cbjwvc3R5bGU+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1ODIyLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTU4MjItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE1ODIyLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1ODIyLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by xingyixiang** [comment]
cc @kooriookami @btea @FrontEndDog

**Comment by kooriookami** [comment]
Please fix the test.

**Comment by xingyixiang** [comment]
> Please fix the test.

Okay.

**Comment by xingyixiang** [comment]
@kooriookami done

**Review by kooriookami — APPROVED** [review]
Nice!

**Pull request merged**
