### PR TITLE
chore: set `package-manager-strict` to false

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

After pnpm releases version [9.0.3](https://github.com/pnpm/pnpm/releases/tag/v9.0.3), when the local pnpm version and packageManger version do not match, an error message will appear and the process will exit when running `pnpm dev`.

### CODE REVIEW

**Comment by kooriookami** [comment]
Will the lock file be changed in different version?

**Comment by btea** [comment]
Yes, the `lockfileVersion` corresponding to the lock file generated by pnpm 9 is `9.0`. We will update `packageManager` to version 9 later.
The problem now is that if the `packageManager` version is set to `9.0.3`, if you install `9.0.4` locally, an error will occur and the process will exit. I think this restriction is too strict.

**Comment by kooriookami** [comment]
What about `pnpm@9` without minor version.

**Comment by btea** [comment]
This looks good, but I'm not sure if this will throw an error, I might try it later.

**Comment by btea** [comment]
> What about `pnpm@9` without minor version.

That does not work.

image

**Comment by kooriookami** [comment]
OK, I see.

**Review by kooriookami — APPROVED** [review]

**Pull request merged**
