### PR TITLE
chore: fixed `@element-plus/build-constants` version

### PR DESCRIPTION
**Pull request by xxholly32**
#16793

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xxholly32** [comment]
My company has an Intranet npm register, so I did not upload pnpm-lock.yaml

**Comment by xxholly32** [comment]
My company has an Intranet npm register, so I did not upload pnpm-lock.yaml

**Comment by xxholly32** [comment]
My company has an Intranet npm register, so I did not upload pnpm-lock.yaml

**Comment by xxholly32** [comment]
My company has an Intranet npm register, so I did not upload pnpm-lock.yaml

**Comment by warmthsea** [comment]
> My company has an Intranet npm register, so I did not upload pnpm-lock.yaml

If pnpm-lock.yaml is not changed, the check will fail.
I encountered the same problem https://github.com/element-plus/element-plus/issues/16793.

**Comment by xxholly32** [comment]
updated lockfile @warmthsea

**Review by warmthsea — COMMENTED** [review]
LGTM.

**Review by btea — APPROVED** [review]

**Review by plainheart — APPROVED** [review]

**Pull request merged**
