### PR TITLE
fix(components): [page-header] icon slots not working

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## Description

We have confirmed that icon slots are not working properly.

image

## What is Expected?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnZS1oZWFkZXIgY29udGVudD1cImRldGFpbFwiPlxuICAgIDx0ZW1wbGF0ZSAjaWNvbj4gXG4gICAgXHQ8QWxhcm1DbG9jayAvPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcGFnZS1oZWFkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgQWxhcm1DbG9jayB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+IiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTgyMTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AbGF0ZXN0L2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEBsYXRlc3QvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy04MjExLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTgyMTEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctODIxMS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

### if Exists icon slot

```vue
<template>
  <el-page-header content="detail">
    // working
    <template #icon> 
    	<AlarmClock />
    </template>
  </el-page-header>
</template>

<script lang="ts" setup>
import { AlarmClock } from '@element-plus/icons-vue'
</script>
```

I have confirmed that it works normally in the following cases.

1. If there are only icon props
2. When icon props and slots exist at the same time
3. If both icon props and slots are missing
4. If there is only icon slot

## What is actually happening?

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnZS1oZWFkZXIgY29udGVudD1cImRldGFpbFwiPlxuICAgIDx0ZW1wbGF0ZSAjaWNvbj5cbiAgICBcdDxBbGFybUNsb2NrIC8+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1wYWdlLWhlYWRlcj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBBbGFybUNsb2NrIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

```vue
<template>
  <el-page-header content="detail">
    // not working
    <template #icon> 
    	<AlarmClock />
    </template>
  </el-page-header>
</template>

<script lang="ts" setup>
import { AlarmClock } from '@element-plus/icons-vue'
</script>
```

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by btea — APPROVED** [review]

**Comment by tolking** [comment]
You may need to wrap the `icon component` through the `<el-icon>XX</el-icon>` to use. 

[reference input slot](https://element-plus.org/en-US/component/input.html#input-with-icon)

[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtcGFnZS1oZWFkZXIgY29udGVudD1cImRldGFpbFwiPlxuICAgIDx0ZW1wbGF0ZSAjaWNvbj5cbiAgICAgIDxlbC1pY29uPlxuICAgICAgICA8QWxhcm1DbG9jayAvPlxuICAgICAgPC9lbC1pY29uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcGFnZS1oZWFkZXI+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgQWxhcm1DbG9jayB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Comment by ryuhangyeong** [comment]
@tolking Thanks for the review. As you said, I thought it would make more sense to keep the existing code. I will close the issue.

**Comment by ryuhangyeong** [comment]
@tolking By the way, you gave an example of <el-input />. <el-button> also displays icons well without <el-icon>. Each component seems to work differently. Can you comment on this?

**Comment by tolking** [comment]
The [Combined with el-icon](https://element-plus.org/en-US/component/icon.html#combined-with-el-icon) is different with [Using SVG icon directly](https://element-plus.org/en-US/component/icon.html#using-svg-icon-directly)

The icon component works with `@element-plus/icons-vue` icon library, but not necessarily with third-party icon libraries,  maybe we should avoid use it in slots.

**Comment by ryuhangyeong** [comment]
@tolking Thanks for your kind reply. As I have confirmed that I can achieve the desired behavior with `<el-icon />` in the current API, it seems appropriate to close this PR. Thank you for caring me.

**Comment by ryuhangyeong** [comment]
@btea After discussing the issue, we decided to close it. Thanks for the review!

**Comment by btea** [comment]
@ryuhangyeong ok, I see. Thank you for your contribution.

**Pull request closed without merging**
