### PR TITLE
fix(input-number): fix border color when disabled and hover over buttons

### PR DESCRIPTION
**Pull request by qige2016**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by iamkun** [comment]
Any screenshot or issue to detail this pr, please?

**Comment by qige2016** [comment]
@iamkun When it is disabled and hovering over buttons, screenshot:

**Comment by JeremyWuuuuu** [comment]
Hi @qige2016 which issue does this PR address? If there was none please ignore me. If there was any, please add
`closes #issue_number` in your description. Thank you!

**Comment by qige2016** [comment]
@JeremyWuuuuu No issue.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
Before fix:
image

After fix:
image

**Pull request merged**
