### PR TITLE
docs(docs): fix custom theme doc

### LINKED ISSUE #4148: [bug report] 1.2.0-bata cannot customize the theme
### Element Plus version
1.2.0-beta.1

### OS/Browsers version
macOS 11

### Vue version
3.2.14

### Reproduction Link
https://github.com/Otto-J/element-plus-bugs

### Steps to reproduce
1. 安装依赖
2. 观察 vite.config.js 和 main.ts
3. 运行 pnpm run dev

### What is Expected?
不报错

### What is actually happening?
一堆报错`Error: Module loop: this module is already being loaded.`

### PR DESCRIPTION
**Pull request by Otto-J**
fix #4148

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by YunYouJun** [comment]
I think we can add comments to it.

```scss
// If you just import on demand, you can ignore the following content.
// if you want to import all styles:
// @use "element-plus/theme-chalk/src/index.scss" as *;
```

**Comment by msidolphin** [comment]
@YunYouJun WDYT

If you are using vite, and you want to custom theme when importing on demand.

Use `scss.additionalData` to compile variables with scss of every compoent.

```ts
import path from 'path'
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'

import ElementPlus from 'unplugin-element-plus/vite'
// You can also use unplugin-vue-components
// import { ElementPlusResolver } from "unplugin-vue-components/resolvers"

// vite.config.ts
export default defineConfig({
  resolve: {
    alias: {
      '~/': `${path.resolve(__dirname, 'src')}/`,
    },
  },
  css: {
    preprocessorOptions: {
      scss: {
        additionalData: `@use "~/styles/element/index.scss" as *;`,
      },
    },
  },
  plugins: [
    vue(),
    ElementPlus({
      useSource: true,
    }),
    // ElementPlusResolver({
    //   importStyle: "sass",
    // }),
  ],
})
```

There is difference between global import and demand import, you don't need to import `element-plus/theme-chalk/src/index.scss`

```scss
// styles/element/index.scss
/* just override what you need */
@forward "element-plus/theme-chalk/src/common/var.scss" with (
  $colors: (
    "primary": (
      "base": green,
    ),
  ),
);
```

**Comment by Otto-J** [comment]
我同意在 quick start 明确一下 unplugin 两个插件的使用方法和相关选项，现在过于黑盒，需要看源码才能了解选项含义

**Comment by Otto-J** [comment]
照顾 1.0.x 和 1.1.x 和 1.2.x 的版本之间的不同写法，可能还要添加 label

**Review by YunYouJun — APPROVED** [review]

**Review by msidolphin — APPROVED** [review]

**Comment by YunYouJun** [comment]
Thanks.

**Pull request merged**
