### PR TITLE
Feat/picker

### PR DESCRIPTION
**Pull request by jianjunyuu**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

根据 #3198  描述，补充了相关的特性

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@mryujianjun @iamkun I don't think this is a good feature, because without the `:` symbol, how do you distinguish which part is minutes, which part is hours, when the digits were like: `113`, how to separate them? We cannot introduce branching here.

**Comment by mryujianjun** [comment]
> @mryujianjun I don't think this is a good feature, because without the `:` symbol, how do you distinguish which part is minutes, which part is hours, when the digits were like: `113`, how to separate them? We cannot introduce branching here. /cc @iamkun

First of all thank you for your feedback.
Based on the situation you proposed: enter "113", the program will replace it according to the format, and the default will be filled with 0.
For example: when the format is HH:mm:ss, the user inputs "113", then the program will first verify whether the user input is a valid time format and whether it is a pure numeric string, if so, it will be processed as 11:03: 00
This is my way of thinking.

**Comment by iamkun** [comment]
I do think it is a bit wired.

To me, maybe, 1212 is not a time string but 12:12 is.

**Comment by mryujianjun** [comment]
> I do think it is a bit wired.
> 
> 
> 
> To me, maybe, 1212 is not a time string but 12:12 is.
> 
> 
> 
> 
> 
> 
> 
> 

ok,I got it, thanks.

**Pull request closed without merging**
