### PR TITLE
fix(components): [radio] the id attribute acts on the input

### LINKED ISSUE #8449: [Component] [radio] el-radio  id无效问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.6`
- Browser / OS: `chrome`
- Build Tool: `Vue CLI`

### Related Component

- `el-radio`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCByYWRpbzEgPSByZWYoJzEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAgPGxhYmVsIGZvcj1cIjEyM1wiPmNsaWNrIG1lPC9sYWJlbD5cbiAgICA8ZWwtcmFkaW8tZ3JvdXAgdi1tb2RlbD1cInJhZGlvMVwiIGNsYXNzPVwibWwtNFwiPlxuICAgICAgPGVsLXJhZGlvIGlkPVwiMTIzXCIgbGFiZWw9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgICAgPGVsLXJhZGlvIGxhYmVsPVwiMlwiIHNpemU9XCJsYXJnZVwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgICA8L2VsLXJhZGlvLWdyb3VwPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

设置el-radio组件的id，当使用label for属性绑定id时，点击label   el-radio无反应。

### What is Expected?

el-radio有反应

### What is actually happening?

el-radio无反应

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #8449

### CODE REVIEW

**Comment by tolking** [comment]
Maybe you should refer to the Input component modification.

**Comment by chenxch** [comment]
> Maybe you should refer to the Input component modification.

Received, I will make adjustments.

**Comment by chenxch** [comment]
@tolking Due to the use of useFormItemInputId, the test case of a11y has been adjusted and needs your review again.

**Comment by tolking** [comment]
Sorry I did not prompt to be more details.

Maybe you do not need to add the id attribute, just assign the `attrs` attribute with reference to the Input component after used `inheritAttrs: false`.

**Comment by chenxch** [comment]
>

**Comment by chenxch** [comment]
@tolking Received, I resubmit a pr.

**Pull request closed without merging**
