### PR TITLE
refactor(components): [step] switch to script-setup syntax

### PR DESCRIPTION
**Pull request by ryuhangyeong**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu Pleaese Review! Thank you always.

**Review by jw-foss — APPROVED** [review]
LGTM, thanks!

**Comment by JeremyWuuuuu** [comment]
@ryuhangyeong One more thing, would you mind removing the entry in `internal/build/src/type-unsafe.json` file?

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu OK~! `internal/build/src/type-unsafe.json` Can I delete that file?

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu OK~! `internal/build/src/type-unsafe.json` Can I delete that file? Or delete a specific line?

The specific line it is.

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu I have reflected your review.

**Pull request merged**
