### PR TITLE
fix(components): [el-popper] visible default value to false

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
It seems that unit test failed. Could you please fix it?

**Comment by btea** [comment]
@sxzz ok, I will fix it.

**Comment by btea** [comment]
@sxzz I tried to fix it, and I found the reason of cause the unit test failure seems here, the emit seems invalid.
https://github.com/element-plus/element-plus/blob/d71c87344a36f1837027683fd847a85aa5e4ba17/packages/components/popper/src/use-popper/index.ts#L83-L85  
As so far, I can't resolve it, Could you give me some help? Thank you!

**Comment by btea** [comment]
@sxzz I changed the visibility's `get` and `set` and I'm not sure if it will cause other problems.  Please check it! Thanks!

**Comment by sxzz** [comment]
OK. I will this later.

**Comment by JeremyWuuuuu** [comment]
Well, actually it was set to default `undefined` for reasons, for users that didn't want to use `v-model` binding we use that as an indicator for determining whether this is the case. May I ask based on what purpose we need to change this?

**Comment by btea** [comment]
> Well, actually it was set to default `undefined` for reasons, for users that didn't want to use `v-model` binding we use that as an indicator for determining whether this is the case. May I ask based on what purpose we need to change this?

I want to change it because here has a ts error
image

**Comment by JeremyWuuuuu** [comment]
> > Well, actually it was set to default `undefined` for reasons, for users that didn't want to use `v-model` binding we use that as an indicator for determining whether this is the case. May I ask based on what purpose we need to change this?
> 
> I want to change it because here has a ts error, and I don't think the default value of boolean type should be undefined.
> image

But we need to figure out a way to indicate the value was not passed into `popper`, actually I think I had found a way before you can checkout `hooks/use-popper` for more detail, my question is that, changing the code this way **might** break some functionalities, we need to be careful on this one though(not saying that we wouldn't want your PR, I think it is legit).

**Comment by btea** [comment]
@JeremyWuuuuu Yes, I agree with you. At first, I thought it was simple, just changing a default value. But,  When I commit  the change, the unit test failed. To past the test, I changed the visibility and I'm not sure the change will affect other functions.~~

**Pull request closed without merging**
