### PR TITLE
chore(components): change the wait in the el-carousel tests to sleep

### PR DESCRIPTION
**Pull request by emojiiii**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by undefined-degisn** [comment]
看单测的错误，似乎与我此次提交无关，本地跑单测也通过了，很奇怪

**Comment by msidolphin** [comment]
Consider using `jest.runAllTimers()` instead of sleep

**Comment by undefined-degisn** [comment]
`carousel`组件因为存在一个`interval`的参数，并不是渲染的问题，所以使用`jest.runAllTimers()`似乎不太合适

**Comment by JeremyWuuuuu** [comment]
> `carousel`组件因为存在一个`interval`的参数，并不是渲染的问题，所以使用`jest.runAllTimers()`似乎不太合适

The `sleep` API is not recommended to use because we cannot know the what was going on inside the component itself, normally I would suggest using `jest.fakeTimer` API for testing components like this, with `fakeTimer` rich APIs we developers can test components exactly the way it should be functioning. 

The interval is considered as constant when doing unit testing, via `fakeTimer` it enables us to test the functions without waiting for the timer to resolve, because we need to be assuming that the timer API provided by the browser (which our apps run in) is 100% correct. Timer is just nothing but a constant. 

Since the component should behave as we designed it to, there will be no trouble testing.

**Pull request closed without merging**
