### PR TITLE
feat(components): [dropdown] add buttonProps (#6183)

### LINKED ISSUE #6183: [Feature Request] el-dropdown split-button 的时候希望提供buttonProps 可以给到button 比如 plain
### Existing Component
Yes

### Component Name
el-dropdown

### Description
提供buttonProps

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

closes #6183

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@gjfei Would you like to elaborate why do we need this?

**Comment by gjfei** [comment]
> @gjfei Would you like to elaborate why do we need this?

就是想要这个参数去设置button 的plain

**Comment by gjfei** [comment]
> > @gjfei Would you like to elaborate why do we need this?
> 
> 就是想要这个参数去设置button 的plain

如果我一排button 都是plain 这个el-dropdown没办法统一

**Comment by gjfei** [comment]
> @gjfei Would you like to elaborate why do we need this?

没办法合并进去吗？

**Comment by gjfei** [comment]
@JeremyWuuuuu 没办法合并进去吗？

**Comment by gjfei** [comment]
@JeremyWuuuuu 你有更好的解决方法吗？

**Comment by gjfei** [comment]
> # [Codecov](https://codecov.io/gh/element-plus/element-plus/pull/6185?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus) Report
> > Merging [#6185](https://codecov.io/gh/element-plus/element-plus/pull/6185?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus) ([1dfd8f8](https://github.com/element-plus/element-plus/commit/1dfd8f861de2b8f33d65c23b03b49d03ac7f6afc)) into [dev](https://codecov.io/gh/element-plus/element-plus/commit/6b7bc4fd9437b79f87adb2c972c6c5cf1bada883?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus) ([6b7bc4f](https://github.com/element-plus/element-plus/commit/6b7bc4fd9437b79f87adb2c972c6c5cf1bada883)) will **increase** coverage by `84.37%`.
> > The diff coverage is `n/a`.
> 
> > ❗ Current head [1dfd8f8](https://github.com/element-plus/element-plus/commit/1dfd8f861de2b8f33d65c23b03b49d03ac7f6afc) differs from pull request most recent head 20212d5. Consider uploading reports for the commit 20212d5 to get more accurate results
> 
> [Impacted file tree graph](https://codecov.io/gh/element-plus/element-plus/pull/6185?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus)
> 
> ```diff
> @@           Coverage Diff            @@
> ##           dev    #6185       +/-   ##
> ========================================
> + Coverage     0   84.37%   +84.37%     
> ========================================
>   Files        0      485      +485     
>   Lines        0    17599    +17599     
>   Branches     0     4370     +4370     
> ========================================
> + Hits         0    14850    +14850     
> - Misses       0     2725     +2725     
> - Partials     0       24       +24     
> ```
> 
> [Impacted Files](https://codecov.io/gh/element-plus/element-plus/pull/6185?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus)	Coverage Δ	
> [packages/components/dropdown/src/dropdown.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9kcm9wZG93bi9zcmMvZHJvcGRvd24udHM=)	`100.00% <ø> (ø)`	
> [packages/components/dropdown/src/dropdown.vue](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9kcm9wZG93bi9zcmMvZHJvcGRvd24udnVl)	`90.74% <ø> (ø)`	
> [.../components/table/src/table-header/utils-helper.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy90YWJsZS9zcmMvdGFibGUtaGVhZGVyL3V0aWxzLWhlbHBlci50cw==)	`96.07% <0.00%> (ø)`	
> [packages/components/badge/index.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9iYWRnZS9pbmRleC50cw==)	`100.00% <0.00%> (ø)`	
> [packages/components/popper/src/deprecation.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9wb3BwZXIvc3JjL2RlcHJlY2F0aW9uLnRz)	`100.00% <0.00%> (ø)`	
> [packages/components/drawer/index.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9kcmF3ZXIvaW5kZXgudHM=)	`100.00% <0.00%> (ø)`	
> [packages/components/affix/index.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9hZmZpeC9pbmRleC50cw==)	`100.00% <0.00%> (ø)`	
> [packages/components/menu/src/menu-item-group.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy9tZW51L3NyYy9tZW51LWl0ZW0tZ3JvdXAudHM=)	`100.00% <0.00%> (ø)`	
> [...components/virtual-list/src/builders/build-grid.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy92aXJ0dWFsLWxpc3Qvc3JjL2J1aWxkZXJzL2J1aWxkLWdyaWQudHM=)	`82.88% <0.00%> (ø)`	
> [packages/components/tabs/src/tab-nav.ts](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus#diff-cGFja2FnZXMvY29tcG9uZW50cy90YWJzL3NyYy90YWItbmF2LnRz)	`58.55% <0.00%> (ø)`	
> ... and [477 more](https://codecov.io/gh/element-plus/element-plus/pull/6185/diff?src=pr&el=tree-more&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=element-plus)

@JeremyWuuuuu 我还需要做什么？

**Comment by gjfei** [comment]
@JeremyWuuuuu 你有什么更好的建议？？？？？？

**Comment by gjfei** [comment]
> @JeremyWuuuuu 你有什么更好的建议？？？？？？

@sxzz 你有什么更好的建议吗？

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
@JeremyWuuuuu WDYT? Also, why Semantic Pull Request failed?

**Comment by sxzz** [comment]
Could you please add documentation for it?

**Pull request merged**
