### PR TITLE
feat(dev): add global component types for volar

### LINKED ISSUE #3530: [feature request] wants to provide a global component type declaration file to cooperate with volar on vs code to achieve a better development experience
### Existing Component
否

### Component Name
-

### Description
[Volar](https://github.com/johnsoncodehk/volar#using) 能够通过 GlobalComponents 为全局注册的组件提供代码提示、类型提示、跳转等功能。提供一个全局组件类型声明文件，并在适合的文档中提示在tsconfig文件中引入文件即可。

根据现在的构建流程，我认为可以在 packages/element-plus/ 下增加一个文件来管理这些内容。

### PR DESCRIPTION
**Pull request by sxzz**
close #3530

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@sxzz The file is now empty, is that valid for the users to add?

**Comment by sxzz** [comment]
It just renamed, not empty. 
https://github.com/element-plus/element-plus/blob/feat/volar/packages/element-plus/global.d.ts

**Comment by JeremyWuuuuu** [comment]
@sxzz Got it, do we need to add some guideline into the README.md or HOW_TO_CONTRIBUTE for this part when new component came in we should update this file as well? Can you do that>

**Comment by sxzz** [comment]
@JeremyWuuuuu I added a tip to `README.md`, and I will refactor dev docs in another PR.

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
