### PR TITLE
fix(theme-chalk): fixe radio-button background style

### LINKED ISSUE #11985: [Style] [radio-button] radio-button background variable error
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-radio-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uICxvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyB2ZXJzaW9uIGFzIEVwVmVyc2lvbiB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IEVsZW1lbnRQbHVzIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbmNvbnN0IGRhdGUgPSByZWYoKVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBjb25zdCBlbCA9IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudFxuXG4gIGVsLnN0eWxlLnNldFByb3BlcnR5KCctLWVsLWJ1dHRvbi1iZy1jb2xvcicsICdyZWQnKVxufSlcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG4gIDxlbC1yYWRpby1ncm91cFxuICAgICAgdi1tb2RlbD1cImRhdGVcIlxuICAgICAgc2l6ZT1cInNtYWxsXCJcbiAgICAgIHN0eWxlPVwibWFyZ2luLXJpZ2h0OiAxNXB4XCJcbiAgICAgIGZpbGw9XCJyZWRcIlxuICAgICAgdGV4dC1jb2xvcj1cImJsdWVcIlxuICAgID5cbiAgICAgIDxlbC1yYWRpby1idXR0b24gOmxhYmVsPVwiMzBcIj4zMDwvZWwtcmFkaW8tYnV0dG9uPlxuICAgICAgPGVsLXJhZGlvLWJ1dHRvbiA6bGFiZWw9XCIxNVwiPjE1PC9lbC1yYWRpby1idXR0b24+XG4gICAgICA8ZWwtcmFkaW8tYnV0dG9uIDpsYWJlbD1cIjdcIj43PC9lbC1yYWRpby1idXR0b24+XG4gICAgPC9lbC1yYWRpby1ncm91cD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

Set the css var dynamically

### What is Expected?

You shouldn't change the background color

### What is actually happening?

Changed the background color

### Additional comments

dark 模式下是正常的

### PR DESCRIPTION
**Pull request by qsyjlab**
closed #11985

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by chenxch — COMMENTED** [review]
font-weight and color， Maybe deal with it accordingly

**Comment by YunYouJun** [comment]
I think we should set `el-button-bg-color` default value `fill-color-blank` for `radio-button`. Just like default value in button.

**Comment by chenxch** [comment]
https://github.com/element-plus/element-plus/blob/a9ef3f0502d032e201cab16c793fa8823a9c87be/packages/theme-chalk/src/button.scss#L19-L21

Is it possible to elevate this part to root？

**Comment by YunYouJun** [comment]
> https://github.com/element-plus/element-plus/blob/a9ef3f0502d032e201cab16c793fa8823a9c87be/packages/theme-chalk/src/button.scss#L19-L21
> 
> Is it possible to elevate this part to root？

We have previously placed it under root, but based on feedback this may cause debugging panel performance.

**Comment by YunYouJun** [comment]
@qsyjlab Can use set `el-button-bg-color` default value (`fill-color-blank`) in `@include e(inner) {`.

**Comment by qsyjlab** [comment]
> @qsyjlab Can use set `button-bg-color` default value (`fill-color-blank`) in `@include e(inner) {`?

If root sets button-bg-color, it will be affected by the root variable

**Pull request closed without merging**
