### PR TITLE
fix(components): about ElMessageBox  #11753

### PR DESCRIPTION
**Pull request by Zourunfa**
Please make sure these boxes are checked before submitting your PR, thank you!

- [done] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [done] Make sure you are merging your commits to `dev` branch.
- [done] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
Why make such a change? Want to support custom html error messages in Prompt?

**Comment by Zourunfa** [comment]
> 

yes 

> Why make such a change? Want to support custom html error messages in Prompt?

You can customize the wrong font style on the one hand, and on the other hand, I use the validator function to verify that the character of the current return is a successful style when it is correct. I want to define that there is often such a requirement in the project that when the exchange code is correct, I can display the number of currently convertible characters. We really need this change

**Comment by chenxch** [comment]
In fact, it can also be achieved through the Use VNode mode.

**Comment by Zourunfa** [comment]
> 



> 



> In fact, it can also be achieved through the Use VNode mode.

Can you ask me how to operate it？   use creatVNode

**Comment by Zourunfa** [comment]
> In fact, it can also be achieved through the Use VNode mode.
use createVNode function? Can I ask you how to operate it?

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW5cIj5Db21tb24gVk5vZGU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPkR5bmFtaWMgcHJvcHM8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3gsIEVsSW5wdXQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYWdlJyxcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnZWxpbnB1dCcsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICB9KVxufVxuXG5jb25zdCBvcGVuMSA9ICgpID0+IHtcbiAgY29uc3QgaW5wdXQgPSByZWY8c3RyaW5nPignJylcbiAgY29uc3QgZXJyb3IgPSByZWY8c3RyaW5nPignJylcbiAgRWxNZXNzYWdlQm94KHtcbiAgICB0aXRsZTogJ01lc3NhZ2UnLFxuICAgIC8vIFNob3VsZCBwYXNzIGEgZnVuY3Rpb24gaWYgVk5vZGUgY29udGFpbnMgZHluYW1pYyBwcm9wc1xuICAgIG1lc3NhZ2U6ICgpID0+XG4gICAgIGgoJ2RpdicsbnVsbCxcbiAgICAgIFtoKEVsSW5wdXQsIHtcbiAgICAgICAgbW9kZWxWYWx1ZTogaW5wdXQudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogYm9vbGVhbiB8IHN0cmluZyB8IG51bWJlcikgPT4ge1xuICAgICAgICAgIGlucHV0LnZhbHVlID0gdmFsXG4gICAgICAgICAgaWYodmFsLmxlbmd0aD4zKXtcbiAgICAgICAgICAgICBlcnJvci52bGF1ZSA9ICdsZW5ndGggeHgnXG4gICAgICAgICAgICAgfSBlbHNle1xuICAgICAgICAgICAgICAgZXJyb3IudmxhdWUgPSAnJ1xuICAgICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgIH0pLFxuICAgICAgaCgnc3Bhbicse3N0eWxlOntjb2xvcjoncmVkJ30sY2xhc3M6XCJteS1jbGFzc1wifSxlcnJvci52bGF1ZSldKSxcbiAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by Zourunfa** [comment]
> 

Amazing， I'm surprised to learn ，i want to say : niu bi

**Comment by Zourunfa** [comment]
> [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW5cIj5Db21tb24gVk5vZGU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPkR5bmFtaWMgcHJvcHM8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3gsIEVsSW5wdXQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYWdlJyxcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnZWxpbnB1dCcsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICB9KVxufVxuXG5jb25zdCBvcGVuMSA9ICgpID0+IHtcbiAgY29uc3QgaW5wdXQgPSByZWY8c3RyaW5nPignJylcbiAgY29uc3QgZXJyb3IgPSByZWY8c3RyaW5nPignJylcbiAgRWxNZXNzYWdlQm94KHtcbiAgICB0aXRsZTogJ01lc3NhZ2UnLFxuICAgIC8vIFNob3VsZCBwYXNzIGEgZnVuY3Rpb24gaWYgVk5vZGUgY29udGFpbnMgZHluYW1pYyBwcm9wc1xuICAgIG1lc3NhZ2U6ICgpID0+XG4gICAgIGgoJ2RpdicsbnVsbCxcbiAgICAgIFtoKEVsSW5wdXQsIHtcbiAgICAgICAgbW9kZWxWYWx1ZTogaW5wdXQudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogYm9vbGVhbiB8IHN0cmluZyB8IG51bWJlcikgPT4ge1xuICAgICAgICAgIGlucHV0LnZhbHVlID0gdmFsXG4gICAgICAgICAgaWYodmFsLmxlbmd0aD4zKXtcbiAgICAgICAgICAgICBlcnJvci52bGF1ZSA9ICdsZW5ndGggeHgnXG4gICAgICAgICAgICAgfSBlbHNle1xuICAgICAgICAgICAgICAgZXJyb3IudmxhdWUgPSAnJ1xuICAgICAgICAgICAgIH1cbiAgICAgICAgfSxcbiAgICAgIH0pLFxuICAgICAgaCgnc3Bhbicse3N0eWxlOntjb2xvcjoncmVkJ30sY2xhc3M6XCJteS1jbGFzc1wifSxlcnJvci52bGF1ZSldKSxcbiAgfSlcbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

But I still feel that it is not convenient for users. It is hard for a novice like me to think of doing so

**Comment by chenxch** [comment]
From the perspective of component design, it is a simple implementation to meet conventional requirements. For this kind of more customized requirements, we also provide the use vnode scenario. The responsible scenario will inevitably take a little time.

**Comment by Zourunfa** [comment]
> From the perspective of component design, it is a simple implementation to meet conventional requirements. For this kind of more customized requirements, we also provide the use vnode scenario. The responsible scenario will inevitably take a little time.
I understand that it is reasonable. Now I want to return the blue font when the verification is successful, and the red font when the verification fails. Can you ask me how to use vnode? This is a small requirement of our project. I am not familiar with the use of vnode.

嗯嗯
理解了 有道理，对于vnode的使用我现在还不太熟练，我现在想在校验成功的时候 返回蓝色的字体，校验失败的时候返回红色字体 ，可以请教一下用vnode怎么实现吗，这是我们项目的一个小小需求，我想快速搞完后睡觉。https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuaW1wb3J0IHtFbE1lc3NhZ2VCb3h9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmNvbnN0IG1zZyA9IHJlZignSGVsbG8gV29ybGQhJylcbiBFbE1lc3NhZ2VCb3gucHJvbXB0KGDmt7vliqDlrZfnrKbkuLLov5Tlm55odG1s57uT5p6E5pSv5oyBYCwgJ1JlZGVlbScsIHtcbiAgICBjb25maXJtQnV0dG9uVGV4dDogJ09rJyxcbiAgICBjYW5jZWxCdXR0b25UZXh0OiAnQ2FuY2VsJyxcblxuICAgIGlucHV0VmFsaWRhdG9yKHZhbHVlKSB7XG4gICAgICBpZiAodmFsdWU+NSkge1xuICAgICAgICByZXR1cm4gYDxzdHJvbmcgc3R5bGU9XCJjb2xvcjpibHVlO1wiPuagoemqjOaIkOWKn+S6hjwvc3Ryb25nPmBcbiAgICAgIH0gZWxzZSB7XG4gICAgICAgIHJldHVybiBgPHN0cm9uZyBzdHlsZT1cImNvbG9yOiByZWQ7XCI+IOagoemqjOWksei0pSc8L3N0cm9uZz5gXG4gICAgICB9XG4gICAgfSxcbiAgfSlcbiAgICAudGhlbihhc3luYyAoaW5mbykgPT4ge30pXG4gICAgLmNhdGNoKChlcnIpID0+IHt9KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cblx0PGRpdj5cbiAgICBcbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319

**Comment by chenxch** [comment]
[demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW5cIj5Db21tb24gVk5vZGU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPkR5bmFtaWMgcHJvcHM8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3gsIEVsSW5wdXQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYWdlJyxcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnZWxpbnB1dCcsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICB9KVxufVxuXG5jb25zdCBvcGVuMSA9ICgpID0+IHtcbiAgY29uc3QgaW5wdXQgPSByZWY8c3RyaW5nPignJylcbiAgY29uc3Qgc3VjY2VzcyA9IHJlZjxib29sZWFuPihmYWxzZSlcbiAgRWxNZXNzYWdlQm94KHtcbiAgICB0aXRsZTogJ01lc3NhZ2UnLFxuICAgIC8vIFNob3VsZCBwYXNzIGEgZnVuY3Rpb24gaWYgVk5vZGUgY29udGFpbnMgZHluYW1pYyBwcm9wc1xuICAgIG1lc3NhZ2U6ICgpID0+XG4gICAgIGgoJ2RpdicsbnVsbCxcbiAgICAgIFtoKEVsSW5wdXQsIHtcbiAgICAgICAgbW9kZWxWYWx1ZTogaW5wdXQudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogYm9vbGVhbiB8IHN0cmluZyB8IG51bWJlcikgPT4ge1xuICAgICAgICAgIGlucHV0LnZhbHVlID0gdmFsXG4gICAgICAgICAgc3VjY2Vzcy52YWx1ZSA9IHZhbC5sZW5ndGg+NVxuICAgICAgICAgICBcbiAgICAgICAgfSxcbiAgICAgIH0pLFxuICAgICAgaCgnc3Ryb25nJyx7c3R5bGU6e2NvbG9yOnN1Y2Nlc3MudmFsdWU/J2JsdWUnOidyZWQnfSxjbGFzczpcIm15LWNsYXNzXCJ9LGlucHV0LnZhbHVlID8gKHN1Y2Nlc3MudmFsdWU/J+agoemqjOaIkOWKnyc6J+agoemqjOWksei0pScpIDogJycpXSksXG4gIH0pXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

good night.

**Comment by Zourunfa** [comment]
> [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHBsYWluIEBjbGljaz1cIm9wZW5cIj5Db21tb24gVk5vZGU8L2VsLWJ1dHRvbj5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJvcGVuMVwiPkR5bmFtaWMgcHJvcHM8L2VsLWJ1dHRvbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyBoLCByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2VCb3gsIEVsSW5wdXQgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IG9wZW4gPSAoKSA9PiB7XG4gIEVsTWVzc2FnZUJveCh7XG4gICAgdGl0bGU6ICdNZXNzYWdlJyxcbiAgICBtZXNzYWdlOiBoKCdwJywgbnVsbCwgW1xuICAgICAgaCgnZWxpbnB1dCcsIG51bGwsICdNZXNzYWdlIGNhbiBiZSAnKSxcbiAgICAgIGgoJ2knLCB7IHN0eWxlOiAnY29sb3I6IHRlYWwnIH0sICdWTm9kZScpLFxuICAgIF0pLFxuICB9KVxufVxuXG5jb25zdCBvcGVuMSA9ICgpID0+IHtcbiAgY29uc3QgaW5wdXQgPSByZWY8c3RyaW5nPignJylcbiAgY29uc3Qgc3VjY2VzcyA9IHJlZjxib29sZWFuPihmYWxzZSlcbiAgRWxNZXNzYWdlQm94KHtcbiAgICB0aXRsZTogJ01lc3NhZ2UnLFxuICAgIC8vIFNob3VsZCBwYXNzIGEgZnVuY3Rpb24gaWYgVk5vZGUgY29udGFpbnMgZHluYW1pYyBwcm9wc1xuICAgIG1lc3NhZ2U6ICgpID0+XG4gICAgIGgoJ2RpdicsbnVsbCxcbiAgICAgIFtoKEVsSW5wdXQsIHtcbiAgICAgICAgbW9kZWxWYWx1ZTogaW5wdXQudmFsdWUsXG4gICAgICAgICdvblVwZGF0ZTptb2RlbFZhbHVlJzogKHZhbDogYm9vbGVhbiB8IHN0cmluZyB8IG51bWJlcikgPT4ge1xuICAgICAgICAgIGlucHV0LnZhbHVlID0gdmFsXG4gICAgICAgICAgc3VjY2Vzcy52YWx1ZSA9IHZhbC5sZW5ndGg+NVxuICAgICAgICAgICBcbiAgICAgICAgfSxcbiAgICAgIH0pLFxuICAgICAgaCgnc3Ryb25nJyx7c3R5bGU6e2NvbG9yOnN1Y2Nlc3MudmFsdWU/J2JsdWUnOidyZWQnfSxjbGFzczpcIm15LWNsYXNzXCJ9LGlucHV0LnZhbHVlID8gKHN1Y2Nlc3MudmFsdWU/J+agoemqjOaIkOWKnyc6J+agoemqjOWksei0pScpIDogJycpXSksXG4gIH0pXG59XG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> good night.

Thank you for letting me feel the charm of open source

**Comment by jw-foss** [comment]
You can use it with `jsx` to reduce the complexity of using `h()`. Closing

**Pull request closed without merging**
