### PR TITLE
fix(components): [el-tree]  Accordion mode does not collapse other nodes with setCurrentKey

### LINKED ISSUE #13818: [Component] [tree] Tree 树组件 手风琴模式用 setCurrentKey 不会折叠其他节点
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `Arch Linux / Chrome`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICByZWY9XCJ0cmVlUmVmXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gICAgYWNjb3JkaW9uXG4gICAgbm9kZS1rZXk9XCJrZXlcIlxuICAgIEBub2RlLWNsaWNrPVwiaGFuZGxlTm9kZUNsaWNrXCJcbiAgICA6aGlnaGxpZ2h0LWN1cnJlbnQ9XCJ0cnVlXCJcbiAgLz5cbiAgICA8ZWwtcm93IGNsYXNzPVwibWItNFwiPlxuICAgIDxlbC1idXR0b24gdi1mb3I9XCJpbmRleCBpbiAxMFwiIEBjbGljaz1cIigpPT57YnV0dG9uKGluZGV4KX1cIj7ngrnlh7t7e2luZGV4fX08L2VsLWJ1dHRvbj5cbiAgPC9lbC1yb3c+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtyZWZ9IGZyb20gXCJ2dWVcIlxuY29uc3QgdHJlZVJlZiA9IHJlZih2b2lkIDApXG5cbmludGVyZmFjZSBUcmVlIHtcbiAgbGFiZWw6IHN0cmluZyxcbiAga2V5Om51bWJlcixcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cbmNvbnN0IGJ1dHRvbiA9IChpbmRleDogbnVtYmVyKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLnNldEN1cnJlbnRLZXkoaW5kZXgsIHRydWUpXG59XG5cbmNvbnN0IGhhbmRsZU5vZGVDbGljayA9IChkYXRhOiBUcmVlKSA9PiB7XG4gIGNvbnNvbGUubG9nKGRhdGEpXG59XG5cbmNvbnN0IGRhdGE6IFRyZWVbXSA9IFtcbiAge1xuICAgIGxhYmVsOiAnMScsXG4gICAga2V5OjExLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnMS0xJyxcbiAgICAgICAga2V5OjFcbiAgICAgIH0sXG4gICAgICAgICAgICB7XG4gICAgICAgIGxhYmVsOiAnMS0yJyxcbiAgICAgICAga2V5OjJcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnMicsXG4gICAga2V5OjIyLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnMi0xJyxcbiAgICAgICAga2V5OjNcbiAgICAgIH0sXG4gICAgICAgICAgICB7XG4gICAgICAgIGxhYmVsOiAnMi0yJyxcbiAgICAgICAga2V5OjRcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnMycsXG4gICAga2V5OjMzLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnMy0xJyxcbiAgICAgICAga2V5OjVcbiAgICAgIH0sXG4gICAgICAgICAgICB7XG4gICAgICAgIGxhYmVsOiAnMy0yJyxcbiAgICAgICAga2V5OjZcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIGxhYmVsOiAnNCcsXG4gICAga2V5OjQ0LFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnNC0xJyxcbiAgICAgICAga2V5OjdcbiAgICAgIH0sXG4gICAgICB7XG4gICAgICAgIGxhYmVsOiAnNC0yJyxcbiAgICAgICAga2V5OjhcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbiAgICB7XG4gICAgbGFiZWw6ICc1JyxcbiAgICBrZXk6NTUsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICc1LTEnLFxuICAgICAgICBrZXk6OVxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICc1LTInLFxuICAgICAgICBrZXk6MTBcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcblxuICBcbl1cbmNvbnN0IGRlZmF1bHRQcm9wcyA9IHtcbiAgY2hpbGRyZW46ICdjaGlsZHJlbicsXG4gIGxhYmVsOiAnbGFiZWwnLFxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

点击按钮调用 setCurrentKey 函数

### What is Expected?

在 手风琴模式 下,使用 `setCurrentKey` 来设置选中的节点,可以正确的折叠其他节点,以保证(对于同一级的节点，每次只能展开一个)

### What is actually happening?

第二个参数为true,可以正确展开父节点,但不会折叠其他节点

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by sv-98-maxin**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

## Description

copilot: Fixed Tree component Accordion mode does not collapse other nodes with setCurrentKey

## Related Issue

Fixes #13818  .

## Explanation of Changes

copilot: fix bug

### CODE REVIEW

**Comment by btea** [comment]
@sv-98-maxin Hello, thank you for your contribution ! Cound you translate the commit message into English?

**Comment by sv-98-maxin** [comment]
> @sv-98-maxin Hello, thank you for your contribution ! Cound you translate the commit message into English?

of course

**Review by btea — APPROVED** [review]
Thanks !

**Comment by youkiu714** [comment]
您好，请问这个已经修复了吗？是哪个版本的呀？我现在调用 setCurrentKey 之后依旧不能收缩其他的目录

**Comment by youkiu714** [comment]
Hello, this problem still persists，and the version I am using is as follows;
Element Plus: 2.6.3
vue:  3.4.21

**Comment by btea** [comment]
Sorry, it seems that there has been no response for too long and the creator has closed this PR. I will create a new PR to solve this problem.

**Pull request closed without merging**
