### PR TITLE
fix(components): [select-v2] multiple and only one list user selected…

### PR DESCRIPTION
**Pull request by weiguanglai**
… auto hide dropdown list

Optimization: When multiple options are selected, automatically hide the dropdown list after the user selects when there is only one data entry

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 245e025</samp>

Fix select-v2 dropdown closing logic when filtering options. Add a check in `useSelect.ts` to close the dropdown when only one option remains.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 245e025</samp>

* Close the select dropdown when there is only one filtered option left to improve user experience ([link](https://github.com/element-plus/element-plus/pull/14605/files?diff=unified&w=0#diff-6018da2b9e35c71aca0d0a0f881a93c00ab1f1958a3a9c69e332fa8d0b2e9865R424-R426))

### CODE REVIEW

**Comment by tolking** [comment]
Thank for your contribution, But I think this may not be a good idea.

This will make it more difficult for users to cancel the selection after selecting an option.

**Comment by weiguanglai** [comment]
> Thank for your contribution, But I think this may not be a good idea.
> 
> This will make it more difficult for users to cancel the selection after selecting an option.

我们在做业务的过程中会遇到这样一个小问题，列表很长 用户直接复制一个完整的名称来搜索 ，这时候只能匹配一个，用户选中之后 需要点一下旁边的空白处 下拉框才会消失 这个小更改就是让那个下拉框自动消失 而不需要用户在点一下旁边的空白处。使用起来更加的连贯流畅 不会影响其他功能 就是一个体验优化

**Comment by btea** [comment]
cc @element-plus/backers

**Comment by kooriookami** [comment]
When clicked the select option, the filter value needs to be cleared. That's the correct behavior.

https://github.com/element-plus/element-plus/assets/38392315/796a9536-b956-466d-9d81-843148956514

**Comment by FrontEndDog** [comment]
> > Thank for your contribution, But I think this may not be a good idea.
> > This will make it more difficult for users to cancel the selection after selecting an option.
> 
> 我们在做业务的过程中会遇到这样一个小问题，列表很长 用户直接复制一个完整的名称来搜索 ，这时候精确匹配只有一条数据，用户选中之后 需要点一下旁边的空白处 下拉框才会消失 用户觉得单选框那种体验比较好 选中一条之后下拉框自动消失 这个更改就是让那个下拉框只有一条数据的时候自动消失 而不需要用户在点一下旁边的空白处。使用起来更加的连贯流畅 应该不会影响其他功能 就是一个用户体验优化 复制以下地址 分别在浏览器打开 查看效果 [https://p1-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/a75cd62e9c4c4dc89b34a6e4c5879849~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=720&h=396&s=135785&e=gif&f=54&b=fefefe](url)
> 
> [https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/96577d2ad8ac4230952f88d0dca82000~tplv-k3u1fbpfcp-jj-mark:0:0:0:0:q75.image#?w=720&h=396&s=24402&e=gif&f=36&b=ffffff](url)

我认为在可以多选的时候，只有一个选项和 有多个选项的情况下表现应该保持一致，都不会自动收起面板，如果你就觉得这样体验比较好，可以像下面这个例子这样处理，也可以达到你要的效果。

[例子](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXNlbGVjdC12MiB2LW1vZGVsPVwidmFsdWVcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIiBzdHlsZT1cIndpZHRoOiAyNDBweFwiIG11bHRpcGxlIGZpbHRlcmFibGVcbiAgICBAY2hhbmdlPVwiY2hhbmdlXCIgcmVmPVwiRWxTZWxlY3RWMlJlZlwiIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgaW5pdGlhbHMgPSBbJ2EnLCAnYicsICdjJywgJ2QnLCAnZScsICdmJywgJ2cnLCAnaCcsICdpJywgJ2onXVxuY29uc3QgRWxTZWxlY3RWMlJlZiA9IHJlZihudWxsKVxuY29uc3QgdmFsdWUgPSByZWYoW10pXG5jb25zdCBvcHRpb25zID0gcmVmKFxuICBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICAgIHZhbHVlOiBgT3B0aW9uICR7aWR4ICsgMX1gLFxuICAgIGxhYmVsOiBgJHtpbml0aWFsc1tpZHggJSAxMF19JHtpZHh9YCxcbiAgfSkpXG4pXG5cbmNvbnN0IGNoYW5nZSA9ICgpID0+IHtcbiAgaWYgKEVsU2VsZWN0VjJSZWYudmFsdWUuZmlsdGVyZWRPcHRpb25zLmxlbmd0aCA9PT0gMSkge1xuICAgIEVsU2VsZWN0VjJSZWYudmFsdWUuZHJvcGRvd25NZW51VmlzaWJsZSA9IGZhbHNlXG4gIH1cbn1cbjwvc2NyaXB0PiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Pull request closed without merging**
