### PR TITLE
chore(deps): update gulp-sass use new Sass JS API

### PR DESCRIPTION
**Pull request by warmthsea**
https://github.com/dlmanning/gulp-sass/pull/846
https://github.com/element-plus/element-plus/pull/18428#issuecomment-2448868980

Before:

image

After:

image

### CODE REVIEW

**Review by btea — APPROVED** [review]

**Comment by warmthsea** [comment]
It's strange that although there is no warning when building, there will still be a warning when running. 🤔

**Comment by btea** [comment]
> It's strange that although there is no warning when building, there will still be a warning when running. 🤔

What conditions do you mean by `running`?

**Comment by warmthsea** [comment]
> What conditions do you mean by `running`?

/play dev

image

image

**Comment by btea** [comment]
For vite related issues, we can upgrade the version or modify the related configuration.
https://github.com/vitejs/vite/pull/17937

**Comment by warmthsea** [comment]
> For vite related issues, we can upgrade the version or modify the related configuration. [vitejs/vite#17937](https://github.com/vitejs/vite/pull/17937)

It seems that users must manually configure or upgrade Vite to 6.0 to avoid warnings.

**Pull request merged**
