### PR TITLE
fix(components): [el-select] input newline

### LINKED ISSUE #2858: [Bug Report] El-Select 'Create New Items' Input wrapped
### Element Plus version
1.0.2-beta.69

### OS/Browsers version
OSX 10.15.7 / Chrome 91.0.4472.164

### Vue version
3.1.2

### Reproduction Link
https://codepen.io/tangdaoyuan/pen/MWmPQEw

### Steps to reproduce
1. select 'HTML' and 'css'
2. input 'a' and enter

### What is Expected?
Input area no-wrap (like element-ui 2.15.5)
image

### What is actually happening?
input area wrapped
image

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #2858

### CODE REVIEW

**Comment by msidolphin** [comment]
I don't think it's a bug, not recommended to modify, it will cause the input box to be narrow in most cases,

**Comment by Alanscut** [comment]
> I don't think it's a bug, not recommended to modify, it will cause the input box to be narrow in most cases
> 
> image

yeah, not a bug, because @sxzz marked it as an enhancement , I just update it to be consistent with element ui,  should I close this PR?

**Comment by JeremyWuuuuu** [comment]
Let's temporarily hold this PR, we need some discussion with the designer for a better solution.

**Comment by kooriookami** [comment]
Fixed in 2.5.0

**Pull request closed without merging**
