### PR TITLE
docs(ssr): component ssr/ssg usage tips

### PR DESCRIPTION
**Pull request by loosheng**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
@loosheng Thank you very much for your hard work. Maybe it's more appropriate to add it to `dev faq`, WDYT?

**Comment by chenxch** [comment]
@loosheng Thank you very much for your hard work. Maybe it's more appropriate to add it to `dev faq`, WDYT?

**Comment by loosheng** [comment]
@chenxch  I think it's most intuitive to show hints on the component page, some users don't check the `dev faq,` and we need this strong reminder.

**Comment by chenxch** [comment]
Not all users need to develop SSR/SSG. You can't write all the components in one scenario, which makes the document very cumbersome. @jw-foss , I'd like to hear your opinion

**Review by jw-foss — APPROVED** [review]

**Comment by jw-foss** [comment]
> Not all users need to develop SSR/SSG. You can't write all the components in one scenario, which makes the document very cumbersome. @jw-foss , I'd like to hear your opinion

Actually, SSG and SSR are commonly used worldwide, so I think this is a good thing to include. Praise to @loosheng for adding it.

**Comment by chenxch** [comment]
> Actually, SSG and SSR are commonly used worldwide, so I think this is a good thing to include. Praise to @loosheng for adding it.

I get it. approved~🚀

**Review by chenxch — APPROVED** [review]

**Pull request merged**
