### PR TITLE
fix(table): fix filter icon height of table header

### PR DESCRIPTION
**Pull request by kooriookami**
Please make sure these boxes are checked before submitting your PR, thank you!

Before
image
After
image

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by justwiner** [comment]
Under what circumstances will cause style problems, i don't know what the problem is for the time being. thanks!
@kooriookami

**Comment by kooriookami** [comment]
> Under what circumstances will cause style problems, i don't know what the problem is for the time being. thanks!
> @kooriookami

When the table is filterable or sortable, the two icon shows and have a height of 34px, it will stretch the header. The normal height of the header is 48px, and the stretched height is 59px.
image

**Comment by justwiner** [comment]
> > Under what circumstances will cause style problems, i don't know what the problem is for the time being. thanks!
> > @kooriookami
> 
> When the table is filterable or sortable, the two icon shows and have a height of 34px, it will stretch the header. The normal height of the header is 48px, and the stretched height is 59px.
> image

OK!
Thank you for fixing this bug!

**Review by justwiner — APPROVED** [review]

**Comment by kooriookami** [comment]
The comment is a test for creating pr build.

**Pull request merged**
