### PR TITLE
fix: dialog cannot be closed by clicking modal

### LINKED ISSUE #3419: [Bug Report] Dialog cannot be closed by clicking modal
### Element Plus version
1.1.0-beta.12

### OS/Browsers version
Chrome 92

### Vue version
3.2.11

### Reproduction Link
https://jsfiddle.net/Belinchung/jk9mhorp/5/

### Steps to reproduce
1. open dialog
2. click modal to close diaog

### What is Expected?
dialog is not close

### What is actually happening?
dialog should be closed

### PR DESCRIPTION
**Pull request by xiaoxian521**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xiaoxian521** [comment]
fix: https://github.com/element-plus/element-plus/issues/3419

**Comment by sxzz** [comment]
It seems that I can't reproduce this issue.

**Comment by xiaoxian521** [comment]
https://element-plus.org/#/zh-CN/component/dialog
click outside modal, the dialog not close

**Comment by sxzz** [comment]
I see. But I have no time to review this for now... 😅

/cc @element-plus/backers

**Pull request closed without merging**
