### PR TITLE
refactor(utils): refactor with-install

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Seems like you have submitted the same code in https://github.com/element-plus/element-plus/pull/3341 was it on purpose or you just forgot about it?

**Review by jw-foss — APPROVED** [review]

**Comment by sxzz** [comment]
On purpose. I think it would be better that this PR is not mixing in https://github.com/element-plus/element-plus/pull/3341

**Comment by JeremyWuuuuu** [comment]
> On purpose. I think it would be better that this PR is not mixing in #3341

You might need to rebase the upstream for this since the code is identical you wouldn't have any issue with that.

**Comment by JeremyWuuuuu** [comment]
Great work on this! 👍

**Comment by sxzz** [comment]
@JeremyWuuuuu In fact, there is no need to rebase, just squash and merge directly. Repeated changes will be ignored.

**Pull request merged**
