### PR TITLE
fix(components): [date-picker] el-date-picker cannot display date

### LINKED ISSUE #14342: [Component] [date-picker] el-date-picker无法显示日期
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: ` Chrome 116.0.5845.97`
- Build Tool: `Vite`

### Related Component

- `el-date-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxlbC1pbnB1dCB2LW1vZGVsPVwibXNnXCIgLz5cbiAg5peg5rOV5pi+56S65pel5pyfXG4gIDxjb21wb25lbnQgaXM9XCJlbC1kYXRlLXBpY2tlclwiPlxuICAgIDx0ZW1wbGF0ZSB2LWlmPVwiZmFsc2VcIj5cbiAgICAgIDxkaXY+XG4gICAgICAgIDEyM1xuICAgICAgPC9kaXY+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9jb21wb25lbnQ+XG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj5cbiAgICAgIDxFbGVtZW50UGx1cyAvPlxuICAgIDwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgZXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

el-date-picker在component动态渲染时 component里面不能有代码或注释 否则el-date-picker无法显示日期

### What is Expected?

正常显示日期

### What is actually happening?

无法显示日期

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by zbncs**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 9a173d6</samp>

Updated the filter condition for the cell slot in `basic-cell-render.tsx` to avoid rendering unwanted elements in the date picker. This fixed a bug where some cells showed a dot and improved the component's compatibility and performance.

## Related Issue

Fixes #14342.

## Explanation of Changes

When there is an annotation node in the slot and a template without a default slot, the date display will be blank.

### <samp>🤖 Generated by Copilot at 9a173d6</samp>

* Fix a bug where some empty cells would show a dot in the date picker component by updating the filter condition for the cell slot children elements to exclude v-cmt and template ([link](https://github.com/element-plus/element-plus/pull/14358/files?diff=unified&w=0#diff-2d0a60e1bf84549bcbd25d8fb941ede708d4314e22f06bf363938b53547f4760L17-R20) in `basic-cell-render.tsx`)

### CODE REVIEW

**Comment by zbncs** [comment]
> 👋 @zbncs, seems like this is your first time contribution to element-plus.
> 
> * Please make sure that you have read our [guidelines](#%7Bguideline_url%7D) and [code of conduct](%7Bcoc_url%7D) before making a contribution.
> * You can comment with `/label Components:[component_name]` to add a label for which component you are working on.
> * You may join our Discord for staying tuned.
> type = 'template'
image

> type = 'Symbol(v-cmt)'
image

**Comment by FrontEndDog** [comment]
The same to #14354 , I don't think it should be added `type===”template“`, The expectation of `tsx` should be consistent with the `<template>`.  `<template>` without slot attributes should not be displayed [Example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbmltcG9ydCB0ZXN0IGZyb20gJy4vdGVzdC52dWUnO1xuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHRlc3Q+XG4gICAgPHRlbXBsYXRlPnNqaWRzamQ8L3RlbXBsYXRlPlxuICA8L3Rlc3Q+XG4gIC0tLS0tLS0tLS0tLS0tXG4gIDx0ZXN0PlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5zamlkc2pkPC90ZW1wbGF0ZT5cbiAgPC90ZXN0PlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy90ZXN0LnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgICA8ZGl2PlxuICAgICAgICA8c2xvdD7lrZDnu4Tku7ZzbG9055qE5YaF5a65PC9zbG90PlxuICAgIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnO1xuXG5jb25zdCBhID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbmNvbnNvbGUubG9nKCdhJywgYS5zbG90cy5kZWZhdWx0KCkpXG48L3NjcmlwdD4iLCJfbyI6e319)

**Comment by zbncs** [comment]
> Example

Templates without default slots display nothing and are not user friendly enough, just like regular nodes.

**Comment by btea** [comment]
@zbncs Thank you for your contribution, I think #14354 should have fixed this issue and I will close this PR.

If you have any further questions, please continue to comment below.

**Pull request closed without merging**
