### PR TITLE
fix(components): [el-tooltip] effect type error

### LINKED ISSUE #1670: [Bug Report] Typescript errors in multiple components when enum is used for props
### Element Plus version
1.0.2-beta.35

### OS/Browsers version
Windows 10 / Chrome 90

### Vue version
3.0.7

### Steps to reproduce
1. Create a Vue typescript project using Vite.
2. Add a component in a Vue template that has a prop which is defined as an enum value, such as <el-tooltip effect="light">
3. Compile the project with npm run build

### What is Expected?
Compilation is successful.

### What is actually happening?
image

Typescript complains about incompatible types, because a string is passed to the prop where it is expecting an enum. A better implementation would be to use union types instead of enums in this scenario. e.g.

Replace the current:
```
export declare enum Effect {
    DARK = "dark",
    LIGHT = "light"
}
```

With:
```
type Effect = "light" | "dark";

<!-- generated by https://elementui.github.io/issue-generator DO NOT REMOVE -->

### LINKED ISSUE #3257: [Bug Report] el-tooltip in typescript ,effect cannot be directly assigned to dark
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
mac

### Vue version
3.2.9

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-ms973?file=/src/App.vue&1

### Steps to reproduce
Because the bug can be seen through the screenshot, i think there is no need to provide a Reproduction Link.
image

Until the official solution to this problem. My temporary solution is
``` ts
import { Effect } from 'element-plus'
// 
<ElTooltip effect={Effect.DARK} />
```

### What is Expected?
effect can be directly assigned to dark.

### What is actually happening?
effect can not be directly assigned to dark.

### PR DESCRIPTION
**Pull request by imswk**
fix (#3257)

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sxzz** [comment]
This may reduce type rigor.
https://github.com/element-plus/element-plus/issues/3257#issuecomment-914071388

**Comment by imswk** [comment]
> This may reduce type rigor.
> [#3257 (comment)](https://github.com/element-plus/element-plus/issues/3257#issuecomment-914071388)

But the `effect` type is `string` instead of `enum`

**Comment by sxzz** [comment]
How about change `enum` to union type?

**Comment by JeremyWuuuuu** [comment]
> How about change `enum` to union type?

I've thought about that before, and I think i could be better than enum since the current SFC typing system sucks.

**Comment by sxzz** [comment]
@imswk Would you mind change `enum Effect` to `union literal type`?
```ts
type Effect = 'dark' | 'light'
```

**Comment by imswk** [comment]
> @imswk Would you mind change `enum Effect` to `union literal type`?
> 
> ```ts
> type Effect = 'dark' | 'light'
> ```

I have seen it before, and I found that the change is much more, do you have to make such a revision?

**Comment by sxzz** [comment]
@imswk I think it is necessary for strict typescript (because I planned to change it like this before.)

**Comment by sxzz** [comment]
@imswk Would you mind modify it to union type. Or I will handle it in the future, and please close this issue.

**Comment by sxzz** [comment]
We will refactor it in #3113. So I will close it.

**Pull request closed without merging**
