### PR TITLE
Select

### PR DESCRIPTION
**Pull request by webvs2**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at e2dc251</samp>

This pull request fixes two bugs in the table and select components. It makes the `row` variable reactive in `table-body/styles-helper.ts` to enable highlighting the current row, and it adjusts the `maxWidth` calculation in `select/useSelect.ts` to prevent tags from overflowing the input.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at e2dc251</samp>

* Fix a bug in the select component where the tags would overflow the input when multiple values are selected ([link](https://github.com/element-plus/element-plus/pull/14163/files?diff=unified&w=0#diff-ae55c3efc549b49d40b3f5b535ac2fc1572374d9309b6439f8d529b06edb1368L970-R979)). Adjust the maxWidth calculation of the selectTagsStyle to account for the padding and margin of each tag, as well as the status icon if present.

### CODE REVIEW

**Comment by webvs2** [comment]
### The exception is as follows:
455cb7440fb857a6872899b7809967d

**Comment by webvs2** [comment]
@xiaotao2018

**Comment by btea** [comment]
@webvs2 Can you provide a reproduction link?

**Comment by webvs2** [comment]
> 你能提供复制链接吗？

您指的链接是指错误示例吗

**Comment by btea** [comment]
@webvs2 Yes, it is convenient for us to reproduce and compare the changes before and after modification.

**Comment by webvs2** [comment]
> @webvs2 Yes, it is convenient for us to reproduce and compare the changes before and after modification.

@btea  我将关闭这个PR，我验证已经修复，谢谢

**Pull request closed without merging**
