### PR TITLE
fix(components): lazy image is not work when it changes src

### PR DESCRIPTION
**Pull request by zycoJamie**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

el-image has a problem.
image opens lazy props , if i do not trigger lazy-load of image ,  i change src of image , picture will load immediately. lazy loading is not work.

### CODE REVIEW

**Comment by msidolphin** [comment]
Can you provide a demo?

**Comment by zycoJamie** [comment]
https://codesandbox.io/s/friendly-pond-4ht68?file=/src/ImageDemo.vue

**Comment by zycoJamie** [comment]
WeChatce7eb6aafd42f1c1dc2d552b60a7c7f4
WeChatc5334d1db6e0836e2c98fd7636d45920

change src, all picture will be loading.

**Comment by JeremyWuuuuu** [comment]
@zycoJamie Can you record a video of after this modification how it behaves? 
Also I would like you to open a issue for tracking this bug

**Comment by zycoJamie** [comment]
#3210

**Comment by zycoJamie** [comment]
fix
after the fixes... when i change src of image, only loading the visible image, lazy loading do work.

**Comment by msidolphin** [comment]
I think it is caused by you using the wrong key, try to use a unique id instead of idx

**Comment by zycoJamie** [comment]
> I think it is caused by you using the wrong key, try to use a unique id instead of idx

when props.src is changed, the "loadImage" function must be called in the source code. So the problem has nothing to do with key..

**Comment by JeremyWuuuuu** [comment]
LGTM, I would like to ask you for writing a unit test, for testing whether the `loadImage` is called right away. Note that we can also create a follow up issue for the unit test. This **is not** mandatory request.

**Review by jw-foss — APPROVED** [review]

**Comment by msidolphin** [comment]
> > I think it is caused by you using the wrong key, try to use a unique id instead of idx
> 
> when props.src is changed, the "loadImage" function must be called in the source code. So the problem has nothing to do with key..
> 
> /packages/components/image/src/index.vue
> 
> ```js
> 286  watch(() => props.src, () => {
> 287   loadImage()
> 288  })
> ```

Since it's the same component instance, maybe using a unique key is a better solution, using the idx as the key is a bad habit

**Comment by zycoJamie** [comment]
> LGTM, I would like to ask you for writing a unit test, for testing whether the `loadImage` is called right away. Note that we can also create a follow up issue for the unit test. This **is not** mandatory request.

umm...i can not think out how to check calling of the `loadImage ` in jest, i am not good at unit testing. sry..

**Comment by JeremyWuuuuu** [comment]
@zycoJamie Please rebase the upstream so we can get this merged. About the test w can add a follow up issue for it. :bow:

**Review by sxzz — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
Let's get this merged! 🥂

**Pull request merged**
