### PR TITLE
fix: remove outline and padding 

### PR DESCRIPTION
**Pull request by BeADre**
**outline**: like this

image

**padding**: like this

image

### CODE REVIEW

**Comment by zazzaz** [comment]
fixed in #584

**Comment by BeADre** [comment]
padding的问题似乎已经修了  那文档的outline呢？我修改当前的pr还是你那边来修复？

**Comment by zazzaz** [comment]
seems to fix the outline in popper is better?

**Comment by BeADre** [comment]
but the outline I modified seems to have nothing to do with popper

**Pull request closed without merging**
