### PR TITLE
fix(components): [infinite-scroll] Infinite scroll

### LINKED ISSUE #5358: [Bug Report] Infinite Scroll 触发一次后继续执行
### Element Plus version
1.3.0-beta.5

### OS/Browsers version
win10

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/q2419068625/pen/MWEzdOY

### Steps to reproduce
Popover  和 Infinite Scroll 搭配使用，v-infinite-scroll 方法会一直触发不会停止

### What is Expected?
触发后停止

### What is actually happening?
触发一次后继续执行，不会停止,会一直执行该方法

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #5358

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@Alanscut Would you mind add some tests for covering that?

**Comment by Alanscut** [comment]
[playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcyc7XG5pbXBvcnQgeyBVc2VyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG5cbi8vIHNldHVwIGZvciBlbGVtZW50IHBsdXMsIGRvbid0IHJlbW92ZS5cbnNldHVwRWxlbWVudFBsdXMoKTtcblxuY29uc3QgY291bnQgPSByZWYoMClcbmNvbnN0IGxvYWQgPSAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdsb2FkJykgXG4gIGNvdW50LnZhbHVlICs9IDJcbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1wb3BvdmVyIHRyaWdnZXI9XCJjbGlja1wiPlxuICAgIDx0ZW1wbGF0ZSAjcmVmZXJlbmNlPlxuICAgICAgPGVsLWJ1dHRvbj50ZXN0PC9lbC1idXR0b24+XG4gICAgPC90ZW1wbGF0ZT5cbiAgICA8dWwgdi1pbmZpbml0ZS1zY3JvbGw9XCJsb2FkXCIgc3R5bGU9XCJvdmVyZmxvdzphdXRvO2hlaWdodDoyMDBweDtcIj5cbiAgICAgIDxsaSB2LWZvcj1cImkgaW4gY291bnRcIiA6a2V5PVwiaVwiPnt7IGkgfX08L2xpPlxuICAgIDwvdWw+XG4gIDwvZWwtcG9wb3Zlcj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

**Comment by Alanscut** [comment]
The test seems to be difficult to write, because the value obtained by clientHeight in the test seems to always be 0 if we do not set it. It doesn't change when I click the button. And the updated hook doesn't seem to trigger either.

**Review by jw-foss — APPROVED** [review]

**Comment by ealldy** [comment]
The problem remains unresolved.
@Alanscut @JeremyWuuuuu

**Pull request merged**
