### PR TITLE
feat: support node 18+ & update tsx and vitest

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by kooriookami** [comment]
Wow, it's a big change.

**Comment by kooriookami** [comment]
image
Does this node version need to be changed to 18?

**Comment by btea** [comment]
>Does this node version need to be changed to 18?

Yes.

**Comment by kooriookami** [comment]
image

Same here~

**Review by kooriookami — APPROVED** [review]

**Comment by kooriookami** [comment]
Maybe we can merge it and see if it's OK.

**Comment by btea** [comment]
No rush, I plan to verify again over the weekend whether it will affect the packaged code.

**Comment by kooriookami** [comment]
OK

**Comment by btea** [comment]
I checked it roughly, and the changes that occurred are roughly as follows:
1. the names of some packaged component files have changed, such as `autocomplete.mjs` => `autocomplete2.mjs` `autocomplete2.mjs` => `autocomplete.mjs`.
(Before the modification, `autocomplete.ts` will be packaged into `autocomplete.mjs`, and `autocomplete.vue` will be packaged into `autocomplete2.mjs`. After the modification, it will be reversed, and the content of `autocomplete.mjs` will be `autocomplete.vue` packaged.)
2. The content packaged by the `icon` component has one more line of style import.
`components/icon/style/css.mjs`
```diff
import '../../base/style/css.mjs';
+import 'element-plus/theme-chalk/el-icon.css';
```
`components/icon/style/index.mjs`
```diff
import '../../base/style/index.mjs';
+import 'element-plus/theme-chalk/src/icon.scss';
```

The above modifications seem to have no impact on the overall code logic.

**Review by tolking — APPROVED** [review]
The changes in the packaged files may affect some users. I think merging this PR in the next major release might be more appropriate, WDYT.

**Comment by btea** [comment]
Do you think we should merge it when we release `2.7.0` or `3.0.0`?

**Comment by tolking** [comment]
2.7.0

**Pull request merged**
