### PR TITLE
test(input-number): complete test

### PR DESCRIPTION
**Pull request by FengXingyuan**
-write test of input-number
-fix repeat emit event of input-number
-change docs up-to-date

### CODE REVIEW

**Comment by zazzaz** [comment]
Thanks. Any reason to close this PR, please? Or r u going to divide it into some small PRs like #568

**Comment by FengXingyuan** [comment]
> Thanks. Any reason to close this PR, please? Or r u going to divide it into some small PRs like #568

yes, i would like to divide it into small PRs incase hard to review

**Comment by zazzaz** [comment]
cool

**Comment by FengXingyuan** [comment]
> cool

some bug was found when i wrote test and was fixed in #568 
now the question is: should i make my PR of test right now or wait for merging of #568?

我是在写测试的时候发现了几个bug，修完以后在#568提交。请问我的测试文件应该是等到#568通过后提交还是现在就提交？

**Comment by zazzaz** [comment]
It will be great if you could split into small PRs which is easy to review.

**Pull request closed without merging**
