### PR TITLE
fix(docs): outDir error of VitePWA

### PR DESCRIPTION
**Pull request by tolking**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Seems still can't work

**Comment by tolking** [comment]
I test offline access is work on the Safari 15.3 and Chrome 100.

You can check whether sw.js is registered successfully.

[](https://imgtu.com/i/LET59J)

**Comment by tolking** [comment]
Maybe you should test after modifying document

**Comment by sxzz** [comment]
Enable `offline` and refresh page.
image

**Comment by tolking** [comment]
Can you describe the relevant information about sw.js on below your screenshot?  (time , Status ...)

**Comment by tolking** [comment]
Can you describe the relevant information about sw.js on below your screenshot?  (time , Status ...)

**Comment by sxzz** [comment]
image
image
image

**Comment by tolking** [comment]
It seems that sw.js is not registered successfully.

You can cancel offline before accessing (or refresh), Then wait for the network request to load completed. Caching everything is a time-consuming process, switch to the Network to see the progress.

Then check if the status is activated

**Comment by sxzz** [comment]
Oh, it works! Thanks a lot!

**Comment by sxzz** [comment]
🎉 It has been release to stable docs! Thanks for your contribution!

**Pull request merged**
