### PR TITLE
fix(components): [select] display error when setting persistent to false

### LINKED ISSUE #6479: [Bug Report] [Component] [select] el-select且关闭持久化（:persistent="false"）时，显示的值时value的值而非lable的值，且如果value值为数字是会报类型错误警告
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.0.5`
- Browser / OS: `win11  /  Microsoft Edge 99`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPiBcbiAgPGVsLXNlbGVjdCB2LW1vZGVsPVwidmFsdWVcIiA6cGVyc2lzdGVudD1cImZhbHNlXCIgY2xhc3M9XCJtLTJcIiA6ZmlsdGVyYWJsZT1cInRydWVcIiBwbGFjZWhvbGRlcj1cIlNlbGVjdFwiIDpkZWZhdWx0Rmlyc3RPcHRpb249XCJ0cnVlXCIgc2l6ZT1cInNtYWxsXCI+XG4gICAgPGVsLW9wdGlvblxuICAgICAgdi1mb3I9XCJpdGVtIGluIG9wdGlvbnNcIlxuICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmxhYmVsPVwiaXRlbS5sYWJlbFwiXG4gICAgICA6dmFsdWU9XCJpdGVtLnZhbHVlXCJcbiAgICA+XG4gICAgPC9lbC1vcHRpb24+XG4gIDwvZWwtc2VsZWN0PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgdmFsdWUgPSByZWYoMSlcblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnYScsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogMixcbiAgICBsYWJlbDogJ2InLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDMsXG4gICAgbGFiZWw6ICdjJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiA0LFxuICAgIGxhYmVsOiAnZCcsXG4gIH0sXG4gIHtcbiAgICB2YWx1ZTogNSxcbiAgICBsYWJlbDonZScsXG4gIH1cbl1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1wiaW1wb3J0c1wiOnt9fSJ9)

### Steps to reproduce

`el-select`   设置可本地搜索时（`:filterable="true"`） 且关闭持久化（`:persistent="false"`）时，当options数组中的value值为数字时会报类型错误警告,且显示的值是value的值而非lable的值，即当我选中第一项，此时`el-select`的输入框显示的值是1，而不是’a‘， 正常情况应该显示’a‘

### What is Expected?

不报错，不报警告，显示lable的值

### What is actually happening?

输入框会的placeholder会报类型错误，且显示value的值

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #6479

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@Alanscut You have some conflicts please rebase to resolve it.

**Comment by Alanscut** [comment]
@JeremyWuuuuu done

**Review by jw-foss — APPROVED** [review]

**Comment by mxp131011** [comment]
@JeremyWuuuuu 还是没被修复 在2.1.0中

**Comment by mxp131011** [comment]
@Alanscut  还是没被修复 在2.1.0中 ，新的[Issues](https://github.com/element-plus/element-plus/issues/6579)

**Pull request merged**
