### PR TITLE
fix(components): [message] If the type does not match, use the info type

### PR DESCRIPTION
**Pull request by lete114**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by tolking** [comment]
Can you provide a issues demo

**Comment by Lete114** [comment]
Error types that are not one of `['success', 'warning', 'message', 'error']`, resulting in loss of style
The class attribute is `class="el-message el-message--errorType"`
```vue
<template>
  <el-button :plain="true" @click="open0">error type</el-button>
</template>

<script lang="ts" setup>
import { ElMessage } from 'element-plus'

const open0 = () => {
  ElMessage({
    duration: 0,
    message: 'This is a type error message.',
    // type determines the el-message--errorType
    type: 'errorType',
  })
}
</script>
```

**Comment by Lete114** [comment]
Probably no one would make such a small mistake, but it's a real potential problem

**Comment by tolking** [comment]
@Lete114 It seems that there is no need to do this, the wrong attribute will directly cause Vue to generate a warning message.

**Pull request closed without merging**
