### PR TITLE
fix(components): [select-v2] missing validate action when clear

### LINKED ISSUE #4875: [Bug Report] el-select-v2 clearable时触发不了表单验证
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
win11 /谷歌 96.0.4664.93

### Vue version
3.2.26

### Reproduction Link
https://github.com/chengzhile/vue3-issue-demo.git

### Steps to reproduce
1、选中选项
2、消除选项

### What is Expected?
el-select-v2 clearable时触发表单验证

### What is actually happening?
el-select-v2 clearable时触发不了表单验证

### PR DESCRIPTION
**Pull request by Ryan2128**
- Fix the bug that missing validate when clear
- Add the same icon and style as the select component

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Fixed #4875

### CODE REVIEW

**Comment by Ryan2128** [comment]
Please do not merge, the test cases will be added later. 🌟

**Comment by msidolphin** [comment]
image
I found an error in tag

**Comment by Ryan2128** [comment]
>

**Comment by Ryan2128** [comment]
> image I found an error in tag


I checked the code and found that it was not caused by my changes, it was caused by the tag component and size changes.

@YunYouJun 

Please check these two commits.

efb48a61fd7e0d39437a541eaae7af608e9f793d
efb48a61fd7e0d39437a541eaae7af608e9f793d

**Comment by Ryan2128** [comment]
In my commit, I only add the icons of validation status. @msidolphin @YunYouJun

**Review by msidolphin — APPROVED** [review]

**Pull request merged**
