### PR TITLE
fix(carousel): fix a bug about carousel arrow transition

### PR DESCRIPTION
**Pull request by shlroland**
- [ ] Component Migration

Fix #

### CODE REVIEW

**Comment by zazzaz** [comment]
Can you please detail what this bug is?

**Comment by shlroland** [comment]
> Can you please detail what this bug is?

vue3.0 remove `v-enter` lifecycle hook . it leads that when i enter carousel component, the arrows entering transition effect can't be triggered.

**Comment by JeremyWuuuuu** [comment]
Changing the class name seems reasonable to me, but what's the point of changing CSS properties? Could you please detail it?

**Comment by JeremyWuuuuu** [comment]
I'll close this issue since it's been a while since it's been opened. Feel free to reopen if you have updates on this

**Pull request closed without merging**
