### PR TITLE
fix(components): [select] correct update selectSize

### LINKED ISSUE #11962: [Component] [select] selsect
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.2.36`
- Browser / OS: `Chrome 111`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/form.html#尺寸控制)

### Steps to reproduce

切换form尺寸时，el-select 的高度一直保持默认高度，不会随size 的改变而改变高度

### What is Expected?

根据size的切换 高边select 的高度

### What is actually happening?

切换form尺寸时，el-select 的高度一直保持默认高度

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by acyza**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #11962

### CODE REVIEW

**Comment by chenxch** [comment]
@acyza Thanks for your contribution, would you mind adding a test case for this?

**Comment by acyza** [comment]
> @acyza Thanks for your contribution, would you mind adding a test case for this?

https://github.com/element-plus/element-plus/blob/dev/packages/components/select/__tests__/select.test.ts#L2030
这条测试能过是因为它测试环境拿到的input的clientHeight始终为0，给它模拟一个clientHeight的值问题就显现出来了。

相关代码：https://github.com/element-plus/element-plus/blob/dev/packages/components/select/src/useSelect.ts#L377-L386

**Review by chenxch — APPROVED** [review]
Good job.

**Review by btea — APPROVED** [review]

**Pull request merged**
