### PR TITLE
fix(components): [form] clear validate after reset fields

### PR DESCRIPTION
**Pull request by jw-foss**
- Enhancement for #6758 
- Followup for #6623 
- Add test case against changes

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by zouhangwithsweet — APPROVED** [review]

**Comment by zhoufanglu** [comment]
I reinstalled el-plus locally, but it still doesn't take effect. Do I need to wait for the release?

**Comment by JeremyWuuuuu** [comment]
> I reinstalled el-plus locally, but it still doesn't take effect. Do I need to wait for the release?

@zhoufanglu we haven't publish the release yet, it was supposed to be tonight, if you really needed this to work properly, please fallback to version `2.0.5`, this version should work as charm.

**Comment by zhoufanglu** [comment]
> > I reinstalled el-plus locally, but it still doesn't take effect. Do I need to wait for the release?
> 
> @zhoufanglu we haven't publish the release yet, it was supposed to be tonight, if you really needed this to work properly, please fallback to version `2.0.5`, this version should work as charm.

ok thanks,

**Comment by JeremyWuuuuu** [comment]
@zhoufanglu Sincerely sorry for the trouble we caused! :bow:

**Comment by zhoufanglu** [comment]
> @zhoufanglu Sincerely sorry for the trouble we caused! 🙇
It doesn't matter can solve good, hard, have a good day.

**Comment by zhoufanglu** [comment]
> @zhoufanglu Sincerely sorry for the trouble we caused! 🙇

sorry,excuse, https://github.com/element-plus/element-plus/issues/6800#issue-1179123833  Is that what the problem is about?

**Pull request merged**
