### PR TITLE
[WIP] fix(components): [el-datetime-picker] can't change defafultTime

### LINKED ISSUE #1304: [Bug Report] date-picker default-time props not work
### Element Plus version
1.0.1-beta.27

### OS/Browsers version
MacOS10.15.7 / 87.0.4280.141

### Vue version
3.0.5

### Reproduction Link
https://codepen.io/tothingway/pen/QWKYgwp?editors=1111

### Steps to reproduce
1. use default-time prop in el-date-picker
2. default-time is not work
3. warning appears in console when I use other custom props, like <el-date-picker :abc="myProp" />

### What is Expected?
1. default-time work
2. warning for custom props disappears

### What is actually happening?
1. default-time is not work
2. warning appears in console when I use other custom props, like <el-date-picker :abc="myProp" />

### LINKED ISSUE #3244: Datetime picker with default time queries
Refer to datetime picker with default time, 
https://element-plus.org/#/en-US/component/datetime-picker

I found the time value can't change after set a default time, if 
dest not set default time, the time value can't changed

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix #3244

### CODE REVIEW

**Comment by sxzz** [comment]
It seems that the test failed, please fix it.

**Comment by sxzz** [comment]
The unit test failed, please run `yarn format`.

**Comment by Alanscut** [comment]
thanks, will fix it later

**Comment by Alanscut** [comment]
Hi @sxzz ,  I have a question about the failed test case, according to the [docs](https://element-plus.org/#/zh-CN/component/date-picker), the `defatult-time` in date-picker component should be `Date[]`, namely it only works for type `daterange`, and in the below test case, it is should be invalid.  And the expected behavior of the test case is inconsistent with that of `element`.

https://github.com/element-plus/element-plus/blob/d943a664345871027fd42036bd769bf1cc94905c/packages/components/date-picker/__tests__/date-picker.spec.ts#L105-L128

**Comment by Alanscut** [comment]
in element, the `default-time` won't take effect in `date-picker`: https://codepen.io/Alan_scut/pen/ExXXmXM?editors=1010
and in element plus, `default-time` works: https://codepen.io/Alan_scut/pen/mdwMjJR

Maybe we should unify the behavior, and update the doc that `default-time` could be `Date` type in `date-picker`(type is date), what do you think @sxzz?

**Comment by Alanscut** [comment]
closing it because #4228 has fixed this issue

**Pull request closed without merging**
