### PR TITLE
fix(components): [tour] isSameSteps Return an error value, Return true when the same is true

### PR DESCRIPTION
**Pull request by youpinyao**
isameSteps Return an error value, Return true when the same is true

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
@youpinyao Maybe you can provide a demo to reproduce this error, but your modification seems to just return true directly. I look forward to your demo.

**Comment by youpinyao** [comment]
> @youpinyao Maybe you can provide a demo to reproduce this error, but your modification seems to just return true directly. I look forward to your demo.

@chenxch 

This is the [demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnO1xuaW1wb3J0IHsgTW9yZUZpbGxlZCB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJztcbmltcG9ydCB0eXBlIHsgQnV0dG9uSW5zdGFuY2UgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuaW1wb3J0IHsgRWxUb3VyLCBFbFRvdXJTdGVwIH0gZnJvbSAnZWxlbWVudC1wbHVzJztcbmltcG9ydCBBdFRvdXIgZnJvbSAnLi9Ub3VyJztcblxuY29uc3QgcmVmMSA9IHJlZjxCdXR0b25JbnN0YW5jZT4oKTtcbmNvbnN0IHJlZjIgPSByZWY8QnV0dG9uSW5zdGFuY2U+KCk7XG5jb25zdCByZWYzID0gcmVmPEJ1dHRvbkluc3RhbmNlPigpO1xuXG5jb25zdCBvcGVuID0gcmVmKGZhbHNlKTtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG46cm9vdCB7XG4gIC0tZWwtdG91ci10ZXh0LWNvbG9yOiAjMDAwO1xufVxuPC9zdHlsZT5cblxuPHRlbXBsYXRlPlxuICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCIgQGNsaWNrPVwib3BlbiA9IHRydWVcIj5CZWdpbiBUb3VyPC9lbC1idXR0b24+XG5cbiAgPGVsLWRpdmlkZXIgLz5cblxuICA8ZWwtc3BhY2U+XG4gICAgPGVsLWJ1dHRvbiByZWY9XCJyZWYxXCI+dXBsb2FkPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiByZWY9XCJyZWYyXCIgdHlwZT1cInByaW1hcnlcIj5zYXZlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiByZWY9XCJyZWYzXCIgOmljb249XCJNb3JlRmlsbGVkXCIgLz5cbiAgPC9lbC1zcGFjZT5cbiAgPGF0LXRvdXIgdi1tb2RlbD1cIm9wZW5cIj5cbiAgICA8ZWwtdG91ci1zdGVwIDp0YXJnZXQ9XCJyZWYxPy4kZWxcIiB0aXRsZT1cIlVwbG9hZCBGaWxlXCI+XG4gICAgICA8ZGl2PlB1dCB5b3UgZmlsZXMgaGVyZS48L2Rpdj5cbiAgICA8L2VsLXRvdXItc3RlcD5cbiAgICA8ZWwtdG91ci1zdGVwIDp0YXJnZXQ9XCJyZWYyPy4kZWxcIiB0aXRsZT1cIlNhdmVcIiBkZXNjcmlwdGlvbj1cIlNhdmUgeW91ciBjaGFuZ2VzXCIgLz5cbiAgICA8ZWwtdG91ci1zdGVwIDp0YXJnZXQ9XCJyZWYzPy4kZWxcIiB0aXRsZT1cIk90aGVyIEFjdGlvbnNcIiBkZXNjcmlwdGlvbj1cIkNsaWNrIHRvIHNlZSBvdGhlclwiIC8+XG4gIDwvYXQtdG91cj5cbjwvdGVtcGxhdGU+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vZWxlbWVudC1wbHVzQDIuNS4zL2Rpc3QvaW5kZXguZnVsbC5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2VsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xNTYzMy1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTU2MzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59Iiwic3JjL1RvdXIudHMiOiJpbXBvcnQgeyBFbFRvdXIgfSBmcm9tICdlbGVtZW50LXBsdXMnO1xuaW1wb3J0IHsgY3JlYXRlVk5vZGUsIGRlZmluZUNvbXBvbmVudCB9IGZyb20gJ3Z1ZSc7XG5cbmNvbnN0IEF0VG91ciA9IGRlZmluZUNvbXBvbmVudCh7XG5cdG5hbWU6ICdBdFRvdXInLFxuXHRpbmhlcml0QXR0cnM6IGZhbHNlLFxuXHRzZXR1cChwcm9wcywgY3R4KSB7XG5cdFx0cmV0dXJuICgpID0+IHtcblx0XHRcdHJldHVybiBjcmVhdGVWTm9kZShcblx0XHRcdFx0RWxUb3VyLFxuXHRcdFx0XHR7XG5cdFx0XHRcdFx0Li4ucHJvcHMsXG5cdFx0XHRcdFx0Li4uY3R4LmF0dHJzLFxuXHRcdFx0XHR9LFxuXHRcdFx0XHR7XG5cdFx0XHRcdFx0Li4uY3R4LnNsb3RzLFxuXHRcdFx0XHR9XG5cdFx0XHQpO1xuXHRcdH07XG5cdH0sXG59KTtcblxuZXhwb3J0IGRlZmF1bHQgQXRUb3VyO1xuIiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTU2MzMtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=), Please change vue version to 3.2.37, Operation Tour will appear 
`[Vue warn]: Maximum recursive updates exceeded in component <ElTour>. This means you have a reactive effect that is mutating its own dependencies and thus recursively triggering itself. Possible sources include component template, render function, updated hook or watcher source function.`

**Comment by chenxch** [comment]
This is a recursion limitation problem in vue3.2 and 3.3, but it may be modified
```
if (!isSameProps(a[index], b[index])) {
      return false
    }
```

**Comment by Fuphoenixes** [comment]
Yes, I wrote it wrong.

**Comment by chenxch** [comment]
> Yes, I wrote it wrong.

Then I leave this to you to review.

**Pull request closed without merging**
