### PR TITLE
fix(components): add validate-event for form types component

### LINKED ISSUE #7739: [Bug Report] [Component] [form, form-item] form validate issue
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.25`
- Element Plus Version: `2.1.10`
- Browser / OS: ` Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.64 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-form`
- `el-form-item`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDdXN0b21Db21wb25lbnQgZnJvbSAnLi9DdXN0b21Db21wb25lbnQudnVlJ1xuXG5jb25zdCBmb3JtVmFsdWVzID0gcmVhY3RpdmUoe1xuICB2YWx1ZTogdW5kZWZpbmVkLFxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIDptb2RlbD1cImZvcm1WYWx1ZXNcIj5cbiAgXHQ8ZWwtZm9ybS1pdGVtIHByb3A9XCJ2YWx1ZVwiIGxhYmVsPVwiYW55d2F5XCIgOnJ1bGVzPVwiW3sgcmVxdWlyZWQ6IHRydWUsIG1lc3NhZ2U6ICdyZXF1aXJlZCcsIHRyaWdnZXI6ICdjaGFuZ2UnIH1dXCI+XG4gICAgICA8Y3VzdG9tLWNvbXBvbmVudCB2LW1vZGVsPVwiZm9ybVZhbHVlcy52YWx1ZVwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gIDwvZWwtZm9ybT5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXG4gIH1cbn0iLCJDdXN0b21Db21wb25lbnQudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbiAgaW1wb3J0IHsgcmVmLCByZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcblxuICBjb25zdCBwcm9wcyA9IGRlZmluZVByb3BzPHtcbiAgICBtb2RlbFZhbHVlPzogc3RyaW5nO1xuICB9PigpXG4gIGNvbnN0IGVtaXQgPSBkZWZpbmVFbWl0czx7XG4gICAgKGU6ICd1cGRhdGU6bW9kZWxWYWx1ZScpOiB2b2lkO1xuICB9PigpO1xuICBcbiAgY29uc3QgaW5wdXRSZWYgPSByZWYoKTtcbiAgY29uc3QgcG9wb3ZlclJlZiA9IHJlZigpO1xuICBjb25zdCByYWRpb1ZhbHVlID0gcmVmKCk7XG5cblxuICBjb25zdCBoYW5kbGVDYWxlbmRhckNvbmZpcm0gPSAodmFsdWVzOiBDYWxlbmRhclZhbHVlcykgPT4ge1xuICAgIGVtaXQoJ3VwZGF0ZTptb2RlbFZhbHVlJywgdmFsdWVzKTtcbiAgfTtcbiAgXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpdj5cbiAgPGVsLWlucHV0XG4gICAgICByZWY9XCJpbnB1dFJlZlwiXG4gICAgICBwbGFjZWhvbGRlPVwicGxlYXNlIGlucHV0XCJcbiAgICAgIHJlYWRvbmx5XG4gICAgLz5cbiAgICA8ZWwtcG9wb3ZlclxuICAgICAgcmVmPVwicG9wb3ZlclJlZlwiXG4gICAgICA6dmlydHVhbC1yZWY9XCJpbnB1dFJlZlwiXG4gICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgOndpZHRoPVwiNDAwXCJcbiAgICAgIDpzaG93LWFycm93PVwiZmFsc2VcIlxuICAgICAgOmhpZGUtYWZ0ZXI9XCIwXCJcbiAgICA+XG4gICAgICA8dGVtcGxhdGUgI2RlZmF1bHQ+XG4gICAgICAgIDxlbC1yYWRpby1ncm91cCB2LW1vZGVsPVwicmFkaW9WYWx1ZVwiPlxuICAgICAgICAgIDxlbC1yYWRpbyA6bGFiZWw9XCIxXCI+MTwvZWwtcmFkaW8+XG4gICAgICAgICAgPGVsLXJhZGlvIDpsYWJlbD1cIjJcIj4yPC9lbC1yYWRpbz5cbiAgICAgICAgICA8ZWwtcmFkaW8gOmxhYmVsPVwiM1wiPjM8L2VsLXJhZGlvPlxuICAgICAgICA8L2VsLXJhZGlvLWdyb3VwPlxuICAgICAgPC90ZW1wbGF0ZT5cbiAgICA8L2VsLXBvcG92ZXI+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT4iLCJfbyI6e319)

### Steps to reproduce

create a custom component that contains a component E.g el-radio-group or el-input etc as form-item input, then change the value of el-component inside custom component, form-item validate will be trigging

### What is Expected?

do not trigg form-item validate

### What is actually happening?

form-item validate has triggered

### Additional comments

can offer a prop to those components E.g el-input、el-radio-group etc to decide as a form-item input or not

### LINKED ISSUE #8159: [Bug Report] [Component] [input-number] Input Number 数字输入框不支持validate-event属性
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.4`
- Browser / OS: `Chrome/Mac OS`
- Build Tool: `Vite`

### Related Component

- `el-input-number`

### Reproduction Link

[Link](无)

### Steps to reproduce

!

### What is Expected?

期望支持

### What is actually happening?

！

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by HeftyKoo**
fix: #7739
fix: #8159

Add `validate-event` props for those components. The user can decide whether to trigger form validation or not.
* cascader
* checkbox
* color-picker
* input-number
* radio
* select-v2
* select
* slider
* transfer

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by HeftyKoo** [comment]
> 

These is two reason:
* The normal use case expect  trigger form validation by default.
* The logic before act like set to `true`，so set to `true` won't cause a breaking change.

**Comment by HeftyKoo** [comment]
> 

Provide this prop，user can set `validate-event` to `false`，then use those components to define a custom form like componet，and manual control the form validate timing.

you can see the use case in #7739

**Review by chenxch — APPROVED** [review]

**Comment by chenxch** [comment]
There are conflicts that need to be resolved.

**Comment by chenxch** [comment]
Need to review coach to confirm again.

**Comment by HeftyKoo** [comment]
> There are conflicts that need to be resolved.

resolved

**Comment by chenxch** [comment]
cc @tolking Need you review again.

**Review by tolking — APPROVED** [review]

**Pull request merged**
