### PR TITLE
refactor(locale): change short months naming of Thai

### PR DESCRIPTION
**Pull request by ADISAKBOONMARK**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

Type: Information
Description: The abbreviation months of the Thai language(th). It is still unclear. I recommend changing the abbreviation following the table below.

Screenshot 2023-01-23 143030

Result:

```
<template>
  <el-config-provider :locale="locale">
    <div class="play-container">
      Date Picker &nbsp;
      <el-date-picker v-model="value" type="date" placeholder="YYYY-MM-DD" />
    </div>
  </el-config-provider>
</template>

<script lang="ts" setup>

import { ref } from 'vue'
import th from '@element-plus/locale/lang/th.js'

const locale = ref(th)

const value = ref('2566-01-23')

</script>
```

messageImage_1674456652021

### CODE REVIEW

**Comment by ADISAKBOONMARK** [comment]
Hello @beta, I am not sure, are you reviewing this PR? If you reviewed it, sorry for tagging.

**Comment by btea** [comment]
@ADISAKBOONMARK Hello, I have not reviewed this pr. After translating with the help of a translation tool, I found that the meaning before and after the modification seems to be the same. Is there any difference between them?

**Comment by ADISAKBOONMARK** [comment]
Thank @btea for your reply. Yes, It is a difference. In my country(Thailand), people popularly used the abbreviation months following the above [table](https://github.com/element-plus/element-plus/pull/11326#issue-1552643862). Currently, I working as a developer. And use Element-Plus to implement software. I found many projects, users required the abbreviation months that I recommended. And I fixed it with hard-coding. 

``` js
import th from "element-plus/dist/locale/th.mjs";
...
  setup() {
    //================== Fix short months display ==================
    th.el.datepicker.months = {
      jan: 'ม.ค.',
      feb: 'ก.พ.',
      mar: 'มี.ค.',
      apr: 'เม.ย.',
      may: 'พ.ค.',
      jun: 'มิ.ย.',
      jul: 'ก.ค.',
      aug: 'ส.ค.',
      sep: 'ก.ย.',
      oct: 'ต.ค.',
      nov: 'พ.ย.',
      dec: 'ธ.ค.',
    }
    //==============================================================
...
```

I think it is better. If we use the popular format from the beginning. However, their meanings are similar.

**Comment by btea** [comment]
Ok, thanks for the explanation.

**Review by btea — APPROVED** [review]

**Review by plainheart — APPROVED** [review]
LGTM. The same month abbreviation as the [TH locale](https://github.com/apache/echarts/blob/master/i18n/langTH.js) of Apache ECharts. :)

**Pull request merged**
