### PR TITLE
fix(components): [select] loading pointer-events

### LINKED ISSUE #10225: [Component] [select] When the container is v-loading=true, the drop-down arrow of el-select can still be clicked。容器在 v-loading=true 的情况下，el-select 的 下拉箭头仍能点击。
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.41`
- Element Plus Version: `2.2.19`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPHA+XG4gICAg54i25YWD57Sg5a655ZmoIHYtbG9hZGluZz1cInRydWVcIu+8jOS9hiBlbC1zZWxlY3Qg55qE5LiL5ouJ566t5aS05LuN6IO954K55Ye75Lqk5LqS44CCXG4gIDwvcD5cblx0PGRpdiBjbGFzcz1cImNvbnRhaW5lclwiIHYtbG9hZGluZz1cInRydWVcIiBlbGVtZW50LWxvYWRpbmctYmFja2dyb3VuZD1cInJnYmEoMjU1LCAyNTUsIDAsIDAuMylcIj5cbiAgICA8ZWwtc2VsZWN0PjwvZWwtc2VsZWN0PlxuICA8L2Rpdj5cbiAgPHA+XG4gICAgPGVsLWljb24gY29sb3I9XCJ2YXIoLS1lbC1jb2xvci1wcmltYXJ5KVwiPjxFbGVtZW50UGx1cyAvPjwvZWwtaWNvbj5cbiAgICBFbGVtZW50IFBsdXMge3sgRXBWZXJzaW9uIH19ICsgVnVlIHt7IHZ1ZVZlcnNpb24gfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuICAuY29udGFpbmVyIHtcbiAgICB3aWR0aDogMTAwJTtcbiAgICBoZWlnaHQ6IDIwdmg7XG4gICAgYm9yZGVyOiAxcHggc29saWQgIzAwMDtcbiAgfVxuPC9zdHlsZT4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

<script setup lang="ts">
import { ref, version as vueVersion } from 'vue'
import { version as EpVersion } from 'element-plus'
import { ElementPlus } from '@element-plus/icons-vue'
</script>

<template>
  <p>
    父元素容器 v-loading="true"，但 el-select 的下拉箭头仍能点击交互。
  </p>
	<div class="container" v-loading="true" element-loading-background="rgba(255, 255, 0, 0.3)">
    <el-select></el-select>
  </div>
  <p>
    <el-icon color="var(--el-color-primary)"><ElementPlus /></el-icon>
    Element Plus {{ EpVersion }} + Vue {{ vueVersion }}
  </p>
</template>

<style>
  .container {
    width: 100%;
    height: 20vh;
    border: 1px solid #000;
  }
</style>

### What is Expected?

When the container is v-loading=true, the drop-down arrow of el-select should not be interactive.
容器在 v-loading=true 的情况下，el-select 的下拉箭头应不能交互。

### What is actually happening?

When the container is v-loading=true, the drop-down arrow of el-select can still be clicked.
容器在 v-loading=true 的情况下，el-select 的 下拉箭头仍能点击。

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by Simon-He95**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix: #10225

### CODE REVIEW

**Comment by holazz** [comment]
The issue is caused by #5822, I'm going to revert it.

**Comment by Simon-He95** [comment]
@holazz revert it may be caused that element can be clicked by loading.
I think just let the inner style to inherit the parent style `pointer-event:none`

**Comment by holazz** [comment]
> @holazz revert it may be caused that element can be clicked by loading. I think just let the inner style to inherit the parent style `pointer-event:none`

Using `pointer-event:none` is not a good idea because we cannot restrict how the user can define styles, such as this [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHYtbG9hZGluZz1cInRydWVcIj5cbiAgICA8ZWwtYnV0dG9uIHN0eWxlPVwicG9pbnRlci1ldmVudHM6IGFsbDtcIiB0eXBlPVwicHJpbWFyeVwiPiBCdXR0b24gPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

**Comment by Simon-He95** [comment]
> > @holazz revert it may be caused that element can be clicked by loading. I think just let the inner style to inherit the parent style `pointer-event:none`
> 
> Using `pointer-event:none` is not a good idea because we cannot restrict how the user can define styles, such as this [demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHYtbG9hZGluZz1cInRydWVcIj5cbiAgICA8ZWwtYnV0dG9uIHN0eWxlPVwicG9pbnRlci1ldmVudHM6IGFsbDtcIiB0eXBlPVwicHJpbWFyeVwiPiBCdXR0b24gPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

You are right, then we need to prevent from the event itself

**Pull request closed without merging**
