### PR TITLE
build(element-plus): [gulp] delete needless task

### PR DESCRIPTION
**Pull request by Valar103769**

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@Valar103769 May I ask what is the purpose for doing this? /cc @sxzz

**Comment by Valar103769** [comment]
> @Valar103769 May I ask what is the purpose for doing this? /cc @sxzz

Because he's invalid.

**Comment by sxzz** [comment]
@Valar103769 抱歉，可能没懂你的意思。创建 `epOutput` 在某些情况下，`copyFiles` 可能会先执行，没有目录会导致出错。

**Comment by sxzz** [comment]
That's why unit test failed.
https://github.com/element-plus/element-plus/runs/4836045967?check_suite_focus=true

**Pull request closed without merging**
