### PR TITLE
fix(table): remove tooltip when the component destroyed

### LINKED ISSUE #1236: [bug report] the column of the table component opens show overflow toolkit, and the toolkit does not disappear after the mouse clicks the cell to jump the route.
### Element Plus version
1.0.1-beta.23

### OS/Browsers version
chrome 87.0.4280.88

### Vue version
3.0.5

### Reproduction Link
https://github.com/mingtianyihou33/element-plus-table-tootip

### Steps to reproduce
1. 启动项目后
2.在home界面能看的table，然后点击地址列的某一项将会跳转到about页后会发现tooltip没有消失

### What is Expected?
跳转路由后tooltip消失

### What is actually happening?
跳转路由后tooltip还存在，且没法移除

### PR DESCRIPTION
**Pull request by BeADre**
fix #1236 

I think this is just a temporary solution and maybe need a better method

### CODE REVIEW

**Review by justwiner — APPROVED** [review]

**Comment by mingtianyihou33** [comment]
合并失败了吗？

**Comment by BeADre** [comment]
@zazzaz @justwiner  The check seems to have failed. what should I do？

**Comment by zazzaz** [comment]
@BeADre Because there's some modification in the test config, would you please rebase the current dev branch and submit a new PR to make it work?

**Comment by BeADre** [comment]
@zazzaz  done

**Review by zazzaz — APPROVED** [review]

**Comment by zazzaz** [comment]
Thanks

**Pull request merged**
