### PR TITLE
feat(components): [select] add label-in-value prop

### PR DESCRIPTION
**Pull request by Simon-He95**
#10048

### CODE REVIEW

**Comment by sxzz** [comment]
Could you please rename the title of your PRs? Please follow the rules:
https://element-plus.org/en-US/guide/commit-examples.html

**Comment by Simon-He95** [comment]
of course :)

**Comment by Simon-He95** [comment]
@holazz can you help me review the code?

**Comment by Simon-He95** [comment]
@sxzz can you help me review the code?

**Comment by holazz** [comment]
see https://github.com/element-plus/element-plus/discussions/10048#discussioncomment-3883351

**Pull request closed without merging**
