### PR TITLE
[WIP]fix(var): use css var for border-color

### LINKED ISSUE #4968: [Feature Request] request support custom border color for button button-group and button-radio with css vars
### Existing Component
Yes

### Component Name
radio-button

### Description
Currently, `.el-radio-button__inner` set fixed color for border, what about add a css var to custom border-color?

If you think it a good idea,I am glad to contribute it.

### PR DESCRIPTION
**Pull request by ishowman**
close #4968

fix #4968

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]
LGTM. Thanks.

**Comment by YunYouJun** [comment]
Any other change for `WIP`?

I think we can not set `border: var(--el-button-border-color)` directly.
Because `border-color` will override `$border-base`. (So we can not have `border-width` `border-style`).

And can you screenshot for me, what does this modification improve?

**Comment by ishowman** [comment]
> Here are screenshot of radio-group of our team design. If I want to achieve base on `el-radio-group`, I need to custom it's `border-color` & `border-radius`.  @YunYouJun 

image
image

**Comment by YunYouJun** [comment]
I think we should use `border-color: var(--el-button-border-color, var(--el-border-color-base))`.
Try it out if it meets your needs, and if you can, take a screenshot of your effect and modify your PR.

**Pull request closed without merging**
