### PR TITLE
fix(components): [el-input] icon center

### LINKED ISSUE #4854: [Bug Report] ElIcon 样式问题
### Element Plus version
1.2.0-beta.6

### OS/Browsers version
Chrome 96.0.4664.93

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/kailong321200875/pen/dyVvmRv

### Steps to reproduce
el-icon 图标没有垂直居中，需要给 el-icon 加上 el-input--icon 的类名才能居中

### What is Expected?
能不能内置 类名，而不需要手动去添加这个类名

### What is actually happening?
能不能内置 类名，而不需要手动去添加这个类名

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #4854

### CODE REVIEW

**Comment by Alanscut** [comment]
@YunYouJun I didn't pay attention to your reply. I added a centering style, and if it doesn’t fit, I’ll turn off pr.

**Comment by YunYouJun** [comment]
We can discuss it.

If we provide the default center style, it seems difficult for users to customize left alignment in the template.

Do you have any other ideas?

**Comment by Alanscut** [comment]
Only set the vertical center, I think that the vertical direction generally needs to be centered.

**Comment by Alanscut** [comment]
I didn't think of a better way, because we have provided two options, one is to use attributes, which has a centering style by default; the other is to use slots, and the style is customized by the user.

**Pull request closed without merging**
