### PR TITLE
refactor(components): el-dropdown icon

### PR DESCRIPTION
**Pull request by adaex**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
image
@adaex Looks quite weird 🤣

**Comment by adaex** [comment]
> @adaex Looks quite weird 🤣


The` el-icon` component has a default `font-size` that doesn't inherit directly from the parent's size. I need to take care of this a little extra, now updated. 🙇

**Comment by JeremyWuuuuu** [comment]
@adaex 
image
Don't forget about the small sizes

**Review by imswk — APPROVED** [review]
LGTM

**Review by adaex — COMMENTED** [review]
PTAL @JeremyWuuuuu 
https://preview-3517-element-plus.surge.sh/en-US/component/dropdown.html

**Pull request merged**
