### PR TITLE
fix(components): [el-tooltip]enable enter and space eventDefault(#13708)

### LINKED ISSUE #13708: [Component] el-popover trigger 拦截了空格和回车事件
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `chrome 115`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-popper`
- `el-popconfirm`
- `el-tooltip`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQge3JlZn0gZnJvbSAndnVlJ1xuY29uc3QgY291bnQgPSByZWY8bnVtYmVyPigwKVxuY29uc3QgZW50ZXJDb3VudCA9IHJlZjxudW1iZXI+KDApXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtcG9wb3ZlciB0cmlnZ2VyPVwiY2xpY2tcIiB3aWR0aD1cIjIwMFwiPlxuICAgIDx0ZW1wbGF0ZSAjZGVmYXVsdD5cbiAgICAgIOS9oOWlvVxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlICNyZWZlcmVuY2U+XG4gICAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImNvdW50KytcIiAgQGtleXVwLmVudGVyPVwiZW50ZXJDb3VudCsrXCI+5omT5byAcG9wb3ZlcjwvZWwtYnV0dG9uPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtcG9wb3Zlcj5cbiAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJjb3VudCsrXCIgIEBrZXl1cC5lbnRlcj1cImVudGVyQ291bnQrK1wiPuaZrumAmuaMiemSruinpuWPkeWbnui9pjwvZWwtYnV0dG9uPlxuICA8ZGl2PuaMiemSrmNsaWNr5qyh5pWwOiB7e2NvdW50fX08L2Rpdj5cbiAgPGRpdj7lm57ovaZlbnRlcuasoeaVsDoge3tlbnRlckNvdW50fX08L2Rpdj5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce

使用键盘上的TAB选中按钮, 敲下回车触发回车事件, 此时按钮无法正常触发click事件

### What is Expected?

回车和空格能够正常触发click事件

### What is actually happening?

当鼠标点击时可以触发click, 回车和空格不行

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by ly-chn**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 952c8d5</samp>

Removed `e.preventDefault()` from `handleFocus` in `trigger.vue` to fix tooltip bug on keyboard focus.

## Related Issue

Fixes #13708 .

### <samp>🤖 Generated by Copilot at 952c8d5</samp>

* Remove `e.preventDefault()` from `handleFocus` method to fix tooltip bug on focus ([link](https://github.com/element-plus/element-plus/pull/13709/files?diff=unified&w=0#diff-ac4515be6324f53b4399b0196ca4ea51fe7b52640849b395a1ca4ab22dd5fa10L90))

### CODE REVIEW

**Comment by ly-chn** [comment]
对于这行代码, 我没能通过之前的commit message找到具体作用, 也没能想到具体作用, 认为不必与鼠标事件区别对待

**Comment by btea** [comment]
@ly-chn Can you explain why it was removed?

**Comment by ly-chn** [comment]
I'm not good at English, so I asked Claude to help me with the following translation:

I reviewed commit af732b124bdb5c57e45688c07fcb8cf72e44a15a which added e.preventDefault() without explaining the rationale. I'm unable to see any positive effects of this change. However, testing for issue #13708 (https://github.com/element-plus/element-plus/issues/13708) shows two potential negative impacts:

1. Hitting enter on buttons prevents click events from firing, even when trigger is set to hover. This breaks enter/space key support.
2. Comments in issue #13708 also indicate this causes input boxes in popovers to not properly respond to input events.

In summary, I'm unable to determine the motivation for the e.preventDefault() change in the commit, and testing shows it may introduce bad UX by breaking keyboard support in certain situations. Please let me know if I have summarized my findings clearly, or if you need any clarification!

下面是一些中文的辅助说明: 
1. 当popover的reference为input组件时, 无法在input中正常输入空格

2. 假设一个场景: reference为button, trigger为hover, 需求为用户点击按钮时触发指定操作, 用户鼠标悬浮时给出一些提示信息
. 那么此时用户如果只有键盘没有鼠标, 理想情况应当是敲击空格或回车来触发按钮点击事件. 正常的按钮也是可以触发的. 而popover阻止了空格和回车的默认事件, 将导致无法正常触发按钮点击事件. 

3. 我知道解决这些问题可以通过自己写阻止冒泡来实现, 但我更期望element-plus能直接支持. 至于为什么之前的pr中加上了这行代码, 我并不知晓原因

**Comment by ly-chn** [comment]
@btea plz

**Comment by btea** [comment]
In fact, I'm not sure why the default keyboard events are blocked here. Do you know? @tolking @ryuhangyeong

**Pull request closed without merging**
