### PR TITLE
fix(popover): v-popover can't work

### PR DESCRIPTION
**Pull request by XingXiaoWu**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
This fix is legit but it could produce this warning message:
```
[Vue warn]: Component "ElPopover" has already been registered in target app. 
```

So we need to make popover directive installation function individually.
Can you do that?

**Comment by XingXiaoWu** [comment]
> So we need to make popover directive installation function individually.
> Can you do that?

let me try

**Comment by XingXiaoWu** [comment]
> This fix is legit but it could produce this warning message:
> 
> ```
> [Vue warn]: Component "ElPopover" has already been registered in target app. 
> ```
> 
> So we need to make popover directive installation function individually.
> Can you do that?

I refer to ElLoading, the components have directive only in plugins, not components

https://github.com/element-plus/element-plus/blob/98714cc3f158fc459f74b1dc9d65ce39d86c7579/packages/element-plus/index.ts#L220-L226

**Comment by XingXiaoWu** [comment]
> This fix is legit but it could produce this warning message:
> 
> ```
> [Vue warn]: Component "ElPopover" has already been registered in target app. 
> ```
> 
> So we need to make popover directive installation function individually.
> Can you do that?

I have refer to InfiniteScroll, only in `plugins` is OK

https://github.com/element-plus/element-plus/blob/98714cc3f158fc459f74b1dc9d65ce39d86c7579/packages/element-plus/index.ts#L220-L226

**Review by iamkun — APPROVED** [review]
LGTM

**Comment by XingXiaoWu** [comment]
Sorry, I don't quite understand what 'regression' label means.
Can someone explain this to me？：）

**Comment by XingXiaoWu** [comment]
Sorry, I don't quite understand what 'regression' label means.
It means I need to test it in next version and feedback? 
I'll do that if I need to
@JeremyWuuuuu

**Comment by JeremyWuuuuu** [comment]
Nah, regression means something we did right in the past, but we broke it. So I marked it as a regression. This PR is meant to fix it. No worries, only for categorization.

**Comment by JeremyWuuuuu** [comment]
But also I found the functionalities isn't working I will fix it soon. I'll make a follow up issue to track that.

**Comment by XingXiaoWu** [comment]
Ah, does it mean that I can't fix in this pr? it's normal for me to test the function in website:play. Are there any other test steps? can you tell me that I will pay attention to add this step in the future?

**Comment by JeremyWuuuuu** [comment]
Well, the simplest way for fixing a bug locally is what you did before, which loads all dependencies you need to work.
The bug itself should be individually tracked since it was not the same type bug compares to this one.

**Comment by XingXiaoWu** [comment]
Thx, I will notice these steps next time.

**Pull request merged**
