### PR TITLE
docs(components): add direction api description for segmented

### PR DESCRIPTION
**Pull request by thinkasany**
补充一下api描述

add api description.

image

### CODE REVIEW

**Review by warmthsea — COMMENTED** [review]
Can be placed at the bottom.

image

**Comment by thinkasany** [comment]
> Can be placed at the bottom.
> 


done

**Review by warmthsea — APPROVED** [review]
Thanks, we overlooked this in #18733

**Review by btea — APPROVED** [review]
Thanks!

**Pull request merged**
