### PR TITLE
fix(components): [collapse] fix accessibility issues

### PR DESCRIPTION
**Pull request by Karolis-Stoncius**
Using tab related aria attributes results in accessibility issues

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at fbef87b</samp>

The pull request improves the accessibility and semantics of the `collapse` component by using `<button>` elements instead of `<div>` elements for the collapse item headers, and by adjusting the `role` and `aria-` attributes accordingly. It also refactors some code and adds some CSS styles to maintain the appearance of the component.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at fbef87b</samp>

*  Replace `<div>` elements with `<button>` elements for collapse item headers to improve accessibility and semantics ([link](https://github.com/element-plus/element-plus/pull/13832/files?diff=unified&w=0#diff-c6f05c610009ff1fb4cee40b878ec64e16be5dd7f4eedc0ef32769abc43dc63eL3-R26), [link](https://github.com/element-plus/element-plus/pull/13832/files?diff=unified&w=0#diff-b2a0d1422dc002e134a9bca7ba6fe1541713d474104f6e85f97001ea000c0c92R21-R23))
*  Remove unnecessary `role` and `aria` attributes from collapse component and collapse item content ([link](https://github.com/element-plus/element-plus/pull/13832/files?diff=unified&w=0#diff-c6f05c610009ff1fb4cee40b878ec64e16be5dd7f4eedc0ef32769abc43dc63eL3-R26), [link](https://github.com/element-plus/element-plus/pull/13832/files?diff=unified&w=0#diff-7e90df7d5118ca68b4bd2f623be310b1f50860ef53091c2d17a01661ae5e66d7L2-R2))
*  Move code from `collapse.vue` to `collapse-item.vue` to simplify component structure ([link](https://github.com/element-plus/element-plus/pull/13832/files?diff=unified&w=0#diff-7e90df7d5118ca68b4bd2f623be310b1f50860ef53091c2d17a01661ae5e66d7L2-R2))

### CODE REVIEW

**Comment by btea** [comment]
I have limited knowledge of the content related to a11y and may need you to review it. @tolking

**Review by tolking — APPROVED** [review]
LGTM

**Review by btea — APPROVED** [review]

**Comment by btea** [comment]
@Karolis-Stoncius Based on the problem with #14304, perhaps we should switch back to `div`.

**Comment by Karolis-Stoncius** [comment]
> @Karolis-Stoncius Based on the problem with #14304, perhaps we should switch back to `div`

It seems like it's an issue with `el-form`, because [this happens if I add a simple `<button>` as well](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLWZvcm0gYWN0aW9uPVwiaHR0cHM6Ly9nb29nbGUuY29tXCI+XG4gIDxidXR0b24+Q2xpY2s8L2J1dHRvbj5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by btea** [comment]
Yeah, this is a feature of form, but changing the `div` to a `button` will cause this kind of problem, so this may be a breaking change for previous users and cause problems with 14034.

**Comment by Karolis-Stoncius** [comment]
> Yeah, this is a feature of form, but changing the `div` to a `button` will cause this kind of problem, so this may be a breaking change for previous users and cause problems with 14034.

Yeah, you're right. Changing it back to `div` will bring back the a11y issues tho. Adding `role="button"` seems to fix it https://stackoverflow.com/a/66294321

**Comment by btea** [comment]
Could you create a new PR to fix it? Thank you!

**Pull request merged**
