### PR TITLE
feat(components): [upload] added index parameter to default slot

### PR DESCRIPTION
**Pull request by zhuchaoling**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
Can you describe your usage scenario?

**Comment by zhuchaoling** [comment]
> Can you describe your usage scenario?  

自定义文件样式时，删除文件有点麻烦。传index后，直接splice，很ok

**Comment by btea** [comment]
Perhaps the relevant parameters in the document also need to be updated synchronously.

**Comment by zhuchaoling** [comment]
> Perhaps the relevant parameters in the document also need to be updated synchronously.

Do I need to update the document, or will you do the update?

**Comment by btea** [comment]
Yes, you can update it.

**Comment by zhuchaoling** [comment]
> slot

updatedupdated

**Comment by zhuchaoling** [comment]
> It seems you haven't committed any new code.

Oh sorry, I forgot to push the code. It's okay now.

**Comment by btea** [comment]
Since `index` is not passed here, the `file` slot should not get the corresponding value.

https://github.com/element-plus/element-plus/blob/7648011303b49814557b3a29e890c1563e33c461/packages/components/upload/src/upload.vue#L44

**Comment by zhuchaoling** [comment]
> Since `index` is not passed here, the `file` slot should not get the corresponding value.
> 
> https://github.com/element-plus/element-plus/blob/7648011303b49814557b3a29e890c1563e33c461/packages/components/upload/src/upload.vue#L44

okay already updated

**Comment by zhuchaoling** [comment]
> Since `index` is not passed here, the `file` slot should not get the corresponding value.
> 
> https://github.com/element-plus/element-plus/blob/7648011303b49814557b3a29e890c1563e33c461/packages/components/upload/src/upload.vue#L44

Many thanks for your review.

**Comment by btea** [comment]
@zhuchaoling  Hello, it seems that you have taken the initiative to close this PR?

**Comment by zhuchaoling** [comment]
reopen，Many thanks for your check.

**Review by btea — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Pull request merged**
