### PR TITLE
fix(types): packing unexpected types

### LINKED ISSUE #19413: [Build] [select] 2.9.0+版本配合vite-plugin-dts打包时el-selefct无法生成.d.ts文件，旧版本可以
Bug Type: **`Build`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.9.1`
- Browser / OS: `Chrome 131.0.6778.205`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/p/devbox/vq455h)

### Steps to reproduce

1.打开复现链接，packages文件中包含select、form以及button三个组件，分别基于el-select、el-form以及el-button封装的示例；
2.执行npm run build，根目录生成一个dist文件夹，里面包含button和form的.d.ts文件，缺少select.d.ts文件；
3.经排查，element-plus 2.9.0+版本会有此问题，其他版本无问题，期待修复；

### What is Expected?

el-select组件打包时正常构建出类型文件

### What is actually happening?

el-select打包时正常构建出类型文件

### Additional comments

相关依赖：element-plus，vite-plugin-dts

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #19413

element-plus/es/components/select/src/select.vue.d.ts  815k  => 20k

### CODE REVIEW

**Comment by tolking** [comment]
I do not quite understand why this change is needed. It seems that our current types can be generated and used normally.

For the secondary encapsulated types, it seems that they can also be generated normally through vue-tsc. Is this perhaps a problem with vite-plugin-dts?

**Comment by btea** [comment]
I'm not sure exactly where the problem is, but version 2.9.0 is much larger than version 2.8.8.
|2.9.0|2.8.8|
|-----|-----|
| image | image|

For example, in 2.9.0, the vue.d.ts file has more than 10,000 lines, while 2.8.8 has only more than 200 lines.

element-plus/es/components/select/src/select.vue.d.ts 815k(2.9.0) => 20k(2.8.8)

**Comment by tolking** [comment]
Looks like it might be caused by using `defineExpose` and `Ref` together, now the Ref is the entire type, not just the reference type.

Perhaps we can pass a generic type to defineExpose

```ts
defineExpose<{
  popperRef: Ref<PopperInstance | undefined>
  contentRef: Ref<TooltipContentInstance | undefined>
  isFocusInsideContent: (event?: FocusEvent) => boolean | undefined
  updatePopper: () => void
  onOpen: (event?: Event) => void
  onClose: (event?: Event) => void
  hide: () => void
}>({
// ...
})
```

WDYT

**Comment by btea** [comment]
Great, I tried it and it really works.  👍 
But I don't understand why?

**Review by tolking — APPROVED** [review]

**Comment by btea** [comment]
The modifications to the mention component and transfer component are also quite obvious.

**Pull request merged**
