### PR TITLE
fix(components): [el-select] label text beyond hiding（#5861）

### LINKED ISSUE #5861: [Bug Report] el-select  多选状态并且size为small时样式错乱问题
### Element Plus version
2.0.1

### OS/Browsers version
Google Chrome 版本 97.0.4692.99

### Vue version
3.2.30

### Reproduction Link
https://codepen.io/sunjianxu/pen/WNXpOvN

### Steps to reproduce
1. select为多选状态且为
2. size 为 small
3. 文字长度大于十个字符
4. 选中后文字会遮罩住
5. filterable：true 时，选中时高度会被撑高

### What is Expected?
1. 文字不被遮罩住或者文字超出长度显示...
2. filterable：true 时，选中时高度不被撑高，保持样式统一

### What is actually happening?
select 为多选状态并且size是small 时，选中时的文字样式会被遮罩住
filterable：true 时，选中时高度会被撑高

### PR DESCRIPTION
**Pull request by imswk**
fix #5861
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sunjianxu** [comment]
size 为small 时，高度会被突然撑高，样式挺难看的，感觉不统一

**Comment by imswk** [comment]
>  size 为small 时，高度会被突然撑高，样式挺难看的，感觉不统一

This is my local. Please describe your needs in detail.
image

**Comment by sunjianxu** [comment]
> >  size 为small 时，高度会被突然撑高，样式挺难看的，感觉不统一
> 
> This is my local. Please describe your needs in detail. image

filterable：true 时，选中el-select height 会被撑高
问题重现链接：https://codepen.io/sunjianxu/pen/WNXpOvN

**Comment by kooriookami** [comment]
Fixed

**Pull request closed without merging**
