### PR TITLE
fix(components): [radio] tab access style

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## Description

Applies styles to radio buttons when accessed as tabs.

If you want to activate a radio button, just access the tab and press the space key.

image

## What is Expected?

Applies styles to radio buttons when accessed as tabs.

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8xXCIgbGFiZWw9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8xXCIgbGFiZWw9XCIyXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDI8L2VsLXJhZGlvPlxuICA8L2Rpdj5cbiAgPGRpdj5cbiAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMlwiIGxhYmVsPVwiMVwiPk9wdGlvbiAxPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMlwiIGxhYmVsPVwiMlwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgPC9kaXY+XG4gIDxkaXY+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjFcIiBzaXplPVwic21hbGxcIj5PcHRpb24gMTwvZWwtcmFkaW8+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjJcIiBzaXplPVwic21hbGxcIj5PcHRpb24gMjwvZWwtcmFkaW8+XG4gIDwvZGl2PlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8zXCIgbGFiZWw9XCIxXCIgc2l6ZT1cInNtYWxsXCIgZGlzYWJsZWRcbiAgICAgID5PcHRpb24gMTwvZWwtcmFkaW9cbiAgICA+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjJcIiBzaXplPVwic21hbGxcIiBkaXNhYmxlZFxuICAgICAgPk9wdGlvbiAyPC9lbC1yYWRpb1xuICAgID5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCByYWRpbzEgPSByZWYoJzEnKVxuY29uc3QgcmFkaW8yID0gcmVmKCcxJylcbmNvbnN0IHJhZGlvMyA9IHJlZignMScpXG48L3NjcmlwdD5cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy03NzUyLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctNzc1Mi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWUvZGlzdC9pbmRleC5taW4ubWpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJlbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTc3NTItZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gIH0pXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctNzc1Mi1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

## What is actually happening?

No style applied to radio buttons when accessed as tabs.

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8xXCIgbGFiZWw9XCIxXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDE8L2VsLXJhZGlvPlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8xXCIgbGFiZWw9XCIyXCIgc2l6ZT1cImxhcmdlXCI+T3B0aW9uIDI8L2VsLXJhZGlvPlxuICA8L2Rpdj5cbiAgPGRpdj5cbiAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMlwiIGxhYmVsPVwiMVwiPk9wdGlvbiAxPC9lbC1yYWRpbz5cbiAgICA8ZWwtcmFkaW8gdi1tb2RlbD1cInJhZGlvMlwiIGxhYmVsPVwiMlwiPk9wdGlvbiAyPC9lbC1yYWRpbz5cbiAgPC9kaXY+XG4gIDxkaXY+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjFcIiBzaXplPVwic21hbGxcIj5PcHRpb24gMTwvZWwtcmFkaW8+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjJcIiBzaXplPVwic21hbGxcIj5PcHRpb24gMjwvZWwtcmFkaW8+XG4gIDwvZGl2PlxuICA8ZGl2PlxuICAgIDxlbC1yYWRpbyB2LW1vZGVsPVwicmFkaW8zXCIgbGFiZWw9XCIxXCIgc2l6ZT1cInNtYWxsXCIgZGlzYWJsZWRcbiAgICAgID5PcHRpb24gMTwvZWwtcmFkaW9cbiAgICA+XG4gICAgPGVsLXJhZGlvIHYtbW9kZWw9XCJyYWRpbzNcIiBsYWJlbD1cIjJcIiBzaXplPVwic21hbGxcIiBkaXNhYmxlZFxuICAgICAgPk9wdGlvbiAyPC9lbC1yYWRpb1xuICAgID5cbiAgPC9kaXY+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCByYWRpbzEgPSByZWYoJzEnKVxuY29uc3QgcmFkaW8yID0gcmVmKCcxJylcbmNvbnN0IHJhZGlvMyA9IHJlZignMScpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by Giwayume** [comment]
Hey @ryuhangyeong this was already fixed & merged in this PR:

https://github.com/element-plus/element-plus/pull/7563

**Comment by ryuhangyeong** [comment]
@Giwayume

thank you for telling me. The old method is more usable. I will close the current issue.

**Comment by ryuhangyeong** [comment]
@Giwayume 

image

hello. Some comments before closing this issue.

In my current situation, it's not clear exactly where the tab focus is pointing, which is confusing.

image

But for my Pull Request, it was clear where exactly the tab focus was, so I thought it would be a better way. Could you please review the comments?

**Comment by Giwayume** [comment]
I'm guessing you figured it out

**Pull request closed without merging**
