### PR TITLE
fix(components): [select-v2] should make input blurred when trigger select

### LINKED ISSUE #8353: [Bug Report] [Component] [select-v2] <el-select-v2 />单选模式下选完后依旧是focus状态
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.20`
- Element Plus Version: `2.2.6`
- Browser / OS: `macOS 11.2.3`
- Build Tool: `Vue CLI`

### Related Component

- `el-select-v2`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IHN0eWxlPVwiZmxleDogYXV0b1wiPlxuICAgIDxkaXY+XG4gICAgICA8ZWwtc2VsZWN0LXYyXG4gICAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgICA6b3B0aW9ucz1cIm9wdGlvbnNcIlxuICAgICAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBzZWxlY3RcIlxuICAgICAgICBzdHlsZT1cIndpZHRoOiAyNDBweDsgdmVydGljYWwtYWxpZ246IG1pZGRsZVwiXG4gICAgICAgIGZpbHRlcmFibGVcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCBpbml0aWFscyA9IFsnYScsICdiJywgJ2MnLCAnZCcsICdlJywgJ2YnLCAnZycsICdoJywgJ2knLCAnaiddXG5cbmNvbnN0IHZhbHVlMSA9IHJlZihbXSlcbmNvbnN0IHZhbHVlMiA9IHJlZignJylcbmNvbnN0IHZhbHVlMyA9IHJlZihbXSlcbmNvbnN0IG9wdGlvbnMgPSBBcnJheS5mcm9tKHsgbGVuZ3RoOiAxMDAwIH0pLm1hcCgoXywgaWR4KSA9PiAoe1xuICB2YWx1ZTogYE9wdGlvbiAke2lkeCArIDF9YCxcbiAgbGFiZWw6IGAke2luaXRpYWxzW2lkeCAlIDEwXX0ke2lkeH1gLFxufSkpXG48L3NjcmlwdD5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

add filterable props

### What is Expected?

选完值后input不再保持focus状态，并且显示内容颜色正常

### What is actually happening?

选完值后，依旧是focus状态，并且显示内容颜色为灰色，只有再次点击外边，才会正常

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by webfansplz**
Please make sure these boxes are checked before submitting your PR, thank you!

Close #8353 

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
@webfansplz Hi, nice to meet you in ep. Maybe we try to save the `focus` state after selection according to the `w3c standard`, and perform `blur` processing on the internal input. The effect can refer to `select`.

**Comment by webfansplz** [comment]
> @webfansplz Hi, nice to meet you in ep. Maybe we try to save the `focus` state after selection according to the `w3c standard`, and perform `blur` processing on the internal input. The effect can refer to `select`.

https://github.com/element-plus/element-plus/blob/9da7564856e1003fc811bd0e9788a6a50d482701/packages/components/select/src/useSelect.ts#L226

Nice meet you too,bro.  The `select v1 component` seems to triggered `element's blur` event when the `visible state` to be falsely directly, any better solutions in v2 ? Thanks .

**Comment by chenxch** [comment]
> > @webfansplz Hi, nice to meet you in ep. Maybe we try to save the `focus` state after selection according to the `w3c standard`, and perform `blur` processing on the internal input. The effect can refer to `select`.
> 
> https://github.com/element-plus/element-plus/blob/9da7564856e1003fc811bd0e9788a6a50d482701/packages/components/select/src/useSelect.ts#L226
> 
> Nice meet you too,bro. The `select v1 component` seems to triggered `element's blur` event when the `visible state` to be falsely directly, any better solutions in v2 ? Thanks .

Yes, this is an out-of-spec behavior, we are re-checking and planning to fix this part of the interaction in the near future. Maybe you can perform the `blur` operation on the `input`, but the `style` did not have the same effect as the `filterable` mode of v1.

**Comment by webfansplz** [comment]
> > > @webfansplz Hi, nice to meet you in ep. Maybe we try to save the `focus` state after selection according to the `w3c standard`, and perform `blur` processing on the internal input. The effect can refer to `select`.
> > 
> > 
> > https://github.com/element-plus/element-plus/blob/9da7564856e1003fc811bd0e9788a6a50d482701/packages/components/select/src/useSelect.ts#L226
> > 
> > Nice meet you too,bro. The `select v1 component` seems to triggered `element's blur` event when the `visible state` to be falsely directly, any better solutions in v2 ? Thanks .
> 
> Yes, this is an out-of-spec behavior, we are re-checking and planning to fix this part of the interaction in the near future. Maybe you can perform the `blur` operation on the `input`, but the `style` did not have the same effect as the `filterable` mode of v1.

Sorry to missing the spec behavior, close the PR which let the more experienced developers to fixed it 🫡.

**Pull request closed without merging**
