### PR TITLE
fix(components): [menu] fix infinite flicker after choosing subMenu

### LINKED ISSUE #8525: 横向的菜单,hover显示隐藏的闪动的BUG，在官方文档和自己项目中都存在该问题
### Discussed in https://github.com/element-plus/element-plus/discussions/8188

<div type='discussions-op-text'>

<sup>Originally posted by **wangrongding** June  8, 2022</sup>
当鼠标点击子菜单后，菜单开始闪动。

czxczxc

另外提不了issues了，因为选择框没有选项，选不了但是又是必填项。。。😅

image
</div>

### PR DESCRIPTION
**Pull request by ParkerFiend**
closed #8525, #8487

Please make sure these boxes are checked before submitting your PR, thank you!

- [ x ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ x ] Make sure you are merging your commits to `dev` branch.
- [ x ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by tolking** [comment]
Is not this equivalent to directly disabling the focus event?

**Comment by ParkerFiend** [comment]
@tolking Please review again.

**Comment by tolking** [comment]
same problem

You can test it yourself by pressing the Tab key.

**Comment by Giwayume** [comment]
From my understanding, sub menus can't be accessed today by keyboard, they only expand when you tab which is pointless if you have to switch to the mouse to start using it.

This is good enough for a quick patch for mouse users, proper keyboard implementation can come in later PR if needed (because it doesn't really exist today).

**Comment by ParkerFiend** [comment]
@tolking 
Well, Sorry for not considering all the usage scenarios.
I try to solve it in another way,
although I still wonder how this problem came about and disappeared.

**Comment by tolking** [comment]
@ParkerFiend You can disable focus events, and we will fix the A11y problem in the near future.

You can go back to the first time commit, or refer to

// line 205
```diff
- if (event.type === 'focus' && !event.relatedTarget) {
+ if (event.type === 'focus') {
```

The reason for the problem should be that focus event will be triggered when the ElTooltip closed.

**Comment by ParkerFiend** [comment]
@tolking Done.

**Review by tolking — APPROVED** [review]

**Comment by zkr12345644** [comment]
@tolking 我认为直接在tooltip过渡阶段直接使用pointer-event:none；禁用掉鼠标事件，会比现在这样更加合理。现在这样导致tab无法激活sub-menu菜单了

**Comment by tolking** [comment]
@zkr12345644 这也是一个临时的解决办法，接下来将尽快修复 A11y 功能

**Comment by wangrongding** [comment]
蹲一个

**Pull request merged**
