### PR TITLE
docs(components): [message-box] add description of props modal-class

### PR DESCRIPTION
**Pull request by vaebe**
- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 345687b</samp>

Add `modal-class` option to `message-box` component. This option lets users style the mask layer behind the message box with custom class names.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 345687b</samp>

* Add a new option `modal-class` to the `message-box` component to customize the mask layer class names ([link](https://github.com/element-plus/element-plus/pull/13161/files?diff=unified&w=0#diff-a32d736a39bf41ec94aa0c117332f90cdbd97ffcaf8574d006e76a0e1d542466R169))

### CODE REVIEW

**Comment by vaebe** [comment]
@btea Can you help review this PR? It is very simple and only adds description of props modal-class to the message-box component docs.

Thanks

**Comment by btea** [comment]
There are code conflicts that need to be resolved

**Comment by vaebe** [comment]
> There are code conflicts that need to be resolved

Thanks, this is probably too long, I resubmitted a PR (#17843) and I will close it

**Pull request closed without merging**
