### PR TITLE
fix: Cascader Unexpected display 'No Data'

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
fix #6739

**Comment by JeremyWuuuuu** [comment]
@chenxch Would you mind elaborate a little bit about why did you do changes like this? Just some thoughts would be good! Thanks!

**Comment by chenxch** [comment]
You can also see in the discussion on the issue that I have located that the update of `props.nodes` will not trigger `computed`, and traced up to find that adding nodes is added through the `appendChild` method of the `class store`, but I have never known why this would cause a two-way Binding's dependency collection fails, so nodes are passed through a destructuring method.

**Comment by JeremyWuuuuu** [comment]
@chenxch I see, seems like shallow watching issue related, since the `nodes` referencing object did not change it was considered as **untouched** so that the `computed` did not get re-triggered.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
As as temporary fix I think the change looks good, approving, BTW, if we can add some tests for ensuring this won't happen again it'd be just great, you can do that in an additional PR if you'd like that.

**Comment by chenxch** [comment]
I am also trying to read and understand the original design of this component, trying to solve more problems, and from the issue point of view, there are still some problems with this component.

**Pull request merged**
