### PR TITLE
feat(components): add the ability to append dialog to any element

### PR DESCRIPTION
**Pull request by Karolis-Stoncius**
BREAKING CHANGE :
"append-to" will override the "append-to-body" if defined

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 29c9a4b</samp>

This pull request adds a new feature to the Dialog component that allows users to customize the element that the Dialog appends to. It updates the component's documentation, script and template to support the new `append-to` attribute.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 29c9a4b</samp>

*  Add `appendTo` prop to Dialog component to allow users to specify which element the Dialog appends to ([link](https://github.com/element-plus/element-plus/pull/13819/files?diff=unified&w=0#diff-8e4884ffc45253766cb46796a84d2aeb1fb07f95966b3a4e2440f264948807b6R17-R23), [link](https://github.com/element-plus/element-plus/pull/13819/files?diff=unified&w=0#diff-e9f41878502088bc1f6f1f49029526fcd3fa71df716e6b4dd199947c046b469dL2-R2))
*  Modify Dialog component template to use `appendTo` prop as the target of the teleport directive and disable teleport if both `appendToBody` and `appendTo` are falsy ([link](https://github.com/element-plus/element-plus/pull/13819/files?diff=unified&w=0#diff-e9f41878502088bc1f6f1f49029526fcd3fa71df716e6b4dd199947c046b469dL2-R2))
*  Update Dialog component documentation to include the new `append-to` attribute and its usage ([link](https://github.com/element-plus/element-plus/pull/13819/files?diff=unified&w=0#diff-abbb3d078da77db6d9ad1eed9a9356891f9119733d8e8bb4fc8771e3429dc626R128))

### CODE REVIEW

**Comment by Karolis-Stoncius** [comment]
Can anyone review this @btea @ryuhangyeong @chenxch ?

**Comment by Karolis-Stoncius** [comment]
> IMO, `append-to-body` seems to be enough, can you explain the use case when you add this prop? 🤔

I'm fixing accessibility issues and when the dialog is appended to body `Document should not have more than one banner landmark` issue is raised. This happens because it's higher on the DOM than my main header with `role="banner"`. Adding `append-to` allows me to append the dialog somewhere else and avoid this issue.

**Comment by Karolis-Stoncius** [comment]
@btea if that's all right, could you review this and my other PR's 🙏

**Comment by btea** [comment]
> I'm fixing accessibility issues and when the dialog is appended to body `Document should not have more than one banner landmark` issue is raised. This happens because it's higher on the DOM than my main header with `role="banner"`. 

I don't seem to have encountered this situation, can you provide an example?

**Comment by Karolis-Stoncius** [comment]
> > I'm fixing accessibility issues and when the dialog is appended to body `Document should not have more than one banner landmark` issue is raised. This happens because it's higher on the DOM than my main header with `role="banner"`.
> 
> I don't seem to have encountered this situation, can you provide an example?

Couldn't reproduce it on `element-plus.run` so here's a github repo https://github.com/Karolis-Stoncius/element-plus-accessibility-test. I'm using axe devtool chrome extension to find accessibility issues

**Comment by Karolis-Stoncius** [comment]
@btea any updates on this?

**Comment by btea** [comment]
The test seems to be failing,

**Comment by xionglongxiang** [comment]
> [子window中的dialog，想弹出到父window](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuY29uc3QgdmlzaWJsZSA9IHJlZihmYWxzZSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtYnV0dG9uIEBjbGljaz1cIigpPT4ge1xuICAgIHZpc2libGU9dHJ1ZVxuICB9XCI+5pi+56S65by55qGGPC9lbC1idXR0b24+XG4gIDxocj5cbiAgPGVsLWRpYWxvZyB2LW1vZGVsPVwidmlzaWJsZVwiPlxuICAgIOaIkeaDs+W8ueWHuuWIsOeItndpbmRvd1xuICA8L2VsLWRpYWxvZz5cbiAgPGlmcmFtZSB3aWR0aD1cIjgwMFwiICBoZWlnaHQ9XCI2MDBcIiBzcmM9XCJodHRwczovL2VsZW1lbnQtcGx1cy5ydW4vI2V5SnpjbU12UVhCd0xuWjFaU0k2SWp4elkzSnBjSFFnYzJWMGRYQWdiR0Z1WnoxY0luUnpYQ0krWEc1cGJYQnZjblFnZXlCeVpXWXNJSFpsY25OcGIyNGdZWE1nZG5WbFZtVnljMmx2YmlCOUlHWnliMjBnSjNaMVpTZGNibWx0Y0c5eWRDQjdJSFpsY25OcGIyNGdZWE1nWlhCV1pYSnphVzl1SUgwZ1puSnZiU0FuWld4bGJXVnVkQzF3YkhWekoxeHVhVzF3YjNKMElIc2dSV3hsYldWdWRGQnNkWE1nZlNCbWNtOXRJQ2RBWld4bGJXVnVkQzF3YkhWekwybGpiMjV6TFhaMVpTZGNibHh1WTI5dWMzUWdiWE5uSUQwZ2NtVm1LQ2RJWld4c2J5QlhiM0pzWkNFbktWeHVZMjl1YzNRZ2RtbHphV0pzWlNBOUlISmxaaWhtWVd4elpTbGNiand2YzJOeWFYQjBQbHh1WEc0OGRHVnRjR3hoZEdVK1hHNGdJRHhvTVQ1N2V5QnRjMmNnZlgwOEwyZ3hQbHh1SUNBOFpXd3RZblYwZEc5dUlFQmpiR2xqYXoxY0lpZ3BQVDRnZTF4dUlDQWdJSFpwYzJsaWJHVTlkSEoxWlZ4dUlDQjlYQ0krNXBpKzU2UzY1Ynk1NXFHR1BDOWxiQzFpZFhSMGIyNCtYRzRnSUR4b2NqNWNiaUFnUEdWc0xXUnBZV3h2WnlCMkxXMXZaR1ZzUFZ3aWRtbHphV0pzWlZ3aVBseHVJQ0FnSU9hSWtlYURzK1c4dWVXSHV1V0lzT2VJdG5kcGJtUnZkMXh1SUNBOEwyVnNMV1JwWVd4dlp6NWNiaUFnUEdsbWNtRnRaU0IzYVdSMGFEMWNJamd3TUZ3aUlDQm9aV2xuYUhROVhDSTJNREJjSWlCemNtTTlYQ0pvZEhSd2N6b3ZMMlZzWlcxbGJuUXRjR3gxY3k1eWRXNHZJMlY1U25wamJVMTJVVmhDZDB4dVdqRmFVMGsyU1dwNGVsa3pTbkJqU0ZGbll6SldNR1JZUVdkaVIwWjFXbm94WTBsdVVucFlRMGtyV0VjMWNHSllRblpqYmxGblpYbENlVnBYV1hOSlNGcHNZMjVPY0dJeU5HZFpXRTFuWkc1V2JGWnRWbmxqTW14MlltbENPVWxIV25saU1qQm5Tak5hTVZwVFpHTmliV3gwWTBjNWVXUkRRamRKU0Zwc1kyNU9jR0l5TkdkWldFMW5XbGhDVjFwWVNucGhWemwxU1Vnd1oxcHVTblppVTBGdVdsZDRiR0pYVm5Wa1F6RjNZa2hXZWtveGVIVmhWekYzWWpOS01FbEljMmRTVjNoc1lsZFdkV1JHUW5Oa1dFMW5abE5DYldOdE9YUkpRMlJCV2xkNGJHSlhWblZrUXpGM1lraFdla3d5YkdwaU1qVjZURmhhTVZwVFpHTmliSGgxV1RJNWRXTXpVV2RpV0U1dVNVUXdaMk50Vm0xTFEyUkpXbGQ0YzJKNVFsaGlNMHB6V2tORmJrdFdlSFZaTWpsMVl6TlJaMlJ0YkhwaFYwcHpXbE5CT1VsSVNteGFhV2h0V1ZkNGVscFRiR05pYW5kMll6Sk9lV0ZZUWpCUWJIaDFXRWMwT0dSSFZuUmpSM2hvWkVkVksxaEhOR2RKUkhodlRWUTFOMlY1UW5Sak1tTm5abGd3T0V3eVozaFFiSGgxU1VOQk9GcFhkM1JaYmxZd1pFYzVkVWxGUW1waVIyeHFZWG94WTBscFozQlFWRFJuWlRGNGRVbERRV2RKU0Zwd1l6SnNhV0pIVlRsa1NFb3hXbFo0ZFVsRFFqbFlRMGtyTlhCcEt6VTJVelkxWW5rMU5YRkhSMUJET1d4aVF6RnBaRmhTTUdJeU5DdFlSelJuU1VSNGIyTnFOV05pYVVGblVFZFdjMHhYVW5CWlYzaDJXbmxDTWt4WE1YWmFSMVp6VUZaM2FXUnRiSHBoVjBweldsWjNhVkJwUVRoTU1sWnpURmRTY0ZsWGVIWmFlalZqWW1sQloxQkhiRzFqYlVaMFdsTkNNMkZYVWpCaFJERmpTV3BuZDAxR2QybEpRMEp2V2xkc2JtRklVVGxZUTBreVRVUkNZMGxwUW5wamJVMDVXRU5LYjJSSVVuZGplbTkyVERKV2MxcFhNV3hpYmxGMFkwZDRNV041Tlhsa1Z6UjJTVEpXTlZOdWNHcGlWVEV5VlZab1EyUXdlSFZYYWtaaFZUQnJNbE5YY0RSbGJHdDZVMjVDYWxOR1JtNVpla3BYVFVkU1dWRlhaR2xTTUZveFYyNXZlRmt3YkhWVmJuQlpVVEJyY2xkRll6RmpSMHBaVVc1YWFtSnNSbTVhV0d4RFpWWndXRmRZVGtwVFJuQnpXVEkxVDJOSFNYbE9SMlJhVjBVeGJscEhOVmRpUmxwMFZtNXNhazF0ZURKWmJXeERUMVZzU0ZkdWJHbE5ha0p1VTJwT1lVMVdjRlJhUjA1cFlsZDRNRmt3WXpWbFYxSkVVV3BrU2xOR2NITlpNalZQWTBkSmVVNUhaRnBYUlRGdVYyeG9RMVl4Y0ZsVGJuQm9WbnBzTVZOVlozZGFNWEIxVTI1YWFWVXdSblZYYkdRMFlrZEtXRlp1Vm10UmVrWXpXV3RvVjJWcmIzaGxTRlpvVm5wR00xbHFUa3ROUld4Sll6SmtVMVl6YUhOWmJHUlhaRmRTUjFGdVRtdFhSVEZ1V214T1EySlhUblJQV0ZKS1VUSlNRbGRzWkRSaVIwcFlWbTVXYTFGNlJqTlphMmhYWld0M2VXSkhjR2xOYWxZMlZFWm9ZVTFXY0ZSYVIwNXBZa2hvTVZkVVNUVmtWMDE2VlZka2FWZEZOWFZUVlZGM1dqSk9kRlp0TVV4Uk1sSktWMnhrTkdNeVNqVlJiR2hwVFRCd2VsZHJUa1ppYTNSWFpVaFdVVkY2YkRaWFZFNUxZMGRPU1ZWVGRGbFNlbFpxV1cxd05FMUdjRmhOV0dScFVqQlpkMWRzVVRGWk1rcHdVVmRrVVZJeVpEUlZSelV3VGpCc1NFMVljR0ZsVlVrMVdteFNNMlJ0UmtWU1UzUlpVbnBTYmxOVlVqUmlSMHBFVFZkMGFGWXdXbnBaYWtwcVdqRkNjRkZVYUUxTmJGcDZWRVprVTJOR2JGaGxTRnBoWldwV2FsbHRiRUphTVVKSVlrY3hhbUpWV2pCWGJFNURaVzFPZEZSVWJGbFJNSEJxVTFkck5Fc3hhRWhPUkdoTlRURktjMWxzYUVOak1XeFpWVzE0VVdKSWFERlRWMnd6WVZkR1dFMVlaR2xOTUc5M1ZFWmplR0ZIVGtST1dFWnFUV3BzTVZOWGNIWmhWMVY0WlVoV1NsRXdTbXBUVnpGelpFZE9TRTlZYkd0VFJUVnFVMWR3ZGxveVZYcE5WMDVwWW1wQ2NGUkZUa3ROUjAxNVZHNWFhV0pXY0hkWGJtc3hZMWROZVU5WVZrcGhiVGx3V2xSR05HUlZiRVJSYlU1S1lsVTFNbGxzYUVOalIwcElWbTVzVlUwd1NYZFpWbU0xWkZkTmVHUXliRkJoVlVrelYwVmpNRm93YkVSUlYyUlpVVEJ3YjFsclpEUmtiVkYzWTBod1dWRXdhekpUVldoVFpWZFNXRlpZVGxsU2VsSnVVMVZPUWxveGFFUlRiWEJvVWpGYWNWbFVRbmRsYkdoRVUxUmFTbE5HU2pWYVJtUldZekZvU0U1SFpFcFJNRVp1VjBWT1MyTlhUWHBoUjA1S1lXMDVibGRGVGt0a01rNTBWbTV3WVZkRmIzbFhiRm96WVZWNFIyVklWa3BSTUVadVUxVmFNMkZYVWtoU2JteGhUV3haZDFkRlRrcE9hMnhIWkRKc1UxWnJOVkJYYkdodlRVWm9SRk5ZVGxsU2VsSnVVMVZPUWxveGFFUlRibEpwVFd4SmVGbHJaRmRaTUd4eFlqSmtXVkV3Y0VkV1ZFRXhZa2RXU1ZWdFRrcGhXR2hxV1cxc1Fsb3diRVJSYlU1S1lsUkdNbGRyYUZkak1YQlhVMjE0YWsxcWJIcGFSbWhUWTBkSmVVNVhUa3BoYlRsdVYwVk9TMUV5VWxoT1YzUnBVakZhTlZkRlRrcGpNV2hJVGtka1NsRXdSbTVYUlU1TFlVZEtTR1ZJV210TlIzZ3dXVEJqTldWWFVraGlTRlpoVFZaS05sVnNhRzlOUm5CWVRsaHdhRlo2YkRGWmVrWXpZVlU1Y0ZGcVFtcGliRnB6VkVWYU5HUlZiRVJSVjJSS1VtNWtjRnBGYUhOa01YQlpWRzFPU21GdE9XNVdla1l6WVZad1dHVkhlR2xXTVZveFdrVk5lR1F5U2tsV2JuQk5UVzFTZWxscVNrdGhSMHBFVGxkMFRXSnNTalpYUlU1TFdrWm9TRTVIWkVwVFJFSjZWMFZqTUZvd2JFZGtNbXhyWW14YWMxVlVTVFZrUjA1SVlraE9ZVmRGY0ZGWk1HaFRZMGRKZVU1WWNGbFJNR3N5VTFWb01Ga3lTbkJSVjJSS1VUQkthbE5YTlZOaFIwNTBXa2Q0YTFKdVpIQlVNbXhDWld0NGNWUnRUbWxoVlVadVdteGFOR1JYV2xkbFNGWktZVmhrY0ZkRVNUUmhWVGwxWkVSc2JWVlVNRGxZUTBsMlVHeDRkVkJET1RCYVZ6RjNZa2RHTUZwVU5XTmlhVWx6U1cxc2RHTkhPWGxrUXpGMFdWaEJkV0Z1VG5aaWFVazJTVzUwWTJKcFFXZFlRMHB3WWxoQ2RtTnVVbnBZUTBrMlNVaDBPVmhITlRsSmFYZHBaRWhPYW1JeU5XMWhWMk4xWVc1T2RtSnBTVFpKYm5SalltbEJaMWhEU21waU1qRjNZVmQ0YkdOck9YZGtSMngyWW01T1kwbHFiMmRsTVhoMVNVTkJaMGxHZDJsWlYzaHpZak5rUzJNeGQybFBhVUl3WTI1V2JFeEdlSFZKUTBGblNVWjNhVmt5YUd4Wk1uUkxZekYzYVU5cFFqQmpibFpzVEVaNGRVbERRV2RKUm5kcFlXNU9ORmhEU1RaSlJuZHBZMGhLYkdNeVZubGtiVlpqU1dsNFkySnBRV2RKUTBKalNXNVNhR050Wkd4a1JuZHBUMmxDWTBsclZsUlViVlkwWkVaM2FVeEdlSFZKUTBGblNVWjNhV0pYT1d0a1YzaHNXRU5KTmtsR2QybFNWazVQV2xob01GaERTWE5ZUnpSblNVTkJaMWhEU25SaU1sSXhZa2RXVTFwWVRuWmlTRll3WVZjNWRWaERTVFpKUm5kcFVXNVdkVnBIZUd4amJIZHBURVo0ZFVsRFFXZEpSbmRwV1ZkNGMySXpaRXBpV0VKMlkyNVNjR0p0WkZWak1GWTBaRWRXZFdNeWJIWmliazVqU1dwdloyUklTakZhVTNoalltbEJaMGxEUW1OSmJsSTFZMGRXZWxoRFNUWkpSblJqU1cxV2MxcFhNV3hpYmxGMFkwZDRNV041T1c1aVJ6bHBXVmQzZFZwRE5UQmpNWGRwV0ZaNGRVbERRamxNUm5oMVNVTkNZMGx1V2pGYVZVNTJZbGhDY0dKSFZubFVNMEl3WVZjNWRXTXhkMmxQYVVJM1dFYzBaMGxEUVdkWVEwb3dXVmhLYmxwWVVtTkphbTluVFhrMGVsaEhOR2RKU0RGalltNHhZMkpwU1hOSmJEbDJTV3B3TjJaWU1EMWNJaTgrWEc0OEwzUmxiWEJzWVhSbFBseHVJaXdpYVcxd2IzSjBMVzFoY0M1cWMyOXVJam9pZTF4dUlDQmNJbWx0Y0c5eWRITmNJam9nZTMxY2JuMGlMQ0owYzJOdmJtWnBaeTVxYzI5dUlqb2llMXh1SUNCY0ltTnZiWEJwYkdWeVQzQjBhVzl1YzF3aU9pQjdYRzRnSUNBZ1hDSmhiR3h2ZDBwelhDSTZJSFJ5ZFdVc1hHNGdJQ0FnWENKamFHVmphMHB6WENJNklIUnlkV1VzWEc0Z0lDQWdYQ0pxYzNoY0lqb2dYQ0p3Y21WelpYSjJaVndpTEZ4dUlDQWdJRndpZEdGeVoyVjBYQ0k2SUZ3aVJWTk9aWGgwWENJc1hHNGdJQ0FnWENKdGIyUjFiR1ZjSWpvZ1hDSkZVMDVsZUhSY0lpeGNiaUFnSUNCY0ltMXZaSFZzWlZKbGMyOXNkWFJwYjI1Y0lqb2dYQ0pDZFc1a2JHVnlYQ0lzWEc0Z0lDQWdYQ0poYkd4dmQwbHRjRzl5ZEdsdVoxUnpSWGgwWlc1emFXOXVjMXdpT2lCMGNuVmxMRnh1SUNBZ0lGd2lkSGx3WlhOY0lqb2dXMXdpWld4bGJXVnVkQzF3YkhWekwyZHNiMkpoYkM1a0xuUnpYQ0pkWEc0Z0lIMHNYRzRnSUZ3aWRuVmxRMjl0Y0dsc1pYSlBjSFJwYjI1elhDSTZJSHRjYmlBZ0lDQmNJblJoY21kbGRGd2lPaUF6TGpOY2JpQWdmVnh1ZlZ4dUlpd2lYMjhpT250OWZRPT1cIi8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

有什么应对措施吗。

**Pull request closed without merging**
