### PR TITLE
feat(components): [el-upload] support put method

### LINKED ISSUE #3352: [Feature Request] HTTP Put support for upload
### Existing Component
Yes

### Component Name
upload

### Description
Sometime, we prefer to use put than post to upload a file.  
Now the post request is hard encode in the impl of [ajax.ts](https://github.com/element-plus/element-plus/blob/dev/packages/components/upload/src/ajax.ts#L81) (a short string), maybe just need add a prop to decide how file upload?

### PR DESCRIPTION
**Pull request by xiaoxian521**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xiaoxian521** [comment]
feat: https://github.com/element-plus/element-plus/issues/3352

**Review by btea — COMMENTED** [review]
https://github.com/element-plus/element-plus/blob/7128cad014c9ad00e664e59f4e6cab0703e2ca7c/packages/components/upload/src/ajax.ts#L24
this should be `option.method`

**Comment by xiaoxian521** [comment]
> https://github.com/element-plus/element-plus/blob/7128cad014c9ad00e664e59f4e6cab0703e2ca7c/packages/components/upload/src/ajax.ts#L24
> 
> 
> this should be `option.method`

Thanks for reminding i didn't notice this

**Comment by sxzz** [comment]
https://github.com/element-plus/element-plus/pull/3358/files#diff-abe5073fc7604d817b28680ac58a38a7c08c017d604bb8b0ea621a5d4cbd18bbR19

This line should be modfied too.

**Review by sxzz — APPROVED** [review]

**Comment by hughcube** [comment]
Put uploads should put the contents of the file directly instead of using a form

**Pull request merged**
