### PR TITLE
fix(components): [tree] Fix there are disabled nodes that require two clicks on the checkbox to take effect

### LINKED ISSUE #15353: [Component] [tree] el-tree 有禁用节点，需点击两次复选框才能生效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.11`
- Element Plus Version: `2.4.4`
- Browser / OS: `Chrome 120.0.6099.200 `
- Build Tool: `Other`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiA8ZWwtY2hlY2tib3hcbiAgICAgICAgICB2LW1vZGVsPVwiY2hlY2tlZFwiXG4gICAgICAgICAgQGNoYW5nZT1cImNoZWNrZWRBbGxcIlxuICAgICAgICAgID7lhajpgIlcbiAgICAgICAgPC9lbC1jaGVja2JveD5cbiAgPGVsLXRyZWUgICAgICBcbiAgICAgIG5vZGUta2V5PVwiaWRcIlxuICAgICAgIHJlZj1cInRyZWVSZWZcIiBcbiAgICAgICA6ZGF0YT1cImRhdGFcIiA6cHJvcHM9XCJkZWZhdWx0UHJvcHNcIiBzaG93LWNoZWNrYm94IC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbiAgZGlzYWJsZWQ6ICdkaXNhYmxlZCcsXG59XG5jb25zdCBjaGVja2VkID0gcmVmKGZhbHNlKVxuY29uc3QgaXNJbmRldGVybWluYXRlID0gcmVmKGZhbHNlKVxuY29uc3QgdHJlZVJlZiA9IHJlZihudWxsKVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgaWQ6IDMsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMScsXG4gICAgICAgIGNoaWxkcmVuOiBbXG4gICAgICAgICAge1xuICAgICAgICAgICAgaWQ6IDQsXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA1LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTEtMicsXG4gICAgICAgICAgICBkaXNhYmxlZDogdHJ1ZSxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDIsXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDItMicsXG4gICAgICAgIGRpc2FibGVkOiB0cnVlLFxuICAgICAgICBjaGlsZHJlbjogW1xuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiA2LFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAzLTItMScsXG4gICAgICAgICAgfSxcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogNyxcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0yLTInLFxuICAgICAgICAgICAgZGlzYWJsZWQ6IHRydWUsXG4gICAgICAgICAgfSxcbiAgICAgICAgXSxcbiAgICAgIH0sXG4gICAgXSxcbiAgfSxcbl1cblxuZnVuY3Rpb24gZmxhdHRlblRyZWUoZGF0YSkge1xuICBjb25zdCByZXN1bHQgPSBbXVxuXG4gIGZ1bmN0aW9uIGZsYXR0ZW4obm9kZSkge1xuICAgIHJlc3VsdC5wdXNoKG5vZGUpXG4gICAgaWYgKG5vZGU/LmNoaWxkcmVuPy5sZW5ndGgpIHtcbiAgICAgIG5vZGUuY2hpbGRyZW4uZm9yRWFjaChmbGF0dGVuKVxuICAgIH1cbiAgfVxuXG4gIGRhdGEuZm9yRWFjaChmbGF0dGVuKVxuICByZXR1cm4gcmVzdWx0XG59XG5cbmNvbnN0IGNoZWNrZWRBbGwgPSAoYm9vbCkgPT4ge1xuICBjb25zb2xlLmxvZyhib29sLCAnY2hlY2tlZEFsbCcpXG4gIC8vIOiuvue9ruWLvumAieiKgueCuSAg5bmz6ZO655qE5pWw5o2uXG4gIHRyZWVSZWYudmFsdWUuc2V0Q2hlY2tlZE5vZGVzKGJvb2wgPyBmbGF0dGVuVHJlZShkYXRhKS5maWx0ZXIoaXRlbSA9PiAgIWl0ZW0uZGlzYWJsZWQgKTogW10pXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

[示例2](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICByZWY9XCJ0cmVlUmVmXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIHNob3ctY2hlY2tib3hcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBoaWdobGlnaHQtY3VycmVudFxuICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gIC8+XG5cbiAgPGRpdiBjbGFzcz1cImJ1dHRvbnNcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImdldENoZWNrZWROb2Rlc1wiPmdldCBieSBub2RlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJnZXRDaGVja2VkS2V5c1wiPmdldCBieSBrZXk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInNldENoZWNrZWROb2Rlc1wiPnNldCBieSBub2RlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPnNldCBieSBrZXk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Q2hlY2tlZFwiPnJlc2V0PC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsVHJlZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcblxuaW50ZXJmYWNlIFRyZWUge1xuICBpZDogbnVtYmVyXG4gIGxhYmVsOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cblxuY29uc3QgdHJlZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVHJlZT4+KClcblxuY29uc3QgZ2V0Q2hlY2tlZE5vZGVzID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyh0cmVlUmVmLnZhbHVlIS5nZXRDaGVja2VkTm9kZXMoZmFsc2UsIGZhbHNlKSlcbn1cbmNvbnN0IGdldENoZWNrZWRLZXlzID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyh0cmVlUmVmLnZhbHVlIS5nZXRDaGVja2VkS2V5cyhmYWxzZSkpXG59XG5jb25zdCBzZXRDaGVja2VkTm9kZXMgPSAoKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLnNldENoZWNrZWROb2RlcyhcbiAgICBbXG4gICAgICB7XG4gICAgICAgIGlkOiA1LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDksXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgfSxcbiAgICBdIGFzIE5vZGVbXSxcbiAgICBmYWxzZVxuICApXG59XG5jb25zdCBzZXRDaGVja2VkS2V5cyA9ICgpID0+IHtcbiAgdHJlZVJlZi52YWx1ZSEuc2V0Q2hlY2tlZEtleXMoWzNdLCBmYWxzZSlcbn1cbmNvbnN0IHJlc2V0Q2hlY2tlZCA9ICgpID0+IHtcbiAgdHJlZVJlZi52YWx1ZSEuc2V0Q2hlY2tlZEtleXMoW10sIGZhbHNlKVxufVxuXG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cblxuY29uc3QgZGF0YTogVHJlZVtdID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbGFiZWw6ICdMZXZlbCAxJyxcbiAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMixcbiAgICAgICAgICAgIGRpc2FibGVkOiB0cnVlLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCAyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAzLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCAzJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319)

### Steps to reproduce
先勾选Level one 1，然后点全选，再取消全选，最后重新勾选Level one 1 需点击两次才能生效

https://github.com/element-plus/element-plus/assets/69613314/fb31a67d-b3f1-4036-add2-143754597c32

示例2：
先勾选Level 1
然后取消 Level 3 
再点Level 1 复选框需要点两次

https://github.com/element-plus/element-plus/assets/69613314/d7c91370-258e-499a-8af8-c8b921455c49

### What is Expected?

能够正常的点击

### What is actually happening?

需要点击两次复选框

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by xingyixiang**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xingyixiang** [comment]
[Example](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXRyZWVcbiAgICByZWY9XCJ0cmVlUmVmXCJcbiAgICA6ZGF0YT1cImRhdGFcIlxuICAgIHNob3ctY2hlY2tib3hcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBoaWdobGlnaHQtY3VycmVudFxuICAgIDpwcm9wcz1cImRlZmF1bHRQcm9wc1wiXG4gIC8+XG5cbiAgPGRpdiBjbGFzcz1cImJ1dHRvbnNcIj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cImdldENoZWNrZWROb2Rlc1wiPmdldCBieSBub2RlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJnZXRDaGVja2VkS2V5c1wiPmdldCBieSBrZXk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInNldENoZWNrZWROb2Rlc1wiPnNldCBieSBub2RlPC9lbC1idXR0b24+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJzZXRDaGVja2VkS2V5c1wiPnNldCBieSBrZXk8L2VsLWJ1dHRvbj5cbiAgICA8ZWwtYnV0dG9uIEBjbGljaz1cInJlc2V0Q2hlY2tlZFwiPnJlc2V0PC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IEVsVHJlZSB9IGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB0eXBlIE5vZGUgZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvbm9kZSdcblxuaW50ZXJmYWNlIFRyZWUge1xuICBpZDogbnVtYmVyXG4gIGxhYmVsOiBzdHJpbmdcbiAgY2hpbGRyZW4/OiBUcmVlW11cbn1cblxuY29uc3QgdHJlZVJlZiA9IHJlZjxJbnN0YW5jZVR5cGU8dHlwZW9mIEVsVHJlZT4+KClcblxuY29uc3QgZ2V0Q2hlY2tlZE5vZGVzID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyh0cmVlUmVmLnZhbHVlIS5nZXRDaGVja2VkTm9kZXMoZmFsc2UsIGZhbHNlKSlcbn1cbmNvbnN0IGdldENoZWNrZWRLZXlzID0gKCkgPT4ge1xuICBjb25zb2xlLmxvZyh0cmVlUmVmLnZhbHVlIS5nZXRDaGVja2VkS2V5cyhmYWxzZSkpXG59XG5jb25zdCBzZXRDaGVja2VkTm9kZXMgPSAoKSA9PiB7XG4gIHRyZWVSZWYudmFsdWUhLnNldENoZWNrZWROb2RlcyhcbiAgICBbXG4gICAgICB7XG4gICAgICAgIGlkOiA1LFxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgaWQ6IDksXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMS0xLTEnLFxuICAgICAgfSxcbiAgICBdIGFzIE5vZGVbXSxcbiAgICBmYWxzZVxuICApXG59XG5jb25zdCBzZXRDaGVja2VkS2V5cyA9ICgpID0+IHtcbiAgdHJlZVJlZi52YWx1ZSEuc2V0Q2hlY2tlZEtleXMoWzNdLCBmYWxzZSlcbn1cbmNvbnN0IHJlc2V0Q2hlY2tlZCA9ICgpID0+IHtcbiAgdHJlZVJlZi52YWx1ZSEuc2V0Q2hlY2tlZEtleXMoW10sIGZhbHNlKVxufVxuXG5jb25zdCBkZWZhdWx0UHJvcHMgPSB7XG4gIGNoaWxkcmVuOiAnY2hpbGRyZW4nLFxuICBsYWJlbDogJ2xhYmVsJyxcbn1cblxuY29uc3QgZGF0YTogVHJlZVtdID0gW1xuICB7XG4gICAgaWQ6IDEsXG4gICAgbGFiZWw6ICdMZXZlbCAxJyxcbiAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBpZDogMixcbiAgICAgICAgICAgIGRpc2FibGVkOiB0cnVlLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCAyJyxcbiAgICAgICAgICB9LFxuICAgICAgICAgIHtcbiAgICAgICAgICAgIGlkOiAzLFxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCAzJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1NTcxLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgY29uc3Qgc3R5bGVzID0gWydodHRwczovL3ByZXZpZXctMTU1NzEtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnLCAnaHR0cHM6Ly9wcmV2aWV3LTE1NTcxLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ10ubWFwKChzdHlsZSkgPT4ge1xuICAgIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgICBsaW5rLnJlbCA9ICdzdHlsZXNoZWV0J1xuICAgICAgbGluay5ocmVmID0gc3R5bGVcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2Vycm9yJywgcmVqZWN0KVxuICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgICB9KVxuICB9KVxuICByZXR1cm4gUHJvbWlzZS5hbGwoc3R5bGVzKVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1NTcxLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

**Comment by xingyixiang** [comment]
@qppq54s 我看其他版本也会有这个问题 (根节点点击后，无法取消选中)

**Comment by qppq54s** [comment]
> @qppq54s 我看其他版本也会有这个问题 (根节点点击后，无法取消选中)

你用我这个example就可以复现issuse里的问题了，其实这个根节点无法取消选中跟issue里的问题本质上是同一个问题

**Comment by xingyixiang** [comment]
@qppq54s （把禁用节点也认为是选中节点）你说的有道理

**Pull request closed without merging**
