### PR TITLE
fix(components): [dialog] cause input focus problem

### LINKED ISSUE #10154: [Component] [dialog, input] The input box component at the same level cannot obtain focus while the dialog is not closed -- 对话框未关闭时，同层输入框无法获取焦点
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.38`
- Element Plus Version: `2.2.18`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-dialog`
- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgRWxEaWFsb2cgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBkaWFsb2dWaXNpYmxlID0gcmVmKHRydWUpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8ZWwtZGlhbG9nIHYtbW9kZWw9XCJkaWFsb2dWaXNpYmxlXCIgYXBwZW5kLXRvLWJvZHk+XG4gICAgZGlhbG9n5by556qX5L2/55SoVGlueU1DReWvjOaWh+acrOe8lui+keWZqCzlvLnmoYbkuK3nmoRpbnB1dOaXoOazleiBmueEplxuICA8L2VsLWRpYWxvZz5cbiAgPGRpdiBjbGFzcz1cInBvcFwiPlxuICAgIDxpbnB1dCB0eXBlPVwidGV4dFwiIGNsYXNzPVwiaW5wXCIgcGxhY2Vob2xkZXI9XCLov5nph4zml6Dms5XogZrnhKZcIi8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbjxzdHlsZT5cbiAgLnBvcHtcbiAgICBwb3NpdGlvbjogZml4ZWQ7IFxuICAgIHotaW5kZXg6IDMwMDA7XG4gIH1cbiAgLmlucHtcbiAgICBib3JkZXI6c29saWQgMXB4ICMzMzM7XG4gIH1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1、dialog box is not closed
2、same layer display opens the input box
3、input box cannot get focus

### What is Expected?

input box can get focus

### What is actually happening?

input box cannot get focus，can only put the input box inside the dialog box（只能把输入框放到对话框内部）

### Additional comments

Dialog boxes do not need to lock focus inside them ? or provides a props control

### PR DESCRIPTION
**Pull request by Simon-He95**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix: #10154

### CODE REVIEW

**Comment by jw-foss** [comment]
@Giwayume hi, would you mind give review to this PR? Thanks in advance!

**Comment by Giwayume** [comment]
This is disabling the modal focus trapping in order to support a fringe scenario to focus on an input outside of a modal. It doesn't make sense.

**Comment by Giwayume** [comment]
Try this? https://github.com/element-plus/element-plus/pull/10160

**Comment by jw-foss** [comment]
Based on @Giwayume 's suggestion, I will close this PR. Thank you for your contribution!

**Pull request closed without merging**
