### PR TITLE
fix(docs): fix el-tree props disabled type

### PR DESCRIPTION
**Pull request by Yueyanc**
fix:[#5481](https://github.com/element-plus/element-plus/issues/5481)
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ChenAdien** [comment]
@emojiiii

**Comment by kooriookami** [comment]
@ChenAdien Can you fix the same place of Tree V2?

**Comment by kooriookami** [comment]
Thannks, have you done this PR?

**Comment by ChenAdien** [comment]
> Thanks, have you done this PR?

yes

**Review by kooriookami — APPROVED** [review]
Thanks.

**Pull request merged**
