### PR TITLE
docs: added dropdown disabled attribute for all languages

### LINKED ISSUE #2006: [Doc] `<el-dropdown>` supports the `disabled` attribute, but is not documented.
### Existing Component
Yes

### Component Name
`<el-dropdown>`

### Description
`<el-dropdown>` supports the `disabled` attribute, but is not documented.

### PR DESCRIPTION
**Pull request by wenfangdu**
fixes https://github.com/element-plus/element-plus/issues/2006

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Could you also add the documentation for `fr`, `jp`, `es`?

**Comment by ioslh** [comment]
need a polyglot contributor 🤣

**Comment by wenfangdu** [comment]
@JeremyWuuuuu done.

**Comment by JeremyWuuuuu** [comment]
> need a polyglot contributor 🤣

Not really, simply copy and paste English version would be fine lol.

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
