### PR TITLE
refactor(utils): improve debug warn

### PR DESCRIPTION
**Pull request by adaex**
refactor debug warn

- [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Hey, could you please modify eslint rule for disabling `console.warn`.

**Comment by sxzz** [comment]
Also, maybe we can ignore `no-console` for tests.

```javascript
// .eslintrc.js
module.exports = {
  overrides: [
    {
      // not tested
      files: ['**/__tests__'],
      rules: {
        'no-console': 'off',
      },
    },
  ],
}
```

**Comment by adaex** [comment]
https://github.com/element-plus/element-plus/blob/55348b30b6ae59b0efe8abfa9f8dbbeaabb5614a/packages/components/pagination/__tests__/pagination.spec.ts#L34-L44

Please see here. In the unit test, check if `console.warn` is called, if the `debugWarn` method does not allow `console.warn` to call in the `test` environment, the unit test will not pass.

**Comment by sxzz** [comment]
IMO just use `console.warn` and disable eslint rule in tests.

**Comment by adaex** [comment]
element plus love you

**Comment by sxzz** [comment]
LGTM. Thanks.

element plus love you

**Pull request merged**
