### PR TITLE
docs(components): [time-picker] remove non-existent attribute

### LINKED ISSUE #7632: [Bug Report] [Docs] [time-picker] The align property type is incorrect
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.11`
- Browser / OS: `Chrome 101.0.4951.54`
- Build Tool: `Vue CLI`

### Related Component

- `el-time-picker`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/time-picker.html)

### Steps to reproduce

align	对齐方式	left / center / right	left	

### What is Expected?

修改完善最新文档

### What is actually happening?

修改完善最新文档

### Additional comments

_(empty)_

63F58322-6612-4727-BC74-E25434308D5E

### PR DESCRIPTION
**Pull request by josonho**
fix #7632 

***

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
Optional value column is missing.

**Comment by josonho** [comment]
@chenxch yes，
But I found that the align attribute is not implemented, referring to components such as date-picker, I think align may not be necessary, so I will remove it first.

**Comment by chenxch** [comment]
Good job!

**Comment by xiaoxian521** [comment]
fix: https://element-plus.org/zh-CN/component/time-picker.html#timepicker-%E5%B1%9E%E6%80%A7

**Pull request closed without merging**
