### PR TITLE
fix(components): [el-button] Add props click-auto-blur to fix bug #14637

### LINKED ISSUE #14637: [Style] [button, button-group] I want the style to automatically return to its original state after clicking the button
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `chrome/win10`
- Build Tool: `Vite`

### Related Component

- `el-button`
- `el-button-group`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/button.html#%E5%9B%BE%E6%A0%87%E6%8C%89%E9%92%AE)

### Steps to reproduce

The buttons in the elementUI will have a focus style after clicking, and only after clicking elsewhere will the button lose focus and the style will be restored to the previous style. For example, the main button is bright blue, and when clicked, it is dark blue. Clicking elsewhere will restore the bright blue color。elementUI 中的按钮，点击后会有focus样式，且只有点击其他地方后，按钮才会失焦，样式才会恢复到点击之前的样式。例如主要按钮是亮蓝色，点击后是暗蓝色。点击其他地方才会恢复亮蓝色。

### What is Expected?

I want the style to automatically return to its original state after clicking the button。我希望点击按钮后样式自动恢复到点击前的样子

### What is actually happening?

After clicking the button, there will be a focus style, and only after clicking elsewhere will the button lose focus and the style will be restored to the previous style。按钮点击后会有focus样式，且只有点击其他地方后，按钮才会失焦，样式才会恢复到点击之前的样式。

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by CherishTheYouth**
Please make sure these boxes are checked before submitting your PR, thank you!

- [X] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [X] Make sure you are merging your commits to `dev` branch.
- [X] Add some descriptions and refer to relative issues for your PR.

## Description

I add a property `click-auto-blur` which could set button to to restore its original style after being clicked.

## Related Issue

Fixes #14637

## Explanation of Changes

When set property `click-auto-blur` true, the button will lose focus status immediately to restore it original style.

### CODE REVIEW

**Review by ryuhangyeong — APPROVED** [review]

**Comment by CherishTheYouth** [comment]
For I am a new contributor, I wonder if there anything I have not done, the pull request has blocked for several days.

**Comment by ryuhangyeong** [comment]
Requires approval from more members.

**Comment by tolking** [comment]
Thank for your contribution. but for a11y, this is a bad idea.

Some like #14258

**Comment by CherishTheYouth** [comment]
> Thank for your contribution. but for a11y, this is a bad idea.
> 
> Some like #14258

Thank you, it really is. I will give a solution on my blog  for anyone need it.

Could I have your email or weChat for some help about how to make contribution to element-plus?

Best Wishes!

**Comment by tolking** [comment]
contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](~~https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).

**Pull request closed without merging**
