### PR TITLE
fix(components): [popover] fix dark mode background color

### LINKED ISSUE #8113: [Bug Report] [Component] [popover, dropdown] 暗黑模式下 同时使用el-popover 和 el-dropdown，导致el-popover 无法进入暗黑模式
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.36`
- Element Plus Version: `2.2.4`
- Browser / OS: `macos`
- Build Tool: `Vite`

### Related Component

- `el-popover`
- `el-dropdown`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-tjd7ys?file=src%2FApp.vue)

### Steps to reproduce

同时使用el-popover 和 el-dropdown

### What is Expected?

el-popover 进入暗黑模式

### What is actually happening?

el-popover的 .is-light 样式 被覆盖

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by holazz**
fixes https://github.com/element-plus/element-plus/issues/8113

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jw-foss** [comment]
@YunYouJun PTAL

**Comment by YunYouJun** [comment]
I think we should modify here.

https://github.com/element-plus/element-plus/blob/470286097f63c7795373351e525e9511f5b73ef2/packages/theme-chalk/src/common/var.scss#L835

**Comment by holazz** [comment]
> I think we should modify here.
> 
> https://github.com/element-plus/element-plus/blob/470286097f63c7795373351e525e9511f5b73ef2/packages/theme-chalk/src/common/var.scss#L835

agree.

**Review by jw-foss — APPROVED** [review]

**Comment by holazz** [comment]
https://github.com/element-plus/element-plus/blob/884b0d71b7fe802e044cabb50b65d1599296f904/packages/theme-chalk/src/popover.scss#L9
Or is it possible to remove the `background` here? because the same style is defined on `el-popper`.

**Comment by holazz** [comment]
> https://github.com/element-plus/element-plus/blob/884b0d71b7fe802e044cabb50b65d1599296f904/packages/theme-chalk/src/popover.scss#L9
> 
> 
> Or is it possible to remove the `background` here? because the same style is defined on `el-popper`.

https://github.com/element-plus/element-plus/blob/884b0d71b7fe802e044cabb50b65d1599296f904/packages/theme-chalk/src/popover.scss#L11

`border-radius` is also.

**Comment by YunYouJun** [comment]
We can remove `$popover.border-radius` and use `getCssVar('border-radius', 'base')`.

But `popover-bg-color` can be kept because the user may want to customize the popover by modifying the variables.

What is your opinion?

**Comment by holazz** [comment]
> We can remove `$popover.border-radius` and use `getCssVar('border-radius', 'base')`.
> 
> But `popover-bg-color` can be kept because the user may want to customize the popover by modifying the variables.
> 
> What is your opinion?

I missed that point, you are right.

**Pull request merged**
