### PR TITLE
feat(directives): [click-outside] add shadow dom support

### PR DESCRIPTION
**Pull request by danny-hebert**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by consultation-applio** [comment]
This allows users to use Element plus v-click-outside date-picker, time-picker, select and dropdown inside Vue Custom elements.

**Comment by consultation-applio** [comment]
@holazz @chenxch could you please take a look? :)

**Comment by consultation-applio** [comment]
Closing this PR, will opened separate PR for each commit

**Comment by code4you2021** [comment]
Any news?
@holazz @chenxch

**Comment by consultation-applio** [comment]
The content of this PR got moved here: 

https://github.com/element-plus/element-plus/pull/12059

but still no luck getting it reviewed. Our company is currently looking at removing element-plus completely from our projects since there’s no way to get web component support even tho we open PR to contribute to get it supported.

**Pull request closed without merging**
