### PR TITLE
style: css uniformly uses `px`

### LINKED ISSUE #17100: [Style] [upload] el-upload设置list-type="picture-card"属性后，在项目配置了px转rem插件后，会导致鼠标移入显示的删除按钮位置由于内置属性margin-left: 1rem;超出被隐藏
Bug Type: **`Style`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.7.4`
- Browser / OS: `Chrome/123.0.6312.59    win11 23H2`
- Build Tool: `Vite`

### Related Component

- `el-upload`

### Reproduction Link

[Github Repo](https://github.com/element-plus/element-plus/issues?page=4&q=el-upload)

### Steps to reproduce

项目引入"postcss-pxtorem": "^6.0.0",插件后，会全局将px转换为rem，但是由于element plus内部使用了rem，导致使用了rem单位的组件css样式出错

```vue
<script setup>

</script>

<template>
  <el-upload
            class="aq-upload"
            list-type="picture-card"
            v-model:file-list="fileList"
            :auto-upload="false"
            :headers="uploadHeader"
            action=""
            :limit="3"
            accept=".jpg, .jpeg, .png"
            :before-upload="beforeImgUpload"
            :on-progress="imgProgress"
            :on-success="imgSuccess"
            :on-error="imgError"
            :on-preview="imgPreview"
            :on-remove="imgRemove"
          >
            <el-icon><Plus /></el-icon>
          </el-upload>
</template>
<style lang="scss">
.el-upload-list--picture-card .el-upload-list__item-actions span+span {
    margin-left: 1rem;
}
</style>
```

### What is Expected?

element plus应该统一单位类型，不应该额外使用rem来作为新的单位混淆，用户自定义rem转换后，不影响css样式布局

### What is actually happening?

内置极个别组件使用了rem作为单位导致单位尺寸冲突，导致鼠标移入删除按钮距离超出宽度

### Additional comments

解决问题的方法很简单，只需要将rem替换为百分比即可，这样不会受到任何外部影响。

修改前
.el-upload-list--picture-card .el-upload-list__item-actions span+span {
    margin-left: 1rem;
}
修改后
.el-upload-list--picture-card .el-upload-list__item-actions span+span {
    margin-left: 20%;
}

### PR DESCRIPTION
**Pull request by warmthsea**
fixed: https://github.com/element-plus/element-plus/issues/17100

### CODE REVIEW

**Review by warmthsea — COMMENTED** [review]
Of all the codes, only these two places use `rem`.

**Review by btea — APPROVED** [review]
LGTM.

**Review by ryuhangyeong — APPROVED** [review]

**Comment by btea** [comment]
@kooriookami Do you think we need to update this to the issue that records the changes?

**Comment by kooriookami** [comment]
> @kooriookami Do you think we need to update this to the issue that records the changes?

Yes, It would make more sense to use px.

**Review by kooriookami — APPROVED** [review]

**Pull request merged**
