### PR TITLE
fix(utils):[vue] ensure `flattedChildren` traverse component's subTree

### LINKED ISSUE #18646: [Component] [tabs, tab-pane] 在使用h函数且传入数组tab-pane而不是slot时，组件无法使用
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.12`
- Element Plus Version: `2.8.3`
- Browser / OS: `UserAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tabs`
- `el-tab-pane`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8Q29tcC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwIGxhbmc9XCJ0c1wiPlxuaW1wb3J0IENvbXAgZnJvbSAnLi9Db21wLnRzeCdcbjwvc2NyaXB0PlxuIiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvZGlzdC9pbmRleC5jc3MnLCAnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvdGhlbWUtY2hhbGsvZGFyay9jc3MtdmFycy5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvcnVudGltZS1kb21AMy4zLjEyL2Rpc3QvcnVudGltZS1kb20uZXNtLWJyb3dzZXIuanNcIixcbiAgICBcIkB2dWUvc2hhcmVkXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3NoYXJlZEAzLjMuMTIvZGlzdC9zaGFyZWQuZXNtLWJ1bmRsZXIuanNcIixcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQDIuOC4zL2Rpc3QvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAMi44LjMvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiQ29tcC50c3giOiJpbXBvcnQgeyBkZWZpbmVDb21wb25lbnQsIGggfSBmcm9tIFwidnVlXCI7XG5pbXBvcnQgeyBFbFRhYnMsIEVsVGFiUGFuZSB9IGZyb20gXCJlbGVtZW50LXBsdXMvZXMvaW5kZXhcIjtcblxuZXhwb3J0IGRlZmF1bHQgZGVmaW5lQ29tcG9uZW50KHtcbiAgc2V0dXAoKSB7XG4gICAgY29uc3QgcmVuZGVyVGFicyA9ICgpID0+IHtcbiAgICAgIHJldHVybiBoKEVsVGFicywge30sIFtoKEVsVGFiUGFuZSwgeyBsYWJlbDogXCLmoIfnrb4yXCIsIG5hbWU6IFwiaWRcIiB9LCBbaChcImRpdlwiLCB7fSwgXCJhYWFcIildKV0pO1xuICAgIH07XG5cbiAgICByZXR1cm4gKCkgPT4ge1xuICAgICAgcmV0dXJuIChcbiAgICAgICAgPGRpdj5cbiAgICAgICAgICB7cmVuZGVyVGFicygpfVxuICAgICAgICBcbiAgICAgICAgPC9kaXY+XG4gICAgICApO1xuICAgIH07XG4gIH0sXG59KTtcbiIsIl9vIjp7fX0=)

### Steps to reproduce

```tsx
import { defineComponent, h } from "vue";
import { ElTabs, ElTabPane } from "element-plus/es/index";

export default defineComponent({
  setup() {
    const renderTabs = () => {
      return h(ElTabs, {}, [h(ElTabPane, { label: "标签2", name: "id" }, [h("div", {}, "aaa")])]);
    };

    return () => {
      return (
        <div>
          {renderTabs()}
        
        </div>
      );
    };
  },
});
```

### What is Expected?

正常使用

### What is actually happening?

无法正常使用

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by ddeerdevil**
Please make sure these boxes are checked before submitting your PR, thank you!

- [✔ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [✔ ] Make sure you are merging your commits to `dev` branch.
- [✔ ] Add some descriptions and refer to relative issues for your PR.

fix: https://github.com/element-plus/element-plus/issues/18646

### CODE REVIEW

**Comment by ddeerdevil** [comment]
https://github.com/element-plus/element-plus/issues/18646

**Comment by makedopamine** [comment]
Format your code with prettier to fix the lint issue, plus are you able to add a test for this?

**Comment by ddeerdevil** [comment]
> Format your code with prettier to fix the lint issue, plus are you able to add a test for this?

好的，我会尽快修复。我可以尝试去写单元测试，但可能会不太完善。

**Comment by ddeerdevil** [comment]
> Format your code with prettier to fix the lint issue, plus are you able to add a test for this?

done.

**Review by makedopamine — APPROVED** [review]
LGTM

**Comment by ddeerdevil** [comment]
@makedopamine 
Could you please tell me when PR will be merged? Thank you for your reply.
Since this is the first time I submitted a PR, I just clicked merge, and now the status is not completed. How should I deal with it?

**Review by btea — APPROVED** [review]

**Comment by makedopamine** [comment]
Only maintainers with write access on this repo can merge. In general, the maintainers merge pull requests after they get two or more approvals.  However, they are not working full-time on this, so it could be a long time between reviews. Please understand the delayed feedback, and thank you for getting this done. @ddeerdevil

**Comment by ddeerdevil** [comment]
> Only maintainers with write access on this repo can merge. In general, the maintainers merge pull requests after they get two or more approvals. However, they are not working full-time on this, so it could be a long time between reviews. Please understand the delayed feedback, and thank you for getting this done. @ddeerdevil

Thank you very much for your reply. This is my first time trying to submit a PR for an open source project. It is a great encouragement to me. Thank you again.

**Pull request merged**
