### PR TITLE
feat(components): [cascader] expose expandNode function

### PR DESCRIPTION
**Pull request by nothing-sy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

## Description
Expose expandNode function

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 98fc9fb</samp>

Added a new function `expandNode` to the `cascader-panel` component to expand a node by value and level. This fixes a bug where the panel would not expand the correct node when the value prop changes.

## Related Issue
https://github.com/element-plus/element-plus/issues/15006

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 98fc9fb</samp>

*  Add `expandNode` function to expand a node in the cascader panel by value and level ([link](https://github.com/element-plus/element-plus/pull/15136/files?diff=unified&w=0#diff-bc11d0a0926f24e07f0460209f0fc4632de9e2a8e47d0705fa07ff8678b71989R383))

### CODE REVIEW

**Comment by btea** [comment]
@nothing-sy Hello, thank you for your contribution! Can you describe your usage scenario?

**Comment by nothing-sy** [comment]
@btea I need a child node(call it "all_select") for select all children(also need checkStrictly is true). When I checked "all_select" need to update v-model for all children. Then cascader will use syncMenuState to change menu state
image

**Comment by nothing-sy** [comment]
Did I set a wrong position to expose? I didn't find the expose func

**Comment by nothing-sy** [comment]
I hope when update data, component just sync data, don't `syncMenuState` or `scrollToExpandingNode`

**Comment by nothing-sy** [comment]
@btea I close the pr , you can comment in [issue#15006](https://github.com/element-plus/element-plus/issues/15006)

**Pull request closed without merging**
