### PR TITLE
fix(components): [menu] fix `sliceIndex` calculation error

### LINKED ISSUE #19161: [Component] [menu] el-menu组件水平模式，存在注释节点时，省略号计算错误
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.9.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36 Edg/131.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIOS+izHvvJplbC1tZW5157uE5Lu25YaF6YOo5rKh5pyJ5rOo6YeK6IqC54K577yM6K6h566X6ZyA6KaB5pi+56S655qE6I+c5Y2V5Liq5pWw5q2j56GuKOeUqOS6juWSjOS+izLjgIHkvosz5YGa5a+55q+UKSAtLT5cbiAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIj5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCJpIGluIGNvdW50XCI+XG4gICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cImkgKyAnJ1wiPuiPnOWNlXt7IGkgfX08L2VsLW1lbnUtaXRlbT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLW1lbnU+XG4gIDwhLS0g5L6LMu+8mmVsLW1lbnXnu4Tku7blhoXpg6jlrZjlnKjms6jph4roioLngrnvvIzorqHnrpfpnIDopoHmmL7npLrnmoToj5zljZXkuKrmlbDkuI3mraPnoa4gLS0+XG4gIDxlbC1tZW51IG1vZGU9XCJob3Jpem9udGFsXCI+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPCEtLSDov5nmmK/ms6jph4ogLS0+XG4gICAgPHRlbXBsYXRlIHYtZm9yPVwiaSBpbiBjb3VudFwiPlxuICAgICAgPGVsLW1lbnUtaXRlbSA6aW5kZXg9XCJpICsgJydcIj7oj5zljZV7eyBpIH19PC9lbC1tZW51LWl0ZW0+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuICA8IS0tIOS+izPvvJrlvZPlrZjlnKh2LWlm5pe277yMdnVl5qGG5p625Lya5Zyo6K+l5L2N572u55Sf5oiQ5LiA5Liq5rOo6YeK6IqC54K55p2l5Y2g5L2N77yM5LuO6ICM5a+86Ie05L6LMueahOaDheWGteWHuueOsCAtLT5cbiAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIj5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCJpIGluIGNvdW50XCI+XG4gICAgICA8ZWwtbWVudS1pdGVtIHYtaWY9XCJpID4gNVwiIDprZXk9XCJpXCIgOmluZGV4PVwiaSArICcnXCI+6I+c5Y2Ve3sgaSB9fTwvZWwtbWVudS1pdGVtPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCBjb3VudCA9IDIwO1xuPC9zY3JpcHQ+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

### Steps to reproduce

打开最小复现环境的链接

### What is Expected?

3个例子显示的菜单个数应该一致

### What is actually happening?

例2、例3的菜单显示个数小于例1

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by wen-lun**
修复el-menu组件水平模式，存在注释节点时，省略号计算错误

closed: #19161
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

[before](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIOS+izHvvJplbC1tZW5157uE5Lu25YaF6YOo5rKh5pyJ5rOo6YeK6IqC54K577yM6K6h566X6ZyA6KaB5pi+56S655qE6I+c5Y2V5Liq5pWw5q2j56GuKOeUqOS6juWSjOS+izLjgIHkvosz5YGa5a+55q+UKSAtLT5cbiAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIj5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCJpIGluIGNvdW50XCI+XG4gICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cImkgKyAnJ1wiPuiPnOWNlXt7IFN0cmluZyhpKS5wYWRTdGFydCgyLCAnMCcpIH19PC9lbC1tZW51LWl0ZW0+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuICA8IS0tIOS+izLvvJplbC1tZW5157uE5Lu25YaF6YOo5a2Y5Zyo5rOo6YeK6IqC54K577yM6K6h566X6ZyA6KaB5pi+56S655qE6I+c5Y2V5Liq5pWw5LiN5q2j56GuIC0tPlxuICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cImkgaW4gY291bnRcIj5cbiAgICAgIDxlbC1tZW51LWl0ZW0gOmluZGV4PVwiaSArICcnXCI+6I+c5Y2Ve3sgU3RyaW5nKGkpLnBhZFN0YXJ0KDIsICcwJykgfX08L2VsLW1lbnUtaXRlbT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLW1lbnU+XG4gIDwhLS0g5L6LM++8muW9k+WtmOWcqHYtaWbml7bvvIx2dWXmoYbmnrbkvJrlnKjor6XkvY3nva7nlJ/miJDkuIDkuKrms6jph4roioLngrnmnaXljaDkvY3vvIzku47ogIzlr7zoh7Tkvosy55qE5oOF5Ya15Ye6546wIC0tPlxuICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cImkgaW4gY291bnRcIj5cbiAgICAgIDxlbC1tZW51LWl0ZW0gdi1pZj1cImkgPiA1XCIgOmtleT1cImlcIiA6aW5kZXg9XCJpICsgJydcIj7oj5zljZV7eyBTdHJpbmcoaSkucGFkU3RhcnQoMiwgJzAnKSB9fTwvZWwtbWVudS1pdGVtPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCBjb3VudCA9IDIwO1xuPC9zY3JpcHQ+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9lbGVtZW50LXBsdXNAbGF0ZXN0L2Rpc3QvaW5kZXguY3NzJywgJ2h0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vZWxlbWVudC1wbHVzQGxhdGVzdC90aGVtZS1jaGFsay9kYXJrL2Nzcy12YXJzLmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9jZG4uanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvZGlzdC9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJodHRwczovL2Nkbi5qc2RlbGl2ci5uZXQvbnBtL2VsZW1lbnQtcGx1c0BsYXRlc3QvXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vY2RuLmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiX28iOnt9fQ==)

[after](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8IS0tIOS+izHvvJplbC1tZW5157uE5Lu25YaF6YOo5rKh5pyJ5rOo6YeK6IqC54K577yM6K6h566X6ZyA6KaB5pi+56S655qE6I+c5Y2V5Liq5pWw5q2j56GuKOeUqOS6juWSjOS+izLjgIHkvosz5YGa5a+55q+UKSAtLT5cbiAgPGVsLW1lbnUgbW9kZT1cImhvcml6b250YWxcIj5cbiAgICA8dGVtcGxhdGUgdi1mb3I9XCJpIGluIGNvdW50XCI+XG4gICAgICA8ZWwtbWVudS1pdGVtIDppbmRleD1cImkgKyAnJ1wiPuiPnOWNlXt7IFN0cmluZyhpKS5wYWRTdGFydCgyLCAnMCcpIH19PC9lbC1tZW51LWl0ZW0+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9lbC1tZW51PlxuICA8IS0tIOS+izLvvJplbC1tZW5157uE5Lu25YaF6YOo5a2Y5Zyo5rOo6YeK6IqC54K577yM6K6h566X6ZyA6KaB5pi+56S655qE6I+c5Y2V5Liq5pWw5LiN5q2j56GuIC0tPlxuICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDwhLS0g6L+Z5piv5rOo6YeKIC0tPlxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cImkgaW4gY291bnRcIj5cbiAgICAgIDxlbC1tZW51LWl0ZW0gOmluZGV4PVwiaSArICcnXCI+6I+c5Y2Ve3sgU3RyaW5nKGkpLnBhZFN0YXJ0KDIsICcwJykgfX08L2VsLW1lbnUtaXRlbT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLW1lbnU+XG4gIDwhLS0g5L6LM++8muW9k+WtmOWcqHYtaWbml7bvvIx2dWXmoYbmnrbkvJrlnKjor6XkvY3nva7nlJ/miJDkuIDkuKrms6jph4roioLngrnmnaXljaDkvY3vvIzku47ogIzlr7zoh7Tkvosy55qE5oOF5Ya15Ye6546wIC0tPlxuICA8ZWwtbWVudSBtb2RlPVwiaG9yaXpvbnRhbFwiPlxuICAgIDx0ZW1wbGF0ZSB2LWZvcj1cImkgaW4gY291bnRcIj5cbiAgICAgIDxlbC1tZW51LWl0ZW0gdi1pZj1cImkgPiA1XCIgOmtleT1cImlcIiA6aW5kZXg9XCJpICsgJydcIj7oj5zljZV7eyBTdHJpbmcoaSkucGFkU3RhcnQoMiwgJzAnKSB9fTwvZWwtbWVudS1pdGVtPlxuICAgIDwvdGVtcGxhdGU+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCBjb3VudCA9IDIwO1xuPC9zY3JpcHQ+IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcbmltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIGNvbnN0IHN0eWxlcyA9IFsnaHR0cHM6Ly9wcmV2aWV3LTE5MTY0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJywgJ2h0dHBzOi8vcHJldmlldy0xOTE2NC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyddLm1hcCgoc3R5bGUpID0+IHtcbiAgICByZXR1cm4gbmV3IFByb21pc2UoKHJlc29sdmUsIHJlamVjdCkgPT4ge1xuICAgICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICAgIGxpbmsuaHJlZiA9IHN0eWxlXG4gICAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICAgIGRvY3VtZW50LmJvZHkuYXBwZW5kKGxpbmspXG4gICAgfSlcbiAgfSlcbiAgcmV0dXJuIFByb21pc2UuYWxsU2V0dGxlZChzdHlsZXMpXG59XG4iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTkxNjQtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiLFxuICAgIFwiQGVsZW1lbnQtcGx1cy9pY29ucy12dWVcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlQDIvZGlzdC9pbmRleC5taW4uanNcIlxuICB9LFxuICBcInNjb3Blc1wiOiB7fVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE5MTY0LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

### CODE REVIEW

**Comment by btea** [comment]
Please add a test case.

**Comment by wen-lun** [comment]
> Please add a test case.

运行测试用例，源码中获取dom元素的offsetWidth和clientWidth的地方都是0，从而导致el-menu的水平模式下无法计算省略位置。
测试用例要如何写才能正确获取offsetWidth或者clientWidth呢

**Comment by wen-lun** [comment]
> Please add a test case.


@btea 运行测试用例，源码中获取dom元素的clientWidth或offsetWidth的地方得到的值都是0，从而导致el-menu组件的水平模式下无法计算省略位置，测试用例要如何写才能正确获取clientWidth或offsetWidth的值呢

**Comment by btea** [comment]
这个好像确实不行，暂时先保持这样吧。

**Review by btea — APPROVED** [review]
Thanks!

**Review by tolking — APPROVED** [review]

**Pull request merged**
