### PR TITLE
feat(components): [el-ellipsis] add a new component 'el-ellipsis'

### LINKED ISSUE #6938: [Feature Request] [New Component]能否新增一个组件用于处理文本缩略场景？
Feature type: **`New Component`**

## Details

- New component name: `el-ellipsis`

## Description

能否新增一个组件用于处理文本缩略场景？提供组件能够自定义文本缩略字数，和缩略位置，例如 ...xxx或xxx...；xxx...xxx。并且能够提供tooltip进行悬浮显示，参考链接:[n-ellipsis](https://www.naiveui.com/zh-CN/os-theme/components/ellipsis)

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
fix: #6938  
Please make sure these boxes are checked before submitting your PR, thank you!
- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@czh740132583 sorry to tell you that we are NOT accepting new components at this moment. Also, new components should be designed by our designers for making it consistent with the design system.

**Comment by sxzz** [comment]
IMHO, it's a great idea! `ellipsis` component doesn't seem to have much style. So, I think we can have it now, and if designer has some suggestion, then we can change it later.

**Comment by czh740132583** [comment]
> IMHO, it's a great idea! `ellipsis` component doesn't seem to have much style. So, I think we can have it now, and if designer has some suggestion, then we can change it later.

Yes, it just shows the text, not too many styles. I know that this component design needs further discussion, and I hope there will be a good result.😂

**Comment by sxzz** [comment]
WDYT /cc @JeremyWuuuuu

**Pull request closed without merging**
