### PR TITLE
fix: convert arrow function to named function

### PR DESCRIPTION
**Pull request by pzzyf**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by pzzyf** [comment]
cc @kooriookami @chenxch 
before
image
after
image

**Review by FrontEndDog — APPROVED** [review]
LGTM！
I tried to disable all vs-code plugins, but the issue still persists,  This can serve as a temporary solution.

**Comment by kooriookami** [comment]
image
Webstorm is OK.

**Comment by pzzyf** [comment]
> image Webstorm is OK.

I found someone who uses vscode and saw that there is something wrong with it.
image

**Comment by FrontEndDog** [comment]
In my tested, This may be an issue with vscode syntax highlighting. The triggering conditions include:
1.Using arrow functions
2.Using Generics
3.Nesting with more than three `<>`
image

**Pull request closed without merging**
