### PR TITLE
feat(components): [el-form] add valid prop

### LINKED ISSUE #3372: [Bug Report] please transfer a valid prop path to form item!
### Element Plus version
1.1.0-beta.9

### OS/Browsers version
macos 11.5.2 / chrome 版本 93.0.4577.63（正式版本） (arm64)

### Vue version
3.2.11

### Reproduction Link
https://codepen.io/xiaolannuoyi/pen/BaZZpjV?editors=1010

### Steps to reproduce
当 表单中的key 中含有特殊符号的时候，prop 如何写？

```
     numberValidateForm: {
          metadata:{
		    age: '',
		   'baidu.com/age':''
		}
        },
      rules:{
         metadata:{
		['age']:[{ required: true, message: '年龄不能为空'}],
		["baidu.com/age"]:[{ required: true, message: '年龄不能为空'}]
	}
    }
				
```

 prop="metadata['baidu.com/age']"   会报 `please transfer a valid prop path to form item!` 错误
```
<el-form-item
    label="年龄2"
    prop="metadata['baidu.com/age']"
    
  >
    <el-input
      v-model.number="numberValidateForm.metadata['baidu.com/age']"
      autocomplete="off"
    ></el-input>
  </el-form-item>
```

### What is Expected?
 prop="metadata['baidu.com/age']" 这样使用能正常使用，或者含有特殊符号的key 如何使用prop

### What is actually happening?
 prop="metadata['baidu.com/age']"   会报 `please transfer a valid prop path to form item!` 错误

### PR DESCRIPTION
**Pull request by xiaoxian521**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by xiaoxian521** [comment]
feat: https://github.com/element-plus/element-plus/issues/3372

**Comment by xiaoxian521** [comment]
@sxzzIt's strange Build #Element Plus failed What is the reason?

**Comment by sxzz** [comment]
Just ignore it please. We will fix it later.

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
How about use `lodash` `_.get` directly? WDYT?
https://lodash.com/docs/4.17.15#get

**Comment by xiaoxian521** [comment]
> How about use `lodash` `_.get` directly? WDYT?
> https://lodash.com/docs/4.17.15#get

The structure is different from `this var object = {'a': [{'b': {'c': 3} }] }`

**Comment by sxzz** [comment]
I tries. I think `lodash.get` is very useful.

```
const metadata = {
  'baidu.com/age': 'hello',
  '\'?qwd23r\\': 'world',
};
_.get(metadata, '\'?qwd23r\\');
```

**Comment by xiaoxian521** [comment]
> ```ts
> get
> ```
Do you think `_.get` fits this logic
WechatIMG9
WechatIMG10

**Comment by sxzz** [comment]
```ts
const data = {
  metadata: {
    a: {
      b: {
        'baidu.com/age': 'hello world',
      },
    },
  },
};
console.log(_.get(data, 'metadata.a.b["baidu.com/age"]'));
// It will outputs `hello world
```

**Comment by sxzz** [comment]
You can try it on https://lodash.com/docs/4.17.15 (use Console)

**Comment by xiaoxian521** [comment]
such as ?
```
export function getPropByPath(
  obj: any,
  path: string,
  strict: boolean
): {
  o: unknown
  k: string
  v: Nullable<unknown>
} {
  let tempObj = obj
  let key
  let keyArr = []

  if (obj && hasOwn(obj, path)) {
    key = path
  } else {
    path = path.replace(/\[(\w+)\]/g, '.$1')
    path = path.replace(/^\./, '')

    if (path.includes('[') && path.includes(']')) {
      let endStr = path.split('[')[1]
      endStr = endStr.slice(0, endStr.length - 1).replace(/\'/g, '')
      keyArr = [path.split('[')[0], endStr]
    } else {
      keyArr = path.split('.')
    }
    let i = 0
    for (i; i < keyArr.length - 1; i++) {
      if (!tempObj && !strict) break
      const key = keyArr[i]

      if (key in tempObj) {
        tempObj = tempObj[key]
      } else {
        if (strict) {
          throw new Error('please transfer a valid prop path to form item!')
        }
        break
      }
    }
    key = keyArr[i]
  }
  return {
    o: tempObj,
    k: key,
    v: get(obj, path),
  }
}
```

**Comment by sxzz** [comment]
I think it seems a bit too complicated for us to maintain this function ourselves, so it's better to use lodash directly.

**Comment by sxzz** [comment]
WDYT? @JeremyWuuuuu

**Comment by xiaoxian521** [comment]
@JeremyWuuuuu PTAL?

**Comment by JeremyWuuuuu** [comment]
For me personally I agree with @sxzz
My reasons:

1. Lodash covers tons of edge cases that we might miss.
2. We have to maintain this function for our own might be a problem, we need to add test cases against it, since we cannot think of that much use cases to cover them all which Lodash can.

I would say let's put `_.get` it has been there for like forever so I think that this is good for us, I mean there is no need to reinvent the wheel for this on our own right?

**Review by jw-foss — CHANGES_REQUESTED** [review]
Let's use `_.get` directly.

**Pull request closed without merging**
