### PR TITLE
chore(deps): update vite related dependency for play and docs

### PR DESCRIPTION
**Pull request by tolking**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

---

vite-plugin-pwa - The PWA has been uninstalled and this dependency is no longer needed

unplugin-element-plus - unused dependencies

### CODE REVIEW

**Review by btea — APPROVED** [review]
Looks great, I've been meaning to update. 👍

**Review by warmthsea — APPROVED** [review]

**Comment by warmthsea** [comment]
There seems to be a problem. The types below docs are all lost. It seems to be related to `unplugin-element-plus` and `unplugin-vue-components`.

image

**Review by warmthsea — APPROVED** [review]

**Comment by 2840365628** [comment]
为什么无法在浏览器中进行断点调试了，断点行数存在偏差？

**Comment by tolking** [comment]
调试应该没有问题，断点行数存在偏差倒是遇到过，我也没有详细去了解过

**Comment by 2840365628** [comment]
> 调试应该没有问题，断点行数存在偏差倒是遇到过，我也没有详细去了解过

但是用2.8.7的版本可以正常在浏览器调试，到2.8.8就不行了， 比如我对el-select的onOptionCreate方法断点，只会在刷新页面执行一次，后续手动创建的项 都不会走到找个断点里，这确实比较奇怪 😂

**Comment by 2840365628** [comment]
> 调试应该没有问题，断点行数存在偏差倒是遇到过，我也没有详细去了解过

我在vite的问题中看到vite5版本谷歌131版本中断点相关的问题

**Comment by tolking** [comment]
可以在这里发个相关issues的连接，方便跟进问题

**Comment by 2840365628** [comment]
> 可以在这里发个相关issues的连接，方便跟进问题

好的，谢谢

**Comment by 2840365628** [comment]
https://github.com/element-plus/element-plus/issues/18967

**Pull request merged**
