### PR TITLE
refactor: rename el-submenu to el-sub-menu

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

⚠️ **BREAKING CHANGE**

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]

**Comment by Trendymen** [comment]
I believe this's a breacking change! Adter I updated to `1.1.0-beta.4`, my all `<el-submenu>` were rendered as a custom tag. And all my style override class includes `el-submenu` cann't work, I have to rename them to `el-sub-menu`.

**Comment by sxzz** [comment]
Yes, as i wrote above

**Comment by JeremyWuuuuu** [comment]
@Trendymen Yes, this is a breaking change @sxzz have mentioned in the description.

FYI: this should be resolved in the first version of 1.1.0, but for my mistakes that I forgot to do that, since you have already upgraded to `1.1.0-beta.x`, this breaking change is considered acceptable. See the list here: https://github.com/element-plus/element-plus/discussions/3020

**Comment by Trendymen** [comment]
> @Trendymen Yes, this is a breaking change @sxzz have mentioned in the description.
> 
> FYI: this should be resolved in the first version of 1.1.0, but for my mistakes that I forgot to do that, since you have already upgraded to `1.1.0-beta.x`, this breaking change is considered acceptable. See the list here: #3020

Beacuse i'm upgreade from `1.1.0-beta.3`, so I'm shocked.

**Comment by JeremyWuuuuu** [comment]
@Trendymen Sorry for the shocking upgrades, this should be introduced in `1.1.0-beta.1` but I forgot about it, so we were being a little aggressive for upgrading this since 1.1.0 is merely out yesterday. Apologies for this.

**Comment by Trendymen** [comment]
> @Trendymen Sorry for the shocking upgrades, this should be introduced in `1.1.0-beta.1` but I forgot about it, so we were being a little aggressive for upgrading this since 1.1.0 is merely out yesterday. Apologies for this.

It's ok,thanks for your contribution.

**Pull request merged**
