### PR TITLE
fix(build): element plus build typing error

### LINKED ISSUE #5324: [Bug Report] export types missing in latest version
### Element Plus version
1.3.0-beta.4

### OS/Browsers version
-

### Vue version
3.2.26

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0jr35?file=/src/main.ts

Can't reproduce online, need local

### Steps to reproduce
```ts
// in TypeScript
import { ElTag } from 'element-plus'
```

- [v1.3.0-beta.3](https://unpkg.com/browse/element-plus@1.3.0-beta.3/lib/index.d.ts)
- [v1.3.0-beta.4](https://unpkg.com/browse/element-plus@1.3.0-beta.4/lib/index.d.ts)

```diff
- export * from 'element-plus/es/components';
+ export * from '@element-plus/components';
```

Maybe the symbol `@` is causing the error

### What is Expected?
success

### What is actually happening?
Module '"element-plus"' has no exported member 'ElTag'. Did you mean to use 'import ElTag from "element-plus"' instead?

### PR DESCRIPTION
**Pull request by jw-foss**
- Remove types field from tsconfig.json

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by iamkun** [comment]
fixed in 1.3.0-beta.5

**Comment by czq297297** [comment]
什么时候发布下一版

**Comment by JeremyWuuuuu** [comment]
@czq297297 It is on the way, see the pipeline: https://github.com/element-plus/element-plus/actions/runs/1685703255

**Comment by JeremyWuuuuu** [comment]
@tolking @czq297297 Already published.

**Pull request merged**
