### PR TITLE
feat(theme-chalk): [form] add default width to Input in inline form

### LINKED ISSUE #7287: [Bug Report] [Component] [input] clearable 会动态改变宽度
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.31`
- Element Plus Version: `2.1.10`
- Browser / OS: `chrome 99.0.4844.82`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtZm9ybSBpbmxpbmU+XG4gICAgPGVsLWZvcm0taXRlbT5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIGNsZWFyYWJsZSAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICA8L2VsLWZvcm0+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IGlucHV0ID0gcmVmKCcnKVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XCJpbXBvcnRzXCI6e319In0=)

### Steps to reproduce

在表单组件下，input组件增加clearable属性，input组件宽度会动态变化
```vue
  <el-form inline>
    <el-form-item>
      <el-input v-model="input" placeholder="Please input" clearable />
    </el-form-item>
  </el-form>
```

### What is Expected?

不会变化宽度

### What is actually happening?

宽度动态变化

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by tolking**
close #7287

`220px` = `--el-date-editor-width`
 
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

- [before](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENhbGVuZGFyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuY29uc3QgaW5wdXQgPSByZWYoJycpXG5jb25zdCBudW1iZXIgPSByZWYoMClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIGlubGluZT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiaW5wdXRcIiBsYWJlbC13aWR0aD1cIjEwMFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cInBhc3N3b3JkXCIgbGFiZWwtd2lkdGg9XCIxMDBcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIGNsZWFyYWJsZSBzaG93LXBhc3N3b3JkIHR5cGU9XCJwYXNzd29yZFwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cInN1ZmZpeFwiIGxhYmVsLXdpZHRoPVwiMTAwXCI+XG4gICAgXHQ8ZWwtaW5wdXRcbiAgICAgICAgdi1tb2RlbD1cImlucHV0XCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF0ZVwiXG4gICAgICAgIDpzdWZmaXgtaWNvbj1cIkNhbGVuZGFyXCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJudW1iZXJcIiBsYWJlbC13aWR0aD1cIjEwMFwiPlxuICAgICAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtYmVyXCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImN1c3RvbSB3aWR0aFwiIGxhYmVsLXdpZHRoPVwiMTAwXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBjbGVhcmFibGUgY2xhc3M9XCJtLWlucHV0XCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLm0taW5wdXQge1xuICB3aWR0aDogMjUwcHggIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

- [after](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IENhbGVuZGFyIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG4gIFxuY29uc3QgaW5wdXQgPSByZWYoJycpXG5jb25zdCBudW1iZXIgPSByZWYoMClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC1mb3JtIGlubGluZT5cbiAgICA8ZWwtZm9ybS1pdGVtIGxhYmVsPVwiaW5wdXRcIiBsYWJlbC13aWR0aD1cIjEwMFwiPlxuICAgICAgPGVsLWlucHV0IHYtbW9kZWw9XCJpbnB1dFwiIHBsYWNlaG9sZGVyPVwiUGxlYXNlIGlucHV0XCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cInBhc3N3b3JkXCIgbGFiZWwtd2lkdGg9XCIxMDBcIj5cbiAgICAgIDxlbC1pbnB1dCB2LW1vZGVsPVwiaW5wdXRcIiBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiIGNsZWFyYWJsZSBzaG93LXBhc3N3b3JkIHR5cGU9XCJwYXNzd29yZFwiIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cInN1ZmZpeFwiIGxhYmVsLXdpZHRoPVwiMTAwXCI+XG4gICAgXHQ8ZWwtaW5wdXRcbiAgICAgICAgdi1tb2RlbD1cImlucHV0XCJcbiAgICAgICAgcGxhY2Vob2xkZXI9XCJQaWNrIGEgZGF0ZVwiXG4gICAgICAgIDpzdWZmaXgtaWNvbj1cIkNhbGVuZGFyXCJcbiAgICAgICAgY2xlYXJhYmxlXG4gICAgICAvPlxuICAgIDwvZWwtZm9ybS1pdGVtPlxuICAgIDxlbC1mb3JtLWl0ZW0gbGFiZWw9XCJudW1iZXJcIiBsYWJlbC13aWR0aD1cIjEwMFwiPlxuICAgICAgPGVsLWlucHV0LW51bWJlciB2LW1vZGVsPVwibnVtYmVyXCIgY2xlYXJhYmxlIC8+XG4gICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgPGVsLWZvcm0taXRlbSBsYWJlbD1cImN1c3RvbSB3aWR0aFwiIGxhYmVsLXdpZHRoPVwiMTAwXCI+XG4gICAgICA8ZWwtaW5wdXQgdi1tb2RlbD1cImlucHV0XCIgcGxhY2Vob2xkZXI9XCJQbGVhc2UgaW5wdXRcIiBjbGVhcmFibGUgY2xhc3M9XCJtLWlucHV0XCIgLz5cbiAgICA8L2VsLWZvcm0taXRlbT5cbiAgPC9lbC1mb3JtPlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLm0taW5wdXQge1xuICB3aWR0aDogMjUwcHggIWltcG9ydGFudDtcbn1cbjwvc3R5bGU+XG4iLCJQbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTI4OTctZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTEyODk3LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xMjg5Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xMjg5Ny1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

### CODE REVIEW

**Review by YunYouJun — APPROVED** [review]

**Review by YunYouJun — APPROVED** [review]

**Comment by YunYouJun** [comment]
Should we add a few examples to the document?

**Review by ryuhangyeong — APPROVED** [review]

**Review by btea — APPROVED** [review]

**Review by chenxch — APPROVED** [review]
Need to evaluate whether something breaks the change.

**Comment by YunYouJun** [comment]
I think we should add a paragraph in docs to describe the strategy.

**Comment by tolking** [comment]
这确实会破坏 Select 组件的宽度

让用户自己设置宽度应该会更好

**Comment by YunYouJun** [comment]
> 这确实会破坏 Select 组件的宽度
> 
> 让用户自己设置宽度应该会更好
> 
> 或者 `.el-form--inline .el-input` -> `.el-form--inline .el-form-item__content > .el-input` 怎么样？

增加更多的类名似乎并没有解决用户自定义宽度的问题？

**Comment by Realybig** [comment]
根本原因是el-date-picker的flex-grow失效导致的
只需要在el-date-picker加上inline-flex !important、宽度100%，然后外层宽度100%就可以了
下面代码是unocss加的样式
```html
<div class="w-full">
  <el-date-picker
    v-model="form.established"
    type="date"
    value-format="YYYY-MM-DD"
    placeholder="请输入选择共同体成立时间"
    class="important-w-full important-inline-flex"
  />
</div>
```

**Pull request merged**
