### PR TITLE
feat(components): [scrollbar] smooth animation

### PR DESCRIPTION
**Pull request by Benleie**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

[ElScrollbar to add animation effects](https://github.com/element-plus/element-plus/issues/6174)

### CODE REVIEW

**Comment by Benleie** [comment]
@kooriookami

**Comment by Benleie** [comment]
https://element-plus.org/en-US/component/scrollbar.html#manual-scroll

**Comment by kooriookami** [comment]
I mean the style is controlled by user. You don't need to make a PR.

**Comment by Benleie** [comment]
This PR makes scrolling behavior more reasonable in most cases. A user can alter it by css if he really needs auto scroll-behavior.

**Comment by emojiiii** [comment]
> This PR makes scrolling behavior more reasonable in most cases. A user can alter it by css if he really needs auto scroll-behavior.

Not everyone needs it

**Comment by Benleie** [comment]
> Not everyone needs it

Ok, and you can close [this Feature Request](https://github.com/element-plus/element-plus/issues/6174). @emojiiii

**Pull request closed without merging**
