### PR TITLE
feat(input-number): add input-number component

### PR DESCRIPTION
**Pull request by xiaofeng-bm**
- [ ] Component Migration

Fix #

### CODE REVIEW

**Comment by zazzaz** [comment]
Hi, anything I can help?

**Comment by xiaofeng-bm** [comment]
> Hi, anything I can help?

A test case won't pass, but I can't find out why.

**Comment by zazzaz** [comment]
image

**Comment by xiaofeng-bm** [comment]
我知道是这里，但我觉得我这里写的没错，本地测试也正常。再加上，感觉实现的不怎么好，就想着关了这个issues不弄了，后来又想试试，又重现打开了。

**Comment by JeremyWuuuuu** [comment]
Try `yarn test --runInBand`. if this doesn't reproduce your error, you might need download docker to get exact same env as the test case ran by `Github Action`

**Comment by g3r4n** [comment]
@xiaofeng-bm can you merge the latest dev and fix the lint errors please ?

**Comment by xiaofeng-bm** [comment]
OK

**Comment by xiaofeng-bm** [comment]
> @xiaofeng-bm can you merge the latest dev and fix the lint errors please ?

Modifications completed

**Pull request merged**
