### PR TITLE
feat(components): [el-message] merge the same content messages(#3836)

### LINKED ISSUE #3836: [feature request] a maximum pop-up quantity limit should be added to the message
### Existing Component
是

### Component Name
Message 

### Description
在有些情况下,可能会出现很多个Message弹出框,直接铺满整个页面之类的
这样可能会显示不太友好,
建议新增可以设置超过一定数量,
应该把之前得提前已打开自动关闭掉.

### PR DESCRIPTION
**Pull request by zhazhanitian**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

feat: [3836](https://github.com/element-plus/element-plus/issues/3836)

### CODE REVIEW

**Review by HerringtonDarkholme — CHANGES_REQUESTED** [review]
`polymerization` is a chemistry terminology. `grouping` will be a better naming.

**Comment by zhazhanitian** [comment]
> terminology

OK, I'll adjust it

**Review by sxzz — APPROVED** [review]

**Comment by adaex** [comment]
@zhazhanitian Since the `dev` branch has made some changes, this branch has some conflicts, can you resolve it?

**Comment by sxzz** [comment]
@adaex Let me handle this.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@HerringtonDarkholme Could you take a look on this?

**Comment by JeremyWuuuuu** [comment]
@ zhazhanitian can we add a demo for this feature? I think it is worth it.

**Comment by zhazhanitian** [comment]
> @zhazhanitian can we add a demo for this feature? I think it is worth it.

OK，I'll open a new branch to add. Is that all right？

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu 
I plan to add on the new branch, but I find that this function has not been incorporated into dev. do you want me to add it on this PR?

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu I plan to add on the new branch, but I find that this function has not been incorporated into dev. do you want me to add it on this PR?

Just add it in the branch would be good, no need to create another PR for this since this demo is related to your commitment.

**Comment by zhazhanitian** [comment]
OK

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu 
I encountered a problem. I added an example file, but the new parameters could not be resolved.

Should I first reference the local El-message file for development? after development, change to global application?

**Comment by zhazhanitian** [comment]
image

**Comment by JeremyWuuuuu** [comment]
@zhazhanitian You can just ignore the error, it will render correctly, no worries.

**Comment by zhazhanitian** [comment]
> @zhazhanitian您可以忽略错误，它会正确呈现，不用担心。

OK

**Comment by zhazhanitian** [comment]
@JeremyWuuuuu 

add complete.

**Comment by zhazhanitian** [comment]
image

**Review by HerringtonDarkholme — COMMENTED** [review]
LGTM

**Pull request merged**
