### PR TITLE
feat(components): [pagination] format the `total` number

### PR DESCRIPTION
**Pull request by baiwusanyu-c**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

我增加了一个props属性 totalFormat ，使得分页组件能够对外提供自定义显示总数的数字能力（[#10293 ](https://github.com/element-plus/element-plus/discussions/10293)），因为据我了解到，不同于中国大陆，许多国家对数字的使用习惯是不一样的，其中就包含千分符这种使用方式（10,000）

I added a `props` property `totalFormat`, which is a function that enables the `el-pagination` component to provide the ability to customize the number of displayed totals（[#10293 ](https://github.com/element-plus/element-plus/discussions/10293)）. Because as far as I know, different from mainland China, many countries have different usage habits for numbers, including the use of thousand separators.（10,000）

### CODE REVIEW

**Comment by baiwusanyu-c** [comment]
> 👋 @baiwusanyu-c, thank you for contributing element-plus.
> 
> * You can comment with `/label Components:[component_name]` to add a label for which component you are working on.
> * You may join our Discord for staying tuned.

**Comment by webvs2** [comment]
If you look at this proposal, which is being passed, it includes displays of different values, like thousandths, placeholders, and so on #10212  @baiwusanyu-c

**Comment by baiwusanyu-c** [comment]
> 
I voted yes for you, but you know it's kinda hard, ep isn't very active in the community right now

**Comment by webvs2** [comment]
Thanks for your vote, yes, it's a little hard, I've developed the code, but it's better than nothing, keep hoping

**Comment by webvs2** [comment]
我也喜欢三体，贡献如同火炬，照亮黑暗森林。https://note.youdao.com/s/2HDMDjhf，闲话小叙♪(´▽｀)

**Pull request closed without merging**
