### PR TITLE
fix(style): icon font-size inherit

### LINKED ISSUE #4604: [bug report] the icon size in the component does not change with the size of the component
### Element Plus version
1.2.0-beta.4

### OS/Browsers version
Windows10/Chrome 96.0.4664.45（正式版本）（64 位）

### Vue version
3.2.23

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-t3843?file=/src/App.vue

### Steps to reproduce
使用ElButton等组件得icon属性

### What is Expected?
组件内的图标应该随着组件的size的变化而变化

### What is actually happening?
带有图标的组件，比如  ElInput、ElButton、ElDatePicker等组件，在设置 了size后，组件内的图标是固定大小，而字号是变化的大小

### PR DESCRIPTION
**Pull request by YunYouJun**
- icon inherit font-size to avoid spreading height of button with icon

close #4604

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by msidolphin** [comment]
What does this pr want to fix? the size property will be deprecation after this adjustment

**Comment by YunYouJun** [comment]
> What does this pr want to fix? the size property will be deprecation after this adjustment

Auto icon size for different parent. See #4604.

**Review by sxzz — APPROVED** [review]

**Comment by someGenki** [comment]
我说icon的size属性怎么不生效了呢...

**Comment by YunYouJun** [comment]
> 我说icon的size属性怎么不生效了呢...

可以通过直接设置 font-size 修改尺寸。

**Comment by huisir001** [comment]
我说icon的size属性怎么不能用了

**Pull request merged**
