### PR TITLE
docs(components): [el-popover] add missing `effect` option

### PR DESCRIPTION
**Pull request by ghiscoding**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@ghiscoding Seems good, could you please run `pnpm format` or `pnpm prettier -w docs`  in you local environment to get the linter passed?

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
If you are using VSCode and you have installed `Prettier` plugin, with the `meta` + `shift` + `f` key you can format the code without running the command I mentioned above, but the command is recommend.

**Comment by ghiscoding** [comment]
@JeremyWuuuuu 
Would it be possible to merge without this request? I don't really want to install Prettier just to make this 1 small contribution, which actually comes from a copy & paste from the tooltip component. If that is really a problem then I would rather close the PR

**Comment by JeremyWuuuuu** [comment]
@ghiscoding understood. I can upload a suggestion in the comment you can simply apply that suggestion then we should be able to make this merged. WDYT?

**Comment by ghiscoding** [comment]
I'm not entirely sure about your suggestion but I would opt for whatever is the easiest, if you want to apply the change yourself I'm ok with that too.

**Comment by JeremyWuuuuu** [comment]
@ghiscoding I've just updated the code, thank you for contributing!

**Pull request merged**
