### PR TITLE
fix(components): [focus-trap] maximum call stack size exceeded error

### LINKED ISSUE #8201: [Bug Report] dropdown组件点击下拉选项有一定的概率报如下错误：Maximum call stack size exceeded
### Element Plus version
2.2.5

### OS/Browsers version
Chrome 102.0.5005.63 / Windows 10 64位

### Vue version
3.2.37

### Reproduction Link
https://codepen.io/christopherkeith/pen/rNJqPeW

### Steps to reproduce
第一步，使用如下代码或打开复现链接：
```html
<html>
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1.0" />
    <script src="https://unpkg.com/vue@3.2.37/dist/vue.global.js"></script>
    <!-- import CSS -->
    <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
    <!-- import JavaScript -->
    <script src="https://unpkg.com/element-plus@2.2.5/dist/index.full.js"></script>
    <title>Element Plus demo</title>
  </head>
  <body>
    <div id="app">
      <el-dropdown>
    <span class="el-dropdown-link">
      Dropdown List
    </span>
    <template #dropdown>
      <el-dropdown-menu>
        <el-dropdown-item>Action 1</el-dropdown-item>
        <el-dropdown-item>Action 2</el-dropdown-item>
        <el-dropdown-item>Action 3</el-dropdown-item>
        <el-dropdown-item disabled>Action 4</el-dropdown-item>
        <el-dropdown-item divided>Action 5</el-dropdown-item>
      </el-dropdown-menu>
    </template>
  </el-dropdown>
    </div>
    <script>
      const App = {
        data() {
          return {
            message: "Hello Element Plus",
          };
        },
      };
      const app = Vue.createApp(App);
      app.use(ElementPlus);
      app.mount("#app");
    </script>
  </body>
</html>

```
第二步：
将鼠标移到dropdown组件上（先不点击），反复点击出现的下拉菜单，有较大的概率会出现"Maximum call stack size exceeded"的报错，如下图
动图展示

### What is Expected?
不报错

### What is actually happening?
报错"Maximum call stack size exceeded"

### PR DESCRIPTION
**Pull request by webfansplz**
Closes #8201

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by webfansplz** [comment]
[Issue Reproduction](https://codepen.io/christopherkeith/pen/rNJqPeW)

[Issue Fixed Playground Prview](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgIDxlbC1kcm9wZG93bj5cbiAgICA8c3BhbiBjbGFzcz1cImVsLWRyb3Bkb3duLWxpbmtcIj5cbiAgICAgIERyb3Bkb3duIExpc3RcbiAgICA8L3NwYW4+XG4gICAgPHRlbXBsYXRlICNkcm9wZG93bj5cbiAgICAgIDxlbC1kcm9wZG93bi1tZW51PlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbT5BY3Rpb24gMTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0+QWN0aW9uIDI8L2VsLWRyb3Bkb3duLWl0ZW0+XG4gICAgICAgIDxlbC1kcm9wZG93bi1pdGVtPkFjdGlvbiAzPC9lbC1kcm9wZG93bi1pdGVtPlxuICAgICAgICA8ZWwtZHJvcGRvd24taXRlbSBkaXNhYmxlZD5BY3Rpb24gNDwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgICAgPGVsLWRyb3Bkb3duLWl0ZW0gZGl2aWRlZD5BY3Rpb24gNTwvZWwtZHJvcGRvd24taXRlbT5cbiAgICAgIDwvZWwtZHJvcGRvd24tbWVudT5cbiAgICA8L3RlbXBsYXRlPlxuICA8L2VsLWRyb3Bkb3duPlxuPC90ZW1wbGF0ZT5cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy04MjE4LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AdnVlL3J1bnRpbWUtZG9tQGxhdGVzdC9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCIsXG4gICAgXCJAdnVlL3NoYXJlZFwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9zaGFyZWRAbGF0ZXN0L2Rpc3Qvc2hhcmVkLmVzbS1idW5kbGVyLmpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctODIxOC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCIsXG4gICAgXCJAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQGVsZW1lbnQtcGx1cy9pY29ucy12dWVAMi9kaXN0L2luZGV4Lm1pbi5qc1wiXG4gIH0sXG4gIFwic2NvcGVzXCI6IHt9XG59IiwiZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy04MjE4LWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ1xuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICB9KVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTgyMTgtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=)

**Comment by jw-foss** [comment]
@Giwayume could you please help review this one? I don't think this is how we solve a maximum call stack error, this is just avoiding it from being reported. You will still call the function with the same frequency.

**Comment by Giwayume** [comment]
Ok, I'll check it out when I get a chance

**Comment by Giwayume** [comment]
Well, this issue is both difficult to reproduce and doesn't seem to impact end-users.

A general debounce for this emit probably isn't a good idea, since a lot of components rely on the focus changing within the synchronous timeframe of the last event.

I think it should be the responsibility of the popper content to be aware of the consequences of drawing focus inside of the 'focusin' callback, and handle appropriately:

https://github.com/element-plus/element-plus/blob/dev/packages/components/popper/src/content.vue#L153

Moving the `.focus()` call after trapped.value has already been set to `true` will stop the infinite recursion.

```
const onFocusInTrap = async (event: FocusEvent) => {
  if (props.visible && !trapped.value) {
    if (event.target) {
      focusStartRef.value = event.target as typeof focusStartRef.value
    }
    trapped.value = true
    if (event.relatedTarget) {
      ;(event.relatedTarget as HTMLElement)?.focus()
    }
  }
}
```
```

**Comment by webfansplz** [comment]
> Well, this issue is both difficult to reproduce and doesn't seem to impact end-users.
> 
> A general debounce for this emit probably isn't a good idea, since a lot of components rely on the focus changing within the synchronous timeframe of the last event.
> 
> I think it should be the responsibility of the popper content to be aware of the consequences of stealing focus inside of the 'focusin' callback, and handle appropriately:
> 
> https://github.com/element-plus/element-plus/blob/dev/packages/components/popper/src/content.vue#L153
> 
> Moving the `.focus()` call after `trapped.value` has already been set to `true` will stop the infinite recursion.
> 
> ```
> const onFocusInTrap = async (event: FocusEvent) => {
>   if (props.visible && !trapped.value) {
>     if (event.target) {
>       focusStartRef.value = event.target as typeof focusStartRef.value
>     }
>     trapped.value = true
>     if (event.relatedTarget) {
>       ;(event.relatedTarget as HTMLElement)?.focus()
>     }
>   }
> }
> ```

Updated,it's work fine.Thanks for your review and suggestion ♥️.

**Review by Giwayume — APPROVED** [review]

**Review by btea — APPROVED** [review]

**Comment by lrthorhammer007** [comment]
#webfansplz:fix-dropdown
date_picker when initial value is null choose a date in last month it will trigger this proplem and it has anothor proplem if i choose '2022-06-30' it will jump to choose '2022-06-02'

**Comment by lrthorhammer007** [comment]
> 好吧，这个问题既难以重现，似乎也不会影响最终用户。
> 
> 这种发射的一般去抖动可能不是一个好主意，因为许多组件依赖于在最后一个事件的同步时间范围内改变焦点。
> 
> 我认为 popper 内容应该有责任了解在“focusin”回调中窃取焦点的后果，并适当处理：
> 
> https://github.com/element-plus/element-plus/blob/dev/packages/components/popper/src/content.vue#L153
> 
> 在已经设置为之后移动`.focus()`调用将停止无限递归。`trapped.value``true`
> 
> ```
> const onFocusInTrap = async (event: FocusEvent) => {
>   if (props.visible && !trapped.value) {
>     if (event.target) {
>       focusStartRef.value = event.target as typeof focusStartRef.value
>     }
>     trapped.value = true
>     if (event.relatedTarget) {
>       ;(event.relatedTarget as HTMLElement)?.focus()
>     }
>   }
> }
> ```
hi , i found date_picker when initial value is null choose a date in last month it will trigger this proplem and it has anothor proplem if i choose 2022-06-30 it will jump to choose 2022-06-02

**Pull request merged**
