### PR TITLE
fix(components): removed $forceUpdate call inside the render fn

### PR DESCRIPTION
**Pull request by mexican-jack**
$forceUpdate triggers a re-render in vue so it is not necessary inside a render function. this was
causing an infinite render loop.

#3461

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
**There may be a problem if you delete this line, I will check this.**

**Comment by JeremyWuuuuu** [comment]
@kooriookami PTAL on this one. I think this is P0 type.

**Comment by sxzz** [comment]
I can't reproduce this problem. Could you please provide a reproduction link?

**Comment by codelch** [comment]
> I can't reproduce this problem. Could you please provide a reproduction link?

https://codesandbox.io/s/pensive-margulis-eusdt?file=/index.html
change v-for="val in 3"  to v-for="val in 10"

**Comment by mexican-jack** [comment]
I can no longer replicate this issue as well, it appears to  have been resolved by a previous update.

**Pull request closed without merging**
