### PR TITLE
fix(select): fix filter method is not called when input first letter

### LINKED ISSUE #1705: [Bug Report] No response when type the first letter in 'el-select' component
### Element Plus version
1.0.2-beta.36

### OS/Browsers version
Chrome

### Vue version
3.0.9

### Reproduction Link
https://codepen.io/vanoneang/pen/vYgKmav

### Steps to reproduce
Component: select
1. use property `filter-method` to bind a function `search`
2. print the parameter of the `search()` function 

### What is Expected?
Print the letter

### What is actually happening?
No response when typing the first letter in 'el-select' component

### PR DESCRIPTION
**Pull request by inottn**
fix #1705 

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Have you tested on the condition "multiple being true and remote being true"?

**Comment by JeremyWuuuuu** [comment]
I think it'd be better that we cover the branches.

**Comment by inottn** [comment]
I will solve it soon.

**Comment by inottn** [comment]
@JeremyWuuuuu done~

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
