### PR TITLE
fix(table): fix column insertion disorder

### LINKED ISSUE #1285: [bug report] using V-for loop to generate El table -- columns
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
macos bigsur

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/whimsy/pen/LYRXoXo

### Steps to reproduce
尝试使用日期数组，构建表格列，日期数组经过更新后，列的排序出现错误。
点-号更新数据，再点加号更新回来，列的排序出现问题

### What is Expected?
排序应该按照数组排序

### What is actually happening?
实际会出现乱序

### PR DESCRIPTION
**Pull request by justwiner**
fix #1285

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by Ryan2128** [comment]
I have tested repro and it works very well. However, when I test the complex header, it fails, is there any other way to support it?

**Comment by justwiner** [comment]
Can you provide me with test cases? @Ryan2128

**Comment by Ryan2128** [comment]
```
<template>
  <el-button @click="cols=cols1">+</el-button>
  <el-button @click="cols=cols2">-</el-button>
  <el-table :data="data" style="width: 500px">
    <el-table-column
      v-for="item of cols"
      :key="item.name"
      :prop="item.name"
      :label="item.name"
    >
      <template v-if="item.children" #default>
        <el-table-column
          v-for="innerItem in item.children"
          :key="innerItem.name"
          :prop="innerItem.name"
          :label="innerItem.name"
        />
      </template>
    </el-table-column>
  </el-table>
</template>

<style>
body {
  margin: 0;
}
</style>

<script>
import { defineComponent } from 'vue'
import ElTableColumn from '@element-plus/table/src/table-column'

export default defineComponent({
  components: { ElTableColumn },
  data() {
    return {
      cols: [],
      message: 'Hello Element Plus',
      cols1: [{
        name: '1',
      }, {
        name: '2',
        children: [{
          name: '2-1',
        }, {
          name: '2-2',
        }],
      }, {
        name: '3',
      }, {
        name: '4',
      }],
      cols2: [{
        name: '2',
      }, {
        name: '3',
        children: [{
          name: '3-1',
        }, {
          name: '3-2',
        }],
      }, {
        name: '4',
      }, {
        name: '5',
      }],
      data: [],
    }
  },
  mounted() {
    this.cols = this.cols1
  },
})
</script>

```

**Comment by justwiner** [comment]
@Ryan2128  
I think this commit should solve the current problem

**Review by Ryan2128 — APPROVED** [review]
Test demo passed

**Pull request merged**
