### PR TITLE
docs: side-nav refactor with Vue3

### PR DESCRIPTION
**Pull request by dreamqyq**
Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by iamkun** [comment]
Can you please fix the Conflicting files before this PR get merged?

**Comment by iamkun** [comment]
image
https://preview-1943-element-plus.surge.sh/#/en-US/component/i18n

The font size seems larger than before. Can you please double-check the CSS style?

https://element-plus.org/#/en-US/component/installation

**Comment by dreamqyq** [comment]
> image
> https://preview-1943-element-plus.surge.sh/#/en-US/component/i18n
> 
> The font size seems larger than before. Can you please double-check the CSS style?
> 
> https://element-plus.org/#/en-US/component/installation

@iamkun Thanks for your review, I have fixed side-nav style

**Review by iamkun — APPROVED** [review]

**Comment by iamkun** [comment]
THANKS

**Pull request merged**
