### PR TITLE
fix(components): [message] fix message grouping styles

### LINKED ISSUE #8808: [Component] [message] ElMessage set the grouping to true, the el-badge style is lost
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `macos`
- Build Tool: `Vite`

### Related Component

- `el-message`

### Reproduction Link

[Link](https://stackblitz.com/edit/vitejs-vite-ju4d2k?file=src%2Fmain.ts,src%2Fcomponents%2FHelloWorld.vue,vite.config.ts,package.json,src%2Fstyle.css&terminal=dev)

### Steps to reproduce

ElMessage set the grouping to true, and use `unplugin-element-plus`  vite plugin

### What is Expected?

el-badge has style

### What is actually happening?

ElMessage el-badge style is lost 

### Additional comments

_(empty)_

image

### PR DESCRIPTION
**Pull request by gjfei**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #8808

### CODE REVIEW

**Comment by holazz** [comment]
We also need to import `@element-plus/components/badge/style` in `packages/components/message/style/index.ts`.

**Comment by gjfei** [comment]
> 作为@holazz说，我们也应该添加导入`index.ts`。

我还需要做什么？

**Comment by holazz** [comment]
`packages/components/message/style/index.ts`:

```diff
  import '@element-plus/components/base/style'
+ import '@element-plus/components/badge/style'
  import '@element-plus/theme-chalk/src/message.scss'
```

**Review by YunYouJun — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
@gjfei your PR's test code will fail due to a timeline type issue. The timeline type issue has already been resolved, can you incorporate it into your PR? I will merge after reflection.

**Pull request merged**
