### PR TITLE
fix(components): [table] getColumnIndex is undefined  when unmount

### PR DESCRIPTION
**Pull request by Liao-js**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
Can you provide a use case scenario where the error occurs?

**Comment by Liao-js** [comment]
> Can you provide a use case scenario where the error occurs?

last night, the [PR](https://github.com/element-plus/element-plus/pull/16782) developer raised a question in my gihub, saying that using el-table in vuedraggable would report an error, causing the execution to fail.I didn’t expect that he submitted a PR this morning. Let me close this PR.

**Comment by Liao-js** [comment]
when I saw his question, I also felt that my code was not rigorous enough. Just mentioned this PR

**Comment by Liao-js** [comment]
I will close my [PR](https://github.com/element-plus/element-plus/pull/16782)

**Pull request closed without merging**
