### PR TITLE
chore: upgrade dependencies

### PR DESCRIPTION
**Pull request by sxzz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by sxzz** [comment]
upgrade
- vitepress (docs)
- @types/jest
- @types/lodash
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- @vue/compiler-sfc
- eslint-plugin-vue
- vue
- vue-router
- @vitejs/plugin-vue (play)

**Comment by sxzz** [comment]
@JeremyWuuuuu The unit test on Github failed. But I can't reproduce it on my machine. Could you please check this problem? Thanks.

**Comment by sxzz** [comment]
@JeremyWuuuuu 
`vitepress/dist/node/markdown/plugins/highlight` no longer exists, please consider refactoring.

**Comment by JeremyWuuuuu** [comment]
@sxzz I think I might need to add that dependency on my own.

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu The unit test on Github failed. But I can't reproduce it on my machine. Could you please check this problem? Thanks.
> 
> ```
> FAIL packages/components/time-picker/__tests__/time-picker.spec.ts
>   ● TimePicker(range) › cancel button
> 
>     expect(received).toBe(expected) // Object.is equality
> 
>     Expected: ""
>     Received: [2021-09-24T00:21:15.569Z, 2021-09-25T23:21:15.569Z]
> 
>       479 |     await nextTick()
>       480 |     const vm = wrapper.vm as any
>     > 481 |     expect(vm.value).toBe('')
>           |                      ^
>       482 |     input.trigger('blur')
>       483 |     input.trigger('focus')
>       484 |     await nextTick()
> 
>       at Object.<anonymous> (packages/components/time-picker/__tests__/time-picker.spec.ts:481:22)
> ```
> 
> P.S. I re-run the jobs, now it passed.
> Failed job: https://github.com/element-plus/element-plus/runs/3705450791?check_suite_focus=true

I encountered this failure days ago and I have no idea why, it crashes just like the other random ones, I think this one is not that stable could be buggy.

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
