### PR TITLE
fix: Highlighted the search results of document

### PR DESCRIPTION
**Pull request by zouyaoji**
Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

before
image

after
image

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
Looking good cc @iamkun could you verify this?

BTW, I'd like to ask, the key token you used in the `ci.yml` file needs to be added into this organization right? We might not have that as far as I know. Also cc @iamkun to follow this up

**Comment by zouyaoji** [comment]
https://github.com/element-plus/element-plus/blob/de1e9bd5f8c8206134508f02a5ba98d9a23a2dec/website/components/search.vue#L111

The Application ID used in the document seems to be 4C63BTGP6S. Find the Admin API Key corresponding to it in algolia and add it to the environment variables of project settings in Actions secrets. and name it ALGOLIA_KEY.

**Comment by JeremyWuuuuu** [comment]
> https://github.com/element-plus/element-plus/blob/de1e9bd5f8c8206134508f02a5ba98d9a23a2dec/website/components/search.vue#L111
> 
> The Application ID used in the document seems to be 4C63BTGP6S. Find the Admin API Key corresponding to it in algolia and add it to the environment variables of project settings in Actions secrets. and name it ALGOLIA_KEY.

Whops, seems like the token has been compromised lol.

**Review by jw-foss — APPROVED** [review]

**Comment by zouyaoji** [comment]
Don't worry, This is the public API key to use in your frontend code. This key is only usable for search queries and sending data to the Insights API. as long as the Admin API Key is not be compromised , it is safe.

**Comment by JeremyWuuuuu** [comment]
Follow up: the key has been added to secrets, we should be able to use it in the next build

**Pull request merged**
