### PR TITLE
fix(components): [input] update input value length calculate

### LINKED ISSUE #11801: [Component] [input] el-input 组件在有表情输入的情况下，统计字数显示错误
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.32`
- Browser / OS: `Chrome/110.0.0.0`
- Build Tool: `Vite`

### Related Component

- `el-input`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtaW5wdXRcbiAgICB2LW1vZGVsPVwidGV4dGFyZWFcIlxuICAgIG1heGxlbmd0aD1cIjMwXCJcbiAgICBwbGFjZWhvbGRlcj1cIlBsZWFzZSBpbnB1dFwiXG4gICAgc2hvdy13b3JkLWxpbWl0XG4gICAgdHlwZT1cInRleHRhcmVhXCJcbiAgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5jb25zdCB0ZXh0YXJlYSA9IHJlZign8J+YrycpXG5jb25zb2xlLmxvZyh0ZXh0YXJlYS52YWx1ZS5sZW5ndGgpIC8vIDJcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

```vue
<template>
  <el-input
    v-model="textarea"
    maxlength="30"
    placeholder="Please input"
    show-word-limit
    type="textarea"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
const textarea = ref('😯')
console.log(textarea.value.length) // 2
</script>

```

### What is Expected?

'😯'占据两个字符，el-input 输入框中的统计字符应该展示为 2/30

### What is actually happening?

实际展示为 1/30

### Additional comments

很多 emoji 表情会占据两个字符，而源代码对输入字符长度的计算应该不合理。

```vue
const textLength = computed(() => Array.from(nativeInputValue.value).length)
```

### PR DESCRIPTION
**Pull request by btea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

fix #11801

### CODE REVIEW

**Review by ryuhangyeong — APPROVED** [review]

**Comment by ryuhangyeong** [comment]
LGTM!

**Review by jw-foss — APPROVED** [review]

**Comment by jw-foss** [comment]
@ryuhangyeong Thank you for reviewing PRs, many thanks!!!

**Comment by fisker** [comment]
`Array.from()` is use to fix #2653, now we break it again. So, if samilar issue report again, we'll change it back again? 👎 👎 👎

**Comment by btea** [comment]
I think it is wrong to use `Array.from` here. If you encounter some complex emoji, such as `👨‍👨‍👦‍👦`, the value of `'👨‍👨‍👦‍👦'.length` is 11, and the value of `Array.from('👨‍👨‍👦‍👦').length` is 7. So I think it is better to be consistent with the original.

If we need to deal with some special cases, perhaps we can provide an additional attribute to receive a function, allowing users to customize the character length calculation rules.  I think this should be better.

**Comment by fisker** [comment]
Of course `Array.from` is wrong,  `Intl.Segmenter#segment` should be preferred, but I agree it should be configurable to pass a function to calculate length.

I'm unhappy only because no one checks the history, it's so obvious that original code write in this way on purpose.

**Pull request merged**
