### PR TITLE
fix(docs): fixed the link icon would be duplicated when switching pages

### LINKED ISSUE #7207: [Bug Report] [Docs] [All] There is duplicate icon added to the links of source code after switch language
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.1.9`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `All`

### Reproduction Link

[Docs](https://element-plus.org/zh-CN/component/progress.html#progress-%E6%8F%92%E6%A7%BD)

### Steps to reproduce

1. go to document site
2. switch language
3. switch back

### What is Expected?

no duplicate icon 

### What is actually happening?

duplicate icon

### Additional comments

_(empty)_

### LINKED ISSUE #8851: [Docs] Icon duplication of external links only in chinese docs
Bug Type: **`Docs`**

## Environment

- Vue Version: `3.2.37`
- Element Plus Version: `2.2.9`
- Browser / OS: `chrome 103.0.5060.114 / macos 12.1`
- Build Tool: `Vite`

### Related Component

- `N/A`

### Reproduction Link

[Docs1](https://element-plus.org/zh-CN/component/rate.html#%E6%BA%90%E4%BB%A3%E7%A0%81)
[Docs2](https://element-plus.org/zh-CN/component/radio.html#%E6%BA%90%E4%BB%A3%E7%A0%81)
[Docs3](https://element-plus.org/zh-CN/component/config-provider.html#config-provider-%E5%B1%9E%E6%80%A7)

### Steps to reproduce

open the reproduction link

### What is Expected?

only one external link icon

### What is actually happening?

there are two external link icons

image

### Additional comments

There are many more in the documentation than just the ones already listed

### PR DESCRIPTION
**Pull request by SuperRay3**
fix #7207
fix #8851 

This problem can only be reproduced after build. There is no problem with local development. 

Please make sure these boxes are checked before submitting your PR, thank you!

- [✅] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [✅] Make sure you are merging your commits to `dev` branch.
- [✅] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
@SuperRay3 Hello, I think #8857's solution is more concise, what do you think?

**Comment by btea** [comment]
Could you update your code?

**Comment by SuperRay3** [comment]
> Could you update your code?

Ok, I'll do it now.

**Comment by SuperRay3** [comment]
> Ok, Thank you for your contribution! ❤

Element helps me a lot, I should be the one who says thank you.

**Comment by btea** [comment]
@holazz I think it's ok. Do you have anything to add?

**Review by btea — APPROVED** [review]

**Comment by holazz** [comment]
> @holazz I think it's ok. Do you have anything to add?

Nothing, good job! 🥳

**Comment by btea** [comment]
Ok, let's merge it.

**Pull request merged**
