### PR TITLE
fix(theme-chalk): [select] box-shadow noise

### LINKED ISSUE #16077: [Component] [select, input] el-select focus状态，会出现边框溢出的问题。blur后仍有残留的蓝色像素在角落
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.21`
- Element Plus Version: `2.6.0`
- Browser / OS: `Chrome 122.0.6261.95`
- Build Tool: `Vite`

### Related Component

- `el-select`
- `el-input`

### Reproduction Link

[Docs CN](https://element-plus.gitee.io/zh-CN/component/form.html#%E8%A1%A8%E5%8D%95%E6%A0%A1%E9%AA%8C)

### Steps to reproduce

在文档的 #表单校验 部分，点击 Activity zone 选择器，然后仔细观察选择器边框的左上角。
包括 https://issue.element-plus.org/ issue标题的输入框也出现了同样情况。

### What is Expected?

hover、focus、error各个状态的边框范围一致，仅颜色有变化

### What is actually happening?

focus、error状态时，边框除了颜色变化，还溢出到了应有的范围之外。主要体现在左上角和右上角出现多余的蓝色或红色像素点。
且组件失焦后，蓝色像素点仍存在于左上角和右上角。

### Additional comments

其它版本我不清楚，我之前使用的2.3.14版本无此问题，升级到2.6.0则发现了这个问题。

image

### PR DESCRIPTION
**Pull request by HaceraI**
Please make sure these boxes are checked before submitting your PR, thank you!

- [✔] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [✔] Make sure you are merging your commits to `dev` branch.
- [✔] Add some descriptions and refer to relative issues for your PR.

fix: https://github.com/element-plus/element-plus/issues/16077

References: https://github.com/element-plus/element-plus/pull/11518

Before(Random appearance):
image

After:
image

### CODE REVIEW

**Review by btea — APPROVED** [review]
Thanks!

**Comment by HaceraI** [comment]
Using `translate3d` can solve this problem, but its impact on performance is minimal (usually not, but the more elements there are, the worse the performance). I'm trying another way:
```css
backface-visibility: hidden;
will-change: transform;
```

**Review by tolking — APPROVED** [review]

**Comment by HaceraI** [comment]
Continue to use `translate3d` as a fix.

i will continue to look for a solution in the future, but not now.
part of the test code: https://github.com/HaceraI/element-plus-box-shadow-testing

**Comment by tolking** [comment]
Thanks for your contribution.

**Pull request merged**
