### PR TITLE
D2M

### PR DESCRIPTION
**Pull request by iamkun**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by lmcsu** [comment]
```
declare module 'vue' {
  interface App {
    [INSTALLED_KEY]?: boolean
  }
}
```

That thing in make-installer now breaks "app.use" and other things in all my projects.
What to do?
I can't upgrade from 2.2.2 now..

**Comment by jw-foss** [comment]
@lmcsu I believe this was fixed in 2.2.3

**Comment by tolking** [comment]
link #8106

@jw-foss  This bug still exists in the new version.

@lmcsu Maybe the following is possible

```ts
import type { App } from '@vue/runtime-core'
```

**Comment by lmcsu** [comment]
@jw-foss this literally was added in 2.2.3 and still exists in 2.2.4

@tolking thanks, but now it says "property 'use' doesn't exist on type App" and stuff like that.

Ok, I'll be waiting for some fix in future versions...

**Comment by jw-foss** [comment]
> @jw-foss this literally was added in 2.2.3 and still exists in 2.2.4
> 
> @tolking thanks, but now it says "property 'use' doesn't exist on type App" and stuff like that.
> 
> Ok, I'll be waiting for some fix in future versions...

I'm not really sure what issue we have here, but I will do some investigations with the team, thank you for reporting it BTW, will keep you updated :bow:

**Comment by lmcsu** [comment]
@jw-foss @tolking 
yeah this is fixed now in v2.2.5
thanks everyone :)

**Pull request merged**
