### PR TITLE
fix(components): [cascader] checkbox sync error

### LINKED ISSUE #11435: [Component] [cascader] cascader组件回显问题
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.0-alpha.4`
- Element Plus Version: `2.2.29`
- Browser / OS: `Chrome109.0.0.0`
- Build Tool: `Webpack`

### Related Component

- `el-cascader`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPHA+RGlzcGxheSBhbGwgdGFncyAoZGVmYXVsdCk8L3A+XG4gICAgPGVsLWNhc2NhZGVyICB2LW1vZGVsPVwiYS5iXCIgY29sbGFwc2UtdGFncyA6b3B0aW9ucz1cIm9wdGlvbnNcIiA6cHJvcHM9XCJwcm9wc1wiIGZpbHRlcmFibGUgY2xlYXJhYmxlIC8+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBsYW5nPVwidHNcIiBzZXR1cD5cbmltcG9ydCB7cmVmIH0gZnJvbSAndnVlJ1xuY29uc3QgcHJvcHMgPSB7IG11bHRpcGxlOiB0cnVlIH1cbmxldCBhID0gcmVmKHtcbiAgYjpbXVxufSlcbnNldFRpbWVvdXQoKCk9PntcbiAgYS52YWx1ZS5iID0gW1sxXSxbMTRdXVxufSwwKVxuXG5cblxuY29uc3Qgb3B0aW9ucyA9IFtcbiAge1xuICAgIHZhbHVlOiAxLFxuICAgIGxhYmVsOiAnQXNpYScsXG4gICAgY2hpbGRyZW46IFtcbiAgICBdLFxuICB9LFxuICB7XG4gICAgdmFsdWU6IDE0LFxuICAgIGxhYmVsOiAnRXVyb3BlJyxcbiAgICBjaGlsZHJlbjogW1xuXG4gICAgXSxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAyMyxcbiAgICBsYWJlbDogJ05vcnRoIEFtZXJpY2EnLFxuICAgIGNoaWxkcmVuOiBbXG4gICAgICBcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

1.cascader的options层级只有一层
2.异步为v-model的绑定值赋值

### What is Expected?

cascader的panel回显正常

### What is actually happening?

多选框未被选中，且点击无效

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by acyza**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

为了减少#4443 所说的对性能的影响，给checkbox需要响应式的情况单独套上reactive

fixed #11435

### CODE REVIEW

**Comment by acyza** [comment]
没加reactive渲染10000个option。
图片
加了reactive渲染10000个option。
图片
#4544 
#4443

**Comment by acyza** [comment]
加没加reactive测的都很慢，但测了几次似乎差距都没有成倍增加。
vue3是用的proxy做的响应式，响应式的对性能的影响远没有vue2的大，另外数据量大的用懒加载可能会好一些。

**Comment by acyza** [comment]
[测试代码](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwibS00XCI+XG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJhZGRcIj5hZGQgMTAwMDAgb3B0aW9uPC9lbC1idXR0b24+XG4gICAgPHA+RGlzcGxheSBhbGwgdGFncyAoZGVmYXVsdCk8L3A+XG4gICAgPGVsLWNhc2NhZGVyICB2LW1vZGVsPVwiYS5iXCIgOm9wdGlvbnM9XCJvcHRpb25zXCIgOnByb3BzPVwicHJvcHNcIiAvPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQge3JlZiB9IGZyb20gJ3Z1ZSdcbmNvbnN0IHByb3BzID0geyBtdWx0aXBsZTogdHJ1ZSB9XG5sZXQgYSA9IHJlZih7XG4gIGI6W11cbn0pXG5cbmNvbnN0IG9wdGlvbnMgPSByZWYobmV3IEFycmF5KCkpO1xuZnVuY3Rpb24gYWRkKCl7XG4gIGxldCBfb3B0aW9ucyA9IFtdO1xuICBjb25zdCB0aW1lID0gbmV3IERhdGUoKS5nZXRUaW1lKCk7XG5mb3IodmFyIGk9MDtpPDEwMDAwO2krKylcbiAgX29wdGlvbnMucHVzaCh7XG4gICAgICB2YWx1ZTogaSxcbiAgICAgIGxhYmVsOiBgXyR7aX1fYCxcbiAgICAgIGNoaWxkcmVuOiBbXVxuICB9KVxuICBvcHRpb25zLnZhbHVlID0gX29wdGlvbnM7XG4gIGNvbnNvbGUubG9nKFwiZGlmZjpcIiArIChuZXcgRGF0ZSgpLmdldFRpbWUoKSAtIHRpbWUpKVxufVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

**Review by btea — APPROVED** [review]

**Comment by exherb** [comment]
Is this will merge into the next release?

**Review by tolking — APPROVED** [review]

**Pull request merged**
