### PR TITLE
refactor(components): [slider] use JSX in Unit test

### PR DESCRIPTION
**Pull request by holazz**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — COMMENTED** [review]
Unit Test is failed, could you please check it?
```
Error: Failed to resolve import "../src/slider.vue" from "packages/components/slider/__tests__/slider.test.tsx". Does the file exist?
```

**Comment by holazz** [comment]
@sxzz waiting for #8008, could you merge it first?

**Comment by sxzz** [comment]
Oh, sorry about that. I missed it!😅

**Comment by holazz** [comment]
> Oh, sorry about that. I missed it!😅

I'm not very familiar with git in VS Code, something went wrong and I'm about to reopen a PR.

**Comment by sxzz** [comment]
You can run `git rebase origin/dev` in the next time you wanna update your code to upstream.

**Comment by holazz** [comment]
> You can run `git rebase origin/dev` in the next time you wanna update your code to upstream.

Got it, many thanks!

**Pull request closed without merging**
