### PR TITLE
chore(components): clear deprecated API

### PR DESCRIPTION
**Pull request by kooriookami**
This PR will remove the deprecated API before `2.6.0` (include).

- [x] Wait for next minor version.

### CODE REVIEW

**Comment by btea** [comment]
The corresponding documentation doesn't seem to be updated.

I have another question. After the update is released, users seem to be unable to see older versions of the documentation. So, should we provide detailed descriptions of the discarded slots and props, such as the specific abandoned versions and the replacement writing methods after discarding, etc.

**Comment by kooriookami** [comment]
> The corresponding documentation doesn't seem to be updated.
> 
> I have another question. After the update is released, users seem to be unable to see older versions of the documentation. So, should we provide detailed descriptions of the discarded slots and props, such as the specific abandoned versions and the replacement writing methods after discarding, etc.

There're deprecated tags and description in the doc. They have been deprecated for many versions since added.

image

**Comment by btea** [comment]
Well, what I mean is that the corresponding prompt has been abandoned in the code, so should the corresponding attribute be removed directly from the document?

**Comment by kooriookami** [comment]
> Well, what I mean is that the corresponding prompt has been abandoned in the code, so should the corresponding attribute be removed directly from the document?

Well, I think keep deprecated api in doc is better. We can remove them in `3.0.0`.

**Comment by btea** [comment]
`sub-menu` the deprecated api format is incorrect.
image

**Review by btea — APPROVED** [review]

**Pull request merged**
