### PR TITLE
fixed table cell refresh with row key

### LINKED ISSUE #7619: [Bug Report] [Component] [table, alert] el-table row-key 并不能控制column自定义slot里组件的刷新
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.0`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.60 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-table`
- `el-alert`

### Reproduction Link

[Link](http://5l8.cn/TKO0v)

### Steps to reproduce

【https://element-plus.run生成的地址太长，无法提交上来，这是个很严重的问题，链接已转短地址】
el-table 自定义slot 渲染el-alert组件，关闭底部行自定slot中的el-alert，点击删除顶部的行，底部的el-alert重新渲染出来了。

在el-table后存在手动v-for生成的结构，类似操作后el-alert并未重新渲染

代码：

```vue
<script lang="ts" setup>
import { computed, ref, reactive } from 'vue'

interface User {
  date: string
  name: string
  address: string
}

const search = ref('')
const filterTableData = computed(() =>
  tableData.filter(
    (data) =>
      !search.value ||
      data.name.toLowerCase().includes(search.value.toLowerCase())
  )
)
const handleEdit = (index: number, row: User) => {
  console.log(index, row)
}
const handleDelete = (index: number, row: User) => {
  console.log(index, row, 2)
  tableData.splice(index, 1)
}

const tableData: User[] = reactive([
  {
    date: '2016-05-03',
    name: 'Tom',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-02',
    name: 'John',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-04',
    name: 'Morgan',
    address: 'No. 189, Grove St, Los Angeles',
  },
  {
    date: '2016-05-01',
    name: 'Jessy',
    address: 'No. 189, Grove St, Los Angeles',
  },
])
</script>

<template>
  <el-table :data="filterTableData" style="width: 100%" row-key="date">
    <el-table-column label="Date" prop="date" />
    <el-table-column label="Name" prop="name" />
    <el-table-column label="Name" prop="name">
    	<template #default="scope">
      	<el-input v-model="scope.row.name"></el-input>
        <el-alert title="success alert" type="success" :key="scope.row.date"/>
        {{scope.row.date}}
      </template>
    </el-table-column>
    <el-table-column align="right">
      <template #header>
        <el-input v-model="search" size="small" placeholder="Type to search" />
        
      </template>
      <template #default="scope">
        <el-button size="small" @click="handleEdit(scope.$index, scope.row)"
          >Edit</el-button
        >
        <el-button
          size="small"
          type="danger"
          @click="handleDelete(scope.$index, scope.row)"
          >Delete</el-button
        >
      </template>
    </el-table-column>
  </el-table>
  <div>
    <div v-for="(item, index) in tableData" :key="item.date">
    	{{item.date}}
      <el-alert title="success alert" type="success" :key="item.date"/>
      <el-button
          size="small"
          type="danger"
          @click="handleDelete(index, item)"
          >Delete</el-button>
    </div>
  </div>
</template>
```

### What is Expected?

通过row-key控制不让自定义slot中的组件在之前行删除后重新渲染

### What is actually happening?

删除上部分行，下部分行内的自定义组件重新渲染，导致自定义表格内出现渲染问题

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by paul-xia**
fixed issue：https://github.com/element-plus/element-plus/issues/7619

### CODE REVIEW

**Comment by paul-xia** [comment]
waiting。。。。。。。。。。。。。。。。。

**Review by jw-foss — APPROVED** [review]
The change makes sense to me.

**Comment by JeremyWuuuuu** [comment]
@msidolphin would you mind taking a look on this?

**Review by msidolphin — DISMISSED** [review]

**Comment by msidolphin** [comment]
@paul-xia Please adjust your commit message

**Comment by paul-xia** [comment]
> @paul-xia Please adjust your commit message

It's still have some hidden problem in source code, I need time to review it, so sorry to interrupt the flow.

**Pull request closed without merging**
