### PR TITLE
fix: vue app typing

### LINKED ISSUE #8122: [Bug Report] [TypeScript] [All] 2.2.4版本修改了vue默认的App类型，导致项目App类型错误
Bug Type: **`TypeScript`**

## Environment

- Vue Version: `3.2.33`
- Element Plus Version: `2.2.4`
- Browser / OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36`
- Build Tool: `Vue CLI`

### Related Component

- `All`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uIH0gZnJvbSAndnVlJ1xuaW1wb3J0IHsgdmVyc2lvbiBhcyBFcFZlcnNpb24gfSBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbiAgPGVsLWlucHV0IHYtbW9kZWw9XCJtc2dcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IEVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIm1haW4udHMiOiJpbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHpoQ24gZnJvbSAnZWxlbWVudC1wbHVzL2xpYi9sb2NhbGUvbGFuZy96aC1jbidcbmltcG9ydCAnZWxlbWVudC1wbHVzL2Rpc3QvaW5kZXguY3NzJ1xuXG5pbXBvcnQgeyBjcmVhdGVBcHAgfSBmcm9tICd2dWUnXG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcblxuaW1wb3J0IHJvdXRlciBmcm9tICcuL3JvdXRlcidcblxuY29uc3QgYXBwID0gY3JlYXRlQXBwKEFwcClcblxuYXBwLnVzZShFbGVtZW50UGx1cywge1xuICAgIGxvY2FsZTogemhDblxuICB9KVxuICAudXNlKHJvdXRlcikgLy8g6K+l5aSE5oqlQXBw57G75Z6L5LiN5Yy56YWNIiwiX28iOnt9fQ==)

### Steps to reproduce

1. 在vue3+ts项目中安装element-plus@2.2.4
2. 在main.ts中注册app
3. app.use(router) // 该步骤报错 app类型不匹配

### What is Expected?

还原成正确的App类型

### What is actually happening?

App类型被修改
文件路径：/packages/element-plus/make-installer.ts
declare module 'vue' {
    interface App {
        [INSTALLED_KEY]?: boolean;
    }
}

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by sxzz**
closes #8122

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jw-foss** [comment]
Seems like we are having some typing issue on our own?

**Comment by tolking** [comment]
[build interrupt](https://github.com/element-plus/element-plus/runs/6758449813?check_suite_focus=true#step:7:211)

**Comment by sxzz** [comment]
Fixed.

**Review by jw-foss — APPROVED** [review]

**Comment by rfirefly** [comment]
This will lead to some errors. It seems that element-plus(APP type) has a higher priority，it make `Parameters of type "Router" cannot be assigned to parameters of type "Plugin_2"`

**Comment by sxzz** [comment]
It will fixed in next version.

**Pull request merged**
