### PR TITLE
fix: fixed that when multiple selections and filtering exist at the same time, the placeholder display is abnormal and there are overlapping files #5675#5853

### LINKED ISSUE #5612: [Bug Report] cascader：当同时存在多选和筛选的情况下，placeholder显示异常
### Element Plus version
1.3.0-beta.8

### OS/Browsers version
windows

### Vue version
3.2.29

### Reproduction Link
https://codepen.io/frontyang/pen/bGYbyLX

### Steps to reproduce
1、当同时存在多选和筛选的情况下，placeholder显示异常，有重叠文案
image

2、选中元素后，清空全部选中，placeholder会部分消失
image

### What is Expected?
当同时存在多选和筛选的情况下placeholder能显示正常

### What is actually happening?
1、当同时存在多选和筛选的情况下，placeholder显示异常，有重叠文案
2、选中元素后，清空全部选中，placeholder会部分消失

### PR DESCRIPTION
**Pull request by dingyuanjie**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
Duplicate of #5675, and please replace the title with English.

**Comment by dingyuanjie** [comment]
> Duplicate of #5675, and please replace the title with English.
All right

**Comment by JeremyWuuuuu** [comment]
@dingyuanjie Would you mind updating two screenshots in this thread: 1. before this change. 2. after this change

**Comment by dingyuanjie** [comment]
> @dingyuanjie Would you mind updating two screenshots in this thread: 1. before this change. 2. after this change

#5612

**Pull request closed without merging**
