### PR TITLE
feat(components): [select] add header and footer slot

### PR DESCRIPTION
**Pull request by Cheerwhy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fa9dccf</samp>

This pull request adds header and footer slots to the `Select` component, allowing users to customize the content of the dropdown menu. It updates the documentation, the examples, and the styles to support this feature. It also modifies the `SelectDropdown` component to render the slots if they are provided.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at fa9dccf</samp>

*  Add header and footer slots to Select component ([link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5R72-R91), [link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-1fe792429b649feda5d215381b79aa885bdc2ccba1f3dceb0ae4a454ff58dba5L187-R213), [link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-9bfd95a8f0051f829d273a71e6ae89d2f5b583a6bdb2d808dd5b2e22709b2540R252-R254), [link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-9bfd95a8f0051f829d273a71e6ae89d2f5b583a6bdb2d808dd5b2e22709b2540R283-R285), [link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-fbccbe036487a3369a46c0eca847b4dbc2b9f05620657888774a8ebc49bb0af6L6-R12))
* Add style variables and rules for the header and footer of the dropdown menu ([link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-eb85fc73444e26f19f950007c73a7d86028b1453c33efc86d2b5478ea027c01aR445-R446), [link](https://github.com/element-plus/element-plus/pull/14876/files?diff=unified&w=0#diff-dc343b42c78967f96b7fc034865c012df9157bef2dc409f68129a36fb9d79b3eR92-R101))

### CODE REVIEW

**Review by Cheerwhy — COMMENTED** [review]
ok

**Comment by Cheerwhy** [comment]
[Preview Link](https://preview-14876-element-plus.surge.sh/en-US/component/select.html#header-of-the-dropdown)

**Review by ryuhangyeong — APPROVED** [review]
I find that feature useful. 👍

**Review by btea — COMMENTED** [review]
I left a few minor suggestions, but other than that, everything else looks pretty good.

**Comment by Hoopex** [comment]
@Cheerwhy  
Great work, we would like to see this also in `select-v2`

**Pull request merged**
