### PR TITLE
fix(components): [button] style compatible issue with :not

### PR DESCRIPTION
**Pull request by dreambo8563**
downgrade :not(a,b) to :not(a):not(b) for compatiblity

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by dreambo8563** [comment]
related issues:
https://github.com/element-plus/element-plus/issues/7846
https://github.com/element-plus/element-plus/issues/7869

**Comment by dreambo8563** [comment]
recreate RP for https://github.com/element-plus/element-plus/pull/7882

**Review by jw-foss — APPROVED** [review]

**Review by tolking — APPROVED** [review]
Works normally, no extra styles are generated. thanks for your PR

**Pull request merged**
