### PR TITLE
fix(components): [upload] fileList property watch logic

### LINKED ISSUE #3014: [Bug Report] The el-upload will animate when I put el-radio together or v-if, v-show together. The bug fixed 5 months ago，now it show again.
### Element Plus version
1.0.2-beta.71

### OS/Browsers version
windows 10 19041.867 / Edge 89.0.774.57 , Chrome 89.0.4389.90（正式版本）

### Vue version
3.2.4

### Reproduction Link
https://jsfiddle.net/9pgqcde6/3/

### Steps to reproduce
click the el-radio, the el-upload will animate

### What is Expected?
When click the el-radio, the el-upload will not animate. It will lead to a poor user experience.

### What is actually happening?
click the el-radio, the el-upload will animate

### PR DESCRIPTION
**Pull request by adaex**
fix #3014 

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by adaex** [comment]
😔 I am not sure this is the best solution (although this way can also solve the problem)

In fact, I want to figure out why this `watch` is triggered.

**Comment by JeremyWuuuuu** [comment]
@adaex No worries, good product needs to be polished to be shining, we have time and chances to be better, this is a good sign.

**Comment by kooriookami** [comment]
@adaex Hi, do you want to join element-plus team?

**Comment by adaex** [comment]
> @adaex Hi, do you want to join element-plus team?

Yes, I am very honored to join the element-plus team. I will do my best to contribute to the element-plus.

**Comment by sxzz** [comment]
Merged in #6014

**Pull request closed without merging**
