### PR TITLE
fix(table): fix column insertion disorder BUG

### LINKED ISSUE #1285: [bug report] using V-for loop to generate El table -- columns
### Element Plus version
1.0.1-beta.26

### OS/Browsers version
macos bigsur

### Vue version
3.0.0

### Reproduction Link
https://codepen.io/whimsy/pen/LYRXoXo

### Steps to reproduce
尝试使用日期数组，构建表格列，日期数组经过更新后，列的排序出现错误。
点-号更新数据，再点加号更新回来，列的排序出现问题

### What is Expected?
排序应该按照数组排序

### What is actually happening?
实际会出现乱序

### PR DESCRIPTION
**Pull request by justwiner**
fix #1285

Please make sure these boxes are checked before submitting your PR, thank you!

* [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [ ] Make sure you are merging your commits to `dev` branch.
* [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by Ryan2128 — APPROVED** [review]

**Comment by Wolferring** [comment]
When will this fix release?

**Comment by Ryan2128** [comment]
> When will this fix release?

In next version and the time won't be long.

**Comment by Wolferring** [comment]
it seems not fix the bug...

**Comment by Wolferring** [comment]
https://codepen.io/whimsy/pen/LYRXoXo

**Comment by Wolferring** [comment]
> > When will this fix release?
> 
> In next version and the time won't be long.

with release v1.0.2-beta28,the problem is still there

**Comment by justwiner** [comment]
Yes, there are still some problems that will be fixed soon

**Pull request merged**
