### PR TITLE
improvement(components) [divider] add separator role

### PR DESCRIPTION
**Pull request by ryuhangyeong**
## descriptions 

- Improved a11y of divider component.

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
please do rebase on the dev branch again for getting updated CI code @ryuhangyeong

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu I did the rebasing as you said. By the way, force-pushed is floating in git history. Would this be a problem? Sorry for the stupid question....

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu I did the rebasing as you said. By the way, force-pushed is floating in git history. Would this be a problem? Sorry for the stupid question....

No worries, it won't

**Comment by ryuhangyeong** [comment]
@JeremyWuuuuu Thank you! Can you review this?

https://github.com/element-plus/element-plus/issues/6114#issuecomment-1125966089

**Review by jw-foss — APPROVED** [review]

**Pull request merged**
