### PR TITLE
解决新版chrome中input密码框切换光标位置不对的问题

### PR DESCRIPTION
**Pull request by xiaofeng-bm**
- [ ] Component Migration

Fix #
对应issues： https://github.com/ElemeFE/element/issues/18573

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]
Great!

**Comment by JeremyWuuuuu** [comment]
Before this one gets merged, I think you need to deal with the branch thing, you need to rebase `dev` branch towards your working branch, instead of merge it onto your working branch, the way you were handling the branch is not how we working here.
在这个PR合进`dev`之前, 请先使用 `git rebase` 命令把 `dev` 变基到你到分支上，这是这个仓库开发的要求，你现在做的方式是直接用`git merge` 而我们需要 **rebase**, 请先完善这一点，谢谢

**Comment by Ryan2128** [comment]
@JeremyWuuuuu  This PR have the commits included his previous PR, and I just fix the error of his previous PR.

**Comment by JeremyWuuuuu** [comment]
@Ryan2128 I know, I am asking him to deal with it before it gets merged.

**Comment by JeremyWuuuuu** [comment]
Oh, I just checked it out on storybook, I'm closing this PR due to it is not reproducible in V3
https://deploy-preview-253--element-plus.netlify.app check it out yourselves.

**Comment by Ryan2128** [comment]
@JeremyWuuuuu It should be that he fixed it in this PR. I tried it in other deploy, this behavior is exist.

You can reproduce it in [its password](https://deploy-preview-257--element-plus.netlify.app/?path=/story/input--basic-usage) component.

**Comment by JeremyWuuuuu** [comment]
> @JeremyWuuuuu It should be that he fixed it in this PR. I tried it in other deploy, this behavior is exist.
> 
> You can reproduce it in [its password](https://deploy-preview-257--element-plus.netlify.app/?path=/story/input--basic-usage) component.

Yes you are right. My mistake, the link that I send is the fixed version, sorry for the mistake I made

**Comment by xiaofeng-bm** [comment]
> Before this one gets merged, I think you need to deal with the branch thing, you need to rebase `dev` branch towards your working branch, instead of merge it onto your working branch, the way you were handling the branch is not how we working here.
> 在这个PR合进`dev`之前, 请先使用 `git rebase` 命令把 `dev`变基到你到分支上，这是这个仓库开发的要求，你现在做的方式是直接用`git merge` 而我们需要 **rebase**, 请先完善这一点，谢谢



> Yes you are right. My mistake, the link that I send is the fixed version, sorry for the mistake I made

那我还需要改什么吗，我也是第一次给开源项目贡献代码，整个流程不太懂

**Comment by Ryan2128** [comment]
> 那我还需要改什么吗，我也是第一次给开源项目贡献代码，整个流程不太懂

先把dev分支上的代码rebase到本地，这个PR只需要提交修复的代码，只需要提交下边这次commit就好了。

`fix(input): 解决chrome版本中密码框焦点错位问题`

Rebase不行的话就重新拉一个dev分支只提交修复BUG的代码，然后关掉这个PR重新开一个PR

**Pull request closed without merging**
