### PR TITLE
fix(components): [tree] fix always trigger drag

### LINKED ISSUE #12089: [Component] [tree] ElTree拖拽节点悬停在某个节点上时，不断触发node-drag-enter和node-drag-leave事件
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Electron 22 / macOS 13.1`
- Build Tool: `Vite`

### Related Component

- `el-tree`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtdHJlZVxuICAgIDphbGxvdy1kcm9wPVwiYWxsb3dEcm9wXCJcbiAgICA6YWxsb3ctZHJhZz1cImFsbG93RHJhZ1wiXG4gICAgOmRhdGE9XCJkYXRhXCJcbiAgICBkcmFnZ2FibGVcbiAgICBkZWZhdWx0LWV4cGFuZC1hbGxcbiAgICBub2RlLWtleT1cImlkXCJcbiAgICBAbm9kZS1kcmFnLXN0YXJ0PVwiaGFuZGxlRHJhZ1N0YXJ0XCJcbiAgICBAbm9kZS1kcmFnLWVudGVyPVwiaGFuZGxlRHJhZ0VudGVyXCJcbiAgICBAbm9kZS1kcmFnLWxlYXZlPVwiaGFuZGxlRHJhZ0xlYXZlXCJcbiAgICBAbm9kZS1kcmFnLW92ZXI9XCJoYW5kbGVEcmFnT3ZlclwiXG4gICAgQG5vZGUtZHJhZy1lbmQ9XCJoYW5kbGVEcmFnRW5kXCJcbiAgICBAbm9kZS1kcm9wPVwiaGFuZGxlRHJvcFwiXG4gIC8+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHR5cGUgTm9kZSBmcm9tICdlbGVtZW50LXBsdXMvZXMvY29tcG9uZW50cy90cmVlL3NyYy9tb2RlbC9ub2RlJ1xuaW1wb3J0IHR5cGUgeyBEcmFnRXZlbnRzIH0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvbW9kZWwvdXNlRHJhZ05vZGUnXG5pbXBvcnQgdHlwZSB7XG4gIEFsbG93RHJvcFR5cGUsXG4gIE5vZGVEcm9wVHlwZSxcbn0gZnJvbSAnZWxlbWVudC1wbHVzL2VzL2NvbXBvbmVudHMvdHJlZS9zcmMvdHJlZS50eXBlJ1xuXG5jb25zdCBoYW5kbGVEcmFnU3RhcnQgPSAobm9kZTogTm9kZSwgZXY6IERyYWdFdmVudHMpID0+IHtcbiAgY29uc29sZS5sb2coJ2RyYWcgc3RhcnQnLCBub2RlKVxufVxuY29uc3QgaGFuZGxlRHJhZ0VudGVyID0gKFxuICBkcmFnZ2luZ05vZGU6IE5vZGUsXG4gIGRyb3BOb2RlOiBOb2RlLFxuICBldjogRHJhZ0V2ZW50c1xuKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgZW50ZXI6JywgZHJvcE5vZGUubGFiZWwpXG59XG5jb25zdCBoYW5kbGVEcmFnTGVhdmUgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBsZWF2ZTonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdPdmVyID0gKGRyYWdnaW5nTm9kZTogTm9kZSwgZHJvcE5vZGU6IE5vZGUsIGV2OiBEcmFnRXZlbnRzKSA9PiB7XG4gIGNvbnNvbGUubG9nKCd0cmVlIGRyYWcgb3ZlcjonLCBkcm9wTm9kZS5sYWJlbClcbn1cbmNvbnN0IGhhbmRsZURyYWdFbmQgPSAoXG4gIGRyYWdnaW5nTm9kZTogTm9kZSxcbiAgZHJvcE5vZGU6IE5vZGUsXG4gIGRyb3BUeXBlOiBOb2RlRHJvcFR5cGUsXG4gIGV2OiBEcmFnRXZlbnRzXG4pID0+IHtcbiAgY29uc29sZS5sb2coJ3RyZWUgZHJhZyBlbmQ6JywgZHJvcE5vZGUgJiYgZHJvcE5vZGUubGFiZWwsIGRyb3BUeXBlKVxufVxuY29uc3QgaGFuZGxlRHJvcCA9IChcbiAgZHJhZ2dpbmdOb2RlOiBOb2RlLFxuICBkcm9wTm9kZTogTm9kZSxcbiAgZHJvcFR5cGU6IE5vZGVEcm9wVHlwZSxcbiAgZXY6IERyYWdFdmVudHNcbikgPT4ge1xuICBjb25zb2xlLmxvZygndHJlZSBkcm9wOicsIGRyb3BOb2RlLmxhYmVsLCBkcm9wVHlwZSlcbn1cbmNvbnN0IGFsbG93RHJvcCA9IChkcmFnZ2luZ05vZGU6IE5vZGUsIGRyb3BOb2RlOiBOb2RlLCB0eXBlOiBBbGxvd0Ryb3BUeXBlKSA9PiB7XG4gIGlmIChkcm9wTm9kZS5kYXRhLmxhYmVsID09PSAnTGV2ZWwgdHdvIDMtMScpIHtcbiAgICByZXR1cm4gdHlwZSAhPT0gJ2lubmVyJ1xuICB9IGVsc2Uge1xuICAgIHJldHVybiB0cnVlXG4gIH1cbn1cbmNvbnN0IGFsbG93RHJhZyA9IChkcmFnZ2luZ05vZGU6IE5vZGUpID0+IHtcbiAgcmV0dXJuICFkcmFnZ2luZ05vZGUuZGF0YS5sYWJlbC5pbmNsdWRlcygnTGV2ZWwgdGhyZWUgMy0xLTEnKVxufVxuXG5jb25zdCBkYXRhID0gW1xuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMScsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDEtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMicsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMi0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuICB7XG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXG4gICAgY2hpbGRyZW46IFtcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0xJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMS0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICAgIHtcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMy0yJyxcbiAgICAgICAgY2hpbGRyZW46IFtcbiAgICAgICAgICB7XG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDMtMi0xJyxcbiAgICAgICAgICB9LFxuICAgICAgICBdLFxuICAgICAgfSxcbiAgICBdLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

直接使用文档中ELTree组件的可拖拽节点示例代码
拖拽任意节点到任意上悬停，会不断触发node-drag-enter和node-drag-leave事件

### What is Expected?

期望实现进入某个节点并悬停，只会触发一次node-drag-enter事件。待离开节点时，也只会触发一次node-drag-leave事件。

### What is actually happening?

tree drag enter: Level two 3-1
about:srcdoc:160 tree drag over: Level two 3-1
about:srcdoc:160 tree drag leave: Level two 3-1
about:srcdoc:160 tree drag enter: Level two 3-1
about:srcdoc:160 tree drag over: Level two 3-1
about:srcdoc:160 tree drag end: Level two 3-1 none

### Additional comments

这样就可以根据当前拖拽到某个节点并悬停一定时间后，控制是否展开或关闭当前拖拽悬停的节点

### PR DESCRIPTION
**Pull request by init-qy**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

close #12089

In fact, `oldDropNode !== dropNode` will always be `true`

### CODE REVIEW

**Review by ryuhangyeong — APPROVED** [review]
/cc @element-plus/backers

**Review by btea — APPROVED** [review]
LGTM

**Review by tolking — APPROVED** [review]

**Comment by Surlyyoung** [comment]
请问什么时候发版本？

**Comment by YunYouJun** [comment]
> 请问什么时候发版本？

每周五

**Pull request merged**
