### PR TITLE
feat(components): [select] add destroyOnBlur functionality(#5579)

### PR DESCRIPTION
**Pull request by Bowencn**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
Can you elaborate on your reasoning for doing this?

**Comment by Bowencn** [comment]
> Can you elaborate on your reasoning for doing this?

Because it's about solving this [issues](https://github.com/element-plus/element-plus/issues/5579)

**Comment by kooriookami** [comment]
`destroy-on-close` is better, and consistent with `el-dialog`

**Comment by Bowencn** [comment]
> `destroy-on-close` is better, and consistent with `el-dialog`

so I change it to `destroy-on-close` ?

**Comment by kooriookami** [comment]
Yes, you can change it first. And We need to discuss whether needed to add this prop.

**Comment by Bowencn** [comment]
> Yes, you can change it first. And We need to discuss whether needed to add this prop.

It's been modified.

**Comment by tolking** [comment]
Thank for your contribution.

This PR duplicated with `persistent` attribute.

**Pull request closed without merging**
