### PR TITLE
fix: sass declaration deprecation error

### LINKED ISSUE #17487: [Style] [All] Sass rules deprecation warnings
Bug Type: **`Style`**

## Environment

- Vue Version: `3.4.31`
- Element Plus Version: `2.7.6`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36`
- Build Tool: `Nuxt`

### Related Component

- `All`

### Reproduction Link

[Link](I think reproduction is not needed for this issue)

### Steps to reproduce

start a new nuxt project with @element-plus/nuxt

### What is Expected?

fix [sass](https://sass-lang.com/d/mixed-decls) warnings.

### What is actually happening?

Almost every component throws a warning like
```bash
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

More info: https://sass-lang.com/d/mixed-decls

   ┌──> node_modules\element-plus\theme-chalk\src\mixins\_button.scss
159│     padding: $padding-vertical $padding-horizontal;
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ declaration
   ╵
   ┌──> node_modules\element-plus\theme-chalk\src\button.scss
71 │ ┌   & + & {
72 │ │     margin-left: 12px;
73 │ │   }
   │ └─── nested rule
   ╵
    node_modules\element-plus\theme-chalk\src\mixins\_button.scss 159:3  button-size()
    node_modules\element-plus\theme-chalk\src\button.scss 75:3           @content
    node_modules\element-plus\theme-chalk\src\mixins\mixins.scss 60:5    b()
    node_modules\element-plus\theme-chalk\src\button.scss 23:1           root stylesheet
```

### Additional comments

```json
"dependencies": {
    "@element-plus/icons-vue": "^2.3.1",
    "@element-plus/nuxt": "^1.0.9",
    "element-plus": "^2.7.6",
    "vue": "^3.4.31",
  },
  "devDependencies": {
    "nuxt": "^3.12.3",
    "sass": "^1.77.7",
  },
```

### PR DESCRIPTION
**Pull request by jw-foss**
Based on the major breaking change of Sass: https://sass-lang.com/documentation/breaking-changes/mixed-decls/

* Add `&{}` for wrapping nested css blocks.
* Update files with warnings by applying the `&{}` block and repositioning.

### Screenshot after fixed

CleanShot 2024-07-17 at 09 50 02@2x

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
I upgraded my local sass to version 1.77.8, and then there were a lot of warning messages when I built the style.

image

**Comment by jw-foss** [comment]
> I upgraded my local sass to version 1.77.8, and then there were a lot of warning messages when I built the style.
> 
> image

Yes, this MR is meant to fix this issue caused by the deprecation related to [mixed decl](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)

I'm trying to fix this with minimum code changes, and try not to break anything.

**Comment by warmthsea** [comment]
This modification method requires all components to be modified.

**Comment by jw-foss** [comment]
> This modification method requires all components to be modified.

True, I'm trying to fix them one by one. Try not to break things.

**Review by YunYouJun — APPROVED** [review]

**Comment by YunYouJun** [comment]
The final view looks like it's just format. Are there any new changes?

**Comment by jw-foss** [comment]
> The final view looks like it's just format. Are there any new changes?

This is unfinished work, I will convert it to a draft until I finish all work.

**Review by btea — APPROVED** [review]

**Review by YunYouJun — APPROVED** [review]

**Review by tolking — APPROVED** [review]

**Pull request merged**
