### PR TITLE
feat(components): [menu] add `ellipsisPopperOffset` and `ellipsisIcon` props(#14923)

### LINKED ISSUE #14923: [Component] [menu] menu仅提供了sub-menu的popper-offset属性，但`ellipsis`属性下的sub-menu没有popper-offset控制
Bug Type: **`Component`**

## Environment

- Vue Version: `3.4.0-alpha.1`
- Element Plus Version: `2.4.2`
- Browser / OS: `Chrome`
- Build Tool: `Vite`

### Related Component

- `el-menu`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLW1lbnVcbiAgICA6ZGVmYXVsdC1hY3RpdmU9XCJhY3RpdmVJbmRleDJcIlxuICAgIGNsYXNzPVwiZWwtbWVudS1kZW1vXCJcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgYmFja2dyb3VuZC1jb2xvcj1cIiM1NDVjNjRcIlxuICAgIHRleHQtY29sb3I9XCIjZmZmXCJcbiAgICBhY3RpdmUtdGV4dC1jb2xvcj1cIiNmZmQwNGJcIlxuICAgIEBzZWxlY3Q9XCJoYW5kbGVTZWxlY3RcIlxuICA+XG4gICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjFcIj5Qcm9jZXNzaW5nIENlbnRlcjwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjJcIiA6cG9wcGVyLW9mZnNldD1cIjMwXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPldvcmtzcGFjZTwvdGVtcGxhdGU+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjItNFwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPml0ZW0gZm91cjwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTQtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTQtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPC9lbC1zdWItbWVudT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiM1wiIGRpc2FibGVkPkluZm88L2VsLW1lbnUtaXRlbT5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNFwiPk9yZGVyczwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjVcIiA6cG9wcGVyLW9mZnNldD1cIjMwXCI+XG4gICAgICA8dGVtcGxhdGUgI3RpdGxlPldvcmtzcGFjZTwvdGVtcGxhdGU+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNS0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI1LTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjUtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1zdWItbWVudSBpbmRleD1cIjUtNFwiPlxuICAgICAgICA8dGVtcGxhdGUgI3RpdGxlPml0ZW0gZm91cjwvdGVtcGxhdGU+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI1LTQtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI1LTQtMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI1LTQtM1wiPml0ZW0gdGhyZWU8L2VsLW1lbnUtaXRlbT5cbiAgICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPC9lbC1zdWItbWVudT5cbiAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCI2XCIgOnBvcHBlci1vZmZzZXQ9XCIzMFwiPlxuICAgICAgPHRlbXBsYXRlICN0aXRsZT5Xb3Jrc3BhY2U8L3RlbXBsYXRlPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjYtMVwiPml0ZW0gb25lPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNi0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI2LTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtc3ViLW1lbnUgaW5kZXg9XCI2LTRcIj5cbiAgICAgICAgPHRlbXBsYXRlICN0aXRsZT5pdGVtIGZvdXI8L3RlbXBsYXRlPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNi00LTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNi00LTJcIj5pdGVtIHR3bzwvZWwtbWVudS1pdGVtPlxuICAgICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNi00LTNcIj5pdGVtIHRocmVlPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDwvZWwtc3ViLW1lbnU+XG4gICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiN1wiIDpwb3BwZXItb2Zmc2V0PVwiMzBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+V29ya3NwYWNlPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI3LTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjctMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiNy0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiNy00XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjctNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjctNC0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjctNC0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuICA8L2VsLW1lbnU+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBhY3RpdmVJbmRleCA9IHJlZignMScpXG5jb25zdCBhY3RpdmVJbmRleDIgPSByZWYoJzEnKVxuY29uc3QgaGFuZGxlU2VsZWN0ID0gKGtleTogc3RyaW5nLCBrZXlQYXRoOiBzdHJpbmdbXSkgPT4ge1xuICBjb25zb2xlLmxvZyhrZXksIGtleVBhdGgpXG59XG48L3NjcmlwdD5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

### Steps to reproduce

有人已经提过这个**discuss**讨论，但无人问津。

见：https://github.com/element-plus/element-plus/discussions/14724

烦请关注一下，谢谢~

### What is Expected?

提供一个属性，类似：`morePopperOffset`设置`ellipsis`省略多余菜单的popper偏移

### What is actually happening?

没有

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by zhixiaotong**
- feat(components): [menu] add `ellipsisPopperOffset`、`ellipsisIcon` props
- docs(components): [menu] add `ellipsisPopperOffset`、`ellipsisIcon` props

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 79edca1</samp>

This pull request enhances the menu component by adding two new props: `ellipsis-icon` and `ellipsis-popper-offset`. These props allow users to customize the appearance and position of the ellipsis menu, which shows hidden menu items. The pull request also updates the documentation and adds an example for the new features.

## Related Issue

Fixes #14923 .

### <samp>🤖[[deprecated]](https://githubnext.com/copilot-for-prs-sunset) Generated by Copilot at 79edca1</samp>

*  Add new features to menu component to customize ellipsis menu icon and popper offset ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R22), [link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5L34-R40), [link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R76-R82), [link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R409), [link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5L404-R423))
  * Import `iconPropType` and `Component` types from `utils/props` and `vue` modules ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R22), [link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5L34-R40))
  * Declare `ellipsis-icon` and `ellipsis-popper-offset` props with types, default values, and validators in `menuProps` object ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R76-R82))
  * Pass `ellipsis-popper-offset` prop value to `popperOffset` option of `usePopper` hook in `menu.ts` ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5R409))
  * Render `ellipsis-icon` prop value as default slot of `el-tooltip` component in `menu.ts`, with fallback to default `More` icon ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-f9cfce3f7ed6319f8bb3a5b1fe2c62988bc10954b89bd1f93d7bf3b49fcd5bc5L404-R423))
* Update documentation of menu component to include new section on ellipsis popper offset and icon in `menu.md` ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-68f9957a7840b355dcdda10667dc726edd89eefcade651c450066137e7c5e3a8L54-R82))
* Add new example file for menu component to demonstrate usage of new features in `ellipsis.vue` ([link](https://github.com/element-plus/element-plus/pull/15033/files?diff=unified&w=0#diff-284d278a25fa942ead46e0acbf73f175b25abe3da2a04348a36e2ca1ddc67b9fR1-R30))

### CODE REVIEW

**Comment by zhixiaotong** [comment]
@chenxch 麻烦你审查下呢，看一下是否有问题。谢谢~

**Comment by zhixiaotong** [comment]
https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBNb3JlRmlsbGVkIH0gZnJvbSAnQGVsZW1lbnQtcGx1cy9pY29ucy12dWUnXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGVsLW1lbnVcbiAgICBlbGxpcHNpc1xuICAgIGNsYXNzPVwiZWwtbWVudS1lbGxpcHNpcy1kZW1vXCJcbiAgICBtb2RlPVwiaG9yaXpvbnRhbFwiXG4gICAgOmVsbGlwc2lzLXBvcHBlci1vZmZzZXQ9XCIyMFwiXG4gICAgOmVsbGlwc2lzLWljb249XCJNb3JlRmlsbGVkXCJcbiAgICBzdHlsZT1cIndpZHRoOiA0MDBweFwiXG4gID5cbiAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMVwiPlByb2Nlc3NpbmcgQ2VudGVyPC9lbC1tZW51LWl0ZW0+XG4gICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMlwiIDpwb3BwZXItb2Zmc2V0PVwiMjBcIj5cbiAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+V29ya3NwYWNlPC90ZW1wbGF0ZT5cbiAgICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIyLTFcIj5pdGVtIG9uZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItMlwiPml0ZW0gdHdvPC9lbC1tZW51LWl0ZW0+XG4gICAgICA8ZWwtbWVudS1pdGVtIGluZGV4PVwiMi0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPGVsLXN1Yi1tZW51IGluZGV4PVwiMi00XCI+XG4gICAgICAgIDx0ZW1wbGF0ZSAjdGl0bGU+aXRlbSBmb3VyPC90ZW1wbGF0ZT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0xXCI+aXRlbSBvbmU8L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0yXCI+aXRlbSB0d288L2VsLW1lbnUtaXRlbT5cbiAgICAgICAgPGVsLW1lbnUtaXRlbSBpbmRleD1cIjItNC0zXCI+aXRlbSB0aHJlZTwvZWwtbWVudS1pdGVtPlxuICAgICAgPC9lbC1zdWItbWVudT5cbiAgICA8L2VsLXN1Yi1tZW51PlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCIzXCIgZGlzYWJsZWQ+SW5mbzwvZWwtbWVudS1pdGVtPlxuICAgIDxlbC1tZW51LWl0ZW0gaW5kZXg9XCI0XCI+T3JkZXJzPC9lbC1tZW51LWl0ZW0+XG4gIDwvZWwtbWVudT5cbjwvdGVtcGxhdGU+XG4iLCJzcmMvUGxheWdyb3VuZE1haW4udnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCBBcHAgZnJvbSAnLi9BcHAudnVlJ1xuaW1wb3J0IHsgc2V0dXBFbGVtZW50UGx1cyB9IGZyb20gJy4vZWxlbWVudC1wbHVzLmpzJ1xuc2V0dXBFbGVtZW50UGx1cygpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8QXBwIC8+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE1MDMzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIlxuICB9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsInNyYy9lbGVtZW50LXBsdXMuanMiOiJpbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5pbXBvcnQgRWxlbWVudFBsdXMgZnJvbSAnZWxlbWVudC1wbHVzJ1xuXG5sZXQgaW5zdGFsbGVkID0gZmFsc2VcbmF3YWl0IGxvYWRTdHlsZSgpXG5cbmV4cG9ydCBmdW5jdGlvbiBzZXR1cEVsZW1lbnRQbHVzKCkge1xuICBpZiAoaW5zdGFsbGVkKSByZXR1cm5cbiAgY29uc3QgaW5zdGFuY2UgPSBnZXRDdXJyZW50SW5zdGFuY2UoKVxuICBpbnN0YW5jZS5hcHBDb250ZXh0LmFwcC51c2UoRWxlbWVudFBsdXMpXG4gIGluc3RhbGxlZCA9IHRydWVcbn1cblxuZXhwb3J0IGZ1bmN0aW9uIGxvYWRTdHlsZSgpIHtcbiAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICBjb25zdCBsaW5rID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnbGluaycpXG4gICAgbGluay5yZWwgPSAnc3R5bGVzaGVldCdcbiAgICBsaW5rLmhyZWYgPSAnaHR0cHM6Ly9wcmV2aWV3LTE1MDMzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzJ1xuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignbG9hZCcsIHJlc29sdmUpXG4gICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdlcnJvcicsIHJlamVjdClcbiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICB9KVxufSIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE1MDMzLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19

**Comment by kooriookami** [comment]
ellipsis的菜单也算是一个二级菜单，它们应该用一个popper-offset，理想情况是直接在menu组件上设置。现在popper-offset是在SubMenu上的，这个设计有点问题。
我有个想法，menu上也加上popper-offset属性，默认适用于二级、三级以及折叠菜单。如果SubMenu有自己的popper-offset，则覆盖。
image
image

**Comment by zhixiaotong** [comment]
> ellipsis的菜单也算是一个二级菜单，它们应该用一个popper-offset，理想情况是直接在menu组件上设置。现在popper-offset是在SubMenu上的，这个设计有点问题。 我有个想法，menu上也加上popper-offset属性，默认适用于二级、三级（无限层级）以及折叠菜单。如果SubMenu有自己的popper-offset，则覆盖。 image image @element-plus/backers

目前这个subMenu都可以设置自己的popper的确不合理。若menu可以统一设置，是更好的。这里，如果submenu可以单独设置覆盖，那么ellpsis下的Menu是否也需要有单独设置offset的处理？offset仅作用一层（这个是offsetTop的处理），对于超过二层层级的无限层级菜单不应该生效。你是否同意这个？

**Comment by kooriookami** [comment]
我的建议还是这两点，到时候看看其他人的意见：
1. Menu的popper-offset影响所有层级
2. 不需要单独设置ellpsis的层级

**Comment by zhixiaotong** [comment]
> 我的建议还是这两点，到时候看看其他人的意见：
> 
> 1. Menu的popper-offset影响所有层级
> 2. 不需要单独设置ellpsis的popper-offset

合理，我修改下代码。

**Comment by zhixiaotong** [comment]
我关闭这个pr，重新开启一个。

**Comment by FrontEndDog** [comment]
> 我的建议还是这两点，到时候看看其他人的意见：
> 
> 1. Menu的popper-offset影响所有层级
> 2. 不需要单独设置ellpsis的popper-offset

我同意这两个观点  理由：
1.不管是ellpsis的弹出层还是sub-menu的弹出层，本质都是一个sub-menu，设置其偏移量的地方应该统一，在menu上设置。
2.至于其他的sub-menu，可以有一个设置自身偏移量的地方。sub-menu上的优先级更高。

**Comment by kooriookami** [comment]
@zhixiaotong 其实没必要文档都写出所有的案例，如果一定要写的话，把两个功能分开写，不要写在一起哈。

**Comment by zhixiaotong** [comment]
> @zhixiaotong 其实没必要文档都写出所有的案例，如果一定要写的话，把两个功能分开写，不要写在一起哈。

好，那我就去掉icon的demo效果，只保留popperOffset的demo

**Comment by zhixiaotong** [comment]
20231205173006_rec_

**Pull request closed without merging**
