### PR TITLE
fix(components): [tree-select] won't import succcessfully

### PR DESCRIPTION
**Pull request by 7086cmd**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

---

A possible fix of #7008

### CODE REVIEW

**Comment by chenxch** [comment]
import '@element-plus/theme-chalk/el-tree-select.scss' 需要修改一下哦

**Review by chenxch — CHANGES_REQUESTED** [review]
import '@element-plus/theme-chalk/src/tree-select.scss'

**Comment by chenxch** [comment]
@7086cmd 
 Local testing is available, you need to address the workflows.

**Comment by chenxch** [comment]
> import '@element-plus/theme-chalk/src/tree-select.scss'

This one is wrong, your edit is the correct answer.

**Review by jw-foss — APPROVED** [review]

**Comment by 7086cmd** [comment]
@JeremyWuuuuu It ran successfully just now.

**Comment by JeremyWuuuuu** [comment]
@7086cmd Thank you for your contribution!

**Pull request merged**
