### PR TITLE
fix(components): [form] fix scrollToField bug,add unit test

### LINKED ISSUE #11382: [Component] [tabs, form] el-tabs切换后调用tab页内el-form的scrollToField不生效
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.45`
- Element Plus Version: `2.2.27`
- Browser / OS: `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36`
- Build Tool: `Other`

### Related Component

- `el-tabs`
- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiwgdmVyc2lvbiBhcyB2dWVWZXJzaW9uLCBuZXh0VGljayB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgRXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKCdIZWxsbyBXb3JsZCEnKVxuXG5jb25zdCBhY3RpdmVUYWIgPSByZWYoJ3RhYi0xJyk7XG4gIFxuY29uc3QgdGFiUGFuZVN0eWxlID0gcmVmKHtcbiAgaGVpZ2h0OiAnMjAwcHgnLFxuICBvdmVyZmxvdzogJ2F1dG8nXG59KVxuXG5jb25zdCBmb3JtUmVmID0gcmVmKCk7XG5cbmNvbnN0IGlucHV0Q291bnQgPSAxMDtcbiAgXG5jb25zdCBkZXNpcmVkUHJvcCA9ICdkZXNpcmVkLXByb3AnO1xuXG5jb25zdCB0ZXN0ID0gKCkgPT4ge1xuICBhY3RpdmVUYWIudmFsdWUgPSAndGFiLTInO1xuICBuZXh0VGljaygoKSA9PiB7XG4gICAgZm9ybVJlZi52YWx1ZS5zY3JvbGxUb0ZpZWxkKGRlc2lyZWRQcm9wKTtcbiAgfSk7XG59XG5cbmNvbnN0IG9uVGFiQ2hhbmdlID0gKHRhYk5hbWUpID0+IHtcbiAgaWYgKHRhYk5hbWUgPT09ICd0YWItMicpIHtcbiAgICBmb3JtUmVmLnZhbHVlLnNjcm9sbFRvRmllbGQoZGVzaXJlZFByb3ApO1xuICB9XG59XG5cbmNvbnN0IHJlc2V0ID0gKCkgPT4ge1xuICBhY3RpdmVUYWIudmFsdWUgPSAndGFiLTEnO1xuICBmb3JtUmVmLnZhbHVlLnNjcm9sbFRvRmllbGQoJ2Zvcm0tMScpO1xufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYnMgdi1tb2RlbD1cImFjdGl2ZVRhYlwiIHR5cGU9XCJib3JkZXItY2FyZFwiIEB0YWItY2hhbmdlPVwiXCI+XG4gIFx0PGVsLXRhYi1wYW5lIG5hbWU9XCJ0YWItMVwiIGxhYmVsPVwi56ys5LiA5LiqXCIgOnN0eWxlPVwidGFiUGFuZVN0eWxlXCI+XG4gICAgXHRUQUIxXG4gICAgPC9lbC10YWItcGFuZT5cbiAgXHQ8ZWwtdGFiLXBhbmUgbmFtZT1cInRhYi0yXCIgbGFiZWw9XCLnrKzkuozkuKpcIiA6c3R5bGU9XCJ0YWJQYW5lU3R5bGVcIj5cbiAgICBcdDxlbC1mb3JtIHJlZj1cImZvcm1SZWZcIiBsYWJlbC13aWR0aD1cIjE1MHB4XCI+XG4gICAgICBcdDxlbC1mb3JtLWl0ZW0gdi1mb3I9XCJpIGluICgxLCBpbnB1dENvdW50KVwiIDpwcm9wPVwiJ2Zvcm0tJyArIGlcIiA6bGFiZWw9XCIn6KGo5Y2VJyArIGlcIj5cbiAgICAgICAgXHQ8ZWwtaW5wdXQgLz5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICBcdDxlbC1mb3JtLWl0ZW0gOnByb3A9XCJkZXNpcmVkUHJvcFwiPlxuICAgICAgICAgIDx0ZW1wbGF0ZSAjbGFiZWw+XG4gICAgICAgICAgICA8c3BhbiBzdHlsZT1cImNvbG9yOiB2YXIoLS1lbC1jb2xvci1kYW5nZXIpXCI+5pyf5pyb55yL6KeB55qE6KGo5Y2VPC9zcGFuPlxuICAgICAgICAgIDwvdGVtcGxhdGU+XG4gICAgICAgIFx0PGVsLWlucHV0IHJvd3M9XCI1XCIgLz5cbiAgICAgICAgPC9lbC1mb3JtLWl0ZW0+XG4gICAgICA8L2VsLWZvcm0+XG4gICAgPC9lbC10YWItcGFuZT5cbiAgXHQ8ZWwtdGFiLXBhbmUgbmFtZT1cInRhYi0zXCIgbGFiZWw9XCLnrKzkuInkuKpcIiA6c3R5bGU9XCJ0YWJQYW5lU3R5bGVcIj5cbiAgICBcdFRBQjNcbiAgICA8L2VsLXRhYi1wYW5lPlxuICA8L2VsLXRhYnM+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxMHB4O1wiPlxuICBcdDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJ0ZXN0XCIgdGl0bGU9XCLliIfmjaLliLDigJznrKzkuozkuKrigJ1UQULlubbmmL7npLrigJzmnJ/mnJvnnIvliLDnmoTooajljZXigJ1cIj7mtYvor5U8L2VsLWJ1dHRvbj5cbiAgXHQ8ZWwtYnV0dG9uIHR5cGU9XCJkYW5nZXJcIiBAY2xpY2s9XCJyZXNldFwiPumHjee9rjwvZWwtYnV0dG9uPlxuICA8L2Rpdj5cblxuICA8cD5cbiAgICA8ZWwtaWNvbiBjb2xvcj1cInZhcigtLWVsLWNvbG9yLXByaW1hcnkpXCI+PEVsZW1lbnRQbHVzIC8+PC9lbC1pY29uPlxuICAgIEVsZW1lbnQgUGx1cyB7eyBFcFZlcnNpb24gfX0gKyBWdWUge3sgdnVlVmVyc2lvbiB9fVxuICA8L3A+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

点击“测试”按钮测试。点击“重置”按钮重置测试。

### What is Expected?

当“测试”按钮被点击时，TAB切换到“第二个”TAB，然后表单滚动到“期望看到的表单”处。

### What is actually happening?

当“测试”按钮被点击时，TAB切换到“第二个”TAB，但表单未能滚动到“期望看到的表单”处。

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by BigPengZai**
closed #11382

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
@BigPengZai Hi, thank you for your contribution. However, I don't think this is a bug. Regarding the problem mentioned by #11382, it can be solved according to the method provided by the comment.

**Comment by BigPengZai** [comment]
> @BigPengZai Hi, thank you for your contribution. However, I don't think this is a bug. Regarding the problem mentioned by #11382, it can be solved according to the method provided by the comment.

> @btea get,Thank you for your reply，I think about the operation of scroll, such as throttling function and delay operation. Can increase fault tolerance

**Comment by btea** [comment]
When the `scrollToField` method is called, the general default is that the `el-form` has been rendered, so there is no need for delay. However, there are many uncertain situations in actual usage scenarios, such as #11382. For this situation, it may be more friendly for users to handle it according to the actual situation.

**Comment by btea** [comment]
@BigPengZai For the reasons described above, I will close this PR. If you have any questions, please comment below. ❤️

**Pull request closed without merging**
