### PR TITLE
modify popper and dropdown style

### PR DESCRIPTION
**Pull request by BeADre**
### popper
*before：*
image
*after：*
image

### dropdown
*before：*
image
*after：*
image

### CODE REVIEW

**Comment by zazzaz** [comment]
Thanks for this PR.

The missing style is because in #545 we have removed all the style in `.vue` and plan to move it to the `.sass` file.

And in #562 we have fixed the style of popper.

After #562 gets merged, we can move on to this PR and see what we can improve on Dropdown and DatePicker.

**Comment by BeADre** [comment]
ok

**Comment by zazzaz** [comment]
Thank you, and I'll close this PR at this moment. I believe most of the style error has been fixed. Feel free to open a new one if you find any.

**Comment by BeADre** [comment]
I'll try to find😂

**Pull request closed without merging**
