### PR TITLE
feat: integrate use popper

### PR DESCRIPTION
**Pull request by jw-foss**
* Integrate popper with use popper hook.
* Reorganize code for better readabilities.

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by jw-foss** [comment]
@ryuhangyeong I updated the test case you modified before, the reason is that somehow the `dataset` attributes cannot be set via `v-bind="contentAttrs"` in testing. See the screenshot below 👇 

CleanShot 2023-01-05 at 23 29 48@2x

In this screenshot, the data attributes were successfully updated, but it cannot be set to the DOM element, I have no idea what is causing this 🤔 

IMG_3069

**Comment by ryuhangyeong** [comment]
@jw-foss I'll take a look at it in the evening.

**Comment by ryuhangyeong** [comment]
I found that I could keep the existing test code by calling nextTick one more time.

However, I think the code you wrote is better test code!

```ts
  it('placement', async () => {
    const TOOLTIP_CLASS = 'custom_tooltip'
    const PLACEMENT = 'left'

    mount(() => <Slider tooltip-class={TOOLTIP_CLASS} placement={PLACEMENT} />)

    await nextTick()
    await nextTick() // here

    expect(
      (document.querySelector(`.${TOOLTIP_CLASS}`) as HTMLElement).dataset
        .popperPlacement
    ).toBe(PLACEMENT)
  })
```

**Comment by jw-foss** [comment]
> I found that I could keep the existing test code by calling nextTick one more time.
> 
> However, I think the code you wrote is better test code!
> 
> ```ts
>   it('placement', async () => {
>     const TOOLTIP_CLASS = 'custom_tooltip'
>     const PLACEMENT = 'left'
> 
>     mount(() => <Slider tooltip-class={TOOLTIP_CLASS} placement={PLACEMENT} />)
> 
>     await nextTick()
>     await nextTick() // here
> 
>     expect(
>       (document.querySelector(`.${TOOLTIP_CLASS}`) as HTMLElement).dataset
>         .popperPlacement
>     ).toBe(PLACEMENT)
>   })
> ```

Oh!! Thank you for pointing this out, I think your way is better than mine, my implementation is only a workaround 👍.

**Comment by jw-foss** [comment]
@ryuhangyeong applied your suggestion to the code, thank you for helping out :bow:

**Comment by ryuhangyeong** [comment]
@jw-foss 

Thanks for your reply. I'm looking at your PR. It looks like it will take some time.

It's a little different story, but I'm going to release a project called element-plus-example next week. We need your feedback later!

image

**Comment by jw-foss** [comment]
> @jw-foss
> 
> Thanks for your reply. I'm looking at your PR. It looks like it will take some time.
> 
> It's a little different story, but I'm going to release a project called element-plus-example next week.
> 
> May I ask for your feedback?

Sure 😊

**Review by ryuhangyeong — APPROVED** [review]

**Comment by tolking** [comment]
I found that one possible problem caused by this PR is that the content will not follow the mouse movement as before after used the virtual trigger on Tooltip.

### Recurrence steps

1.  click the `test` button
2. move your mouse

[before](https://element-plus.org/en-US/component/tooltip.html#virtual-triggering)

[after](https://preview-11045-element-plus.surge.sh/en-US/component/tooltip.html#virtual-triggering)

**Comment by jw-foss** [comment]
> I found that one possible problem caused by this PR is that the content will not follow the mouse movement as before after used the virtual trigger on Tooltip.
> 
> ### Recurrence steps
> 1. click the `test` button
> 2. move your mouse
> 
> [before](https://element-plus.org/en-US/component/tooltip.html#virtual-triggering)
> 
> [after](https://preview-11045-element-plus.surge.sh/en-US/component/tooltip.html#virtual-triggering)

I'll look into this.

**Comment by jw-foss** [comment]
@tolking updated, would you mind taking a look again? Thank you!

**Review by tolking — APPROVED** [review]

**Comment by bitjjj** [comment]
这个合并导致trigger行为不一致了。

下面这个例子是合并前的tooltip行为。把trigger设置成click，然后依次点击top按钮，当点击第二个按钮时，第一个按钮上显示的tooltip会自动隐藏。
[Playgroup](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwidG9vbHRpcC1iYXNlLWJveFwiPlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgY2VudGVyXCI+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgICAgICAgICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgICBjb250ZW50PVwiVG9wIExlZnQgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwidG9wLXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj50b3Atc3RhcnQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgICAgICAgICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgICAgIGNvbnRlbnQ9XCJUb3AgQ2VudGVyIHByb21wdHMgaW5mb1wiXG4gICAgICAgIHBsYWNlbWVudD1cInRvcFwiXG4gICAgICA+XG4gICAgICAgIDxlbC1idXR0b24+dG9wPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgICAgICAgICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgICBjb250ZW50PVwiVG9wIFJpZ2h0IHByb21wdHMgaW5mb1wiXG4gICAgICAgIHBsYWNlbWVudD1cInRvcC1lbmRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnRvcC1lbmQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJMZWZ0IFRvcCBwcm9tcHRzIGluZm9cIlxuICAgICAgICBwbGFjZW1lbnQ9XCJsZWZ0LXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5sZWZ0LXN0YXJ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBUb3AgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHQtc3RhcnRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnJpZ2h0LXN0YXJ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiTGVmdCBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwibGVmdFwiXG4gICAgICA+XG4gICAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJtdC0zIG1iLTNcIj5sZWZ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnJpZ2h0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiTGVmdCBCb3R0b20gcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwibGVmdC1lbmRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPmxlZnQtZW5kPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBCb3R0b20gcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHQtZW5kXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5yaWdodC1lbmQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IGNlbnRlclwiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiQm90dG9tIExlZnQgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwiYm90dG9tLXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b20tc3RhcnQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgY29udGVudD1cIkJvdHRvbSBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwiYm90dG9tXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b208L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgY29udGVudD1cIkJvdHRvbSBSaWdodCBwcm9tcHRzIGluZm9cIlxuICAgICAgICBwbGFjZW1lbnQ9XCJib3R0b20tZW5kXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b20tZW5kPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLnRvb2x0aXAtYmFzZS1ib3gge1xuICB3aWR0aDogNjAwcHg7XG59XG4udG9vbHRpcC1iYXNlLWJveCAucm93IHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xufVxuLnRvb2x0aXAtYmFzZS1ib3ggLmNlbnRlciB7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xufVxuLnRvb2x0aXAtYmFzZS1ib3ggLmJveC1pdGVtIHtcbiAgd2lkdGg6IDExMHB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)

但是这个合并以后的行为是：依次点击按钮，前面按钮上显示的tooltip不会自动消失。会同时显示多个tooltip
image

**Comment by jw-foss** [comment]
> 这个合并导致trigger行为不一致了。
> 
> 下面这个例子是合并前的tooltip行为。把trigger设置成click，然后依次点击top按钮，当点击第二个按钮时，第一个按钮上显示的tooltip会自动隐藏。 [Example Play](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2IGNsYXNzPVwidG9vbHRpcC1iYXNlLWJveFwiPlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgY2VudGVyXCI+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgICAgICAgICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgICBjb250ZW50PVwiVG9wIExlZnQgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwidG9wLXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj50b3Atc3RhcnQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgICAgICAgICAgIHRyaWdnZXI9XCJjbGlja1wiXG4gICAgICAgIGNvbnRlbnQ9XCJUb3AgQ2VudGVyIHByb21wdHMgaW5mb1wiXG4gICAgICAgIHBsYWNlbWVudD1cInRvcFwiXG4gICAgICA+XG4gICAgICAgIDxlbC1idXR0b24+dG9wPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgICAgICAgICAgICB0cmlnZ2VyPVwiY2xpY2tcIlxuICAgICAgICBjb250ZW50PVwiVG9wIFJpZ2h0IHByb21wdHMgaW5mb1wiXG4gICAgICAgIHBsYWNlbWVudD1cInRvcC1lbmRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnRvcC1lbmQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJMZWZ0IFRvcCBwcm9tcHRzIGluZm9cIlxuICAgICAgICBwbGFjZW1lbnQ9XCJsZWZ0LXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5sZWZ0LXN0YXJ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBUb3AgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHQtc3RhcnRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnJpZ2h0LXN0YXJ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiTGVmdCBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwibGVmdFwiXG4gICAgICA+XG4gICAgICAgIDxlbC1idXR0b24gY2xhc3M9XCJtdC0zIG1iLTNcIj5sZWZ0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPnJpZ2h0PC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiTGVmdCBCb3R0b20gcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwibGVmdC1lbmRcIlxuICAgICAgPlxuICAgICAgICA8ZWwtYnV0dG9uPmxlZnQtZW5kPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgICA8ZWwtdG9vbHRpcFxuICAgICAgICBjbGFzcz1cImJveC1pdGVtXCJcbiAgICAgICAgZWZmZWN0PVwiZGFya1wiXG4gICAgICAgIGNvbnRlbnQ9XCJSaWdodCBCb3R0b20gcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwicmlnaHQtZW5kXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5yaWdodC1lbmQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IGNlbnRlclwiPlxuICAgICAgPGVsLXRvb2x0aXBcbiAgICAgICAgY2xhc3M9XCJib3gtaXRlbVwiXG4gICAgICAgIGVmZmVjdD1cImRhcmtcIlxuICAgICAgICBjb250ZW50PVwiQm90dG9tIExlZnQgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwiYm90dG9tLXN0YXJ0XCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b20tc3RhcnQ8L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgY29udGVudD1cIkJvdHRvbSBDZW50ZXIgcHJvbXB0cyBpbmZvXCJcbiAgICAgICAgcGxhY2VtZW50PVwiYm90dG9tXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b208L2VsLWJ1dHRvbj5cbiAgICAgIDwvZWwtdG9vbHRpcD5cbiAgICAgIDxlbC10b29sdGlwXG4gICAgICAgIGNsYXNzPVwiYm94LWl0ZW1cIlxuICAgICAgICBlZmZlY3Q9XCJkYXJrXCJcbiAgICAgICAgY29udGVudD1cIkJvdHRvbSBSaWdodCBwcm9tcHRzIGluZm9cIlxuICAgICAgICBwbGFjZW1lbnQ9XCJib3R0b20tZW5kXCJcbiAgICAgID5cbiAgICAgICAgPGVsLWJ1dHRvbj5ib3R0b20tZW5kPC9lbC1idXR0b24+XG4gICAgICA8L2VsLXRvb2x0aXA+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cblxuPHN0eWxlPlxuLnRvb2x0aXAtYmFzZS1ib3gge1xuICB3aWR0aDogNjAwcHg7XG59XG4udG9vbHRpcC1iYXNlLWJveCAucm93IHtcbiAgZGlzcGxheTogZmxleDtcbiAgYWxpZ24taXRlbXM6IGNlbnRlcjtcbiAganVzdGlmeS1jb250ZW50OiBzcGFjZS1iZXR3ZWVuO1xufVxuLnRvb2x0aXAtYmFzZS1ib3ggLmNlbnRlciB7XG4gIGp1c3RpZnktY29udGVudDogY2VudGVyO1xufVxuLnRvb2x0aXAtYmFzZS1ib3ggLmJveC1pdGVtIHtcbiAgd2lkdGg6IDExMHB4O1xuICBtYXJnaW4tdG9wOiAxMHB4O1xufVxuPC9zdHlsZT5cbiIsImltcG9ydF9tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwiX28iOnt9fQ==)
> 
> 但是这个合并以后的行为是：依次点击按钮，前面按钮上显示的tooltip不会自动消失。会同时显示多个tooltip image

@bitjjj  我来看一下，感谢告知。

**Comment by jw-foss** [comment]
@bitjjj https://github.com/element-plus/element-plus/pull/11377 打了个补丁，在迁移的时候忘记替换掉这个 ref 导致的

**Pull request merged**
