### PR TITLE
fix(components): [el-slider] show properly in el-form-item

### LINKED ISSUE #5103: [Bug Report] el-slider runway doesn't show properly in el-form-item with label
### Element Plus version
1.3.0-beta.1

### OS/Browsers version
Windows 11 21H2, Google Chrome 96.0.4664.110

### Vue version
3.2.26

### Reproduction Link
https://codepen.io/techiscy/pen/YzraEKQ

### Steps to reproduce
Please see the code attached.

### What is Expected?
Slider's runway should show properly, and should be veritically aligned with the form label.

### What is actually happening?
Slider's runway disappered when using slider in el-form-item. By the way, the slider in the el-form-item doesn't align vertically with the form label.

### PR DESCRIPTION
**Pull request by Alanscut**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.
fix #5103

### CODE REVIEW

**Comment by kooriookami** [comment]
There has another PR #5091

**Comment by JeremyWuuuuu** [comment]
@Alanscut I'm about to merge the other PR #5091, are these two duplicated? /cc @kooriookami

**Comment by kooriookami** [comment]
> @Alanscut I'm about to merge the other PR #5091, are these two duplicated? /cc @kooriookami

Yes, this PR is duplicated.

**Comment by JeremyWuuuuu** [comment]
Close due to duplication with #5091

**Pull request closed without merging**
