### PR TITLE
fix(components): [date-picker] monthrange类型选择器在输入结束后报错

### LINKED ISSUE #7554: [Bug Report] [Component] [date-picker] monthrange类型选择器在输入结束后报错
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.10`
- Element Plus Version: `2.0.0`
- Browser / OS: `chrome 版本 100.0.4896.127 / Max OS X 12.2.1 `
- Build Tool: `Webpack`

### Related Component

- `el-date-picker`

### Reproduction Link

[CodeSandbox](https://codesandbox.io/s/element-plus-spa-forked-wimx8p?file=/src/main.js)

### Steps to reproduce

1、选择任一日期区间
2、键盘输入修改日期
3、得到错误：pickerOptions.value.parseUserInput is not a function

### What is Expected?

可以在输入框内手动输入日期

### What is actually happening?

报错

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by n0liu**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by emojiiii** [comment]
would you add unit test for this?

**Comment by xxweb123** [comment]
> would you add unit test for this?

I can have a try

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Comment by TadasMil** [comment]
Is this planned to be fixed? @xiaoxian521

**Comment by iarthit** [comment]
这bug还没修复？？？？？？？
我的天

**Comment by Jasonning92** [comment]
这个bug至今还没有修复吧……

**Pull request closed without merging**
