### PR TITLE
docs(docs): [icon] add loops to display icon

### PR DESCRIPTION
**Pull request by lxKylin**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

image

### CODE REVIEW

**Comment by tolking** [comment]
Thank for your contribution. 

I do not understand, why do we need to add it?

**Comment by lxKylin** [comment]
> Thank for your contribution.
> 
> I do not understand, why do we need to add it?

Maybe some users don't know how to loop an icon

**Comment by tolking** [comment]
This doesn't seem necessary.

**Comment by btea** [comment]
Thank you for your contribution. However, I think this should be the usage of dynamic rendering components in Vue, and we don't need to add a separate example.
Moreover, it seems that no one has any questions about this, so maybe we should close it first.

**Pull request closed without merging**
