### PR TITLE
fix(components): cascader panel, checked status is not sync with UI

### PR DESCRIPTION
**Pull request by exherb**
### <samp>🤖 Generated by Copilot at a4126c4</samp>

The pull request improves the reactivity of the cascader panel component and the compatibility of the element-plus installer. It uses the `reactive` function from `vue` to create reactive `Node` objects in `store.ts`.

fix cascader panel, checked status is not sync with UI

### <samp>🤖 Generated by Copilot at a4126c4</samp>

* Make the cascader panel nodes reactive to enable dynamic updates ([link](https://github.com/element-plus/element-plus/pull/13734/files?diff=unified&w=0#diff-6ca8bec8f218071c13b487edabe4a63e55df6b304cd429d1998cecf1a35405c9R2), [link](https://github.com/element-plus/element-plus/pull/13734/files?diff=unified&w=0#diff-6ca8bec8f218071c13b487edabe4a63e55df6b304cd429d1998cecf1a35405c9L31-R32))
  * Import the `reactive` function from `vue` in `store.ts` ([link](https://github.com/element-plus/element-plus/pull/13734/files?diff=unified&w=0#diff-6ca8bec8f218071c13b487edabe4a63e55df6b304cd429d1998cecf1a35405c9R2))
  * Wrap the `Node` instances created from the `data` array with the `reactive` function in `store.ts` ([link](https://github.com/element-plus/element-plus/pull/13734/files?diff=unified&w=0#diff-6ca8bec8f218071c13b487edabe4a63e55df6b304cd429d1998cecf1a35405c9L31-R32))

### CODE REVIEW

**Comment by exherb** [comment]
hi anyone can review this?

**Comment by exherb** [comment]
@btea Hi, do you got time to review this pull request?

**Comment by exherb** [comment]
@ElementPlusBot review

**Comment by btea** [comment]
Can you provide a demo comparison before and after modification? This will give a clearer picture of the problem you're solving.

**Comment by exherb** [comment]
OK, I will build a demo today

**Comment by exherb** [comment]
@btea because the node is not reactive, so checked change will not sync to UI, here is the example

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYsIHZlcnNpb24gYXMgdnVlVmVyc2lvbiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IHZlcnNpb24gYXMgZXBWZXJzaW9uIH0gZnJvbSAnZWxlbWVudC1wbHVzJ1xuaW1wb3J0IHsgRWxlbWVudFBsdXMgfSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcblxuY29uc3QgbXNnID0gcmVmKFtdKVxuY29uc3QgY2FzY2FkZXJQcm9wcyA9IHtcbiAgbXVsdGlwbGU6IHRydWUsXG4gIGxhYmVsOiBcImxhYmVsXCIsXG59XG5jb25zdCBvcHRpb25zID0gW1xuICB7IHZhbHVlOiBcIua5luWNl1wiLCBsYWJlbDogXCLmuZbljZdcIiwgY2hpbGRyZW46IFt7IHZhbHVlOiBcIumVv+aymVwiLCBsYWJlbDogXCLplb/msplcIiB9XSB9LFxuICB7IHZhbHVlOiBcIuWMl+S6rFwiLCBsYWJlbDogXCLljJfkuqxcIiB9LFxuXVxuc2V0VGltZW91dCgoKSA9PiB7XG4gICBtc2cudmFsdWUgPSBbW1wi5YyX5LqsXCJdXVxufSwgMzAwMClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxoMT57eyBtc2cgfX08L2gxPlxuICA8ZWwtY2FzY2FkZXItcGFuZWwgdi1tb2RlbD1cIm1zZ1wiIDpwcm9wcz1cImNhc2NhZGVyUHJvcHNcIiA6b3B0aW9ucz1cIm9wdGlvbnNcIiAvPlxuXG4gIDxwPlxuICAgIDxlbC1pY29uIGNvbG9yPVwidmFyKC0tZWwtY29sb3ItcHJpbWFyeSlcIj48RWxlbWVudFBsdXMgLz48L2VsLWljb24+XG4gICAgRWxlbWVudCBQbHVzIHt7IGVwVmVyc2lvbiB9fSArIFZ1ZSB7eyB2dWVWZXJzaW9uIH19XG4gIDwvcD5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZSxcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl1cbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJfbyI6e319

**Comment by btea** [comment]
Seems to be a duplicate of #11462, I think his solution seems to be better, what do you think?

**Comment by exherb** [comment]
> Seems to be a duplicate of #11462, I think his solution seems to be better, what do you think?

No, I think he Node should be reactive when init to avoid syncing issues. 😂

**Comment by exherb** [comment]
OK

**Pull request closed without merging**
