### PR TITLE
fix(components):  [button] Buttons are misleading after being clicked and in disabled mode fix #13736

### LINKED ISSUE #13736: [Style] [button] button 按钮在点击过后与禁用模式下 具有一定的误导性
Bug Type: **`Style`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.8`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)`
- Build Tool: `Vite`

### Related Component

- `el-button`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6Ijx0ZW1wbGF0ZT5cbiAgPGVsLXJvdyBjbGFzcz1cIm1iLTRcIj5cbiAgICA8ZWwtYnV0dG9uIHR5cGU9XCJwcmltYXJ5XCI+UHJpbWFyeTwvZWwtYnV0dG9uPlxuICAgIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBkaXNhYmxlZD5QcmltYXJ5PC9lbC1idXR0b24+XG4gIDwvZWwtcm93PlxuXG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IGxhbmc9XCJ0c1wiIHNldHVwPlxuaW1wb3J0IHtcbiAgQ2hlY2ssXG4gIERlbGV0ZSxcbiAgRWRpdCxcbiAgTWVzc2FnZSxcbiAgU2VhcmNoLFxuICBTdGFyLFxufSBmcm9tICdAZWxlbWVudC1wbHVzL2ljb25zLXZ1ZSdcbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWUsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwiX28iOnt9fQ==)

### Steps to reproduce

  <el-button type="primary">Primary</el-button>
  <el-button type="primary" disabled>Primary</el-button>
第一个按钮点击一次后与按钮禁用时,有一定的误导性.
不注意看的话,可能认为按钮被禁用了.
对比了其他UI组件,没有相似的问题.

### What is Expected?

button 点击过后与禁用时不应该有误导性

### What is actually happening?

button 点击过后与禁用时具有一定程度的误导性

### Additional comments

可能在劣质的显示器或者老旧的显示器情况下  误导性会加深

image

### PR DESCRIPTION
**Pull request by enhengenheng-hubowen**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 76be2c5</samp>

This pull request adds a new feature to the `button` component that enables the user to prevent the button from being focused after being clicked. It introduces a new prop `PreventFocus` and a custom `mousedown` event to achieve this behavior.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 76be2c5</samp>

*  Add a new prop `PreventFocus` to the `buttonProps` interface, which allows the user to control whether the button should be focused after being clicked ([link](https://github.com/element-plus/element-plus/pull/14258/files?diff=unified&w=0#diff-043025f7e5f7add14be78f47786cc3980c374f9e6d7ba5f02fc9b901b2d5d1cfR114-R118))
* Implement the logic of preventing the default focus behavior and emitting the `mousedown` event to the parent component in the `mouseDown` function, which is defined in the `useButton` hook and exposed to the button component ([link](https://github.com/element-plus/element-plus/pull/14258/files?diff=unified&w=0#diff-fe680d96593e2581cc3fa44aa7f27dff3e9f02e4b400b128614c06293c9badfaR73-R78), [link](https://github.com/element-plus/element-plus/pull/14258/files?diff=unified&w=0#diff-fe680d96593e2581cc3fa44aa7f27dff3e9f02e4b400b128614c06293c9badfaR88), [link](https://github.com/element-plus/element-plus/pull/14258/files?diff=unified&w=0#diff-1c64d60120c5ede235d1dcb98efa20a889756b54269c59b065eb7f27f5bf79d0L57-R58))
* Add a `@mousedown` event listener to the button component template, which invokes the `mouseDown` function ([link](https://github.com/element-plus/element-plus/pull/14258/files?diff=unified&w=0#diff-1c64d60120c5ede235d1dcb98efa20a889756b54269c59b065eb7f27f5bf79d0R21))

### CODE REVIEW

**Comment by enhengenheng-hubowen** [comment]
fixes: #13736

**Review by HeftyKoo — COMMENTED** [review]
I think it would be better to handle the style on the user's side.

**Comment by enhengenheng-hubowen** [comment]
> I think it would be better to handle the style on the user's side.

Considering the flexibility of the functionality, I recommend adding an attribute to control the style

**Review by ryuhangyeong — COMMENTED** [review]
I think modifying the css would be a better approach.

**Comment by tolking** [comment]
Thank for your contribution, But this idea will affect a11y, causing developers to write poor a11y features.

You can modify the colors yourself

**Pull request closed without merging**
