### PR TITLE
fix(build): externalize vue dependency as Vue

### PR DESCRIPTION
**Pull request by cheqianxiao**

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
I'm not sure if this change is making any sense, since the current version I didn't see any external `Vue` lib in templates
cc @zazzaz 
image

**Comment by zazzaz** [comment]
We should add a CDN link to index.tpl to make this optimization really work.

**Comment by cheqianxiao** [comment]
The current build version in not working in browser due to this bug. 
[the reproduction link](https://codepen.io/oobakoyo/pen/XWdyGqj?editors=1010). @JeremyWuuuuu 

image

**Comment by JeremyWuuuuu** [comment]
Oh, sorry, you were right. I thought this was the config file under `website/` my bad.

**Review by jw-foss — APPROVED** [review]

**Comment by cheqianxiao** [comment]
uh... I was also wrong,  found it not working with webpack after this commit. fixed it again in https://github.com/element-plus/element-plus/pull/380 .

**Pull request merged**
