### PR TITLE
fix(select): fix unselect custom-created tag in ElSelect

### LINKED ISSUE #2562: [Bug Report] could not unselect first tag when there are two tags that are created by Enter with "allow-create" property, by typing Enter
### Element Plus version
1.0.2-beta.55

### OS/Browsers version
Windows10 / Chrome 91.0.4472.124

### Vue version
3.2.0-beta.1

### Reproduction Link
https://codepen.io/codermonkie/pen/wvdegVy

### Steps to reproduce
component:  select
use property of “allow-create”

1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => "TS" tag disappeared, now showing "JS" tag
4. type "JS" and Enter => "TS" tag appeared, now showing "JS TS"

### What is Expected?
1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => "JS" tag disappeared, show "TS" tag only
4. type "JS" and Enter => "JS" tag appeared, now showing "TS JS"

### What is actually happening?
1. type “JS” and Enter => get a JS tag
2. type "TS" and Enter => get a TS tag
3. type "JS" and Enter => [BUG] "TS" tag disappeared, now showing "JS" tag
4. type "JS" and Enter => [BUG] "TS" tag appeared, now showing "JS TS"

and it seems "default-first-option" also doesn't work correctly (or am I miss-understanding..)

### PR DESCRIPTION
**Pull request by CoderMonkie**
fix #2562

Please make sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
cc @msidolphin need some inputs from you.

**Comment by msidolphin** [comment]
But there seems to be a new problem, there is no automatic hover after typing ts

https://user-images.githubusercontent.com/26672484/126160142-1293aef0-088a-42cb-937c-397158bd4bb6.mp4

**Comment by CoderMonkie** [comment]
@JeremyWuuuuu 

thank you but I ..

sorry, miss-operation...
(for rebase)

---

I fixed another bug in #2563 

the same place with this (#2562)

so, maybe should meger that and deprecate this

**Comment by CoderMonkie** [comment]
> there is no automatic hover after typing tx

please check another issue #2563 and pull request #2585 

the problem above was fixed too~

**Comment by CoderMonkie** [comment]
> But there seems to be a new problem, there is no automatic hover after typing ts
> 
>  Kapture.2021-07-19.at.20.30.42.mp4

please check another issue #2563 and pull request #2585

the problem above was fixed too~

**Pull request closed without merging**
