### PR TITLE
fix(components): [carousel] Added function: height is adaptive when height is auto | card direction vertical

### PR DESCRIPTION
**Pull request by qq282126990**
1.Set the height of the carousel to the height of the currently active item
2.Cards can display orientation vertically
3.The position of the indicator adds the inside restraint property
4.The position of the indicator Added the verticalIndicatorDirection property to set whether it is left or right when vertical. The default is left
5.Added cardScale attribute, external values can be passed in to customize the card scaling size
6.Documentation has been added Case

image

image

### CODE REVIEW

**Comment by qq282126990** [comment]
@tolking  
I have added the previous functionality and the newest functionality here Check out

old issues https://github.com/element-plus/element-plus/pull/9754

**Comment by tolking** [comment]
I suggest that you do not combine the Fix and Feat into one PR, but try to ensure that one PR only does one thing.

**Comment by qq282126990** [comment]
> 我建议大家不要把 Fix 和 Feat 合并成一个 PR，而是尽量保证一个 PR 只做一件事。

But these two functions are related to each other

**Comment by qq282126990** [comment]
> 我建议大家不要把 Fix 和 Feat 结合成一个 PR，而且是尽量保证一个 PR 只做一件事。

The auto height must be completed before the card direction can be completed vertically

**Comment by qq282126990** [comment]
> > 我建议大家不要把 Fix 和 Feat 结合成一个 PR，而且是尽量保证一个 PR 只做一件事。
> 
> 必须先完成auto height，才能垂直完成卡片方向

@tolking

**Comment by qq282126990** [comment]
So I merged the two functions together

**Comment by qq282126990** [comment]
@btea hello, any good ideas

**Comment by qq282126990** [comment]
@tolking  hello ，The two functions have been separated independently

this is Added function: height is adaptive when height is auto
https://github.com/element-plus/element-plus/pull/11392

**Pull request closed without merging**
