### PR TITLE
docs(docs): fix the import path problem

### PR DESCRIPTION
**Pull request by jingjing20**
Fix the import path problem

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by itsalimanuel — COMMENTED** [review]
👍🏻

**Comment by chenxch** [comment]
https://github.com/element-plus/unplugin-element-plus/blob/7bc81b30019859b1d644b4df4dd2ad63d1ba650a/package.json#L34-L38

@jingjing20 Is this not working?

**Comment by btea** [comment]
@jingjing20 Thank you for your contribution. But the latest version of `unplugin-element-plus` has been fixed.

**Comment by jingjing20** [comment]
> @jingjing20 Thank you for your contribution. But the latest version of `unplugin-element-plus` has been fixed.

ok

**Comment by jingjing20** [comment]
@btea ok, I installed the latest package, the problem is solved, thanks

**Comment by jingjing20** [comment]
> https://github.com/element-plus/unplugin-element-plus/blob/7bc81b30019859b1d644b4df4dd2ad63d1ba650a/package.json#L34-L38
> 
> @jingjing20 Is this not working?

@chenxch There is no problem after updating unplugin-element-plus to the latest version, but there was still a problem yesterday afternoon

**Pull request closed without merging**
