### PR TITLE
fix(components): [color-picker] fix bug #13239

### LINKED ISSUE #13239: [Component] [color-picker] 颜色选择器 输入框第一次完全删除，失焦后颜色变成红色
Bug Type: **`Component`**

## Environment

- Vue Version: `3.3.4`
- Element Plus Version: `2.3.6`
- Browser / OS: `Chaome / Win11`
- Build Tool: `Vite`

### Related Component

- `el-color-picker`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtY29sb3ItcGlja2VyIHYtbW9kZWw9XCJjb2xvclwiIHNob3ctYWxwaGEgLz5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5cbmNvbnN0IGNvbG9yID0gcmVmKCdyZ2JhKDE5LCAyMDYsIDEwMiwgMC44KScpXG48L3NjcmlwdD5cbiJ9)

### Steps to reproduce

点击Picker, 删除输入框内内容，点击picker的空白处。

### What is Expected?

颜色变为空透明度，与清空效果一致

### What is actually happening?

变成了红色

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by dingyuanjie**

### CODE REVIEW

**Comment by dingyuanjie** [comment]
@sxzz 帮忙审核？很多天了。

**Comment by dingyuanjie** [comment]
> @dingyuanjie Hi, can you elaborate on what problem this PR specifically solves?

link #13239 
[Component] [color-picker] 颜色选择器 输入框第一次完全删除，失焦后颜色变成红色 #13239****
点击Picker, 删除输入框内内容，点击picker的空白处。

**Comment by dingyuanjie** [comment]
> @dingyuanjie Hi, can you elaborate on what problem this PR specifically solves?

点击Picker, 删除输入框内内容，点击picker的空白处。 实际上触发了2个方法。所以会先变红色，再变成初始的颜色。

**Comment by btea** [comment]
Ok, I see, I'll review it later. 

If your pr is to fix an existing issue, it is best to link it in the comments, so that the reviewer can understand the purpose of your modification, and it can also automatically close the related issue after the pr is merged.

**Comment by dingyuanjie** [comment]
> Ok, I see, I'll review it later.
> 
> If your pr is to fix an existing issue, it is best to link it in the comments, so that the reviewer can understand the purpose of your modification, and it can also automatically close the related issue after the pr is merged.
> 
> It's better not to add numbers in the commit information, I have modified your comment link to the corresponding issue.
ok

**Comment by btea** [comment]
This issue doesn't seem to be resolved.

image

**Comment by dingyuanjie** [comment]
image
我看了一下，两次执行时间之前我提交pr的时候执行时间快一点小于100ms。现在我电脑本地测试，也会出现这种情况，两次的时间差跟电脑的性能有关系吧。有时候小于100ms，有时候大于100ms。所以这种情况，我觉得我的思路是没问题的，只需要把防抖的时间从100ms稍微调大一点即可。300ms应该满足需求。

**Comment by dingyuanjie** [comment]
我重新拉了一个分支，之前那个分支7.8有人修改过代码。麻烦你了。帮忙移步下。link13673

**Comment by dingyuanjie** [comment]
link#13673

**Comment by dingyuanjie** [comment]
link #13673

**Comment by btea** [comment]
> 我重新拉了一个分支，之前那个分支7.8有人修改过代码。麻烦你了。帮忙移步下。link13673

Ok, let's close this pr.

**Pull request closed without merging**
