### PR TITLE
chore: upgrade dayjs 1.11.3 to 1.11.13

### PR DESCRIPTION
**Pull request by thinkasany**
https://github.com/iamkun/dayjs/compare/v1.11.12...v1.11.13

有新的fix

### Bug Fixes

* customParseFormat supports Q quter / w ww weekOfYear ([#2705](https://github.com/iamkun/dayjs/issues/2705)) ([8ca74f1](https://github.com/iamkun/dayjs/commit/8ca74f178eff4bb4eb686676cf35fe7edb815536))****

### CODE REVIEW

**Comment by btea** [comment]
Thanks for your contribution, but it's a duplicate of #18662.

**Comment by thinkasany** [comment]
> Thanks for your contribution, but it's a duplicate of #18662.

他这边lock文件不该变更这么大，可以看他后续跟进情况如何，如果合了我就关了，有需要的话我来跟进。
The lock file on his side shouldn't have changed so much. It depends on how he follows up. If it's consistent, I'll close it. If necessary, I'll follow up.
image

**Comment by thinkasany** [comment]
> Yes, I noticed that too, I left a [comment](https://github.com/element-plus/element-plus/pull/18662#pullrequestreview-2409770876).

我添加了 `Co-authored-by`, github 会记录他的贡献，希望社区越来越好。

I added `Co-authored-by`, github will record his contribution, I hope the community will get better and better.

image

**Review by btea — APPROVED** [review]

**Review by warmthsea — APPROVED** [review]
LGTM

**Comment by Jungzl** [comment]
Should also update dayjs in `/packages/element-plus`?
```diff
---    "dayjs": "^1.11.3",
+++    "dayjs": "^1.11.13",
```

**Comment by btea** [comment]
Yes, I think it is necessary!

**Comment by CherishTheYouth** [comment]
Thank you, you did better absolutely!

**Pull request merged**
