### PR TITLE
fix(components): [menu] Fixing Menu component's flickering issue with surplus sub-items on insufficient page height.

### PR DESCRIPTION
**Pull request by ikkkp**
fix：#15308

### CODE REVIEW

**Comment by btea** [comment]
It seems that something went wrong with `pnpm lint`. Maybe you should execute `pnpm format`.

**Comment by ikkkp** [comment]
> It seems that something went wrong with `pnpm lint`. Maybe you should execute ~`pnpm format`~ `pnpm lint:fix`.
> 
> Sorry, I seemed to have written it wrong just now. You should probably adjust it. @ikkkp

I have just run `pnpm lint:fix`

**Comment by btea** [comment]
Hello, can you simplify the commit message and translate it into English? Thanks.

**Comment by ikkkp** [comment]
> Hello, can you simplify the commit message and translate it into English? Thanks.



> Hello, can you simplify the commit message and translate it into English? Thanks.

Sure

**Review by btea — APPROVED** [review]
LGTM

**Comment by btea** [comment]
@ikkkp I see you modified content outside of the menu component, a PR should only solve one problem, if you want to solve other problems, maybe you should create a new PR.

**Comment by ikkkp** [comment]
> @ikkkp I see you modified content outside of the menu component, a PR should only solve one problem, if you want to solve other problems, maybe you should create a new PR.

Would it be possible to merge this PR at this time？Or does it require further modifications? @btea

**Comment by btea** [comment]
Don't worry, you need to wait for others to review it.

**Pull request closed without merging**
