### PR TITLE
fix(components): [table] tooltipOptions.showAfter is not effective 

### PR DESCRIPTION
**Pull request by xingyixiang**
tooltipOptions.showAfter is not effective

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### <samp>🤖 Generated by Copilot at 75d8990</samp>

Improved and fixed tooltip for table component. Added `showAfter` option to `util.ts` and simplified popper events.

## Related Issue

Fixes #\_\_\_.

### <samp>🤖 Generated by Copilot at 75d8990</samp>

*  Add and use `togglePopperVisible` function to show or hide popper element based on `showAfter` option of tooltip ([link](https://github.com/element-plus/element-plus/pull/14741/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L367-R385), [link](https://github.com/element-plus/element-plus/pull/14741/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R427-R429))
*  Simplify `onOpen` and `onClose` handlers for content element and only add mouse events if `enterable` option is truthy ([link](https://github.com/element-plus/element-plus/pull/14741/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4L382-R407))
*  Call `onOpen` handler when popper is created to trigger popper visibility logic ([link](https://github.com/element-plus/element-plus/pull/14741/files?diff=unified&w=0#diff-e6d3319a7079fd77e391d7d2d10e68f50f7bc93bb031a254ab9f8170d58e2ac4R442))

### CODE REVIEW

**Comment by xingyixiang** [comment]
[Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ+i/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrScsXG4gICAgYWRkcmVzczpcbiAgICAgICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMgTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOlxuICAgICAgJ+i/meaYr+S4gOauteW+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+eahOaPj+i/sCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAn6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572uJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbl1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxlbC10YWJsZSA6ZGF0YT1cInRhYmxlRGF0YVwiIHN0eWxlPVwid2lkdGg6IDEwMCVcIj5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICBwcm9wPVwiZGF0ZVwiXG4gICAgICBsYWJlbD1cIkRhdGVcIlxuICAgICAgd2lkdGg9XCIxODBcIlxuICAgICAgc2hvdy1vdmVyZmxvdy10b29sdGlwXG4gICAgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICBwcm9wPVwibmFtZVwiXG4gICAgICBsYWJlbD1cIk5hbWVcIlxuICAgICAgd2lkdGg9XCIxODBcIlxuICAgICAgOnNob3ctb3ZlcmZsb3ctdG9vbHRpcD1cInsgc2hvd0FmdGVyOiA2MDAsIGVudGVyYWJsZTogZmFsc2UgfVwiXG4gICAgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICBwcm9wPVwiYWRkcmVzc1wiXG4gICAgICBsYWJlbD1cIkFkZHJlc3NcIlxuICAgICAgOnNob3ctb3ZlcmZsb3ctdG9vbHRpcD1cInsgc2hvd0FmdGVyOiAxMDAwIH1cIlxuICAgIC8+XG4gIDwvZWwtdGFibGU+XG48L3RlbXBsYXRlPlxuIiwic3JjL1BsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcImVsZW1lbnQtcGx1c1wiOiBcImh0dHBzOi8vcHJldmlldy0xNDc0MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmZ1bGwubWluLm1qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzL1wiOiBcInVuc3VwcG9ydGVkXCJcbiAgfVxufSIsInRzY29uZmlnLmpzb24iOiJ7XG4gIFwiY29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiBcIkVTTmV4dFwiLFxuICAgIFwianN4XCI6IFwicHJlc2VydmVcIixcbiAgICBcIm1vZHVsZVwiOiBcIkVTTmV4dFwiLFxuICAgIFwibW9kdWxlUmVzb2x1dGlvblwiOiBcIkJ1bmRsZXJcIixcbiAgICBcInR5cGVzXCI6IFtcImVsZW1lbnQtcGx1cy9nbG9iYWwuZC50c1wiXSxcbiAgICBcImFsbG93SW1wb3J0aW5nVHNFeHRlbnNpb25zXCI6IHRydWUsXG4gICAgXCJhbGxvd0pzXCI6IHRydWUsXG4gICAgXCJjaGVja0pzXCI6IHRydWVcbiAgfSxcbiAgXCJ2dWVDb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IDMuM1xuICB9XG59XG4iLCJzcmMvZWxlbWVudC1wbHVzLmpzIjoiaW1wb3J0IHsgZ2V0Q3VycmVudEluc3RhbmNlIH0gZnJvbSAndnVlJ1xuaW1wb3J0IEVsZW1lbnRQbHVzIGZyb20gJ2VsZW1lbnQtcGx1cydcblxubGV0IGluc3RhbGxlZCA9IGZhbHNlXG5hd2FpdCBsb2FkU3R5bGUoKVxuXG5leHBvcnQgZnVuY3Rpb24gc2V0dXBFbGVtZW50UGx1cygpIHtcbiAgaWYgKGluc3RhbGxlZCkgcmV0dXJuXG4gIGNvbnN0IGluc3RhbmNlID0gZ2V0Q3VycmVudEluc3RhbmNlKClcbiAgaW5zdGFuY2UuYXBwQ29udGV4dC5hcHAudXNlKEVsZW1lbnRQbHVzKVxuICBpbnN0YWxsZWQgPSB0cnVlXG59XG5cbmV4cG9ydCBmdW5jdGlvbiBsb2FkU3R5bGUoKSB7XG4gIHJldHVybiBuZXcgUHJvbWlzZSgocmVzb2x2ZSwgcmVqZWN0KSA9PiB7XG4gICAgY29uc3QgbGluayA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2xpbmsnKVxuICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgbGluay5ocmVmID0gJ2h0dHBzOi8vcHJldmlldy0xNDc0MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcydcbiAgICBsaW5rLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWQnLCByZXNvbHZlKVxuICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgZG9jdW1lbnQuYm9keS5hcHBlbmQobGluaylcbiAgfSlcbn0iLCJfbyI6eyJzaG93SGlkZGVuIjp0cnVlLCJzdHlsZVNvdXJjZSI6Imh0dHBzOi8vcHJldmlldy0xNDc0MS1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcyJ9fQ==)

**Review by btea — APPROVED** [review]
LGTM

**Comment by xingyixiang** [comment]
@btea Can the code be incorporated into the next version?

**Comment by tolking** [comment]
Is this a normal behavior?

https://github.com/element-plus/element-plus/assets/23313167/092d6d7c-336d-4357-83e8-be04e94b61e1

**Comment by xingyixiang** [comment]
@tolking Is that the same before the modification?
[Playground](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5jb25zdCB0YWJsZURhdGEgPSBbXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wMycsXG4gICAgbmFtZTogJ+i/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrei/m+WFpVBvcHBlcuWFs+mXrScsXG4gICAgYWRkcmVzczpcbiAgICAgICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMgTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICcyMDE2LTA1LTAyJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOlxuICAgICAgJ+i/meaYr+S4gOauteW+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+W+iOmVv+eahOaPj+i/sCcsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAnMjAxNi0wNS0wNCcsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vLiAxODksIEdyb3ZlIFN0LCBMb3MgQW5nZWxlcycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAn6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572uJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICfpu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva4nLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdOby4gMTg5LCBHcm92ZSBTdCwgTG9zIEFuZ2VsZXMnLFxuICAgIGFjdGlvbjogJ+m7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9ricsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAn6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572uJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8nLFxuICB9LFxuICB7XG4gICAgZGF0ZTogJ+m7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9rum7mOiupOmFjee9ricsXG4gICAgbmFtZTogJ1RvbScsXG4gICAgYWRkcmVzczogJ05vJyxcbiAgfSxcbiAge1xuICAgIGRhdGU6ICfpu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva4nLFxuICAgIG5hbWU6ICdUb20nLFxuICAgIGFkZHJlc3M6ICdObycsXG4gIH0sXG4gIHtcbiAgICBkYXRlOiAn6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572u6buY6K6k6YWN572uJyxcbiAgICBuYW1lOiAnVG9tJyxcbiAgICBhZGRyZXNzOiAnTm8uIDE4OSwgR3JvdmUgU3QsIExvcyBBbmdlbGVzJyxcbiAgICBhY3Rpb246ICfpu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva7pu5jorqTphY3nva4nLFxuICB9LFxuXVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLXRhYmxlIDpkYXRhPVwidGFibGVEYXRhXCIgc3R5bGU9XCJ3aWR0aDogNTAwcHhcIiBoZWlnaHQ9MjAwPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgIHByb3A9XCJkYXRlXCJcbiAgICAgIGxhYmVsPVwiRGF0ZVwiXG4gICAgICB3aWR0aD1cIjE4MFwiXG4gICAgICBzaG93LW92ZXJmbG93LXRvb2x0aXBcbiAgICAvPlxuICAgIDxlbC10YWJsZS1jb2x1bW5cbiAgICAgIHByb3A9XCJuYW1lXCJcbiAgICAgIGxhYmVsPVwiTmFtZVwiXG4gICAgICB3aWR0aD1cIjE4MFwiXG4gICAgICA6c2hvdy1vdmVyZmxvdy10b29sdGlwPVwieyBzaG93QWZ0ZXI6IDEwMDAgfVwiXG4gICAgLz5cbiAgICA8ZWwtdGFibGUtY29sdW1uXG4gICAgICBwcm9wPVwiYWRkcmVzc1wiXG4gICAgICB3aWR0aD1cIjEwMFwiXG4gICAgICBsYWJlbD1cIkFkZHJlc3NcIlxuICAgICAgOnNob3ctb3ZlcmZsb3ctdG9vbHRpcD1cInsgc2hvd0FmdGVyOiAxMDAwIH1cIlxuICAgIC8+XG4gICAgPGVsLXRhYmxlLWNvbHVtblxuICAgICAgZml4ZWQ9XCJyaWdodFwiXG4gICAgICBwcm9wPVwiYWN0aW9uXCJcbiAgICAgIGxhYmVsPVwiYWN0aW9uXCJcbiAgICAgIDpzaG93LW92ZXJmbG93LXRvb2x0aXA9XCJ7IHNob3dBZnRlcjogMTAwMCB9XCJcbiAgICAvPlxuICA8L2VsLXRhYmxlPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Comment by xingyixiang** [comment]
@tolking ok

**Comment by xingyixiang** [comment]
@tolking  The problem has been fixed

**Comment by xingyixiang** [comment]
@tolking Please help me review it again. Thanks

**Review by tolking — APPROVED** [review]

**Comment by xingyixiang** [comment]
@btea Can it be incorporated in the next version?

**Comment by kooriookami** [comment]
@btea @tolking I wonder can we replace with `el-tooltip`?

**Review by kooriookami — APPROVED** [review]

**Comment by xingyixiang** [comment]
@tolking @kooriookami @btea El-tootip's singleton mode seems to do it. I'll study it sometime.

**Comment by xingyixiang** [comment]
@kooriookami @btea #15179 The overflowTooltip is implemented using ElTooltip.

**Pull request merged**
