### PR TITLE
feat(components): [select & select-v2] explicit export `selectedLabel`

### PR DESCRIPTION
**Pull request by warmthsea**
❓ Why:

`selectedLabel` is a very commonly used attribute, but it is not explicitly declared in multiple versions.

| version | export |
|-------|-------|
| < 2.5 |  `selectedLabel` |
| >= 2.5 |  `states...` |

[Playground Demo](https://element-plus.run/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCB7IG9wdGlvbnMgfSBmcm9tICcuL2RhdGEnXG5cbmNvbnN0IHZhbHVlID0gcmVmKCd2YWx1ZTEnKVxuY29uc3QgdmFsdWUyID0gcmVmKFsndmFsdWUxJywgJ3ZhbHVlMiddKVxuXG5jb25zdCBzZWxlY3RFbCA9IHJlZigpXG5jb25zdCBzZWxlY3RNRWwgPSByZWYoKVxuY29uc3Qgc2VsZWN0VjJFbCA9IHJlZigpXG5jb25zdCBzZWxlY3RWMk1FbCA9IHJlZigpXG5cbmZ1bmN0aW9uIGdldFNlbGVjdExhYmVsKF9lbCkge1xuICAvLyBjb25zb2xlLmxvZyhfZWwpXG4gIGNvbnNvbGUubG9nKF9lbC5zZWxlY3RlZExhYmVsKVxufVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGRpdj5cbiAgICBlbC1zZWxlY3Q6XG4gICAgPGVsLXNlbGVjdCByZWY9XCJzZWxlY3RFbFwiIHYtbW9kZWw9XCJ2YWx1ZVwiIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuXG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJnZXRTZWxlY3RMYWJlbChzZWxlY3RFbClcIj5nZXQgc2VsZWN0IGxhYmVsPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxMHB4XCI+XG4gICAgZWwtc2VsZWN0IG11bHRpcGxlOlxuICAgIDxlbC1zZWxlY3QgcmVmPVwic2VsZWN0TUVsXCIgdi1tb2RlbD1cInZhbHVlMlwiIG11bHRpcGxlIHN0eWxlPVwid2lkdGg6IDI0MHB4XCI+XG4gICAgICA8ZWwtb3B0aW9uXG4gICAgICAgIHYtZm9yPVwiaXRlbSBpbiBvcHRpb25zXCJcbiAgICAgICAgOmtleT1cIml0ZW0udmFsdWVcIlxuICAgICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgICAgOnZhbHVlPVwiaXRlbS52YWx1ZVwiXG4gICAgICAvPlxuICAgIDwvZWwtc2VsZWN0PlxuXG4gICAgPGVsLWJ1dHRvbiBAY2xpY2s9XCJnZXRTZWxlY3RMYWJlbChzZWxlY3RNRWwpXCI+XG4gICAgICBnZXQgbXVsdGlwbGUgc2VsZWN0IGxhYmVsXG4gICAgPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuXG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiA1MHB4XCI+XG4gICAgZWwtc2VsZWN0LXYy77yaXG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgcmVmPVwic2VsZWN0VjJFbFwiXG4gICAgICB2LW1vZGVsPVwidmFsdWVcIlxuICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgIHNpemU9XCJsYXJnZVwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgIDwvZWwtc2VsZWN0LXYyPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZ2V0U2VsZWN0TGFiZWwoc2VsZWN0VjJFbClcIlxuICAgICAgPmdldCBzZWxlY3QtdjIgbGFiZWw8L2VsLWJ1dHRvblxuICAgID5cbiAgPC9kaXY+XG4gIDxkaXYgc3R5bGU9XCJtYXJnaW4tdG9wOiAxMHB4XCI+XG4gICAgZWwtc2VsZWN0LXYy77yaXG4gICAgPGVsLXNlbGVjdC12MlxuICAgICAgcmVmPVwic2VsZWN0VjJNRWxcIlxuICAgICAgbXVsdGlwbGVcbiAgICAgIHYtbW9kZWw9XCJ2YWx1ZTJcIlxuICAgICAgOm9wdGlvbnM9XCJvcHRpb25zXCJcbiAgICAgIHNpemU9XCJsYXJnZVwiXG4gICAgICBzdHlsZT1cIndpZHRoOiAyNDBweFwiXG4gICAgPlxuICAgIDwvZWwtc2VsZWN0LXYyPlxuICAgIDxlbC1idXR0b24gQGNsaWNrPVwiZ2V0U2VsZWN0TGFiZWwoc2VsZWN0VjJNRWwpXCI+XG4gICAgICBnZXQgbXVsdGlwbGUgc2VsZWN0LXYyIGxhYmVsXG4gICAgPC9lbC1idXR0b24+XG4gIDwvZGl2PlxuPC90ZW1wbGF0ZT5cbiIsImVsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5pbXBvcnQgeyBnZXRDdXJyZW50SW5zdGFuY2UgfSBmcm9tICd2dWUnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xODM1MC1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTgzNTAtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbFNldHRsZWQoc3R5bGVzKVxufVxuIiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIlBsYXlncm91bmRNYWluLnZ1ZSI6IjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgQXBwIGZyb20gJy4vQXBwLnZ1ZSdcbmltcG9ydCB7IHNldHVwRWxlbWVudFBsdXMgfSBmcm9tICcuL2VsZW1lbnQtcGx1cy5qcydcbnNldHVwRWxlbWVudFBsdXMoKVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPEFwcCAvPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHtcbiAgICBcInZ1ZVwiOiBcImh0dHBzOi8vZmFzdGx5LmpzZGVsaXZyLm5ldC9ucG0vQHZ1ZS9ydW50aW1lLWRvbUBsYXRlc3QvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwiQHZ1ZS9zaGFyZWRcIjogXCJodHRwczovL2Zhc3RseS5qc2RlbGl2ci5uZXQvbnBtL0B2dWUvc2hhcmVkQGxhdGVzdC9kaXN0L3NoYXJlZC5lc20tYnVuZGxlci5qc1wiLFxuICAgIFwiZWxlbWVudC1wbHVzXCI6IFwiaHR0cHM6Ly9wcmV2aWV3LTE4MzUwLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguZnVsbC5taW4ubWpzXCIsXG4gICAgXCJlbGVtZW50LXBsdXMvXCI6IFwidW5zdXBwb3J0ZWRcIixcbiAgICBcIkBlbGVtZW50LXBsdXMvaWNvbnMtdnVlXCI6IFwiaHR0cHM6Ly9mYXN0bHkuanNkZWxpdnIubmV0L25wbS9AZWxlbWVudC1wbHVzL2ljb25zLXZ1ZUAyL2Rpc3QvaW5kZXgubWluLmpzXCJcbiAgfSxcbiAgXCJzY29wZXNcIjoge31cbn0iLCJkYXRhLnRzIjoiZXhwb3J0IGNvbnN0IG9wdGlvbnMgPSBbXHJcbiAgeyB2YWx1ZTogJ3ZhbHVlMScsIGxhYmVsOiAnbGFiZWwxJyB9LFxyXG4gIHsgdmFsdWU6ICd2YWx1ZTInLCBsYWJlbDogJ2xhYmVsMicgfSxcclxuICB7IHZhbHVlOiAndmFsdWUzJywgbGFiZWw6ICdsYWJlbDMnIH0sXHJcbl1cclxuXHJcblxyXG5leHBvcnQgY29uc3QgIHRyZWVEYXRhID0gW1xyXG4gIHtcclxuICAgIHZhbHVlOiAnMScsXHJcbiAgICBsYWJlbDogJ0xldmVsIG9uZSAxJyxcclxuICAgIGNoaWxkcmVuOiBbXHJcbiAgICAgIHtcclxuICAgICAgICB2YWx1ZTogJzEtMScsXHJcbiAgICAgICAgbGFiZWw6ICdMZXZlbCB0d28gMS0xJyxcclxuICAgICAgICBjaGlsZHJlbjogW1xyXG4gICAgICAgICAge1xyXG4gICAgICAgICAgICB2YWx1ZTogJzEtMS0xJyxcclxuICAgICAgICAgICAgbGFiZWw6ICdMZXZlbCB0aHJlZSAxLTEtMScsXHJcbiAgICAgICAgICB9LFxyXG4gICAgICAgIF0sXHJcbiAgICAgIH0sXHJcbiAgICBdLFxyXG4gIH0sXHJcbiAge1xyXG4gICAgdmFsdWU6ICcyJyxcclxuICAgIGxhYmVsOiAnTGV2ZWwgb25lIDInLFxyXG4gICAgY2hpbGRyZW46IFtcclxuICAgICAge1xyXG4gICAgICAgIHZhbHVlOiAnMi0xJyxcclxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTEnLFxyXG4gICAgICAgIGNoaWxkcmVuOiBbXHJcbiAgICAgICAgICB7XHJcbiAgICAgICAgICAgIHZhbHVlOiAnMi0xLTEnLFxyXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMS0xJyxcclxuICAgICAgICAgIH0sXHJcbiAgICAgICAgXSxcclxuICAgICAgfSxcclxuICAgICAge1xyXG4gICAgICAgIHZhbHVlOiAnMi0yJyxcclxuICAgICAgICBsYWJlbDogJ0xldmVsIHR3byAyLTInLFxyXG4gICAgICAgIGNoaWxkcmVuOiBbXHJcbiAgICAgICAgICB7XHJcbiAgICAgICAgICAgIHZhbHVlOiAnMi0yLTEnLFxyXG4gICAgICAgICAgICBsYWJlbDogJ0xldmVsIHRocmVlIDItMi0xJyxcclxuICAgICAgICAgIH0sXHJcbiAgICAgICAgXSxcclxuICAgICAgfSxcclxuICAgIF0sXHJcbiAgfSxcclxuICB7XHJcbiAgICB2YWx1ZTogJzMnLFxyXG4gICAgbGFiZWw6ICdMZXZlbCBvbmUgMycsXHJcbiAgICBjaGlsZHJlbjogW1xyXG4gICAgICB7XHJcbiAgICAgICAgdmFsdWU6ICczLTEnLFxyXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMScsXHJcbiAgICAgICAgY2hpbGRyZW46IFtcclxuICAgICAgICAgIHtcclxuICAgICAgICAgICAgdmFsdWU6ICczLTEtMScsXHJcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0xLTEnLFxyXG4gICAgICAgICAgfSxcclxuICAgICAgICBdLFxyXG4gICAgICB9LFxyXG4gICAgICB7XHJcbiAgICAgICAgdmFsdWU6ICczLTInLFxyXG4gICAgICAgIGxhYmVsOiAnTGV2ZWwgdHdvIDMtMicsXHJcbiAgICAgICAgY2hpbGRyZW46IFtcclxuICAgICAgICAgIHtcclxuICAgICAgICAgICAgdmFsdWU6ICczLTItMScsXHJcbiAgICAgICAgICAgIGxhYmVsOiAnTGV2ZWwgdGhyZWUgMy0yLTEnLFxyXG4gICAgICAgICAgfSxcclxuICAgICAgICBdLFxyXG4gICAgICB9LFxyXG4gICAgXSxcclxuICB9LFxyXG5dXHJcbiIsIl9vIjp7InNob3dIaWRkZW4iOnRydWUsInN0eWxlU291cmNlIjoiaHR0cHM6Ly9wcmV2aWV3LTE4MzUwLWVsZW1lbnQtcGx1cy5zdXJnZS5zaC9idW5kbGUvaW5kZXguY3NzIn19)

<hr />

image

<hr />

#### 🚩 Demo

screenshots

### CODE REVIEW

**Review by btea — APPROVED** [review]
LGTM

**Comment by kooriookami** [comment]
image

It's not a method nor object. It's a computed value of string or array type.

**Comment by warmthsea** [comment]
> It's not a method nor object. It's a computed value of string or array type.

I want to be consistent with other components.

image

**Review by makedopamine — APPROVED** [review]
We can improve all inaccurate types in a dedicated PR.

**Comment by btea** [comment]
> We can improve all inaccurate types in a dedicated PR.

It sounds good, but it seems that there are many things that need to be changed, and it may take a long time. 😄

**Pull request merged**
