### PR TITLE
fix: checkbox selfModel use ref

### LINKED ISSUE #2210: [Bug Report] Checkbox "selfModel "property not use ref
### Element Plus version
1.0.2-beta.46

### OS/Browsers version
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36

### Vue version
3.1.1

### Reproduction Link
https://codesandbox.io/s/element-plus-spa-forked-0g2e5?file=/src/App.vue

### Steps to reproduce
el-checkbox非受控特性由 selfModel 控制，selfModel未使用响应式，不触发UI更新

### What is Expected?
selfModel 能通过响应式触发UI更新

### What is actually happening?
selfModel未使用响应式，不触发UI更新

### PR DESCRIPTION
**Pull request by XyyF**
Please make sure these boxes are checked before submitting your PR, thank you!

--------
Jeremy Edited: 
This PR closes #2210

* [x] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
* [x] Make sure you are merging your commits to `dev` branch.
* [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by XyyF** [comment]
add ref to checkbox selfModel

**Review by XyyF — COMMENTED** [review]
When selfModel changes, the UI will not change.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
Very nice catch! Thank you for your contribution.

**Comment by JeremyWuuuuu** [comment]
You might need to use `const` for `selfModel` instead of `let`. Update that statement and we are ready to go.

**Comment by XyyF** [comment]
oh, thank you very much~

**Comment by XyyF** [comment]
I'm sorry to forget run lint, and I fix this. thx~

**Pull request merged**
