### PR TITLE
fix(components): [dialog] remove not used style props

### PR DESCRIPTION
**Pull request by ryuhangyeong**
### `dialog-content.vue`

```vue
<el-dialog-content
  v-if="rendered"
  ref="dialogContentRef"
  :custom-class="customClass"
  :center="center"
  :close-icon="closeIcon"
  :draggable="draggable"
  :fullscreen="fullscreen"
  :show-close="showClose"
  :style="style" // not used props
  :title="title"
  @close="handleClose"
 />
```

### `dialog-content.ts`

It's not even in the props validation syntax.

```ts
export const dialogContentProps = buildProps({
  center: {
    type: Boolean,
    default: false,
  },
  closeIcon: {
    type: iconPropType,
    default: '',
  },
  customClass: {
    type: String,
    default: '',
  },
  draggable: {
    type: Boolean,
    default: false,
  },
  fullscreen: {
    type: Boolean,
    default: false,
  },
  showClose: {
    type: Boolean,
    default: true,
  },
  title: {
    type: String,
    default: '',
  },
} as const)
```

### `dialog-content.vue`

```vue
const { dialogRef, headerRef, bodyId, ns, style } = inject(dialogInjectionKey)! // here!
```

Because the style provided by provide is used, props style is not required.

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by YunYouJun** [comment]
It seems inherited from here. https://github.com/element-plus/element-plus/blob/fb3a170ee39b15757ab2409fdff5d74b90d4efea/packages/components/dialog/src/dialog.vue#L107

**Comment by ryuhangyeong** [comment]
Thanks for the review.

First of all, the reason I thought that the style attribute was unnecessary is as follows.

1. In dialog.vue, the style provided by `useDialog` is delivered to the child components as provide.
2. In dialog-content.vue, the value provided by the parent component as provide is provided by inject and used.

Therefore, I thought that there is no need to receive styles as props.

**Comment by YunYouJun** [comment]
Oh, i see. They seem to repeat.

Just in case, I'd like someone can review it too.

**Review by YunYouJun — APPROVED** [review]

**Review by chenxch — APPROVED** [review]
LGTM.

**Comment by QianMoQingFeng** [comment]
> ## CDN introduces Element-Plus. How to set the style attribute
> ### The following is my attempt, but not correct
`Vue.provide(Symbol('dialogInjectionKey'), { style: { color: '#ff0000' } })`

**Pull request merged**
