### PR TITLE
docs(timeline): remove the description about the reverse

### PR DESCRIPTION
**Pull request by BeADre**
according to the description in the source code, the timeline will not support prop 'reverse' ?

image

### CODE REVIEW

**Comment by zazzaz** [comment]
Thanks

**Review by zazzaz — APPROVED** [review]

**Comment by BeADre** [comment]
对了 日文文档的描述部分我没有更新 因为我实在看不懂  所以只改了代码的部分

**Comment by BeADre** [comment]
然后还有[#483](https://github.com/element-plus/element-plus/pull/483)相关部分的日文文档似乎也没有更新

**Comment by zazzaz** [comment]
Hi, @BeADre you can simply ignore the description that you did not familiar with. 

It will be a great help if you could update the code part in #483

**Comment by BeADre** [comment]
ok, I'll update it later

**Pull request merged**
