### PR TITLE
feat(components): [card] adds footer slot

### LINKED ISSUE #6873: [Feature Request] Card element with footer slot
### Existing Component
Yes

### Component Name
Card
https://element-plus.org/en-US/component/card.html#slots

### Description
Had a use case where i needed footer slot, kinda unfortunate that i can't use Card component just because its missing and i had to resort to make a custom component instead.
Also i think its common nowadays that Card having some actions down the footer. So i would suggest having a footer slot for the Card component :)

Thanks in advance 🙏

### PR DESCRIPTION
**Pull request by faga295**
adds footer slot

closed #6873

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by MARIOMARUI** [comment]
可以的

**Review by ryuhangyeong — APPROVED** [review]

**Comment by faga295** [comment]
If this PR hasn't any problems, please merge it

**Comment by wzc520pyfm** [comment]
What is the current progress of this PR? I also think we need a footer slot.

**Review by btea — APPROVED** [review]
@faga295 Sorry for responding so late. This feature looks great to me.

**Comment by btea** [comment]
@ryuhangyeong Do you think there are any other questions? If not, I think we can merge it.

**Comment by ryuhangyeong** [comment]
@btea 

I have no problem.

I think it's okay for me to merge too.

**Pull request merged**
