### PR TITLE
fix(components): confirm button style when in message-box

### PR DESCRIPTION
**Pull request by YunYouJun**
- fix confirm button style when in message-box
- add highlight.ts for new vitepress

---

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by iamkun — APPROVED** [review]

**Comment by emojiiii** [comment]
fix #4584

**Comment by emojiiii** [comment]
fix #4577

**Comment by fainc** [comment]
enjoy😄

**Comment by emojiiii** [comment]
fix #4601

**Comment by emojiiii** [comment]
fix #4608

**Comment by cxj-github** [comment]
请问为什么要把MessageBox的确认按钮改成plain风格呢，vue2的element不是是这样的的，其他UI框架也不是这样的，个人感觉这样很丑！

**Comment by YunYouJun** [comment]
@cxj-github Sorry, i think it is caused by message-box confirm button is always be focus. So I misunderstood the message-box style.
And it removed it in https://github.com/element-plus/element-plus/pull/4988 . Thanks.

**Pull request merged**
