### PR TITLE
feat(components): [dialog/drawer] add attr escape-close-prevent

### PR DESCRIPTION
**Pull request by warmthsea**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix：https://github.com/element-plus/element-plus/issues/16065

### CODE REVIEW

**Comment by warmthsea** [comment]
fix：https://github.com/element-plus/element-plus/issues/16065

**Comment by warmthsea** [comment]
screenshots

@jiq1997

**Comment by btea** [comment]
IMO, it might be better to provide a prop for users to decide whether to bubble or not. What do you think? cc @element-plus/backers

**Comment by warmthsea** [comment]
> IMO, it might be better to provide a prop for users to decide whether to bubble or not. What do you think? cc @element-plus/backers

I made a new commit and added the escape-close-prevent attribute to dialog and drawer.

How to trigger the execution of pr review? Just like other pr.
image

**Comment by warmthsea** [comment]
## example:

https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyByZWYgLCBvbk1vdW50ZWQgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbE1lc3NhZ2UgfSBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmNvbnN0IGRpYWxvZ1Zpc2libGUgPSByZWYoZmFsc2UpXG5jb25zdCBkaWFsb2dWaXNpYmxlMiA9IHJlZihmYWxzZSlcblxuY29uc3QgZHJhd2VyID0gcmVmKGZhbHNlKVxuY29uc3QgZHJhd2VyMiA9IHJlZihmYWxzZSlcblxuY29uc3QgaGFuZGxlS2V5dXAgPSBhc3luYyAoKSA9PiB7XG4gIGNvbnNvbGUubG9nKCdlc2Mg6Kem5Y+RJylcbiAgRWxNZXNzYWdlKCd1c2VyIGN1c3RvbSBlc2MgZnVuY3Rpb24nKVxufVxuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdrZXlkb3duJywgaGFuZGxlS2V5dXApXG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGVsLWJ1dHRvbiBwbGFpbiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlID0gdHJ1ZVwiPlxuICAgIG9wZW4gZGVmYWx1dCBkaWFsb2dcbiAgPC9lbC1idXR0b24+XG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkaWFsb2dWaXNpYmxlMiA9IHRydWVcIj5cbiAgICBvcGVuIGFkZCBhdHRyIGRpYWxvZ1xuICA8L2VsLWJ1dHRvbj5cblxuICA8ZWwtYnV0dG9uIEBjbGljaz1cImRyYXdlciA9IHRydWVcIj5cbiAgICBvcGVuIGRlZmFsdXQgZHJhd2VyXG4gIDwvZWwtYnV0dG9uPlxuXG4gIDxlbC1idXR0b24gdHlwZT1cInByaW1hcnlcIiBAY2xpY2s9XCJkcmF3ZXIyID0gdHJ1ZVwiPlxuICAgIG9wZW4gYWRkIGF0dHIgZHJhd2VyXG4gIDwvZWwtYnV0dG9uPlxuXG5cbiAgIDxlbC1kaWFsb2dcbiAgICB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZVwiXG4gID5cbiAgICA8c3Bhbj5UaGlzIGlzIGEgbWVzc2FnZTwvc3Bhbj5cbiAgPC9lbC1kaWFsb2c+XG5cbiAgIDxlbC1kaWFsb2dcbiAgICB2LW1vZGVsPVwiZGlhbG9nVmlzaWJsZTJcIlxuICAgIGVzY2FwZS1jbG9zZS1wcmV2ZW50XG4gID5cbiAgICA8c3Bhbj5UaGlzIGlzIGEgbWVzc2FnZTwvc3Bhbj5cbiAgPC9lbC1kaWFsb2c+XG4gIFxuICAgPGVsLWRyYXdlclxuICAgIHYtbW9kZWw9XCJkcmF3ZXJcIlxuICAgIDp3aXRoLWhlYWRlcj1cImZhbHNlXCJcbiAgPlxuICAgIDxzcGFuPkhpIHRoZXJlITwvc3Bhbj5cbiAgPC9lbC1kcmF3ZXI+XG4gIDxlbC1kcmF3ZXJcbiAgICBlc2NhcGUtY2xvc2UtcHJldmVudFxuICAgIHYtbW9kZWw9XCJkcmF3ZXIyXCJcbiAgICA6d2l0aC1oZWFkZXI9XCJmYWxzZVwiXG4gID5cbiAgICA8c3Bhbj5IaSB0aGVyZSE8L3NwYW4+XG4gIDwvZWwtZHJhd2VyPlxuPC90ZW1wbGF0ZT5cbiIsInNyYy9QbGF5Z3JvdW5kTWFpbi52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IEFwcCBmcm9tICcuL0FwcC52dWUnXG5pbXBvcnQgeyBzZXR1cEVsZW1lbnRQbHVzIH0gZnJvbSAnLi9lbGVtZW50LXBsdXMuanMnXG5zZXR1cEVsZW1lbnRQbHVzKClcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxBcHAgLz5cbjwvdGVtcGxhdGU+XG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJlbGVtZW50LXBsdXNcIjogXCJodHRwczovL3ByZXZpZXctMTYwNzYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5mdWxsLm1pbi5tanNcIixcbiAgICBcImVsZW1lbnQtcGx1cy9cIjogXCJ1bnN1cHBvcnRlZFwiXG4gIH1cbn0iLCJ0c2NvbmZpZy5qc29uIjoie1xuICBcImNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogXCJFU05leHRcIixcbiAgICBcImpzeFwiOiBcInByZXNlcnZlXCIsXG4gICAgXCJtb2R1bGVcIjogXCJFU05leHRcIixcbiAgICBcIm1vZHVsZVJlc29sdXRpb25cIjogXCJCdW5kbGVyXCIsXG4gICAgXCJ0eXBlc1wiOiBbXCJlbGVtZW50LXBsdXMvZ2xvYmFsLmQudHNcIl0sXG4gICAgXCJhbGxvd0ltcG9ydGluZ1RzRXh0ZW5zaW9uc1wiOiB0cnVlLFxuICAgIFwiYWxsb3dKc1wiOiB0cnVlLFxuICAgIFwiY2hlY2tKc1wiOiB0cnVlXG4gIH0sXG4gIFwidnVlQ29tcGlsZXJPcHRpb25zXCI6IHtcbiAgICBcInRhcmdldFwiOiAzLjNcbiAgfVxufVxuIiwic3JjL2VsZW1lbnQtcGx1cy5qcyI6ImltcG9ydCB7IGdldEN1cnJlbnRJbnN0YW5jZSB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBFbGVtZW50UGx1cyBmcm9tICdlbGVtZW50LXBsdXMnXG5cbmxldCBpbnN0YWxsZWQgPSBmYWxzZVxuYXdhaXQgbG9hZFN0eWxlKClcblxuZXhwb3J0IGZ1bmN0aW9uIHNldHVwRWxlbWVudFBsdXMoKSB7XG4gIGlmIChpbnN0YWxsZWQpIHJldHVyblxuICBjb25zdCBpbnN0YW5jZSA9IGdldEN1cnJlbnRJbnN0YW5jZSgpXG4gIGluc3RhbmNlLmFwcENvbnRleHQuYXBwLnVzZShFbGVtZW50UGx1cylcbiAgaW5zdGFsbGVkID0gdHJ1ZVxufVxuXG5leHBvcnQgZnVuY3Rpb24gbG9hZFN0eWxlKCkge1xuICBjb25zdCBzdHlsZXMgPSBbJ2h0dHBzOi8vcHJldmlldy0xNjA3Ni1lbGVtZW50LXBsdXMuc3VyZ2Uuc2gvYnVuZGxlL2luZGV4LmNzcycsICdodHRwczovL3ByZXZpZXctMTYwNzYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MnXS5tYXAoKHN0eWxlKSA9PiB7XG4gICAgcmV0dXJuIG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHtcbiAgICAgIGNvbnN0IGxpbmsgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaW5rJylcbiAgICAgIGxpbmsucmVsID0gJ3N0eWxlc2hlZXQnXG4gICAgICBsaW5rLmhyZWYgPSBzdHlsZVxuICAgICAgbGluay5hZGRFdmVudExpc3RlbmVyKCdsb2FkJywgcmVzb2x2ZSlcbiAgICAgIGxpbmsuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCByZWplY3QpXG4gICAgICBkb2N1bWVudC5ib2R5LmFwcGVuZChsaW5rKVxuICAgIH0pXG4gIH0pXG4gIHJldHVybiBQcm9taXNlLmFsbChzdHlsZXMpXG59IiwiX28iOnsic2hvd0hpZGRlbiI6dHJ1ZSwic3R5bGVTb3VyY2UiOiJodHRwczovL3ByZXZpZXctMTYwNzYtZWxlbWVudC1wbHVzLnN1cmdlLnNoL2J1bmRsZS9pbmRleC5jc3MifX0=

**Comment by tolking** [comment]
我不确定这是不是一个问题，但原生 dialog 也是 #16065 这种行为

[Demo](https://element-plus.run/#eyJzcmMvQXBwLnZ1ZSI6IjxzY3JpcHQgc2V0dXAgbGFuZz1cInRzXCI+XG5pbXBvcnQgeyBvbk1vdW50ZWQgfSBmcm9tICd2dWUnO1xuXG5vbk1vdW50ZWQoKCkgPT4ge1xuICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCdrZXlkb3duJywgKGV2ZW50KSA9PiB7XG4gICAgY29uc29sZS5sb2coZXZlbnQua2V5KVxuICB9KVxufSlcblxuZnVuY3Rpb24gb3BlbigpIHtcbiAgY29uc3QgYnV0dG9uID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoXCJ1cGRhdGVEZXRhaWxzXCIpO1xuXG4gIGlmICh0eXBlb2YgZGlhbG9nLnNob3dNb2RhbCA9PT0gXCJmdW5jdGlvblwiKSB7XG4gICAgZGlhbG9nLnNob3dNb2RhbCgpO1xuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuPGRpYWxvZyBpZD1cImRpYWxvZ1wiPlxuICA8Zm9ybSBtZXRob2Q9XCJkaWFsb2dcIj5cbiAgICA8cD5HcmVldGluZ3MsIG9uZSBhbmQgYWxsITwvcD5cbiAgICA8YnV0dG9uPk9LPC9idXR0b24+XG4gIDwvZm9ybT5cbjwvZGlhbG9nPlxuPGJ1dHRvbiBAY2xpY2s9XCJvcGVuXCI+T3BlbjwvYnV0dG9uPlxuPC90ZW1wbGF0ZT5cbiIsImltcG9ydC1tYXAuanNvbiI6IntcbiAgXCJpbXBvcnRzXCI6IHt9XG59IiwidHNjb25maWcuanNvbiI6IntcbiAgXCJjb21waWxlck9wdGlvbnNcIjoge1xuICAgIFwidGFyZ2V0XCI6IFwiRVNOZXh0XCIsXG4gICAgXCJqc3hcIjogXCJwcmVzZXJ2ZVwiLFxuICAgIFwibW9kdWxlXCI6IFwiRVNOZXh0XCIsXG4gICAgXCJtb2R1bGVSZXNvbHV0aW9uXCI6IFwiQnVuZGxlclwiLFxuICAgIFwidHlwZXNcIjogW1wiZWxlbWVudC1wbHVzL2dsb2JhbC5kLnRzXCJdLFxuICAgIFwiYWxsb3dJbXBvcnRpbmdUc0V4dGVuc2lvbnNcIjogdHJ1ZSxcbiAgICBcImFsbG93SnNcIjogdHJ1ZSxcbiAgICBcImNoZWNrSnNcIjogdHJ1ZVxuICB9LFxuICBcInZ1ZUNvbXBpbGVyT3B0aW9uc1wiOiB7XG4gICAgXCJ0YXJnZXRcIjogMy4zXG4gIH1cbn1cbiIsIl9vIjp7fX0=)

**Pull request closed without merging**
