### PR TITLE
feat(docs): Fixed an example to address bugs when packaging vue tsc versions 1.3.13 and above

### PR DESCRIPTION
**Pull request by xuxiaowei-com-cn**
:bug: Fixed an example to address bugs when packaging vue tsc versions 1.3.13 and above

https://github.com/element-plus/element-plus/issues/12531

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ x ] Make sure you are merging your commits to `dev` branch.
- [ x ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by chenxch** [comment]
@xuxiaowei-com-cn Thank you for your congratulations, would you mind modifying the title according to the specification? You can refer to other pr.

**Comment by xuxiaowei-com-cn** [comment]
@chenxch Modified, is it okay?

**Comment by pany-ang** [comment]
vue-tsc 1.4.2 has fixed this issue

**Comment by xuxiaowei-com-cn** [comment]
https://github.com/element-plus/element-plus/issues/12531

**Pull request closed without merging**
