### PR TITLE
feat(components): [el-cascader] lazyLoad prop add reject paramer

### PR DESCRIPTION
**Pull request by yuzhang9804**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

#3481

### CODE REVIEW

**Comment by JeremyWuuuuu** [comment]
@yuzhang9804 Code seems legit to me, could you help adding some tests for the change?

**Comment by yuzhang9804** [comment]
@JeremyWuuuuu Test cases have been added

**Review by KawaiiZapic — APPROVED** [review]

**Comment by KawaiiZapic** [comment]
It's there any problem to merge this?  
Pretty useful PR.

**Review by jw-foss — APPROVED** [review]

**Comment by JeremyWuuuuu** [comment]
@yuzhang9804 I am sorry that this has been stalled for so long, please resolve the conflict so we can get this merged, thanks!

**Comment by KawaiiZapic** [comment]
> @yuzhang9804 I am sorry that this has been stalled for so long, please resolve the conflict so we can get this merged, thanks!

I will do this in a new PR if he is not empty to handle this.

**Comment by xiaoxian521** [comment]
Hey, thank you very much for your contribution, but here are some conflicts that need to be solved by you. We can continue to review the code after solving. One thing to remind is that if the conflicts is still not resolved after `10` days, sorry, we will close this pr ❤️

**Pull request closed without merging**
