### PR TITLE
docs: add how to help translating doc

### PR DESCRIPTION
**Pull request by jw-foss**
- Add how to help translating doc
- Add entry for how to help translating doc

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
How about adding this to element-plus.org docs instead GitHub readme

**Review by sxzz — COMMENTED** [review]
How about adding this to element-plus.org docs instead GitHub readme

**Comment by JeremyWuuuuu** [comment]
> How about adding this to element-plus.org docs instead GitHub readme

I think we can do both. Let's get this merged first.

**Comment by JeremyWuuuuu** [comment]
@sxzz Which section do you think it would be appropriate? `Guide`, `Component` `Resource`

**Comment by YunYouJun** [comment]
I think we should give a example link.
For example, button zh-CN docs is xxx link.

**Pull request merged**
