### PR TITLE
fix(components): [tree-select]check-strictly mode check-on-click-node invalid

### LINKED ISSUE #7415: [Bug Report] [tree-select] tree-select组件关于点击选中的问题
Bug Type: **`Other`**

## Environment

- Vue Version: `3.2.30`
- Element Plus Version: `2.1.8`
- Browser / OS: `Chrome/86.0.4240.198 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-tree-select`

### Reproduction Link

[CodePen](https://codepen.io/mrDao/pen/mdpNGPV)

### Steps to reproduce

tree组件的check-on-click-node属性不生效，默认false的情况下，点击节点后还是选中了当前节点

### What is Expected?

能实现多选状态下，只点击多选框选择。

### What is actually happening?

能实现多选状态下，只点击多选框选择。

### Additional comments

不确定是不是组件的bug。但确实多次尝试后，无法实现只点击复选框选择，每次点击节点都默认选择了当前节点。

### PR DESCRIPTION
**Pull request by chenxch**
Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

fix
#7415

### CODE REVIEW

**Comment by chenxch** [comment]
@yujinpan  This change may result in changes to the current user interaction in check-strictly and showCheckbox mode. Your evaluation is required.

**Review by yujinpan — COMMENTED** [review]
👍

**Review by yujinpan — APPROVED** [review]

**Comment by chenxch** [comment]
This fix may cause inconsistent performance for users who currently use check-strictly. Do you want to add a warning reminder?
@yujinpan @JeremyWuuuuu

**Comment by yujinpan** [comment]
Yes, there are still many areas for improvement in the instance and documentation of the component, and this change will be explained in the subsequent documentation.

**Comment by chenxch** [comment]
> Yes, there are still many areas for improvement in the instance and documentation of the component, and this change will be explained in the subsequent documentation.

OK, then I'll finish this submission first.

**Pull request merged**
