### PR TITLE
Revert "fix(components): [popover] default trigger"

### PR DESCRIPTION
**Pull request by chenxch**
Reverts element-plus/element-plus#12321

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
@chenxch Is there a problem with that code? 🤔

**Comment by chenxch** [comment]
> @chenxch Is there a problem with that code? 🤔

The default trigger method of popover should be hover, not click.

**Comment by btea** [comment]
If so, this revert should be merged with #12342.

**Comment by MrWeilian** [comment]
😅 unlucky

**Comment by chenxch** [comment]
> 😅 unlucky

Don't worry, luck will favor everyone who really loves open source.😬

**Review by plainheart — APPROVED** [review]

**Comment by MrWeilian** [comment]
😬hhh. I found that element-ui default trigger is "click" !

**Comment by chenxch** [comment]
> 😬hhh. I found that element-ui default trigger is "click" !

Yes, but we have compared the practices of several mainstream warehouses with popover by default.

**Pull request merged**
