### PR TITLE
feat(components): [el-virtual-scroll-bar] handle click event

### PR DESCRIPTION
**Pull request by SorrowX**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow Element's contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by SorrowX** [comment]
1.添加点击滚动条槽的功能
@JeremyWuuuuu

**Comment by SorrowX** [comment]
单测用例:
```js
  it('click track', async () => {
    const wrapper = mount({
      template: `
        <div
          style="
            height: 100px;
            position: relative;
            border: 1px solid red;
          "
        >
          <scrollbar
            layout="vertical"
            :total="100"
            :ratio="25"
            :client-size="100"
            :scroll-from="0 / 300"
            :visible="true"
            ref="scrollbar"
          />
        </div>
      `,
      components: {
        Scrollbar,
      },
    })

    await nextTick()

    const scrollbar = wrapper.findComponent(Scrollbar)
    const el = scrollbar.vm.$el

    // layout: vertical; width: auto; height: 100px; scrollHeight: 400px;
    // thumb ratio: (100 / 400) * 100 -> 25   // (clientHeight / scrollHeight) * 100
    // thumbSize: 33   // scrollbar.ts computed thumbSize
    // thumb translateY: (0 / (400 - 100)) * (100 - 25) -> 0  // (scrollTop / (scrollHeight - clientHeight)) * (clientHeight - thumbSize)
    const initializeStyle =
      'height: 33px; transform: translateY(0px); webkit-transform: translateY(0px); width: 100%;'

    expect(wrapper.find('.el-scrollbar__thumb').attributes('style')).toContain(
      initializeStyle
    )

    const e = document.createEvent('MouseEvents')
    const clientY = 20
    e.initMouseEvent(
      'mousedown',
      false,
      false,
      null,
      0,
      0,
      0,
      0,
      clientY,
      false,
      false,
      false,
      false,
      0,
      null
    )
    el.dispatchEvent(e)

    await nextTick()

    expect(
      wrapper.find('.el-scrollbar__thumb').attributes('style')
    ).not.toContain(initializeStyle)
  })
```

**Review by sxzz — APPROVED** [review]

**Comment by sxzz** [comment]
Great! Could you please commit test code above to this pr?

**Comment by SorrowX** [comment]
> Great! Could you please commit test code above to this pr?

我昨天提交过，但是github这边构建会失败😂，我再提交一次试试

**Comment by sxzz** [comment]
Yeah. Because jest with latest Node is broken. This problem has been fixed.

**Comment by sxzz** [comment]
Also, could you please follow this commit message rule?
```
[function](scope): title
empty line here
- Subject.
```

e.g: `feat(components): [el-virtual-scroll-bar] handle click event

**Comment by SorrowX** [comment]
> Also, could you please follow this commit message rule?
> 
> ```
> [function](scope): title
> empty line here
> - Subject.
> ```
> 
> e.g: `feat(components): [el-virtual-scroll-bar] handle click event`

不好意思，这次我提交过了😂。我下次遵循这样的提交标准。
我记得是这样的
image
那我下次改成大佬你这样的

**Comment by msidolphin** [comment]
> > Also, could you please follow this commit message rule?
> > ```
> > [function](scope): title
> > empty line here
> > - Subject.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e.g: `feat(components): [el-virtual-scroll-bar] handle click event`
> 
> 不好意思，这次我提交过了😂。我下次遵循这样的提交标准。
> 我记得是这样的
> image
> 那我下次改成大佬你这样的

还是改一下吧，毕竟是规范要求，以后提交代码的话可以用yarn cz命令

**Comment by msidolphin** [comment]
> > > Also, could you please follow this commit message rule?
> > > ```
> > > [function](scope): title
> > > empty line here
> > > - Subject.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > e.g: `feat(components): [el-virtual-scroll-bar] handle click event`
> > 
> > 
> > 不好意思，这次我提交过了😂。我下次遵循这样的提交标准。
> > 我记得是这样的
> > image
> > 那我下次改成大佬你这样的
> 
> 还是改一下吧，毕竟是规范要求，以后提交代码的话可以用yarn cz命令，按照上面提到的规范去写

**Comment by SorrowX** [comment]
> > > > Also, could you please follow this commit message rule?
> > > > ```
> > > > [function](scope): title
> > > > empty line here
> > > > - Subject.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > e.g: `feat(components): [el-virtual-scroll-bar] handle click event`
> > > 
> > > 
> > > 不好意思，这次我提交过了😂。我下次遵循这样的提交标准。
> > > 我记得是这样的
> > > image
> > > 那我下次改成大佬你这样的
> > 
> > 
> > 还是改一下吧，毕竟是规范要求，以后提交代码的话可以用yarn cz命令，按照上面提到的规范去写

好

**Comment by sxzz** [comment]
改一下PR的标题就行

**Comment by SorrowX** [comment]
好的，大佬操心了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月9日(星期四) 中午11:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [element-plus/element-plus] ElVirtualScrollBar: add feature (#3308)





 
改一下PR的标题就行
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sxzz** [comment]
> > Also, could you please follow this commit message rule?
> > ```
> > [function](scope): title
> > empty line here
> > - Subject.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > e.g: `feat(components): [el-virtual-scroll-bar] handle click event`
> 
> 不好意思，这次我提交过了😂。我下次遵循这样的提交标准。
> 我记得是这样的
> image
> 那我下次改成大佬你这样的

This docs is outdated. Could you please update it if you wish?

**Review by sxzz — APPROVED** [review]

**Comment by SorrowX** [comment]
重新开个pr,修改文档吗？
改成如下吗？
1. eg: `fix(components): [el-dialog] fix xxx bug`
2. eg: `feat(components): [el-virtual-scroll-bar] xxx`
@sxzz 我是愿意改的，就是怕改不好😂

**Comment by sxzz** [comment]
Don't worry. Just do it~

**Comment by sxzz** [comment]
You can create a new pr, and reference this config https://github.com/element-plus/element-plus/blob/dev/commitlint.config.js

**Comment by SorrowX** [comment]
> You can create a new pr, and reference this config https://github.com/element-plus/element-plus/blob/dev/commitlint.config.js

好，我下午搬完砖，尝试下，大佬，我是国人，你直接讲中文就好了😂

**Pull request merged**
