### PR TITLE
feat(components): [form] add getFieldsValue method

### LINKED ISSUE #16719: [Component] [form] form 为何不提供类似getFieldsvalue方法（动态表单，表单项能到达30+）
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.47`
- Element Plus Version: `2.3.0`
- Browser / OS: `Chrome/mac`
- Build Tool: `Vite`

### Related Component

- `el-form`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJ2YWx1ZVwiIFxuIHBsYWNlaG9sZGVyPVwiU2VsZWN0XCIgdi1pZj1cImlzTW91bnRlZFwiPlxuICAgIDxkaXYgdi1pbmZpbml0ZS1zY3JvbGw9XCJsb2FkXCIgXG5pbmZpbml0ZS1zY3JvbGwtZGlzdGFuY2U9XCIyMFwiXG4gICAgICAgICBzdHlsZT1cImhlaWdodDoyMDBweDtcIj5cbiAgICAgICAgICA8ZWwtb3B0aW9uXG4gICAgICAgICAgICAgICAgICAgICAgICAgICB2LWZvcj1cIml0ZW0gaW4gb3B0aW9uc1wiXG4gICAgICA6a2V5PVwiaXRlbS52YWx1ZVwiXG4gICAgICA6bGFiZWw9XCJpdGVtLmxhYmVsXCJcbiAgICAgIDp2YWx1ZT1cIml0ZW0udmFsdWVcIlxuICAgICAgOmRpc2FibGVkPVwiaXRlbS5kaXNhYmxlZFwiXG4gICAgLz5cbiAgICA8L2Rpdj5cblxuICA8L2VsLXNlbGVjdD5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgbGFuZz1cInRzXCIgc2V0dXA+XG5pbXBvcnQgeyByZWYsIG9uTW91bnRlZCB9IGZyb20gJ3Z1ZSdcbiAgXG4gIGNvbnN0IGlzTW91bnRlZCA9IHJlZihmYWxzZSlcblxuY29uc3QgdmFsdWUgPSByZWYoJycpXG5jb25zdCBvcHRpb25zID0gcmVmKFtcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMScsXG4gICAgbGFiZWw6ICdPcHRpb24xJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uMycsXG4gICAgbGFiZWw6ICdPcHRpb24zJyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNCcsXG4gICAgbGFiZWw6ICdPcHRpb240JyxcbiAgfSxcbiAge1xuICAgIHZhbHVlOiAnT3B0aW9uNScsXG4gICAgbGFiZWw6ICdPcHRpb241JyxcbiAgfSxcbiAgICB7XG4gICAgdmFsdWU6ICdPcHRpb242JyxcbiAgICBsYWJlbDogJ09wdGlvbjYnLFxuICB9LFxuICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uNycsXG4gICAgbGFiZWw6ICdPcHRpb243JyxcbiAgfSxcbiAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sXG4gICAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSwgICAgICB7XG4gICAgdmFsdWU6ICdPcHRpb244JyxcbiAgICBsYWJlbDogJ09wdGlvbjgnLFxuICB9LCAgICAgIHtcbiAgICB2YWx1ZTogJ09wdGlvbjgnLFxuICAgIGxhYmVsOiAnT3B0aW9uOCcsXG4gIH0sICAgICAge1xuICAgIHZhbHVlOiAnT3B0aW9uOCcsXG4gICAgbGFiZWw6ICdPcHRpb244JyxcbiAgfSxcbl0pXG5cbiBjb25zdCBsb2FkID0gKCkgPT4ge1xuIC8v5byC5q2l6I635Y+W5pWw5o2u5Ye95pWw77yM6L+Z6YeM55qEZGVib3VuY2XmmK/miJHoh6rlt7HlsIHoo4XnmoTpmLLmipblh73mlbDvvIzkuI3nhLbkvJrmnInkuIvmi4nkuIDmrKHor7fmsYLkuKTmrKHnmoTpl67popjjgIJcbiAgIGNvbnNvbGUubG9nKDEyMylcbiAgIG9wdGlvbnMudmFsdWUucHVzaCh7XG4gICAgICAgICB2YWx1ZTogJ09wdGlvbjEwJyxcbiAgICBsYWJlbDogJ09wdGlvbjEwJyxcbiAgIH0pXG4gfTtcblxub25Nb3VudGVkKCgpID0+IHtcbiAgaXNNb3VudGVkLnZhbHVlID0gdHJ1ZVxufSlcbjwvc2NyaXB0PlxuIiwiaW1wb3J0X21hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0iLCJfbyI6e319)

### Steps to reproduce

无

### What is Expected?

能获取getFeildsvalue类型的api

### What is actually happening?

没有

### Additional comments

动态表单能获取到的展示的表单项值，而不是model所有的字段

### PR DESCRIPTION
**Pull request by Liao-js**
fix https://github.com/element-plus/element-plus/issues/16719

Please make sure these boxes are checked before submitting your PR, thank you!

- [x] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [x] Make sure you are merging your commits to `dev` branch.
- [x] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by btea** [comment]
The functions of this PR overlap with those discussed in #16747. Directly exporting fields will give users more room to operate.

**Comment by Liao-js** [comment]
> The functions of this PR overlap with those discussed in #16747. Directly exporting fields will give users more room to operate.

ok, what do you need me to do?

**Comment by Liao-js** [comment]
directly exporting fields will give users more room to operate，but I think this does not conflict with pr. My method is more suitable for users who use dynamic forms. It can facilitate users to directly obtain the value of the corresponding structure for direct submission without additional processing of propString.

**Comment by warmthsea** [comment]
Related https://github.com/element-plus/element-plus/discussions/16747

https://element.eleme.io/#/zh-CN/component/form

**Comment by btea** [comment]
@tolking  Do you think this new method in PR is necessary? IMO, it should be enough to directly export `fields` and let users handle it themselves.

**Comment by btea** [comment]
> directly exporting fields will give users more room to operate，but I think this does not conflict with pr. The functions is more suitable for users who use dynamic forms. It can facilitate users to directly obtain the value of the corresponding structure for direct submission without additional processing of propString.

Yes, you have a point. But this is the first time I've seen a need in this area, and this method doesn't seem to be used frequently. I don't know if we should add it, maybe more people should be consulted.

**Comment by tolking** [comment]
IMO, It would be better for users to implement this special requirement by themselves.

The newly added code may be redundant for most people.

**Comment by FrontEndDog** [comment]
IMO, This method leans more towards the business level, Not every user needs to submit data of type 'Record<string, any>', It may also be of other types, such as `<label: string, value: any>[]`, So I think it's better to  exporting `fields` and let users handle the data on their own.

在我看来，这个方法更偏向于业务层面，并不是每个用户所需要提交的数据都是`Record<string, any>`类型的，也可能是其他类型，例如`<label: string, value: any>[]`，所以我认为暴露出`fileds`字段让用户自行处理数据更好一些。

**Comment by Liao-js** [comment]
I agree with your point of view, I did not consider it comprehensively enough.

**Pull request closed without merging**
