### PR TITLE
[Refactor] Refactor Plan

### LINKED ISSUE #1795: [Feature Request] Get the correct type inference
### Existing Component
No

### Component Name
all

### Description
How should I get inferences when I use element and typescript.
The type of the method parameter in the component is too difficult to infer.
I don't know how to combine TS with type inference, right.
Hopefully the documentation on TS support will be completed.

### LINKED ISSUE #2040: [Feature Request] Export prop type interfaces such as `IButtonProps`
### Existing Component

Yes

### Component Name

All components

### Description

I'm encapsulating `ElButton` to `VButton`, instead of manually adding prop types, it'll be much more convenient to use the original `IButtonProps` instead, however, it's not exported:

```tsx
import { ElButton } from 'element-plus'
import { defineComponent, ref } from 'vue'

export default defineComponent({
  inheritAttrs: false,
  //           👇 manually adding prop types
  setup(props: { type: string; size: string }, { attrs, slots }) {
    // 👇 it'll be much more convenient to use `IButtonProps` instead
    // setup(props: IButtonProps, { attrs, slots }) {
    const btn = ref<InstanceType<typeof ElButton>>()

    return () => (
      <ElButton
        class='v-button'
        ref={btn}
        size='medium'
        onClick={() => btn.value?.$el.blur()}
        {...attrs}
        vSlots={slots}
      />
    )
  },
})
```

This request applies to all available components.

I'm relatively new to typescript, please correct me if it's infeasible. Also, if there's a better way for achieving the same typing experience without doing the exports, please let me know.

### PR DESCRIPTION
**Pull request by sxzz**
# Refactor

## Summary

- Improve all project typings.
- Drop deprecated APIs.

## Contribute Guide

- Create an PR. e.g `refactor(components): refactor button`
  - Please at`@` me.
  - Please assign to me if you're Element Plus member.
  - Please add PR link to below `Progress` if you have permission.
  - I will review it ASAP.
- 🛠 ❌ **fix ALL TypeScript errors.**
  - ⚠️ Priority: highest
  - Please refer to https://github.com/element-plus/element-plus/pull/3113#issuecomment-967230194
- 🧲 Extract `.vue` props and emits to `.ts`.
  - Philosophy: Write the logical part into ts file as much as possible.
  - add `InstanceType` for each components #4308
- 🎨 Use setup return render method.
  - Use `setup() { return () => { /* code here */ } }`
- 📁 Structure
  - Move `tokens` to `@element-plus/tokens`.
    - Only context type interface
    - Only injection key
- 🔑 Use `withInstall`.
  - Please refer to completed files if you're confused.
- 🪛 Refactor **ALL** APIs in detail.
- 🧱 Do not use SFC(`.vue`), if there is no template.

For more details, please refer to `Task List` and merged pull request below. Thanks for your contribution!

### ⭐️ Feature

- [x] `el-check-tag` support `v-model:checked`.
  - https://github.com/element-plus/element-plus/pull/3311
- [ ] `el-menu` add `v-model:opened`
  - https://github.com/element-plus/element-plus/issues/3122

### ♻️ Typing

- [x] 🦾 use typescript `strict` mode, increase code reliability.
- `RefElement` -> use the exact element type.
  - e.g `HTMLDivElement`
- `null` -> prefer `undefined`.
  - e.g `ref<HTMLDivElement>()`. **NOT** `ref(null)`
- Try not to use type assertions.
  - e.g ❌ BAD `inject(foo, {} as FooType)`
- [ ] improve and export props and emits type.
- [ ] add `InstanceType` for each components.
  - https://github.com/element-plus/element-plus/issues/4308
- [ ] add `vue-tsc` checker for unit test.

### 🔨 Utils / Hooks

- [ ] `VueUse`
  - https://github.com/element-plus/element-plus/pull/3370
  - https://github.com/element-plus/element-plus/pull/3374
  - [ ] `useEventListener` (remove `on`, `off`)
  - [ ] `onClickOutside` (remove directive)
  - [ ] `useResizeObserver` (remove directive and `@element-plus/utils/resize-event`)
  - [x] `isClient` (remove `isServer`)
- [x] ~~Use `useFormItem`.~~ Use `useSize` and `useDisabled`
  - https://github.com/element-plus/element-plus/pull/4730

### 👌 Compatibility

- Now only support `Edge` ≥ 79, `Firefox` ≥ 78, `Chrome` ≥ 64, `Safari` ≥ 12
- [x] Docs
  - https://github.com/element-plus/element-plus/pull/3342
- [x] Drop IE support
  - https://github.com/element-plus/element-plus/pull/3304
- [x] Remove `ResizeObserver` polyfill
  - https://github.com/element-plus/element-plus/pull/4058
- [x] Remove CSS prefix e.g `-ms-`
  - https://github.com/element-plus/element-plus/pull/4075

### Naming

- [ ] 📁 unify file naming rules: `kebab-case`.
  - https://github.com/element-plus/element-plus/pull/3113#issuecomment-917482311
- Rename `index.vue` to `[component-name].vue`.
- Unify file naming rules to `kebab-case.{ts,vue}`.

## Progress

Moved to #6114

- [ ] ✅ `vue-tsc` emit no error and add to ci check.
  - ~~`Found 1823 errors.`~~
  - ~~`Found 1773 errors.`~~
  - ~~`Found 1629 errors.`~~
  - ~~`Found 1617 errors.`~~
  - ~~`Found 1614 errors.`~~
  - ~~`Found 1533 errors.`~~
  - ~~`Found 1353 errors.`~~
  - ~~`Found 1292 errors.`~~
  - ~~`Found 1128 errors.` (144 files)~~
  - `Found 1050 errors.`

🚀 Embrace `TypeScript`!

### CODE REVIEW

**Comment by sxzz** [comment]
```
-rw-r--r--  1 kevin  staff   6120  9 11 16:25 packages/components/checkbox/src/useCheckbox.ts
-rw-r--r--  1 kevin  staff    255  9 11 16:25 packages/components/color-picker/src/useOption.ts
-rw-r--r--  1 kevin  staff   3517  9 11 16:25 packages/components/dropdown/src/useDropdown.ts
-rw-r--r--  1 kevin  staff   2813  9 11 16:25 packages/components/input/src/calcTextareaHeight.ts
-rw-r--r--  1 kevin  staff   3994  9 11 16:25 packages/components/loading/src/createLoadingComponent.ts
-rw-r--r--  1 kevin  staff   5432  9 11 16:25 packages/components/message-box/src/messageBox.ts
-rw-r--r--  1 kevin  staff    174  9 12 05:11 packages/components/pagination/src/usePagination.ts
-rw-r--r--  1 kevin  staff   1137  9 12 05:11 packages/components/popover/src/usePopover.ts
-rw-r--r--  1 kevin  staff   1689  9 11 16:25 packages/components/radio/src/useRadio.ts
-rw-r--r--  1 kevin  staff   2327  9 11 16:25 packages/components/select-v2/src/useAllowCreate.ts
-rw-r--r--  1 kevin  staff    778  9 11 16:25 packages/components/select-v2/src/useInput.ts
-rw-r--r--  1 kevin  staff    346  9 11 16:25 packages/components/select-v2/src/useOption.ts
-rw-r--r--  1 kevin  staff  20774  9 11 16:25 packages/components/select-v2/src/useSelect.ts
-rw-r--r--  1 kevin  staff   3449  9 11 16:25 packages/components/select/src/useOption.ts
-rw-r--r--  1 kevin  staff  22868  9 11 20:05 packages/components/select/src/useSelect.ts
-rw-r--r--  1 kevin  staff    593  9 11 16:25 packages/components/slider/src/useMarks.ts
-rw-r--r--  1 kevin  staff   3726  9 11 16:25 packages/components/slider/src/useSlide.ts
-rw-r--r--  1 kevin  staff   6275  9 11 16:25 packages/components/slider/src/useSliderButton.ts
-rw-r--r--  1 kevin  staff   1446  9 11 20:05 packages/components/slider/src/useStops.ts
-rw-r--r--  1 kevin  staff   3619  9 12 05:11 packages/components/space/src/useSpace.ts
-rw-r--r--  1 kevin  staff    930  9 11 16:25 packages/components/table/src/table-footer/mapState-helper.ts
-rw-r--r--  1 kevin  staff     73  9 11 16:25 packages/components/table/src/tableColumn.ts
-rw-r--r--  1 kevin  staff   2034  9 11 16:25 packages/components/time-picker/src/time-picker-com/useTimePicker.ts
-rw-r--r--  1 kevin  staff   4163  9 11 16:25 packages/components/transfer/src/useCheck.ts
-rw-r--r--  1 kevin  staff    730  9 11 16:25 packages/components/transfer/src/useCheckedChange.ts
-rw-r--r--  1 kevin  staff    930  9 11 16:25 packages/components/transfer/src/useComputedData.ts
-rw-r--r--  1 kevin  staff   1463  9 11 16:25 packages/components/transfer/src/useMove.ts
-rw-r--r--  1 kevin  staff   6186  9 11 16:25 packages/components/tree/src/model/useDragNode.ts
-rw-r--r--  1 kevin  staff   3682  9 11 16:25 packages/components/tree/src/model/useKeydown.ts
-rw-r--r--  1 kevin  staff    763  9 11 16:25 packages/components/tree/src/model/useNodeExpandEventBroadcast.ts
-rw-r--r--  1 kevin  staff   4321  9 11 16:25 packages/components/upload/src/useHandlers.ts
-rw-r--r--  1 kevin  staff  14539  9 11 16:25 packages/components/virtual-list/src/builders/buildGrid.ts
-rw-r--r--  1 kevin  staff  14523  9 11 16:25 packages/components/virtual-list/src/builders/buildList.ts
-rw-r--r--  1 kevin  staff   1484  9 11 16:25 packages/components/virtual-list/src/hooks/useWheel.ts
-rw-r--r--  1 kevin  staff    128  8 27 19:47 packages/element-plus/README.md
-rw-r--r--  1 kevin  staff    540  9 11 16:25 packages/theme-chalk/README.md
-rw-r--r--  1 kevin  staff    131  8 27 19:47 packages/utils/isDef.ts
-rw-r--r--  1 kevin  staff     45  8 27 19:47 packages/utils/isServer.ts
-rw-r--r--  1 kevin  staff  6120  9 11 16:25 useCheckbox.ts
-rw-r--r--  1 kevin  staff   255  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  3517  9 11 16:25 useDropdown.ts
-rw-r--r--  1 kevin  staff   2813  9 11 16:25 calcTextareaHeight.ts
-rw-r--r--  1 kevin  staff  3994  9 11 16:25 createLoadingComponent.ts
-rw-r--r--  1 kevin  staff   5432  9 11 16:25 messageBox.ts
-rw-r--r--  1 kevin  staff   174  9 12 05:11 usePagination.ts
-rw-r--r--  1 kevin  staff  1137  9 12 05:11 usePopover.ts
-rw-r--r--  1 kevin  staff  1689  9 11 16:25 useRadio.ts
-rw-r--r--  1 kevin  staff   2327  9 11 16:25 useAllowCreate.ts
-rw-r--r--  1 kevin  staff    778  9 11 16:25 useInput.ts
-rw-r--r--  1 kevin  staff    346  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  20774  9 11 16:25 useSelect.ts
-rw-r--r--  1 kevin  staff   3449  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  22868  9 11 20:05 useSelect.ts
-rw-r--r--  1 kevin  staff   593  9 11 16:25 useMarks.ts
-rw-r--r--  1 kevin  staff  3726  9 11 16:25 useSlide.ts
-rw-r--r--  1 kevin  staff  6275  9 11 16:25 useSliderButton.ts
-rw-r--r--  1 kevin  staff  1446  9 11 20:05 useStops.ts
-rw-r--r--  1 kevin  staff  3619  9 12 05:11 useSpace.ts
-rw-r--r--  1 kevin  staff     73  9 11 16:25 tableColumn.ts
-rw-r--r--  1 kevin  staff   930  9 11 16:25 mapState-helper.ts
-rw-r--r--  1 kevin  staff   2034  9 11 16:25 useTimePicker.ts
-rw-r--r--  1 kevin  staff  4163  9 11 16:25 useCheck.ts
-rw-r--r--  1 kevin  staff   730  9 11 16:25 useCheckedChange.ts
-rw-r--r--  1 kevin  staff   930  9 11 16:25 useComputedData.ts
-rw-r--r--  1 kevin  staff  1463  9 11 16:25 useMove.ts
-rw-r--r--  1 kevin  staff   6186  9 11 16:25 useDragNode.ts
-rw-r--r--  1 kevin  staff   3682  9 11 16:25 useKeydown.ts
-rw-r--r--  1 kevin  staff    763  9 11 16:25 useNodeExpandEventBroadcast.ts
-rw-r--r--  1 kevin  staff  4321  9 11 16:25 useHandlers.ts
-rw-r--r--  1 kevin  staff  14539  9 11 16:25 buildGrid.ts
-rw-r--r--  1 kevin  staff  14523  9 11 16:25 buildList.ts
-rw-r--r--  1 kevin  staff  1484  9 11 16:25 useWheel.ts
-rw-r--r--  1 kevin  staff   128  8 27 19:47 README.md
-rw-r--r--    1 kevin  staff   540  9 11 16:25 README.md
-rw-r--r--  1 kevin  staff   131  8 27 19:47 isDef.ts
-rw-r--r--  1 kevin  staff    45  8 27 19:47 isServer.ts
```

**Comment by sxzz** [comment]
```
-rw-r--r--  1 kevin  staff   6120  9 11 16:25 packages/components/checkbox/src/useCheckbox.ts
-rw-r--r--  1 kevin  staff    255  9 11 16:25 packages/components/color-picker/src/useOption.ts
-rw-r--r--  1 kevin  staff   3517  9 11 16:25 packages/components/dropdown/src/useDropdown.ts
-rw-r--r--  1 kevin  staff   2813  9 11 16:25 packages/components/input/src/calcTextareaHeight.ts
-rw-r--r--  1 kevin  staff   3994  9 11 16:25 packages/components/loading/src/createLoadingComponent.ts
-rw-r--r--  1 kevin  staff   5432  9 11 16:25 packages/components/message-box/src/messageBox.ts
-rw-r--r--  1 kevin  staff    174  9 12 05:11 packages/components/pagination/src/usePagination.ts
-rw-r--r--  1 kevin  staff   1137  9 12 05:11 packages/components/popover/src/usePopover.ts
-rw-r--r--  1 kevin  staff   1689  9 11 16:25 packages/components/radio/src/useRadio.ts
-rw-r--r--  1 kevin  staff   2327  9 11 16:25 packages/components/select-v2/src/useAllowCreate.ts
-rw-r--r--  1 kevin  staff    778  9 11 16:25 packages/components/select-v2/src/useInput.ts
-rw-r--r--  1 kevin  staff    346  9 11 16:25 packages/components/select-v2/src/useOption.ts
-rw-r--r--  1 kevin  staff  20774  9 11 16:25 packages/components/select-v2/src/useSelect.ts
-rw-r--r--  1 kevin  staff   3449  9 11 16:25 packages/components/select/src/useOption.ts
-rw-r--r--  1 kevin  staff  22868  9 11 20:05 packages/components/select/src/useSelect.ts
-rw-r--r--  1 kevin  staff    593  9 11 16:25 packages/components/slider/src/useMarks.ts
-rw-r--r--  1 kevin  staff   3726  9 11 16:25 packages/components/slider/src/useSlide.ts
-rw-r--r--  1 kevin  staff   6275  9 11 16:25 packages/components/slider/src/useSliderButton.ts
-rw-r--r--  1 kevin  staff   1446  9 11 20:05 packages/components/slider/src/useStops.ts
-rw-r--r--  1 kevin  staff   3619  9 12 05:11 packages/components/space/src/useSpace.ts
-rw-r--r--  1 kevin  staff    930  9 11 16:25 packages/components/table/src/table-footer/mapState-helper.ts
-rw-r--r--  1 kevin  staff     73  9 11 16:25 packages/components/table/src/tableColumn.ts
-rw-r--r--  1 kevin  staff   2034  9 11 16:25 packages/components/time-picker/src/time-picker-com/useTimePicker.ts
-rw-r--r--  1 kevin  staff   4163  9 11 16:25 packages/components/transfer/src/useCheck.ts
-rw-r--r--  1 kevin  staff    730  9 11 16:25 packages/components/transfer/src/useCheckedChange.ts
-rw-r--r--  1 kevin  staff    930  9 11 16:25 packages/components/transfer/src/useComputedData.ts
-rw-r--r--  1 kevin  staff   1463  9 11 16:25 packages/components/transfer/src/useMove.ts
-rw-r--r--  1 kevin  staff   6186  9 11 16:25 packages/components/tree/src/model/useDragNode.ts
-rw-r--r--  1 kevin  staff   3682  9 11 16:25 packages/components/tree/src/model/useKeydown.ts
-rw-r--r--  1 kevin  staff    763  9 11 16:25 packages/components/tree/src/model/useNodeExpandEventBroadcast.ts
-rw-r--r--  1 kevin  staff   4321  9 11 16:25 packages/components/upload/src/useHandlers.ts
-rw-r--r--  1 kevin  staff  14539  9 11 16:25 packages/components/virtual-list/src/builders/buildGrid.ts
-rw-r--r--  1 kevin  staff  14523  9 11 16:25 packages/components/virtual-list/src/builders/buildList.ts
-rw-r--r--  1 kevin  staff   1484  9 11 16:25 packages/components/virtual-list/src/hooks/useWheel.ts
-rw-r--r--  1 kevin  staff    131  8 27 19:47 packages/utils/isDef.ts
-rw-r--r--  1 kevin  staff     45  8 27 19:47 packages/utils/isServer.ts
-rw-r--r--  1 kevin  staff  6120  9 11 16:25 useCheckbox.ts
-rw-r--r--  1 kevin  staff   255  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  3517  9 11 16:25 useDropdown.ts
-rw-r--r--  1 kevin  staff   2813  9 11 16:25 calcTextareaHeight.ts
-rw-r--r--  1 kevin  staff  3994  9 11 16:25 createLoadingComponent.ts
-rw-r--r--  1 kevin  staff   5432  9 11 16:25 messageBox.ts
-rw-r--r--  1 kevin  staff   174  9 12 05:11 usePagination.ts
-rw-r--r--  1 kevin  staff  1137  9 12 05:11 usePopover.ts
-rw-r--r--  1 kevin  staff  1689  9 11 16:25 useRadio.ts
-rw-r--r--  1 kevin  staff   2327  9 11 16:25 useAllowCreate.ts
-rw-r--r--  1 kevin  staff    778  9 11 16:25 useInput.ts
-rw-r--r--  1 kevin  staff    346  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  20774  9 11 16:25 useSelect.ts
-rw-r--r--  1 kevin  staff   3449  9 11 16:25 useOption.ts
-rw-r--r--  1 kevin  staff  22868  9 11 20:05 useSelect.ts
-rw-r--r--  1 kevin  staff   593  9 11 16:25 useMarks.ts
-rw-r--r--  1 kevin  staff  3726  9 11 16:25 useSlide.ts
-rw-r--r--  1 kevin  staff  6275  9 11 16:25 useSliderButton.ts
-rw-r--r--  1 kevin  staff  1446  9 11 20:05 useStops.ts
-rw-r--r--  1 kevin  staff  3619  9 12 05:11 useSpace.ts
-rw-r--r--  1 kevin  staff     73  9 11 16:25 tableColumn.ts
-rw-r--r--  1 kevin  staff   930  9 11 16:25 mapState-helper.ts
-rw-r--r--  1 kevin  staff   2034  9 11 16:25 useTimePicker.ts
-rw-r--r--  1 kevin  staff  4163  9 11 16:25 useCheck.ts
-rw-r--r--  1 kevin  staff   730  9 11 16:25 useCheckedChange.ts
-rw-r--r--  1 kevin  staff   930  9 11 16:25 useComputedData.ts
-rw-r--r--  1 kevin  staff  1463  9 11 16:25 useMove.ts
-rw-r--r--  1 kevin  staff   6186  9 11 16:25 useDragNode.ts
-rw-r--r--  1 kevin  staff   3682  9 11 16:25 useKeydown.ts
-rw-r--r--  1 kevin  staff    763  9 11 16:25 useNodeExpandEventBroadcast.ts
-rw-r--r--  1 kevin  staff  4321  9 11 16:25 useHandlers.ts
-rw-r--r--  1 kevin  staff  14539  9 11 16:25 buildGrid.ts
-rw-r--r--  1 kevin  staff  14523  9 11 16:25 buildList.ts
-rw-r--r--  1 kevin  staff  1484  9 11 16:25 useWheel.ts
-rw-r--r--  1 kevin  staff   131  8 27 19:47 isDef.ts
-rw-r--r--  1 kevin  staff    45  8 27 19:47 isServer.ts
```

**Comment by Otto-J** [comment]
👀  pr welcome?

**Comment by JeremyWuuuuu** [comment]
> 👀  pr welcome?

Absolutely, we are more than happy to have contributions from the community! Please let me know if you are interested in refactoring any of these components. 😃

**Comment by Otto-J** [comment]
> > 👀  pr welcome?
> 
> Absolutely, we are more than happy to have contributions from the community! Please let me know if you are interested in refactoring any of these components. 😃

My pleasure. I'll review the code and then choose one of them.

**Comment by sxzz** [comment]
@Otto-J Hi, I sent an email to you, please check it when you are free.

**Comment by Otto-J** [comment]
被通知邮件淹没了，没看到是哪个，啥内容

**Comment by JeremyWuuuuu** [comment]
> 被通知邮件淹没了，没看到是哪个，啥内容

大概是要邀请你进群（core team

**Comment by Otto-J** [comment]
😭  兴奋！但的确没看到。再邀请一次？

**Comment by JeremyWuuuuu** [comment]
> 😭 兴奋！但的确没看到。再邀请一次？

我先拉你进 Backers team 吧。你看下 GitHub 关联的邮箱。

**Comment by undefined-degisn** [comment]
可以直接改完提pr吗？

**Comment by sxzz** [comment]
@undefined-degisn 可以的

**Comment by sxzz** [comment]
@undefined-degisn @Alanscut 我更新了 Contribute Guide，请参考 Guide 进行重构。Thanks~

**Comment by undefined-degisn** [comment]
> @undefined-degisn @Alanscut 我更新了 Contribute Guide，请参考 Guide 进行重构。Thanks~

好的，我这两天会尽快重构完成的！

**Comment by sxzz** [comment]
```
packages/components/autocomplete/src/index.vue
packages/components/calendar/src/date-table.vue
packages/components/calendar/src/index.vue
packages/components/carousel/src/item.vue
packages/components/carousel/src/main.vue
packages/components/cascader-panel/src/menu.vue
packages/components/cascader-panel/src/node-content.ts
packages/components/cascader-panel/src/node.ts
packages/components/cascader-panel/src/node.vue
packages/components/checkbox/src/checkbox-button.vue
packages/components/checkbox/src/checkbox-group.vue
packages/components/checkbox/src/checkbox.vue
packages/components/checkbox/src/useCheckbox.ts
packages/components/collapse/src/collapse.vue
packages/components/color-picker/src/components/alpha-slider.vue
packages/components/color-picker/src/components/hue-slider.vue
packages/components/color-picker/src/components/predefine.vue
packages/components/color-picker/src/components/sv-panel.vue
packages/components/color-picker/src/index.vue
packages/components/date-picker/src/date-picker-com/basic-date-table.vue
packages/components/date-picker/src/date-picker-com/basic-month-table.vue
packages/components/date-picker/src/date-picker-com/basic-year-table.vue
packages/components/date-picker/src/date-picker-com/panel-date-pick.vue
packages/components/date-picker/src/date-picker-com/panel-date-range.vue
packages/components/date-picker/src/date-picker-com/panel-month-range.vue
packages/components/date-picker/src/date-picker.ts
packages/components/descriptions/src/descriptions-cell.ts
packages/components/descriptions/src/index.vue
packages/components/drawer/src/index.vue
packages/components/dropdown/src/dropdown-item.vue
packages/components/dropdown/src/dropdown-menu.vue
packages/components/dropdown/src/dropdown.vue
packages/components/dropdown/src/useDropdown.ts
packages/components/form/src/form-item.vue
packages/components/form/src/form.vue
packages/components/form/src/label-wrap.ts
packages/components/infinite-scroll/src/index.ts
packages/components/loading/src/createLoadingComponent.ts
packages/components/loading/src/directive.ts
packages/components/loading/src/index.ts
packages/components/menu/src/menu-item.vue
packages/components/message-box/src/index.vue
packages/components/message-box/src/messageBox.ts
packages/components/message/src/message.vue
packages/components/pagination/src/components/sizes.vue
packages/components/pagination/src/pagination.ts
packages/components/popconfirm/__test__/popconfirm.spec.ts
packages/components/popover/src/directive.ts
packages/components/popover/src/index.vue
packages/components/popper/src/index.vue
packages/components/popper/src/renderers/arrow.ts
packages/components/popper/src/use-popper/index.ts
packages/components/progress/src/index.vue
packages/components/select-v2/src/group-item.vue
packages/components/select-v2/src/option-item.vue
packages/components/select-v2/src/select.vue
packages/components/select-v2/src/useAllowCreate.ts
packages/components/select-v2/src/useSelect.ts
packages/components/select-v2/src/util.ts
packages/components/select/src/option-group.vue
packages/components/select/src/option.vue
packages/components/select/src/select-dropdown.vue
packages/components/select/src/select.vue
packages/components/select/src/useOption.ts
packages/components/select/src/useSelect.ts
packages/components/slider/src/index.vue
packages/components/slider/src/marker.vue
packages/components/slider/src/useMarks.ts
packages/components/slider/src/useSlide.ts
packages/components/slider/src/useSliderButton.ts
packages/components/slider/src/useStops.ts
packages/components/steps/src/index.vue
packages/components/steps/src/item.vue
packages/components/switch/src/index.vue
packages/components/table/src/config.ts
packages/components/table/src/filter-panel.vue
packages/components/table/src/layout-observer.ts
packages/components/table/src/store/current.ts
packages/components/table/src/store/helper.ts
packages/components/table/src/store/index.ts
packages/components/table/src/store/tree.ts
packages/components/table/src/store/watcher.ts
packages/components/table/src/table-body/defaults.ts
packages/components/table/src/table-body/events-helper.ts
packages/components/table/src/table-body/index.ts
packages/components/table/src/table-body/render-helper.ts
packages/components/table/src/table-body/styles-helper.ts
packages/components/table/src/table-column/defaults.ts
packages/components/table/src/table-column/index.ts
packages/components/table/src/table-column/render-helper.ts
packages/components/table/src/table-footer/index.ts
packages/components/table/src/table-footer/mapState-helper.ts
packages/components/table/src/table-footer/style-helper.ts
packages/components/table/src/table-header/event-helper.ts
packages/components/table/src/table-header/index.ts
packages/components/table/src/table-header/style.helper.ts
packages/components/table/src/table-header/utils-helper.ts
packages/components/table/src/table-layout.ts
packages/components/table/src/table.vue
packages/components/table/src/table/defaults.ts
packages/components/table/src/table/style-helper.ts
packages/components/table/src/table/utils-helper.ts
packages/components/table/src/util.ts
packages/components/time-picker/src/common/picker.vue
packages/components/time-picker/src/time-picker-com/basic-time-spinner.vue
packages/components/time-picker/src/time-picker-com/panel-time-pick.vue
packages/components/time-picker/src/time-picker-com/panel-time-range.vue
packages/components/time-picker/src/time-picker-com/useTimePicker.ts
packages/components/time-picker/src/time-picker.ts
packages/components/time-select/src/time-select.vue
packages/components/tooltip/src/index.ts
packages/components/transfer/src/index.vue
packages/components/transfer/src/transfer-panel.vue
packages/components/transfer/src/useCheck.ts
packages/components/transfer/src/useComputedData.ts
packages/components/tree/src/model/node.ts
packages/components/tree/src/model/tree-store.ts
packages/components/tree/src/model/useDragNode.ts
packages/components/tree/src/model/useKeydown.ts
packages/components/tree/src/model/useNodeExpandEventBroadcast.ts
packages/components/tree/src/tree-node-content.vue
packages/components/tree/src/tree-node.vue
packages/components/tree/src/tree.vue
packages/components/upload/src/index.vue
packages/components/upload/src/upload-dragger.vue
packages/components/upload/src/upload-list.vue
packages/components/upload/src/upload.vue
packages/components/upload/src/useHandlers.ts
packages/components/virtual-list/setup-mock.ts
packages/directives/click-outside/index.ts
packages/directives/repeat-click/index.ts
packages/directives/resize/index.ts
packages/directives/trap-focus/index.ts
packages/hooks/use-popper/index.ts
packages/hooks/use-throttle-render/index.ts
packages/hooks/use-transition-fallthrough/index.ts
packages/locale/index.ts
packages/tokens/config-provider.ts
packages/utils/global-nodes.ts
packages/utils/menu/menu-item.ts
packages/utils/menu/submenu.ts
packages/utils/popup-manager.ts
packages/utils/scroll-into-view.ts
packages/utils/util.ts
```

**Comment by sxzz** [comment]
#6114

**Pull request closed without merging**
