### PR TITLE
fix(components): [select] array data display at initial rendering

### LINKED ISSUE #12196: [Component] [select] el-select为什么不能显示绑定的数组数据？
Bug Type: **`Component`**

## Environment

- Vue Version: `3.2.46`
- Element Plus Version: `2.3.1`
- Browser / OS: `UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36`
- Build Tool: `Vite`

### Related Component

- `el-select`

### Reproduction Link

[Element Plus Playground](https://element-plus.run/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8c3Bhbj5cbiAgICA8ZGl2PlxuICAgICAg5Yid5aeL5pWw5o2u77yae3tkYXRhfX0g546w5Zyo5bem6L655piv56m655qE77yM5LiN5pi+56S65pWw5o2uXG4gICAgPC9kaXY+XG4gICAgPGRpdj5cbiAgICA8ZWwtc2VsZWN0IHYtbW9kZWw9XCJkYXRhXCI+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi56ysMemhuVwiIDp2YWx1ZT1cIlsxMjAsMTAwXVwiIC8+XG4gICAgICA8ZWwtb3B0aW9uIGxhYmVsPVwi56ysMumhuVwiIDp2YWx1ZT1cIlsxMCwyMF1cIiAvPlxuICAgICAgPGVsLW9wdGlvbiBsYWJlbD1cIuesrDPpoblcIiA6dmFsdWU9XCJbMzAsNTBdXCIgLz5cbiAgICA8L2VsLXNlbGVjdD5cbiAgICA8L2Rpdj5cbiAgICDlpoLmnpzmiJHmiorkuIrpnaLnmoRlbC1zZWxlY3Tms6jph4rmjonvvIzliJ3lp4vmlbDmja7lkI7pnaLlsLHkvJrmraPluLjmmL7npLpbMTAsMjBdXG4gIDwvc3Bhbj5cbjwvdGVtcGxhdGU+XG5cbjxzY3JpcHQgc2V0dXA+XG5pbXBvcnQgeyByZWYgfSBmcm9tICd2dWUnXG5pbXBvcnQgeyBFbGVtZW50UGx1cyB9IGZyb20gJ0BlbGVtZW50LXBsdXMvaWNvbnMtdnVlJ1xuXG5jb25zdCBkYXRhID0gcmVmKFsxMCwyMF0pXG48L3NjcmlwdD4iLCJpbXBvcnRfbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7fVxufSIsIl9vIjp7fX0=)

### Steps to reproduce

刷新即可

### What is Expected?

在el-select组件上正常显示[10,20]选项

### What is actually happening?

实际是显示的为空

### Additional comments

_(empty)_

### PR DESCRIPTION
**Pull request by ryuhangyeong**
closed #12196

Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by ryuhangyeong** [comment]
@HerringtonDarkholme May I request a review from you?

**Comment by btea** [comment]
This seems to be a wrong usage, `multiple` is false, modelValue should not be an array.

**Comment by ryuhangyeong** [comment]
Does this mean that arrays cannot be used in v-model if multiple props is false?

**Comment by btea** [comment]
According to existing logic, it looks like this.

**Comment by wwwwhhhzzzccc** [comment]
> 

but sometimes, we need choose option which is array when "multi" is false, we want option is a range like "10 to 20", in this case, modevalue is better use "[10,20]"

**Comment by btea** [comment]
@wwwwhhhzzzccc Perhaps the array can be converted into a string, otherwise it may affect the logic of multiple selection.

**Pull request closed without merging**
