### PR TITLE
chore(docs): modify tooltip base style

### PR DESCRIPTION
**Pull request by imswk**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

### CODE REVIEW

**Comment by imswk** [comment]
update docs tooltip style 
image

**Comment by YunYouJun** [comment]
Hey, try use [windicss](https://windicss.org/)?

I think this can make our example more concise and avoid css conflicts.

**Comment by emojiiii** [comment]
> Hey, try use [windicss](https://windicss.org/)?
> 
> I think this can make our example more concise and avoid css conflicts.

`Windcss` cannot be used temporarily because the document will be migrated to `playground`

**Comment by imswk** [comment]
How should I modify it now？

**Comment by emojiiii** [comment]
> How should I modify it now？

please use `css`, don't use `scss`.
I will think about how to make playground support `windicss`

**Comment by imswk** [comment]
> > How should I modify it now？
> 
> please use `css`, don't use `scss`. I will think about how to make playground support `windicss`

done

**Comment by YunYouJun** [comment]
> `Windcss` cannot be used temporarily because the document will be migrated to `playground`

Add unocss for it?

**Review by YunYouJun — APPROVED** [review]

**Comment by emojiiii** [comment]
> > `Windcss` cannot be used temporarily because the document will be migrated to `playground`
> 
> Add unocss for it?

i will try me best

**Pull request merged**
