### PR TITLE
fix(theme-chalk): fix deprecated sass function

### PR DESCRIPTION
**Pull request by k713927**
Please make sure these boxes are checked before submitting your PR, thank you!

- [ ] Make sure you follow contributing guide [English](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.en-US.md) | ([中文](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.zh-CN.md) | [Español](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.es.md) | [Français](https://github.com/element-plus/element-plus/blob/master/.github/CONTRIBUTING.fr-FR.md)).
- [ ] Make sure you are merging your commits to `dev` branch.
- [ ] Add some descriptions and refer to relative issues for your PR.

当使用自定义主题的时候，set `vite.config.ts` `.css.preprocessorOptions.scss.additionalData` ,this warming will show

image

image

### CODE REVIEW

**Comment by btea** [comment]
Thanks for your contribution, but it seems to be a duplicate of #18579.

**Comment by k713927** [comment]
> 感谢您的贡献，但它似乎是#18579的重复。

Sorry, I didn't pay attention to see someone submitted, , but I found that `packages/theme-chalk/src/color/index.scss` file  also has expired warming

**Comment by k713927** [comment]
> Thanks for your contribution, but it seems to be a duplicate of #18579.

Sorry, I didn't pay attention to see someone submitted, , but I found that `packages/theme-chalk/src/color/index.scss` file also has expired warming

**Comment by btea** [comment]
You can comment on #18579 to help review and push the PR forward.

**Comment by jiaopengzi** [comment]
> You can comment on #18579 to help review and push the PR forward.

yes, now use the version is  ` "element-plus": "^2.8.6"`  `"sass": "^1.80.3"`

the warning: `Deprecation Warning: Global built-in functions are deprecated and will be removed in Dart Sass 3.0.0.`   still exists, 

please fix it. thanks.

image

**Comment by warmthsea** [comment]
> please fix it. thanks.

You can use https://github.com/element-plus/element-plus/pull/18579#issuecomment-2418911488

**Comment by btea** [comment]
I will close this PR and let's focus all our attention on #18579.

**Comment by warmthsea** [comment]
Thank you for your contribution, this problem has been fixed, you can install it like this:

screenshots

**Pull request closed without merging**
